// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/** Generated DTO interface for `SealPublicEntry`. */
export interface SealPublicEntry {
  readonly kid: string;
  readonly publicSpki: Uint8Array;
}

/** Generated DTO interface for `GetOrLazyProvisionSealPublicKeyInput`. */
export interface GetOrLazyProvisionSealPublicKeyInput {
  readonly serviceId: string;
}

/** Generated DTO interface for `GetOrLazyProvisionSealPublicKeyOutput`. */
export interface GetOrLazyProvisionSealPublicKeyOutput {
  readonly activeKid: string;
  readonly entries: readonly SealPublicEntry[];
}
