// -----------------------------------------------------------------------
// <copyright file="JwtClaimsEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Auth.JwtClaims.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>JwtClaimTypes</c> static class source from
/// a parsed <see cref="JwtClaimsSpec"/>. Stateless and unit-testable in
/// isolation.
/// </summary>
internal static class JwtClaimsEmitter
{
    /// <summary>The namespace the <c>JwtClaimTypes</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.Auth.Abstractions";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "JwtClaimTypes";

    /// <summary>Closed enum of supported claim kinds.</summary>
    public static readonly ImmutableHashSet<string> SR_ValidKinds =
        ImmutableHashSet.Create(
            StringComparer.Ordinal,
            "standard",
            "d2-custom",
            "inside-act");

    private static readonly Regex sr_constNameRegex =
        new("^[A-Z][A-Z0-9_]*$", RegexOptions.Compiled);

    /// <summary>
    /// Emits the <c>JwtClaimTypes</c> class source plus diagnostics for the
    /// supplied spec.
    /// </summary>
    /// <param name="spec">Parsed JWT claims spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(JwtClaimsSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var validEntries = new List<JwtClaimEntry>();
        var seenConstNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.Claims)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (entry.Value.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyValue(entry.ConstName));
                continue;
            }

            if (!SR_ValidKinds.Contains(entry.Kind))
            {
                diagnostics.Add(EmitDiagnostics.UnknownKind(
                    entry.ConstName,
                    entry.Kind,
                    string.Join(
                        ", ",
                        SR_ValidKinds.OrderBy(s => s, StringComparer.Ordinal))));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateConstName(entry.ConstName));
                continue;
            }

            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(List<JwtClaimEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.Auth.JwtClaims.SourceGen.JwtClaimsGenerator");
        sb.AppendLine("//   from contracts/jwt-claims/jwt-claims.spec.json (the source of truth).");
        sb.AppendLine("//   Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// JWT claim name string constants used across the platform. Standard OAuth /");
        sb.AppendLine(
            "/// OIDC claims keep their canonical names (<c>sub</c>, <c>aud</c>, <c>scope</c>,");
        sb.AppendLine(
            "/// <c>act</c>, etc.); D2-specific claims are namespaced with the <c>d2_</c>");
        sb.AppendLine(
            "/// prefix to avoid collisions with future spec additions.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Generated from <c>contracts/jwt-claims/jwt-claims.spec.json</c> — the single");
        sb.AppendLine(
            "/// source of truth for every JWT claim D2 reads or writes. The same spec drives");
        sb.AppendLine(
            "/// the TS-side <c>@dcsv-io/d2-auth-abstractions</c> <c>JwtClaimTypes</c> catalog;");
        sb.AppendLine("/// cross-language drift is structurally impossible.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        foreach (var entry in entries)
        {
            sb.AppendLine("    /// <summary>");
            foreach (var line in entry.Description.Split('\n'))
                sb.AppendLine($"    /// {EscapeXmlDoc(line)}");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    /// <remarks>Kind: <c>{EscapeXmlDoc(entry.Kind)}</c>.</remarks>");
            var literal = EscapeStringLiteral(entry.Value);
            sb.AppendLine(
                $"    public const string {entry.ConstName} = \"{literal}\";");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
