// -----------------------------------------------------------------------
// <copyright file="InterfaceEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Context.SourceGen;

using System.Collections.Immutable;
using System.Text;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting a read-only interface (e.g. <c>IAuthContext</c>,
/// <c>IRequestContext</c>) from a parsed <see cref="ContextSpec"/>. Sectioned
/// via <c>#region</c> blocks; XML doc on every property; properties are
/// declared <c>{ get; }</c> only (read-only contract).
/// </summary>
internal static class InterfaceEmitter
{
    /// <summary>
    /// Emits the interface source for <paramref name="spec"/>.
    /// </summary>
    /// <param name="spec">The parsed context spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(ContextSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var sb = new StringBuilder();

        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//   Generated by DcsvIo.D2.Context.SourceGen.ContextGenerator");
        sb.AppendLine($"//   from a *.spec.json file (the source of truth).");
        sb.AppendLine("//   Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using DcsvIo.D2.Auth.Abstractions;");
        sb.AppendLine("using DcsvIo.D2.Utilities.Attributes;");
        sb.AppendLine("using DcsvIo.D2.Utilities.Enums;");
        sb.AppendLine();
        sb.AppendLine($"namespace {spec.Namespace};");
        sb.AppendLine();

        if (spec.Description.Truthy())
            EmitXmlDocSummary(sb, spec.Description!, indent: 0);

        var extendsClause = spec.Extends.Falsey()
            ? string.Empty
            : $" : global::{spec.Extends}";
        sb.AppendLine($"public interface {spec.Name}{extendsClause}");
        sb.AppendLine("{");

        var first = true;
        foreach (var section in spec.Sections)
        {
            if (!first)
                sb.AppendLine();

            first = false;

            sb.AppendLine($"    #region {section.Name}");
            sb.AppendLine();

            var firstProp = true;
            foreach (var prop in section.Properties)
            {
                if (!firstProp)
                    sb.AppendLine();

                firstProp = false;

                if (!TypeVocabulary.IsValid(prop.Type))
                {
                    diagnostics.Add(EmitDiagnostics.UnknownType(
                        spec.Name, prop.Name, prop.Type, TypeVocabulary.ValidTypesForDiagnostics));
                    continue;
                }

                if (prop.Derived.Truthy() &&
                    !TypeVocabulary.IsValidDerivedRule(prop.Derived!))
                {
                    diagnostics.Add(EmitDiagnostics.UnknownDerivedRule(
                        spec.Name,
                        prop.Name,
                        prop.Derived!,
                        TypeVocabulary.ValidDerivedRulesForDiagnostics));
                }

                EmitProperty(sb, prop, indent: 1);
            }

            sb.AppendLine();
            sb.AppendLine($"    #endregion");
        }

        sb.AppendLine("}");

        return new EmitResult(
            HintName: $"{spec.Name}.g.cs",
            GeneratedSource: sb.ToString().LfNormalized(),
            Diagnostics: diagnostics.ToImmutable());
    }

    private static void EmitProperty(StringBuilder sb, PropertySpec prop, int indent)
    {
        var pad = new string(' ', indent * 4);
        var doc = prop.Doc ?? prop.Name;
        EmitXmlDocSummary(sb, doc, indent);
        if (prop.Redact)
            sb.AppendLine($"{pad}[RedactData(Reason = RedactReason.PersonalInformation)]");

        sb.AppendLine($"{pad}{prop.Type} {prop.Name} {{ get; }}");
    }

    private static void EmitXmlDocSummary(StringBuilder sb, string text, int indent)
    {
        var pad = new string(' ', indent * 4);
        var lines = text.Split('\n');
        sb.AppendLine($"{pad}/// <summary>");
        foreach (var line in lines)
            sb.AppendLine($"{pad}/// {EscapeXmlDoc(line.TrimEnd('\r'))}");

        sb.AppendLine($"{pad}/// </summary>");
    }

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
