// -----------------------------------------------------------------------
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) DCSV
// -----------------------------------------------------------------------

// Tests for the TS extraction helpers (ts-api-adapter.ts) — pure, build-free:
//   - parseApiMembers: fence extraction, multi-line declarations
//   - extractMemberName: identifier extraction per declaration kind
//   - diffApiMembers: added / removed / changed detection
//   - resolveApiMdPath: basename-vs-reportFileName resolution
//   - tsFingerprintBaselinePath: etc/.release-fingerprint
//
// The git-ref apiDiff + source-based fingerprint composition are covered in
// real-diff-provider.test.ts. The real api-extractor runner is exercised by the
// gated CI lane (`.api.md` currency gate); an ESM-require regression test pins
// that it resolves under a plain ESM (tsx) process.

import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { repoRoot } from "./repo-root.js";
import {
  diffApiMembers,
  extractMemberName,
  parseApiMembers,
  resolveApiMdPath,
  tsFingerprintBaselinePath,
} from "../src/ts-api-adapter.js";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/** A representative committed baseline api.md content. */
const BASELINE_API_MD = `## API Report File for "@d2/error-category"

> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).

\`\`\`ts

// @public
export const ALL_ERROR_CATEGORIES: readonly ErrorCategory[];

// @public
export type ErrorCategory = "conflict" | "internal_error";

// @public
export const ErrorCategoryWire: {
    readonly Conflict: "conflict";
    readonly InternalError: "internal_error";
};

// (No @packageDocumentation comment for this package)

\`\`\`
`;

// ---------------------------------------------------------------------------
// parseApiMembers
// ---------------------------------------------------------------------------

describe("parseApiMembers — fence extraction", () => {
  it("parses a simple single-line export const", () => {
    const md = `\`\`\`ts\n\n// @public\nexport const FOO: string;\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.has("export const FOO: string;")).toBe(true);
    expect(members.size).toBe(1);
  });

  it("parses a single-line export type alias", () => {
    const md = `\`\`\`ts\n\n// @public\nexport type Cat = "a" | "b";\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.has(`export type Cat = "a" | "b";`)).toBe(true);
  });

  it("parses a multi-line export const object", () => {
    const md =
      `\`\`\`ts\n\n// @public\nexport const Wire: {\n` +
      `    readonly A: "a";\n    readonly B: "b";\n};\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.size).toBe(1);
    const decl = [...members][0]!;
    expect(decl).toContain("export const Wire:");
    expect(decl).toContain(`readonly A: "a";`);
  });

  it("excludes comment lines and blank lines at top level", () => {
    const md = `\`\`\`ts\n\n// @public\nexport const X: number;\n\n// (No @packageDocumentation comment for this package)\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.size).toBe(1);
    expect([...members][0]).toBe("export const X: number;");
  });

  it("handles content before the fence (ignores it)", () => {
    const md = `# Header\nSome prose\n\n\`\`\`ts\n\n// @public\nexport function foo(): void;\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.has("export function foo(): void;")).toBe(true);
  });

  it("returns empty set for an api.md with no exports", () => {
    const md = `\`\`\`ts\n\n// (No @packageDocumentation comment for this package)\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.size).toBe(0);
  });

  it("parses the representative baseline: 3 members", () => {
    const members = parseApiMembers(BASELINE_API_MD);
    expect(members.size).toBe(3);
    expect(
      members.has(
        "export const ALL_ERROR_CATEGORIES: readonly ErrorCategory[];",
      ),
    ).toBe(true);

    const wireDecl = [...members].find((m) =>
      m.startsWith("export const ErrorCategoryWire:"),
    );

    expect(wireDecl).toBeDefined();
  });
});

// ---------------------------------------------------------------------------
// extractMemberName
// ---------------------------------------------------------------------------

describe("extractMemberName", () => {
  it("extracts name from export const", () => {
    expect(extractMemberName("export const FOO: string;")).toBe("FOO");
  });

  it("extracts name from export type", () => {
    expect(extractMemberName("export type MyType = string;")).toBe("MyType");
  });

  it("extracts name from export function", () => {
    expect(extractMemberName("export function doThing(): void;")).toBe(
      "doThing",
    );
  });

  it("extracts name from export class", () => {
    expect(extractMemberName("export class Foo {")).toBe("Foo");
  });

  it("extracts name from export interface", () => {
    expect(extractMemberName("export interface IBar {")).toBe("IBar");
  });

  it("extracts name from export enum", () => {
    expect(extractMemberName("export enum Status {")).toBe("Status");
  });

  it("falls back to first line for unrecognised pattern", () => {
    expect(extractMemberName("export default something;")).toBe(
      "export default something;",
    );
  });

  it("extracts name from multi-line decl (uses first line only)", () => {
    const decl = `export const Wire: {\n    readonly A: "a";\n};`;
    expect(extractMemberName(decl)).toBe("Wire");
  });
});

// ---------------------------------------------------------------------------
// diffApiMembers
// ---------------------------------------------------------------------------

describe("diffApiMembers", () => {
  it("no change → all false", () => {
    const base = new Set([
      "export const A: string;",
      "export type B = number;",
    ]);
    const fresh = new Set([
      "export const A: string;",
      "export type B = number;",
    ]);

    expect(diffApiMembers(base, fresh)).toEqual({
      added: false,
      removed: false,
      changed: false,
    });
  });

  it("added member → added: true, others false", () => {
    const base = new Set(["export const A: string;"]);
    const fresh = new Set([
      "export const A: string;",
      "export const C: boolean;",
    ]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(true);
    expect(result.removed).toBe(false);
    expect(result.changed).toBe(false);
  });

  it("removed member → removed: true, others false", () => {
    const base = new Set([
      "export const A: string;",
      "export const B: number;",
    ]);
    const fresh = new Set(["export const A: string;"]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(false);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });

  it("changed member signature (same name, different type) → changed: true", () => {
    const base = new Set(["export const A: string;"]);
    const fresh = new Set(["export const A: number;"]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(false);
    expect(result.removed).toBe(false);
    expect(result.changed).toBe(true);
  });

  it("rename (old removed, new added) → added:true + removed:true, changed:false", () => {
    const base = new Set(["export const OldName: string;"]);
    const fresh = new Set(["export const NewName: string;"]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(true);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });

  it("empty baseline + one member fresh → added:true only", () => {
    const result = diffApiMembers(
      new Set(),
      new Set(["export const X: string;"]),
    );

    expect(result.added).toBe(true);
    expect(result.removed).toBe(false);
    expect(result.changed).toBe(false);
  });

  it("one member baseline + empty fresh → removed:true only", () => {
    const result = diffApiMembers(
      new Set(["export const X: string;"]),
      new Set(),
    );

    expect(result.added).toBe(false);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });

  it("both removed and added simultaneously → removed:true + added:true", () => {
    const base = new Set([
      "export const A: string;",
      "export const B: number;",
    ]);
    const fresh = new Set([
      "export const A: string;",
      "export const C: boolean;",
    ]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(true);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// resolveApiMdPath — basename vs reportFileName
// ---------------------------------------------------------------------------

describe("resolveApiMdPath — basename vs reportFileName", () => {
  it("flat package (no api-extractor.json) uses basename fallback", () => {
    const tmp = mkdtempSync(join(tmpdir(), "rap-flat-"));

    try {
      const result = resolveApiMdPath(tmp, join(tmp, "api-extractor.json"));
      const segment = tmp.split(/[\\/]/).at(-1) ?? "";
      expect(result).toBe(join(tmp, "etc", `${segment}.api.md`));
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  it("nested package: reportFileName from api-extractor.json overrides basename", () => {
    const tmp = mkdtempSync(join(tmpdir(), "rap-amqp-"));

    try {
      const configPath = join(tmp, "api-extractor.json");
      writeFileSync(
        configPath,
        JSON.stringify({
          apiReport: { reportFileName: "headers-amqp.api.md" },
        }),
        "utf-8",
      );

      const result = resolveApiMdPath(tmp, configPath);

      expect(result).toBe(join(tmp, "etc", "headers-amqp.api.md"));
      const dirBasename = tmp.split(/[\\/]/).at(-1) ?? "";
      expect(result).not.toBe(join(tmp, "etc", `${dirBasename}.api.md`));
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  it("malformed api-extractor.json falls back to basename", () => {
    const tmp = mkdtempSync(join(tmpdir(), "rap-malformed-"));

    try {
      const configPath = join(tmp, "api-extractor.json");
      writeFileSync(configPath, "NOT VALID JSON", "utf-8");

      const result = resolveApiMdPath(tmp, configPath);

      const segment = tmp.split(/[\\/]/).at(-1) ?? "";
      expect(result).toBe(join(tmp, "etc", `${segment}.api.md`));
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  it("api-extractor.json with no apiReport.reportFileName falls back to basename", () => {
    const tmp = mkdtempSync(join(tmpdir(), "rap-nofield-"));

    try {
      const configPath = join(tmp, "api-extractor.json");
      writeFileSync(
        configPath,
        JSON.stringify({ mainEntryPointFilePath: "./dist/index.d.ts" }),
        "utf-8",
      );

      const result = resolveApiMdPath(tmp, configPath);

      const segment = tmp.split(/[\\/]/).at(-1) ?? "";
      expect(result).toBe(join(tmp, "etc", `${segment}.api.md`));
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  it("real headers/amqp api-extractor.json resolves to etc/headers-amqp.api.md", () => {
    const amqpDir = resolve(
      repoRoot,
      "public/packages/typescript/headers/amqp",
    );
    const configPath = join(amqpDir, "api-extractor.json");

    if (!existsSync(configPath)) return; // skip if package not present

    const result = resolveApiMdPath(amqpDir, configPath);

    expect(result).toBe(join(amqpDir, "etc", "headers-amqp.api.md"));
    expect(result).not.toBe(join(amqpDir, "etc", "amqp.api.md"));
  });
});

// ---------------------------------------------------------------------------
// tsFingerprintBaselinePath
// ---------------------------------------------------------------------------

describe("tsFingerprintBaselinePath", () => {
  it("→ etc/.release-fingerprint under the package dir", () => {
    expect(tsFingerprintBaselinePath(join("/abs", "ts", "result"))).toBe(
      join("/abs", "ts", "result", "etc", ".release-fingerprint"),
    );
  });
});

// ---------------------------------------------------------------------------
// Regression: the real api-extractor runner must resolve under a PLAIN ESM run.
// ---------------------------------------------------------------------------

describe("makeRealApiExtractorRunner — ESM require resolution", () => {
  it("loads + resolves @microsoft/api-extractor under a plain ESM (tsx) process", async () => {
    const { spawnSync } = await import("node:child_process");

    const snippet =
      "import { makeRealApiExtractorRunner } from " +
      `'${resolve(repoRoot, "tools/release-runner/src/ts-api-adapter.ts").replace(/\\/g, "/")}';` +
      "try { makeRealApiExtractorRunner().run('/no/such/dir', '/no/such/config.json'); }" +
      "catch (e) { console.log('CAUGHT:' + String(e && e.message ? e.message : e)); }";

    const result = spawnSync(
      "node",
      ["--import", "tsx", "--input-type=module", "-e", snippet],
      { encoding: "utf-8", cwd: repoRoot, maxBuffer: 10 * 1024 * 1024 },
    );

    const output = (result.stdout ?? "") + (result.stderr ?? "");

    expect(output).not.toContain("require is not defined in ES module scope");
  }, 60_000);
});
