// -----------------------------------------------------------------------
// <copyright file="CompromiseKeyOutput.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Edge.KeyCustodian.App.Application.Handlers.Commands.CompromiseKey;

/// <summary>
/// Result of compromising a key: the kid marked compromised and the optional
/// replacement pending key's kid (when a replacement was requested).
/// </summary>
/// <param name="CompromisedKid">The kid that was marked compromised.</param>
/// <param name="ReplacementKid">
/// The kid of the replacement pending key — either freshly generated by this
/// operation, or the pre-existing live pending successor when the domain was
/// already mid-rotation (no second pending key is inserted in that case).
/// <see langword="null"/> when no replacement was requested, or when replacement
/// generation was requested but failed after the compromise durably committed — a
/// best-effort follow-up whose failure never rolls the compromise back.
/// </param>
public sealed record CompromiseKeyOutput(string CompromisedKid, string? ReplacementKid);
