// -----------------------------------------------------------------------
// <copyright file="ErrorCodesEmitter.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.Auth.ErrorCodes.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using D2.Shared.SourceGen;

/// <summary>
/// Pure logic for emitting the <c>AuthErrorCodes</c> static class source from
/// a parsed <see cref="ErrorCodesSpec"/>. Stateless and unit-testable in
/// isolation. The Roslyn-host integration (<see cref="ErrorCodesGenerator"/>)
/// calls this and translates emit-side <see cref="EmitDiagnostic"/> records
/// into Roslyn <c>Diagnostic</c> instances.
/// </summary>
internal static class ErrorCodesEmitter
{
    /// <summary>The namespace the <c>AuthErrorCodes</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "D2.Shared.Auth.Errors";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "AuthErrorCodes";

    /// <summary>
    /// HTTP statuses the codegen mapping currently supports. Expanding the
    /// runtime auth taxonomy to a new status (e.g. <c>403</c>) requires
    /// adding an entry here AND extending the gRPC StatusCode mapping in
    /// <c>D2RpcStatusExtensions</c>.
    /// </summary>
    public static readonly ImmutableArray<int> SR_SupportedHttpStatuses =
        ImmutableArray.Create(401, 503);

    private static readonly ImmutableHashSet<string> sr_validCategories =
        ImmutableHashSet.Create(
            StringComparer.Ordinal,
            "validation_failure",
            "infrastructure_unavailable",
            "policy_denied");

    /// <summary>
    /// Emits the <c>AuthErrorCodes</c> class source plus diagnostics for the
    /// supplied spec.
    /// </summary>
    /// <param name="spec">Parsed error-codes spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(ErrorCodesSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var supportedStatuses = string.Join(
            ", ",
            SR_SupportedHttpStatuses.Select(
                s => s.ToString(System.Globalization.CultureInfo.InvariantCulture)));

        var validEntries = new List<ErrorCodeEntry>();
        var seenCodes = new HashSet<string>(StringComparer.Ordinal);
        var seenFactories = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.ErrorCodes)
        {
            if (!seenCodes.Add(entry.Code))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateCode(entry.Code));
                continue;
            }

            if (!seenFactories.Add(entry.FactoryName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateFactoryName(entry.FactoryName));
                continue;
            }

            if (!sr_validCategories.Contains(entry.Category))
            {
                diagnostics.Add(EmitDiagnostics.UnknownCategoryEnum(
                    entry.Code,
                    entry.Category,
                    string.Join(
                        ", ",
                        sr_validCategories.OrderBy(c => c, StringComparer.Ordinal))));
                continue;
            }

            if (!SR_SupportedHttpStatuses.Contains(entry.HttpStatus))
            {
                diagnostics.Add(EmitDiagnostics.InvalidHttpStatus(
                    entry.Code, entry.HttpStatus, supportedStatuses));
                continue;
            }

            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(List<ErrorCodeEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by D2.Shared.Auth.ErrorCodes.SourceGen.ErrorCodesGenerator");
        sb.AppendLine(
            "//   from contracts/auth-error-codes/auth-error-codes.spec.json (the source");
        sb.AppendLine("//   of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Machine-readable <c>d2_error_code</c> string constants surfaced on");
        sb.AppendLine(
            "/// <see cref=\"D2.Shared.Result.D2Result\"/> failures + RFC 7807");
        sb.AppendLine("/// <c>ProblemDetails.Extensions[\"d2_error_code\"]</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Generated from the spec file - drift between the codes here and the");
        sb.AppendLine(
            "/// telemetry tag-value enumeration is impossible (the telemetry-tags");
        sb.AppendLine(
            "/// SrcGen consumes the same spec via <c>valuesFromSpec</c>).");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        foreach (var entry in entries)
        {
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.Code} = \"{EscapeStringLiteral(entry.Code)}\";");
            sb.AppendLine();
        }

        EmitAllCodes(sb, entries);
        sb.AppendLine();
        EmitGetHttpStatus(sb, entries);
        sb.AppendLine();
        EmitKebabCase(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitAllCodes(StringBuilder sb, List<ErrorCodeEntry> entries)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// All declared <c>AUTH_*</c> codes in spec order. Useful for");
        sb.AppendLine(
            "    /// telemetry-tag-value membership checks and cross-spec consistency");
        sb.AppendLine("    /// tests.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static IReadOnlyList<string> AllCodes => sr_allCodes;");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyList<string> sr_allCodes = new string[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
            sb.AppendLine($"        \"{EscapeStringLiteral(entry.Code)}\",");

        sb.AppendLine("    };");
    }

    private static void EmitGetHttpStatus(StringBuilder sb, List<ErrorCodeEntry> entries)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Returns the HTTP status code declared in the spec for");
        sb.AppendLine(
            "    /// <paramref name=\"errorCode\"/>, or <c>500</c> if the code is not");
        sb.AppendLine(
            "    /// recognized (defensive default - every shipped <c>AUTH_*</c> code");
        sb.AppendLine("    /// is in the table).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"errorCode\">The auth error code.</param>");
        sb.AppendLine("    /// <returns>The HTTP status code.</returns>");
        sb.AppendLine("    public static int GetHttpStatus(string errorCode) => errorCode switch");
        sb.AppendLine("    {");
        foreach (var entry in entries)
        {
            sb.AppendLine(
                $"        \"{EscapeStringLiteral(entry.Code)}\" => {entry.HttpStatus},");
        }

        sb.AppendLine("        _ => 500,");
        sb.AppendLine("    };");
    }

    private static void EmitKebabCase(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Converts a SCREAMING_SNAKE error code (e.g. <c>AUTH_BEARER_MISSING</c>)");
        sb.AppendLine(
            "    /// to its kebab-case form (<c>auth-bearer-missing</c>) for use in the");
        sb.AppendLine(
            "    /// RFC 7807 ProblemDetails <c>type</c> URI.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    /// <param name=\"upperUnderscore\">The SCREAMING_SNAKE error code.</param>");
        sb.AppendLine("    /// <returns>The kebab-case form.</returns>");
        sb.AppendLine("    public static string KebabCase(string upperUnderscore)");
        sb.AppendLine("    {");
        sb.AppendLine("        var sb = new StringBuilder(upperUnderscore.Length);");
        sb.AppendLine("        for (var i = 0; i < upperUnderscore.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var c = upperUnderscore[i];");
        sb.AppendLine("            sb.Append(c == '_' ? '-' : char.ToLowerInvariant(c));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
