// -----------------------------------------------------------------------
// <copyright file="FailureFactoriesEmitter.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.Auth.ErrorCodes.SourceGen;

using System.Collections.Generic;
using System.Text;

/// <summary>
/// Pure logic for emitting the <c>AuthFailures</c> static class source from
/// a parsed <see cref="ErrorCodesSpec"/>. Stateless and unit-testable in
/// isolation. Validation happens upstream in <see cref="ErrorCodesEmitter"/>;
/// this emitter assumes the spec is already valid (consumer drives both
/// emitters from the same loader output).
/// </summary>
internal static class FailureFactoriesEmitter
{
    /// <summary>The namespace the <c>AuthFailures</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "D2.Shared.Auth.Errors";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "AuthFailures";

    private const string _CATEGORY_VALIDATION_FAILURE = "validation_failure";
    private const string _CATEGORY_INFRASTRUCTURE_UNAVAILABLE = "infrastructure_unavailable";
    private const string _CATEGORY_POLICY_DENIED = "policy_denied";

    /// <summary>
    /// Emits the <c>AuthFailures</c> class source from the supplied spec.
    /// Filters entries by the same category-enum / status / uniqueness rules as
    /// <see cref="ErrorCodesEmitter"/> so the two emitters stay symmetric;
    /// duplicates / invalid entries are silently skipped here (the same
    /// diagnostics fire from <see cref="ErrorCodesEmitter"/>'s walk).
    /// </summary>
    /// <param name="spec">Parsed error-codes spec.</param>
    /// <returns>Generated source.</returns>
    public static EmitResult Emit(ErrorCodesSpec spec)
    {
        var validEntries = new List<ErrorCodeEntry>();
        var seenCodes = new HashSet<string>(System.StringComparer.Ordinal);
        var seenFactories = new HashSet<string>(System.StringComparer.Ordinal);

        foreach (var entry in spec.ErrorCodes)
        {
            if (!seenCodes.Add(entry.Code))
                continue;
            if (!seenFactories.Add(entry.FactoryName))
                continue;
            if (!IsKnownCategory(entry.Category))
                continue;
            if (!ErrorCodesEmitter.SR_SupportedHttpStatuses.Contains(entry.HttpStatus))
                continue;

            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(
            source,
            System.Collections.Immutable.ImmutableArray<EmitDiagnostic>.Empty);
    }

    private static bool IsKnownCategory(string category) =>
        category == _CATEGORY_VALIDATION_FAILURE
            || category == _CATEGORY_INFRASTRUCTURE_UNAVAILABLE
            || category == _CATEGORY_POLICY_DENIED;

    private static string EmitSource(List<ErrorCodeEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by D2.Shared.Auth.ErrorCodes.SourceGen.ErrorCodesGenerator");
        sb.AppendLine(
            "//   from contracts/auth-error-codes/auth-error-codes.spec.json (the source");
        sb.AppendLine("//   of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using D2.Shared.I18n;");
        sb.AppendLine("using D2.Shared.Result;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Pre-built <see cref=\"D2Result\"/> failures for inbound auth runtime -");
        sb.AppendLine(
            "/// JWT validation rejections, session liveness outages, JWKS upstream");
        sb.AppendLine("/// failures.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Two-axis design: coarse user-facing TK key (per status bucket) plus");
        sb.AppendLine(
            "/// granular machine-readable <see cref=\"AuthErrorCodes\"/> constant. Generated");
        sb.AppendLine(
            "/// from the spec file - drift between the factory list and the");
        sb.AppendLine(
            "/// <see cref=\"AuthErrorCodes\"/> constants is impossible (single spec source).");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        foreach (var entry in entries)
        {
            EmitFactory(sb, entry);
            sb.AppendLine();
            if (entry.Category == _CATEGORY_INFRASTRUCTURE_UNAVAILABLE)
            {
                EmitTypedFactory(sb, entry);
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFactory(StringBuilder sb, ErrorCodeEntry entry)
    {
        sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
        sb.AppendLine(
            "    /// <returns>A pre-built <see cref=\"D2Result\"/> failure.</returns>");

        if (entry.Category == _CATEGORY_INFRASTRUCTURE_UNAVAILABLE)
        {
            sb.AppendLine($"    public static D2Result {entry.FactoryName}() =>");
            sb.AppendLine("        D2Result.ServiceUnavailable(");
            sb.AppendLine($"            messages: [{entry.UserMessageKey}],");
            sb.AppendLine(
                $"            errorCode: AuthErrorCodes.{entry.Code});");
        }
        else
        {
            // validation_failure / policy_denied → 401 Unauthorized.
            sb.AppendLine($"    public static D2Result {entry.FactoryName}() =>");
            sb.AppendLine("        D2Result.Unauthorized(");
            sb.AppendLine($"            messages: [{entry.UserMessageKey}],");
            sb.AppendLine(
                $"            errorCode: AuthErrorCodes.{entry.Code});");
        }
    }

    private static void EmitTypedFactory(StringBuilder sb, ErrorCodeEntry entry)
    {
        sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)} Typed overload.</summary>");
        sb.AppendLine(
            "    /// <typeparam name=\"T\">The payload type the caller would have returned on "
            + "success.</typeparam>");
        sb.AppendLine(
            "    /// <returns>A pre-built typed <see cref=\"D2Result{T}\"/> failure.</returns>");
        sb.AppendLine($"    public static D2Result<T> {entry.FactoryName}<T>() =>");
        sb.AppendLine("        D2Result<T>.ServiceUnavailable(");
        sb.AppendLine($"            messages: [{entry.UserMessageKey}],");
        sb.AppendLine($"            errorCode: AuthErrorCodes.{entry.Code});");
    }

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
