// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Audit.Client;

using PingAuditInput = global::D2.Audit.Client.Ping.PingAuditInput;
using PingAuditOutput = global::D2.Audit.Client.Ping.PingAuditOutput;
using D2.Shared.Resilience.Pipeline;

/// <summary>
/// Generated cross-process gRPC client interface for the Audit module.
/// Lists the module's gRPC-exposed operations with the transport-aware signature.
/// </summary>
public interface IAuditGrpcClient
{
    /// <summary>Dispatches the <c>PingAudit</c> operation over gRPC.</summary>
    ValueTask<D2Result<PingAuditOutput?>> PingAuditAsync(
        PingAuditInput input,
        ResilientPipeline<string, PingAuditOutput?>? pipelineOverride = null,
        CancellationToken ct = default);
}
