// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Audit.Client;

using D2.Audit.Client.Ping;
using D2.Services.Protos.Audit.V2Alpha;
using Google.Protobuf;

/// <summary>Generated client-side mappers: DTO ↔ proto for the <c>PingAudit</c> operation (inverse of server transport mappers).</summary>
internal static class PingAuditClientMappers
{
    extension(global::D2.Audit.Client.Ping.PingAuditInput input)
    {
        internal global::D2.Services.Protos.Audit.V2Alpha.PingAuditRequest ToPingAuditRequest()
        {
            return new global::D2.Services.Protos.Audit.V2Alpha.PingAuditRequest();
        }
    }

    extension(global::D2.Services.Protos.Audit.V2Alpha.PingAuditOutput data)
    {
        internal global::D2.Audit.Client.Ping.PingAuditOutput ToPingAuditOutput()
        {
            return new global::D2.Audit.Client.Ping.PingAuditOutput(data.Status);
        }
    }
}
