// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/** Generated DTO interface for `KeyringEntry`. */
export interface KeyringEntry {
  readonly kid: string;
  readonly keyBytes: Uint8Array;
}

/** Generated DTO interface for `GetKeyringInput`. */
export interface GetKeyringInput {
  readonly keyDomain: string;
}

/** Generated DTO interface for `GetKeyringOutput`. */
export interface GetKeyringOutput {
  readonly activeKid: string;
  readonly entries: readonly KeyringEntry[];
  readonly aadContext: Uint8Array;
}
