// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Commands.IssueLeaf;

using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Issuance;

/// <summary>Generated handler interface for the <c>IssueLeaf</c> operation.</summary>
public interface IIssueLeafHandler : IHandler<IssueLeafInput, IssueLeafOutput>;
