#!/usr/bin/env bash
# -----------------------------------------------------------------------
# Copyright (c) DCSV. All rights reserved.
# -----------------------------------------------------------------------

# =============================================================================
# gen-dev-keys.sh — Generate the dev KeyCustodian root key for D2-WORX local dev
#
# Generates (by default):
#   - secrets/keycustodian/root.key       The KeyCustodian root key. Wraps every
#                                         managed key's material at rest. All other
#                                         keys (JWKS signing, payload encryption,
#                                         cookie, client secrets) are KeyCustodian-
#                                         managed rows in keycustodian_db, fetched
#                                         at runtime via the keyring client — never
#                                         files, never per-service key files.
#
# On demand (NOT generated by default — dev mirrors prod steady state, where the
# successor key file exists only during a root-rotation window):
#   - secrets/keycustodian/root-next.key  A staged successor root key. The
#                                         FileRootKeyProvider loads it as a
#                                         decrypt-only kid alongside root.key, so a
#                                         dev box rotates the root without downtime.
#
# All output goes into ./secrets/ which is gitignored AND Claude-deny-ruled
# (Read/Write/Edit blocked at the system level — see .claude/settings.json).
#
# Re-running this script:
#   - Skips the existing root key (idempotent — safe to run multiple times)
#   - Use --rotate-root to stage secrets/keycustodian/root-next.key on demand
#   - Use --force to regenerate the root key (DESTRUCTIVE — invalidates all
#     existing root-wrapped key material)
#
# Usage:
#   ./tools/scripts/gen-dev-keys.sh                  # generate the root key if missing
#   ./tools/scripts/gen-dev-keys.sh --rotate-root    # stage a successor root key
#   ./tools/scripts/gen-dev-keys.sh --force          # regenerate the root key
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SECRETS_DIR="${REPO_ROOT}/secrets"
KEYCUSTODIAN_KEYS_DIR="${SECRETS_DIR}/keycustodian"

# Generate a 32-byte (256-bit) random key as hex.
gen_key() {
  openssl rand -hex 32
}

mkdir -p "${KEYCUSTODIAN_KEYS_DIR}"
chmod 700 "${SECRETS_DIR}" "${KEYCUSTODIAN_KEYS_DIR}"

# ---------- KeyCustodian root key -------------------------------------------
if [[ "${1:-}" == "--force" ]] || [[ ! -f "${KEYCUSTODIAN_KEYS_DIR}/root.key" ]]; then
  gen_key > "${KEYCUSTODIAN_KEYS_DIR}/root.key"
  chmod 600 "${KEYCUSTODIAN_KEYS_DIR}/root.key"
  echo "✓ Generated KeyCustodian root key: secrets/keycustodian/root.key"
else
  echo "  Skipped KeyCustodian root key (already exists)"
fi

# ---------- KeyCustodian successor root key (on demand only) ----------------
if [[ "${1:-}" == "--rotate-root" ]]; then
  gen_key > "${KEYCUSTODIAN_KEYS_DIR}/root-next.key"
  chmod 600 "${KEYCUSTODIAN_KEYS_DIR}/root-next.key"
  echo "✓ Staged KeyCustodian successor root key: secrets/keycustodian/root-next.key"
  echo "  (the FileRootKeyProvider loads it as a decrypt-only kid alongside root.key)"
fi

echo
echo "Dev keys ready under: ${SECRETS_DIR}/"
echo "These files are gitignored AND Claude-deny-ruled."
