#!/usr/bin/env bash
# -----------------------------------------------------------------------
# Copyright (c) DCSV. All rights reserved.
# -----------------------------------------------------------------------

# =============================================================================
# gen-dev-keys.sh — Generate the dev KeyCustodian root key + CA chain for D2-WORX
#
# Generates (by default):
#   - secrets/keycustodian/root.key       The KeyCustodian root key. Wraps every
#                                         managed key's material at rest. All other
#                                         keys (JWKS signing, payload encryption,
#                                         cookie, client secrets) are KeyCustodian-
#                                         managed rows in d2-keycustodian, fetched
#                                         at runtime via the keyring client — never
#                                         files, never per-service key files.
#   - secrets/keycustodian/ca-root.crt    The dev internal mTLS root CA certificate
#     secrets/keycustodian/ca-root.key    + its PKCS#8 private key (ECDSA P-256,
#                                         self-signed, CA pathlen 1). Seeded into
#                                         d2-keycustodian on startup as a managed
#                                         X509CaCertificate key by CaSeedingService.
#   - secrets/keycustodian/ca-intermediate.crt  The dev issuing-intermediate CA
#     secrets/keycustodian/ca-intermediate.key  certificate + PKCS#8 private key
#                                         (ECDSA P-256, signed by the root, CA
#                                         pathlen 0). Signs workload leaf certs.
#                                         FileCaProvider chain-validates this against
#                                         ca-root.crt at load — a mismatch fails loud
#                                         at boot, not silently at first issuance.
#
# On demand (NOT generated by default — dev mirrors prod steady state, where the
# successor key file exists only during a root-rotation window):
#   - secrets/keycustodian/root-next.key  A staged successor root key. The
#                                         FileRootKeyProvider loads it as a
#                                         decrypt-only kid alongside root.key, so a
#                                         dev box rotates the root without downtime.
#
# CA rotation is KeyCustodian-driven (overlap rotation through the managed-key
# lifecycle), NOT a script flag — the C# CaCertificateGeneration rule re-signs
# against the seeded root. The script only bootstraps the initial dev chain.
#
# All output goes into ./secrets/ which is gitignored AND Claude-deny-ruled
# (Read/Write/Edit blocked at the system level — see .claude/settings.json).
#
# Re-running this script:
#   - Skips the existing root key + CA chain (idempotent — safe to run multiple times)
#   - Use --rotate-root to stage secrets/keycustodian/root-next.key on demand
#   - Use --force to regenerate the root key AND the CA chain (DESTRUCTIVE —
#     invalidates all existing root-wrapped key material AND the seeded CA)
#
# Usage:
#   ./tools/scripts/gen-dev-keys.sh                  # generate root key + CA chain if missing
#   ./tools/scripts/gen-dev-keys.sh --rotate-root    # stage a successor root key
#   ./tools/scripts/gen-dev-keys.sh --force          # regenerate the root key + CA chain
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SECRETS_DIR="${REPO_ROOT}/secrets"
KEYCUSTODIAN_KEYS_DIR="${SECRETS_DIR}/keycustodian"

# Generate a 32-byte (256-bit) random key as hex.
gen_key() {
  openssl rand -hex 32
}

mkdir -p "${KEYCUSTODIAN_KEYS_DIR}"
chmod 700 "${SECRETS_DIR}" "${KEYCUSTODIAN_KEYS_DIR}"

# ---------- KeyCustodian root key -------------------------------------------
if [[ "${1:-}" == "--force" ]] || [[ ! -f "${KEYCUSTODIAN_KEYS_DIR}/root.key" ]]; then
  gen_key > "${KEYCUSTODIAN_KEYS_DIR}/root.key"
  chmod 600 "${KEYCUSTODIAN_KEYS_DIR}/root.key"
  echo "✓ Generated KeyCustodian root key: secrets/keycustodian/root.key"
else
  echo "  Skipped KeyCustodian root key (already exists)"
fi

# ---------- KeyCustodian successor root key (on demand only) ----------------
if [[ "${1:-}" == "--rotate-root" ]]; then
  gen_key > "${KEYCUSTODIAN_KEYS_DIR}/root-next.key"
  chmod 600 "${KEYCUSTODIAN_KEYS_DIR}/root-next.key"
  echo "✓ Staged KeyCustodian successor root key: secrets/keycustodian/root-next.key"
  echo "  (the FileRootKeyProvider loads it as a decrypt-only kid alongside root.key)"
fi

# ---------- KeyCustodian dev mTLS CA chain (root + intermediate) -------------
# ECDSA P-256, SHA-256. PEM certs + PKCS#8 PEM keys so ECDsa.ImportFromPem reads
# them directly. The filenames match CaCertificateFiles in the FileCaProvider.
CA_ROOT_CRT="${KEYCUSTODIAN_KEYS_DIR}/ca-root.crt"
CA_ROOT_KEY="${KEYCUSTODIAN_KEYS_DIR}/ca-root.key"
CA_INT_CRT="${KEYCUSTODIAN_KEYS_DIR}/ca-intermediate.crt"
CA_INT_KEY="${KEYCUSTODIAN_KEYS_DIR}/ca-intermediate.key"

if [[ "${1:-}" == "--force" ]] || [[ ! -f "${CA_ROOT_CRT}" ]] || [[ ! -f "${CA_ROOT_KEY}" ]] || [[ ! -f "${CA_INT_CRT}" ]] || [[ ! -f "${CA_INT_KEY}" ]]; then
  # Scratch dir UNDER the keys dir (not an absolute /tmp path) so all openssl file
  # paths stay relative/native — avoids Git-Bash/MSYS path-translation surprises.
  CA_TMP="${KEYCUSTODIAN_KEYS_DIR}/.ca-tmp"
  mkdir -p "${CA_TMP}"
  trap 'rm -rf "${CA_TMP}"' EXIT

  # Keep openssl /CN=... subjects from being path-mangled under Git-Bash/MSYS
  # (a no-op on Linux/macOS, where the subject is already passed through verbatim).
  export MSYS_NO_PATHCONV=1

  # --- Root CA: P-256 key (PKCS#8 PEM) + self-signed cert ---
  # Self-signed CA; may sign one intermediate tier (pathlen:1). -addext keeps the
  # extensions inline (portable — no config file / process substitution needed).
  openssl ecparam -name prime256v1 -genkey -noout \
    | openssl pkcs8 -topk8 -nocrypt -out "${CA_ROOT_KEY}"
  openssl req -x509 -new -sha256 -days 3650 \
    -key "${CA_ROOT_KEY}" \
    -subj "/CN=D2 Internal Root CA" \
    -addext "basicConstraints=critical,CA:TRUE,pathlen:1" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -addext "subjectKeyIdentifier=hash" \
    -out "${CA_ROOT_CRT}"

  # --- Intermediate CA: P-256 key (PKCS#8 PEM) + CSR signed by the root ---
  # CA that signs only leaves (pathlen:0). The extension file pins the CA + AKI.
  printf '%s\n' \
    'basicConstraints = critical,CA:TRUE,pathlen:0' \
    'keyUsage = critical,keyCertSign,cRLSign' \
    'subjectKeyIdentifier = hash' \
    'authorityKeyIdentifier = keyid' \
    > "${CA_TMP}/int-ext.cnf"
  openssl ecparam -name prime256v1 -genkey -noout \
    | openssl pkcs8 -topk8 -nocrypt -out "${CA_INT_KEY}"
  openssl req -new -sha256 \
    -key "${CA_INT_KEY}" \
    -subj "/CN=D2 Internal Issuing CA" \
    -out "${CA_TMP}/int.csr"
  openssl x509 -req -sha256 -days 365 \
    -in "${CA_TMP}/int.csr" \
    -CA "${CA_ROOT_CRT}" -CAkey "${CA_ROOT_KEY}" -CAcreateserial \
    -extfile "${CA_TMP}/int-ext.cnf" \
    -out "${CA_INT_CRT}"

  rm -rf "${CA_TMP}"
  # Drop the CAcreateserial state file — not one of the four CA artifacts the
  # provider loads, and a fresh serial is generated on each --force regen anyway.
  rm -f "${CA_ROOT_CRT%.crt}.srl"
  trap - EXIT
  chmod 600 "${CA_ROOT_KEY}" "${CA_INT_KEY}"
  chmod 644 "${CA_ROOT_CRT}" "${CA_INT_CRT}"
  echo "✓ Generated dev mTLS CA chain: ca-root.{crt,key} + ca-intermediate.{crt,key}"
  echo "  (CaSeedingService seeds these into d2-keycustodian as managed CA keys on startup)"
else
  echo "  Skipped dev mTLS CA chain (already exists)"
fi

echo
echo "Dev keys ready under: ${SECRETS_DIR}/"
echo "These files are gitignored AND Claude-deny-ruled."
