// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/headers/headers.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

/**
 * D2 wire-protocol headers applicable to the amqp catalog.
 * Generated from headers.spec.json. Mirrors .NET D2.Shared.Headers.Amqp.AmqpHeaders.
 */
export const AmqpHeaders = {
  /**
   * Always application/octet-stream for D2 messages — body is encrypted bytes (or proto-canonical JSON bytes, never a directly-readable structured type).
   * Convention: rfc.
   * Applicability: amqp.
   */
  CONTENT_TYPE: "content-type",
  /**
   * Encryption key id (kid). Duplicated from the encrypted frame so ops can decide whether archive keys are needed for a stuck DLQ message without decrypting first.
   * Convention: d2.
   * Applicability: amqp.
   */
  ENCRYPTION_KID: "x-d2-encryption-kid",
  /**
   * Failure reason metadata attached by the consumer when nacking a message to its DLQ. JSON-encoded DlqFailureMetadata.
   * Convention: d2.
   * Applicability: amqp.
   */
  FAILURE_REASON: "x-d2-failure-reason",
  /**
   * UUIDv7 message identifier — sortable, includes timestamp, suitable as an idempotency key.
   * Convention: amqp.
   * Applicability: amqp.
   */
  MESSAGE_ID: "message-id",
  /**
   * Base64url-of-JSON encoded PropagatedContext — small set of cross-hop fields a downstream consumer can't recompute (request id, original request path, fingerprints, WhoIs hash). Same header name + encoding on AMQP / gRPC / HTTP. Identity fields are NEVER in here — they rebuild from the JWT at every hop.
   * Convention: d2.
   * Applicability: amqp, grpc, http.
   */
  PROPAGATED_CONTEXT: "x-d2-context",
  /**
   * Fully-qualified proto type name (e.g. d2.events.files.v1.FileUploadedEvent). Lets consumers fail-fast on a type mismatch before deserialization.
   * Convention: amqp-x.
   * Applicability: amqp.
   */
  PROTO_TYPE: "x-proto-type",
  /**
   * Producer-set ISO 8601 UTC timestamp.
   * Convention: amqp.
   * Applicability: amqp.
   */
  TIMESTAMP: "timestamp",
  /**
   * W3C traceparent header — full {version}-{traceId}-{spanId}-{flags} string per https://www.w3.org/TR/trace-context. Consumers parse it to start a child span whose parent is the producer's span, so cross-hop trace assembly works in any OTel backend without bespoke linking.
   * Convention: w3c.
   * Applicability: amqp, grpc, http.
   */
  TRACEPARENT: "traceparent",
  /**
   * W3C tracestate header (vendor-specific tracing context that rides alongside traceparent). Forwarded as-is so non-D2 tracing systems chained through us don't lose state.
   * Convention: w3c.
   * Applicability: amqp, grpc, http.
   */
  TRACESTATE: "tracestate",
} as const;

export type AmqpHeaderName =
  (typeof AmqpHeaders)[keyof typeof AmqpHeaders];

export const ALL_AMQP_HEADERS: readonly string[] = [
  "content-type",
  "x-d2-encryption-kid",
  "x-d2-failure-reason",
  "message-id",
  "x-d2-context",
  "x-proto-type",
  "timestamp",
  "traceparent",
  "tracestate",
];
