// -----------------------------------------------------------------------
// <copyright file="ProblemDetailsEmitter.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.ProblemDetails.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using D2.Shared.SourceGen;

/// <summary>
/// Pure logic for emitting the static-class source of
/// <c>D2ProblemDetailsKeys</c> from a parsed
/// <see cref="ProblemDetailsSpec"/>. Stateless and unit-testable in
/// isolation. The Roslyn-host integration
/// (<see cref="ProblemDetailsGenerator"/>) calls this and translates
/// emit-side <see cref="EmitDiagnostic"/> records into Roslyn
/// <c>Diagnostic</c> instances.
/// </summary>
internal static class ProblemDetailsEmitter
{
    /// <summary>The namespace the static class lives in.</summary>
    public const string ROOT_NAMESPACE = "D2.Shared.ProblemDetails";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "D2ProblemDetailsKeys";

    /// <summary>The constName prefix applied to every extension-key field.</summary>
    public const string EXTENSION_PREFIX = "EXTENSION_";

    /// <summary>The constName prefix applied to every title field.</summary>
    public const string TITLE_PREFIX = "TITLE_";

    /// <summary>
    /// Emits the static-class source carrying the spec-derived constants +
    /// the <c>TitleFor</c> switch helper.
    /// </summary>
    /// <param name="spec">Parsed problem-details spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(ProblemDetailsSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        if (!spec.TypeUriPrefix.EndsWith("/", StringComparison.Ordinal))
            diagnostics.Add(EmitDiagnostics.TypeUriPrefixMissingTrailingSlash(spec.TypeUriPrefix));

        var validExtensions = new List<ExtensionKeyEntry>();
        var seenExtConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenExtValues = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.ExtensionKeys)
        {
            if (!seenExtConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(
                    EmitDiagnostics.DuplicateExtensionKeyConstName(entry.ConstName));
                continue;
            }

            if (!seenExtValues.Add(entry.Value))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateExtensionKeyValue(entry.Value));
                continue;
            }

            validExtensions.Add(entry);
        }

        var validTitles = new List<TitleEntry>();
        var seenTitleConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenTitleStatuses = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.Titles)
        {
            if (!seenTitleConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateTitleConstName(entry.ConstName));
                continue;
            }

            var statusKey = entry.HttpStatus is null
                ? "null"
                : entry.HttpStatus.Value.ToString(CultureInfo.InvariantCulture);
            if (!seenTitleStatuses.Add(statusKey))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateTitleHttpStatus(statusKey));
                continue;
            }

            validTitles.Add(entry);
        }

        var source = EmitSource(spec.TypeUriPrefix, spec.ContentType, validExtensions, validTitles);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(
        string typeUriPrefix,
        string contentType,
        List<ExtensionKeyEntry> extensions,
        List<TitleEntry> titles)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by D2.Shared.ProblemDetails.SourceGen.ProblemDetailsGenerator");
        sb.AppendLine(
            "//   from contracts/problem-details/problem-details.spec.json (the source");
        sb.AppendLine("//   of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Net;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived RFC 7807 ProblemDetails wire-format catalog —");
        sb.AppendLine(
            "/// <c>TYPE_URI_PREFIX</c>, <c>CONTENT_TYPE</c>, <c>EXTENSION_*</c>");
        sb.AppendLine(
            "/// extension keys, <c>TITLE_*</c> per-status titles, +");
        sb.AppendLine(
            "/// <c>TitleFor</c> switch.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Single source for both .NET emit paths (auth-http");
        sb.AppendLine(
            "/// <c>D2ProblemDetailsExtensions.ToProblemDetails</c> and aspnetcore");
        sb.AppendLine(
            "/// <c>D2ProblemDetailsCustomizer</c>) and the TS-side <c>@d2/problem-details-abstractions</c> (re-exported from <c>@d2/headers</c>)");
        sb.AppendLine(
            "/// catalog. Cross-language drift on the URI prefix, content type,");
        sb.AppendLine(
            "/// extension keys, and per-status titles is structurally impossible.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        sb.AppendLine(
            "    /// <summary>The base URL for the ProblemDetails "
            + "<c>Type</c> URI scheme.</summary>");
        sb.AppendLine(
            $"    public const string TYPE_URI_PREFIX = \"{EscapeStringLiteral(typeUriPrefix)}\";");
        sb.AppendLine();

        sb.AppendLine(
            "    /// <summary>MIME type per RFC 7807 §6.1 "
            + "for JSON ProblemDetails bodies.</summary>");
        sb.AppendLine(
            $"    public const string CONTENT_TYPE = \"{EscapeStringLiteral(contentType)}\";");
        sb.AppendLine();

        foreach (var entry in extensions)
        {
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {EXTENSION_PREFIX}{entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
            sb.AppendLine();
        }

        foreach (var entry in titles)
        {
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {TITLE_PREFIX}{entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
            sb.AppendLine();
        }

        EmitTitleForSwitch(sb, titles);

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static void EmitTitleForSwitch(StringBuilder sb, List<TitleEntry> titles)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Returns the spec-declared <c>Title</c> for");
        sb.AppendLine(
            "    /// <paramref name=\"statusCode\"/>, or the fallback title");
        sb.AppendLine(
            "    /// (<c>httpStatus=null</c> entry in the spec) when no per-status row");
        sb.AppendLine(
            "    /// matches. Defaults to an empty string only when the spec carries no");
        sb.AppendLine(
            "    /// fallback entry — codegen invariant under the schema.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"statusCode\">The HTTP status code.</param>");
        sb.AppendLine("    /// <returns>The matching coarse Title.</returns>");
        sb.AppendLine("    public static string TitleFor(HttpStatusCode statusCode) =>");
        sb.AppendLine("        ((int)statusCode) switch");
        sb.AppendLine("        {");

        string? fallbackConstName = null;
        foreach (var entry in titles)
        {
            if (entry.HttpStatus is null)
            {
                fallbackConstName = entry.ConstName;
                continue;
            }

            sb.AppendLine(
                $"            {entry.HttpStatus.Value.ToString(CultureInfo.InvariantCulture)} "
                    + $"=> {TITLE_PREFIX}{entry.ConstName},");
        }

        if (fallbackConstName is not null)
            sb.AppendLine($"            _ => {TITLE_PREFIX}{fallbackConstName},");
        else
            sb.AppendLine("            _ => string.Empty,");

        sb.AppendLine("        };");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
