// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace D2.Edge.KeyCustodian.App.Application.Facade;

using D2.Edge.KeyCustodian.App.Application.Handlers.Commands.GetOrLazyProvisionOwnSealPrivateKey;
using D2.Edge.KeyCustodian.App.Application.Handlers.Commands.GetOrLazyProvisionSealPublicKey;
using D2.Edge.KeyCustodian.App.Application.Handlers.Commands.IssueLeaf;
using D2.Edge.KeyCustodian.App.Application.Handlers.Queries.GetCaCertificate;
using D2.Edge.KeyCustodian.App.Application.Handlers.Queries.GetJwks;
using D2.Edge.KeyCustodian.App.Application.Handlers.Queries.GetKeyring;
using D2.Edge.KeyCustodian.App.Application.Handlers.Queries.GetOidcConfiguration;
using D2.Edge.KeyCustodian.App.Application.Handlers.Queries.Sign;
using D2.Edge.KeyCustodian.Client.CaCertificate;
using D2.Edge.KeyCustodian.Client.Facade;
using D2.Edge.KeyCustodian.Client.Issuance;
using D2.Edge.KeyCustodian.Client.Jwks;
using D2.Edge.KeyCustodian.Client.Keyring;
using D2.Edge.KeyCustodian.Client.OidcConfiguration;
using D2.Edge.KeyCustodian.Client.Sealing;
using D2.Edge.KeyCustodian.Client.Signing;

/// <summary>
/// Generated façade implementation. Delegates each exposed operation to the
/// corresponding app-layer handler. Registered Transient to match handler lifetime.
/// </summary>
public sealed class KeyCustodianApi(
    IGetJwksHandler getJwksHandler,
    IGetOidcConfigurationHandler getOidcConfigurationHandler,
    ISignHandler signHandler,
    IGetKeyringHandler getKeyringHandler,
    IIssueLeafHandler issueLeafHandler,
    IGetCaCertificateHandler getCaCertificateHandler,
    IGetOrLazyProvisionSealPublicKeyHandler getOrLazyProvisionSealPublicKeyHandler,
    IGetOrLazyProvisionOwnSealPrivateKeyHandler getOrLazyProvisionOwnSealPrivateKeyHandler) : IKeyCustodianApi
{
    /// <inheritdoc/>
    public ValueTask<D2Result<GetJwksOutput?>> GetJwksAsync(GetJwksInput input, CancellationToken ct = default)
        => getJwksHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetOidcConfigurationOutput?>> GetOidcConfigurationAsync(GetOidcConfigurationInput input, CancellationToken ct = default)
        => getOidcConfigurationHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<SignOutput?>> SignAsync(SignInput input, CancellationToken ct = default)
        => signHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetKeyringOutput?>> GetKeyringAsync(GetKeyringInput input, CancellationToken ct = default)
        => getKeyringHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<IssueLeafOutput?>> IssueLeafAsync(IssueLeafInput input, CancellationToken ct = default)
        => issueLeafHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetCaCertificateOutput?>> GetCaCertificateAsync(GetCaCertificateInput input, CancellationToken ct = default)
        => getCaCertificateHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetOrLazyProvisionSealPublicKeyOutput?>> GetOrLazyProvisionSealPublicKeyAsync(GetOrLazyProvisionSealPublicKeyInput input, CancellationToken ct = default)
        => getOrLazyProvisionSealPublicKeyHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetOrLazyProvisionOwnSealPrivateKeyOutput?>> GetOrLazyProvisionOwnSealPrivateKeyAsync(GetOrLazyProvisionOwnSealPrivateKeyInput input, CancellationToken ct = default)
        => getOrLazyProvisionOwnSealPrivateKeyHandler.HandleAsync(input, ct);
}
