// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/** Generated DTO interface for `SignInput`. */
export interface SignInput {
  readonly keyDomain: string;
  readonly signingInput: Uint8Array;
}

/** Generated DTO interface for `SignOutput`. */
export interface SignOutput {
  readonly signature: string;
  readonly kid: string;
}
