// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/auth-context/IAuthContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

export const RequestOrigin = {
  Unestablished: "Unestablished",
  EdgeInbound: "EdgeInbound",
  CrossProcessHop: "CrossProcessHop",
  InProcessModule: "InProcessModule",
  System: "System",
} as const;

export type RequestOrigin = (typeof RequestOrigin)[keyof typeof RequestOrigin];

/** No boundary positively established the origin (the fail-closed default). */
export const RequestOrigin_Unestablished: RequestOrigin = RequestOrigin.Unestablished;
/** The Edge HTTP inbound boundary — start of the call-path. */
export const RequestOrigin_EdgeInbound: RequestOrigin = RequestOrigin.EdgeInbound;
/** A cross-process gRPC hop authenticated by the mutual-TLS client cert. */
export const RequestOrigin_CrossProcessHop: RequestOrigin = RequestOrigin.CrossProcessHop;
/** An in-process module call (the in-host leaf). */
export const RequestOrigin_InProcessModule: RequestOrigin = RequestOrigin.InProcessModule;
/** An in-host system worker (a background service). */
export const RequestOrigin_System: RequestOrigin = RequestOrigin.System;
