// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/auth-scopes/scopes.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

/**
 * OAuth scope catalog emitted from contracts/auth-scopes/scopes.spec.json.
 * Tree-emitted nested constants — `Scopes.auth.user.impersonate.consent` resolves
 * to the dot-segmented spec name.
 */
export const Scopes = {
  anon: {
    auth: {
      signin: {
        attempt: "anon.auth.signin.attempt",
      },
    },
    public: {
      health: "anon.public.health",
    },
  },
  auth: {
    password: {
      change: "auth.password.change",
    },
    user: {
      impersonate: {
        consent: "auth.user.impersonate.consent",
        force: "auth.user.impersonate.force",
      },
    },
  },
  billing: {
    payment: {
      charge: "billing.payment.charge",
    },
  },
  internal: {
    kc: {
      cacert: "internal.kc.cacert",
      issue: "internal.kc.issue",
      keyring: "internal.kc.keyring",
      sign: "internal.kc.sign",
    },
  },
  self: {
    read: "self.read",
    write: "self.write",
  },
} as const;

/**
 * All declared scopes in spec-sorted order.
 */
export const ALL_SCOPES: readonly string[] = [
  "anon.auth.signin.attempt",
  "anon.public.health",
  "auth.password.change",
  "auth.user.impersonate.consent",
  "auth.user.impersonate.force",
  "billing.payment.charge",
  "internal.kc.cacert",
  "internal.kc.issue",
  "internal.kc.keyring",
  "internal.kc.sign",
  "self.read",
  "self.write",
];
