// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/request-context/IRequestContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

import type { CallPathEntry } from "@dcsv-io/d2-auth-context-abstractions";

/**
 * Cross-hop propagated subset of IRequestContext. Identity fields
 * (UserId / OrgId / Scopes / ActorChain) are NOT included — they
 * rebuild from the JWT at every sync hop.
 */
export interface IPropagatedContext {
  readonly requestId?: string;
  readonly requestPath?: string;
  readonly requestStartedAt?: string;
  readonly idempotencyKey?: string;
  readonly sessionFingerprint?: string;
  readonly currentFingerprint?: string;
  readonly riskScore?: number;
  readonly edgeNodeId?: string;
  readonly localeIetfBcp47Tag?: string;
  readonly timezoneIanaName?: string;
  readonly currencyIso4217Code?: string;
  readonly orgPlanTier?: string;
  readonly featureFlagsCsv?: string;
  readonly whoIsHashId?: string;
  readonly callPath?: readonly CallPathEntry[];
}
