// -----------------------------------------------------------------------
// <copyright file="EncryptionDomainsEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.EncryptionDomains.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>EncryptionDomains</c> static class source
/// from a parsed <see cref="EncryptionDomainsSpec"/>.
/// </summary>
internal static class EncryptionDomainsEmitter
{
    /// <summary>The namespace the <c>EncryptionDomains</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.Encryption";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "EncryptionDomains";

    /// <summary>The emitted per-domain encryption-mode enum name.</summary>
    public const string MODE_ENUM_NAME = "EncryptionDomainMode";

    /// <summary>The emitted mode / consumer-service lookup class name.</summary>
    public const string MODES_CLASS_NAME = "EncryptionDomainModes";

    // Defaults kept as public constants for existing unit tests that assert names.
    private const string _MODE_SYMMETRIC = "symmetric";
    private const string _MODE_SEALED = "sealed";

    private static readonly Regex sr_constNameRegex = new(
        "^[A-Z][A-Z0-9_]*$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    private static readonly Regex sr_consumerServiceRegex = new(
        "^[a-z0-9-]{1,64}$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    /// <summary>Emits the EncryptionDomains class source + diagnostics.</summary>
    /// <param name="spec">Parsed encryption-domains spec.</param>
    /// <param name="rootNamespace">Emit namespace (public or private product type).</param>
    /// <param name="className">Emit domains class name.</param>
    /// <param name="modeEnumName">Emit mode enum name.</param>
    /// <param name="modesClassName">Emit modes lookup class name.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(
        EncryptionDomainsSpec spec,
        string? rootNamespace = null,
        string? className = null,
        string? modeEnumName = null,
        string? modesClassName = null)
    {
        var effectiveNamespace = rootNamespace ?? ROOT_NAMESPACE;
        var effectiveClassName = className ?? CLASS_NAME;
        var effectiveModeEnum = modeEnumName ?? MODE_ENUM_NAME;
        var effectiveModesClass = modesClassName ?? MODES_CLASS_NAME;

        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        var validEntries = new List<EncryptionDomainEntry>();
        var seenConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenValues = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.Domains)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (entry.Value.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyValue(entry.ConstName));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateConstName(entry.ConstName));
                continue;
            }

            if (!seenValues.Add(entry.Value))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateValue(entry.Value));
                continue;
            }

            if (!ValidateModeAndConsumer(entry, diagnostics))
                continue;

            validEntries.Add(entry);
        }

        var source = EmitSource(
            validEntries, effectiveNamespace, effectiveClassName, effectiveModeEnum, effectiveModesClass);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(
        List<EncryptionDomainEntry> entries,
        string rootNamespace,
        string className,
        string modeEnumName,
        string modesClassName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.EncryptionDomains.SourceGen.EncryptionDomainsGenerator");
        sb.AppendLine(
            "//   from contracts/encryption-domains/encryption-domains.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived closed catalog of encryption-domain identifiers. Each");
        sb.AppendLine(
            "/// domain corresponds to an independently-rotated keyring registered via");
        sb.AppendLine(
            "/// <c>services.AddD2EncryptionFor(domain, factory)</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Use these constants instead of raw strings so a typo can't silently");
        sb.AppendLine(
            "/// route a message to a non-existent keyring. Adding a new domain is an");
        sb.AppendLine(
            "/// architectural decision that requires KeyCustodian provisioning,");
        sb.AppendLine(
            "/// key-rotation runbook updates, and operator coordination — the spec");
        sb.AppendLine("/// edit forces all parties into the loop.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var first = true;
        foreach (var entry in entries)
        {
            if (!first)
                sb.AppendLine();
            first = false;
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
        }

        if (entries.Count > 0)
            sb.AppendLine();

        EmitAllDomains(sb, entries);

        sb.AppendLine("}");
        sb.AppendLine();
        EmitModeEnum(sb, modeEnumName);
        sb.AppendLine();
        EmitModesClass(sb, entries, modeEnumName, modesClassName);
        return sb.ToString().LfNormalized();
    }

    /// <summary>
    /// Validates an entry's optional <c>mode</c> / <c>consumerService</c> pair.
    /// Appends the relevant fail-loud diagnostic and returns <c>false</c> when
    /// the pair is inconsistent; otherwise returns <c>true</c>.
    /// </summary>
    private static bool ValidateModeAndConsumer(
        EncryptionDomainEntry entry,
        ImmutableArray<EmitDiagnostic>.Builder diagnostics)
    {
        var mode = entry.Mode;

        if (mode is not null
            && !string.Equals(mode, _MODE_SYMMETRIC, StringComparison.Ordinal)
            && !string.Equals(mode, _MODE_SEALED, StringComparison.Ordinal))
        {
            diagnostics.Add(EmitDiagnostics.InvalidMode(entry.ConstName, mode));
            return false;
        }

        var consumer = entry.ConsumerService;

        if (IsSealed(entry))
        {
            if (consumer.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.MissingConsumerService(entry.ConstName));
                return false;
            }

            if (!sr_consumerServiceRegex.IsMatch(consumer!))
            {
                diagnostics.Add(
                    EmitDiagnostics.InvalidConsumerService(entry.ConstName, consumer!));
                return false;
            }

            return true;
        }

        if (consumer.Truthy())
        {
            diagnostics.Add(
                EmitDiagnostics.UnexpectedConsumerService(entry.ConstName, consumer!));
            return false;
        }

        return true;
    }

    /// <summary>True when the entry's mode is <c>sealed</c>.</summary>
    private static bool IsSealed(EncryptionDomainEntry entry) =>
        string.Equals(entry.Mode, _MODE_SEALED, StringComparison.Ordinal);

    private static void EmitModeEnum(StringBuilder sb, string modeEnumName)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Per-domain payload encryption mode. <c>Symmetric</c> = a shared");
        sb.AppendLine(
            "/// keyring AES-256-GCM (version-1 frame) where every grant-holder");
        sb.AppendLine(
            "/// both encrypts and decrypts; <c>Sealed</c> = per-consumer-service");
        sb.AppendLine(
            "/// ephemeral-static ECDH (version-2 frame) where producers seal to a");
        sb.AppendLine(
            "/// recipient service's public key and only that service opens.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public enum {modeEnumName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Shared-keyring symmetric mode (the default).</summary>");
        sb.AppendLine("    Symmetric,");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Per-consumer-service sealed (asymmetric) mode.</summary>");
        sb.AppendLine("    Sealed,");
        sb.AppendLine("}");
    }

    private static void EmitModesClass(
        StringBuilder sb,
        List<EncryptionDomainEntry> entries,
        string modeEnumName,
        string modesClassName)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived per-domain encryption-mode + consumer-service lookups.");
        sb.AppendLine(
            "/// A domain absent from the catalog (e.g. a test-seam synthetic domain)");
        sb.AppendLine(
            "/// resolves to <c>Symmetric</c> — sealed-ness can originate only in the");
        sb.AppendLine(
            "/// spec catalog, so a value that is not a declared sealed domain is by");
        sb.AppendLine("/// construction not sealed.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {modesClassName}");
        sb.AppendLine("{");

        sb.AppendLine(
            "    private static readonly IReadOnlyDictionary<string, "
                + $"{modeEnumName}> sr_modeByDomain =");
        sb.AppendLine(
            $"        new Dictionary<string, {modeEnumName}>(System.StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (var entry in entries)
        {
            var mode = IsSealed(entry) ? "Sealed" : "Symmetric";
            sb.AppendLine(
                $"            {{ \"{EscapeStringLiteral(entry.Value)}\", "
                    + $"{modeEnumName}.{mode} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyDictionary<string, string> "
                + "sr_consumerServiceByDomain =");
        sb.AppendLine(
            "        new Dictionary<string, string>(System.StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (var entry in entries)
        {
            if (!IsSealed(entry))
                continue;

            sb.AppendLine(
                $"            {{ \"{EscapeStringLiteral(entry.Value)}\", "
                    + $"\"{EscapeStringLiteral(entry.ConsumerService!)}\" }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Consumer ServiceId per SEALED domain (the single decryptor). Only");
        sb.AppendLine(
            "    /// sealed domains appear; symmetric / plaintext domains are absent.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static IReadOnlyDictionary<string, string> ConsumerServiceByDomain =>");
        sb.AppendLine("        sr_consumerServiceByDomain;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Resolves the encryption mode for <paramref name=\"domain\"/>. An");
        sb.AppendLine(
            "    /// unknown domain resolves to <c>Symmetric</c> (documented default).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"domain\">The encryption-domain wire value.</param>");
        sb.AppendLine("    /// <returns>The domain's mode, or <c>Symmetric</c> when unknown.</returns>");
        sb.AppendLine($"    public static {modeEnumName} ModeFor(string domain) =>");
        sb.AppendLine("        sr_modeByDomain.TryGetValue(domain, out var mode)");
        sb.AppendLine("            ? mode");
        sb.AppendLine($"            : {modeEnumName}.Symmetric;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Gets the consumer ServiceId for a sealed <paramref name=\"domain\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"domain\">The encryption-domain wire value.</param>");
        sb.AppendLine(
            "    /// <param name=\"consumerService\">The resolved consumer ServiceId "
                + "when sealed; <c>string.Empty</c> otherwise.</param>");
        sb.AppendLine(
            "    /// <returns><c>true</c> when the domain is sealed and mapped; "
                + "otherwise <c>false</c>.</returns>");
        sb.AppendLine(
            "    public static bool TryGetConsumerService(string domain, out string consumerService)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (sr_consumerServiceByDomain.TryGetValue(domain, out var svc))");
        sb.AppendLine("        {");
        sb.AppendLine("            consumerService = svc;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        consumerService = string.Empty;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitAllDomains(StringBuilder sb, List<EncryptionDomainEntry> entries)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// All declared encryption-domain wire-values in spec order.");
        sb.AppendLine(
            "    /// Useful for cross-spec consistency tests (e.g. validating");
        sb.AppendLine(
            "    /// mq-messages.spec's 'encryption' field values against the");
        sb.AppendLine("    /// catalog).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static IReadOnlyList<string> AllDomains => sr_allDomains;");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyList<string> sr_allDomains = new string[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
            sb.AppendLine($"        \"{EscapeStringLiteral(entry.Value)}\",");

        sb.AppendLine("    };");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
