// -----------------------------------------------------------------------
// <copyright file="20260326190046_AddTimezones.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Geo.Infra.Repository.Migrations;

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional
/// <inheritdoc />
public partial class AddTimezones : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "timezones",
            columns: table => new
            {
                iana_identifier = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                display_name = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                utc_offset_std = table.Column<string>(type: "character varying(7)", maxLength: 7, nullable: false),
                utc_offset_dst = table.Column<string>(type: "character varying(7)", maxLength: 7, nullable: true),
                abbreviation_std = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                abbreviation_dst = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true),
                country_iso_3166_1_alpha_2_code = table.Column<string>(type: "character varying(2)", maxLength: 2, nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_timezones", x => x.iana_identifier);
                table.ForeignKey(
                    name: "FK_timezones_countries_country_iso_3166_1_alpha_2_code",
                    column: x => x.country_iso_3166_1_alpha_2_code,
                    principalTable: "countries",
                    principalColumn: "iso_3166_1_alpha_2_code",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.UpdateData(
            table: "reference_data_version",
            keyColumn: "id",
            keyValue: 0,
            columns: new[] { "updated_at", "version" },
            values: new object[] { new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc), "1.5.0" });

        migrationBuilder.InsertData(
            table: "timezones",
            columns: new[] { "iana_identifier", "abbreviation_dst", "abbreviation_std", "country_iso_3166_1_alpha_2_code", "display_name", "utc_offset_dst", "utc_offset_std" },
            values: new object[,]
            {
                { "Africa/Abidjan", null, "GMT", "CI", "Africa / Abidjan", null, "+00:00" },
                { "Africa/Algiers", null, "CET", "DZ", "Africa / Algiers", null, "+01:00" },
                { "Africa/Bissau", null, "GMT", "GW", "Africa / Bissau", null, "+00:00" },
                { "Africa/Cairo", "EEST", "EET", "EG", "Africa / Cairo", "+03:00", "+02:00" },
                { "Africa/Casablanca", "+00", "+01", "MA", "Africa / Casablanca", "+00:00", "+01:00" },
                { "Africa/Ceuta", "CEST", "CET", "ES", "Africa / Ceuta", "+02:00", "+01:00" },
                { "Africa/El_Aaiun", "+00", "+01", "EH", "Africa / El Aaiun", "+00:00", "+01:00" },
                { "Africa/Johannesburg", null, "SAST", "ZA", "Africa / Johannesburg", null, "+02:00" },
                { "Africa/Juba", null, "CAT", "SS", "Africa / Juba", null, "+02:00" },
                { "Africa/Khartoum", null, "CAT", "SD", "Africa / Khartoum", null, "+02:00" },
                { "Africa/Lagos", null, "WAT", "NG", "Africa / Lagos", null, "+01:00" },
                { "Africa/Maputo", null, "CAT", "MZ", "Africa / Maputo", null, "+02:00" },
                { "Africa/Monrovia", null, "GMT", "LR", "Africa / Monrovia", null, "+00:00" },
                { "Africa/Nairobi", null, "EAT", "KE", "Africa / Nairobi", null, "+03:00" },
                { "Africa/Ndjamena", null, "WAT", "TD", "Africa / Ndjamena", null, "+01:00" },
                { "Africa/Sao_Tome", null, "GMT", "ST", "Africa / Sao Tome", null, "+00:00" },
                { "Africa/Tripoli", null, "EET", "LY", "Africa / Tripoli", null, "+02:00" },
                { "Africa/Tunis", null, "CET", "TN", "Africa / Tunis", null, "+01:00" },
                { "Africa/Windhoek", null, "CAT", "NA", "Africa / Windhoek", null, "+02:00" },
                { "America/Adak", "HDT", "HST", "US", "America / Adak", "-09:00", "-10:00" },
                { "America/Anchorage", "AKDT", "AKST", "US", "America / Anchorage", "-08:00", "-09:00" },
                { "America/Araguaina", null, "-03", "BR", "America / Araguaina", null, "-03:00" },
                { "America/Argentina/Buenos_Aires", null, "-03", "AR", "America / Argentina / Buenos Aires", null, "-03:00" },
                { "America/Argentina/Catamarca", null, "-03", "AR", "America / Argentina / Catamarca", null, "-03:00" },
                { "America/Argentina/Cordoba", null, "-03", "AR", "America / Argentina / Cordoba", null, "-03:00" },
                { "America/Argentina/Jujuy", null, "-03", "AR", "America / Argentina / Jujuy", null, "-03:00" },
                { "America/Argentina/La_Rioja", null, "-03", "AR", "America / Argentina / La Rioja", null, "-03:00" },
                { "America/Argentina/Mendoza", null, "-03", "AR", "America / Argentina / Mendoza", null, "-03:00" },
                { "America/Argentina/Rio_Gallegos", null, "-03", "AR", "America / Argentina / Rio Gallegos", null, "-03:00" },
                { "America/Argentina/Salta", null, "-03", "AR", "America / Argentina / Salta", null, "-03:00" },
                { "America/Argentina/San_Juan", null, "-03", "AR", "America / Argentina / San Juan", null, "-03:00" },
                { "America/Argentina/San_Luis", null, "-03", "AR", "America / Argentina / San Luis", null, "-03:00" },
                { "America/Argentina/Tucuman", null, "-03", "AR", "America / Argentina / Tucuman", null, "-03:00" },
                { "America/Argentina/Ushuaia", null, "-03", "AR", "America / Argentina / Ushuaia", null, "-03:00" },
                { "America/Asuncion", null, "-03", "PY", "America / Asuncion", null, "-03:00" },
                { "America/Bahia", null, "-03", "BR", "America / Bahia", null, "-03:00" },
                { "America/Bahia_Banderas", null, "CST", "MX", "America / Bahia Banderas", null, "-06:00" },
                { "America/Barbados", null, "AST", "BB", "America / Barbados", null, "-04:00" },
                { "America/Belem", null, "-03", "BR", "America / Belem", null, "-03:00" },
                { "America/Belize", null, "CST", "BZ", "America / Belize", null, "-06:00" },
                { "America/Boa_Vista", null, "-04", "BR", "America / Boa Vista", null, "-04:00" },
                { "America/Bogota", null, "-05", "CO", "America / Bogota", null, "-05:00" },
                { "America/Boise", "MDT", "MST", "US", "America / Boise", "-06:00", "-07:00" },
                { "America/Cambridge_Bay", "MDT", "MST", "CA", "America / Cambridge Bay", "-06:00", "-07:00" },
                { "America/Campo_Grande", null, "-04", "BR", "America / Campo Grande", null, "-04:00" },
                { "America/Cancun", null, "EST", "MX", "America / Cancun", null, "-05:00" },
                { "America/Caracas", null, "-04", "VE", "America / Caracas", null, "-04:00" },
                { "America/Cayenne", null, "-03", "GF", "America / Cayenne", null, "-03:00" },
                { "America/Chicago", "CDT", "CST", "US", "America / Chicago", "-05:00", "-06:00" },
                { "America/Chihuahua", null, "CST", "MX", "America / Chihuahua", null, "-06:00" },
                { "America/Ciudad_Juarez", "MDT", "MST", "MX", "America / Ciudad Juarez", "-06:00", "-07:00" },
                { "America/Costa_Rica", null, "CST", "CR", "America / Costa Rica", null, "-06:00" },
                { "America/Coyhaique", null, "-03", "CL", "America / Coyhaique", null, "-03:00" },
                { "America/Cuiaba", null, "-04", "BR", "America / Cuiaba", null, "-04:00" },
                { "America/Danmarkshavn", null, "GMT", "GL", "America / Danmarkshavn", null, "+00:00" },
                { "America/Dawson", null, "MST", "CA", "America / Dawson", null, "-07:00" },
                { "America/Dawson_Creek", null, "MST", "CA", "America / Dawson Creek", null, "-07:00" },
                { "America/Denver", "MDT", "MST", "US", "America / Denver", "-06:00", "-07:00" },
                { "America/Detroit", "EDT", "EST", "US", "America / Detroit", "-04:00", "-05:00" },
                { "America/Edmonton", "MDT", "MST", "CA", "America / Edmonton", "-06:00", "-07:00" },
                { "America/Eirunepe", null, "-05", "BR", "America / Eirunepe", null, "-05:00" },
                { "America/El_Salvador", null, "CST", "SV", "America / El Salvador", null, "-06:00" },
                { "America/Fort_Nelson", null, "MST", "CA", "America / Fort Nelson", null, "-07:00" },
                { "America/Fortaleza", null, "-03", "BR", "America / Fortaleza", null, "-03:00" },
                { "America/Glace_Bay", "ADT", "AST", "CA", "America / Glace Bay", "-03:00", "-04:00" },
                { "America/Goose_Bay", "ADT", "AST", "CA", "America / Goose Bay", "-03:00", "-04:00" },
                { "America/Grand_Turk", "EDT", "EST", "TC", "America / Grand Turk", "-04:00", "-05:00" },
                { "America/Guatemala", null, "CST", "GT", "America / Guatemala", null, "-06:00" },
                { "America/Guayaquil", null, "-05", "EC", "America / Guayaquil", null, "-05:00" },
                { "America/Guyana", null, "-04", "GY", "America / Guyana", null, "-04:00" },
                { "America/Halifax", "ADT", "AST", "CA", "America / Halifax", "-03:00", "-04:00" },
                { "America/Havana", "CDT", "CST", "CU", "America / Havana", "-04:00", "-05:00" },
                { "America/Hermosillo", null, "MST", "MX", "America / Hermosillo", null, "-07:00" },
                { "America/Indiana/Indianapolis", "EDT", "EST", "US", "America / Indiana / Indianapolis", "-04:00", "-05:00" },
                { "America/Indiana/Knox", "CDT", "CST", "US", "America / Indiana / Knox", "-05:00", "-06:00" },
                { "America/Indiana/Marengo", "EDT", "EST", "US", "America / Indiana / Marengo", "-04:00", "-05:00" },
                { "America/Indiana/Petersburg", "EDT", "EST", "US", "America / Indiana / Petersburg", "-04:00", "-05:00" },
                { "America/Indiana/Tell_City", "CDT", "CST", "US", "America / Indiana / Tell City", "-05:00", "-06:00" },
                { "America/Indiana/Vevay", "EDT", "EST", "US", "America / Indiana / Vevay", "-04:00", "-05:00" },
                { "America/Indiana/Vincennes", "EDT", "EST", "US", "America / Indiana / Vincennes", "-04:00", "-05:00" },
                { "America/Indiana/Winamac", "EDT", "EST", "US", "America / Indiana / Winamac", "-04:00", "-05:00" },
                { "America/Inuvik", "MDT", "MST", "CA", "America / Inuvik", "-06:00", "-07:00" },
                { "America/Iqaluit", "EDT", "EST", "CA", "America / Iqaluit", "-04:00", "-05:00" },
                { "America/Jamaica", null, "EST", "JM", "America / Jamaica", null, "-05:00" },
                { "America/Juneau", "AKDT", "AKST", "US", "America / Juneau", "-08:00", "-09:00" },
                { "America/Kentucky/Louisville", "EDT", "EST", "US", "America / Kentucky / Louisville", "-04:00", "-05:00" },
                { "America/Kentucky/Monticello", "EDT", "EST", "US", "America / Kentucky / Monticello", "-04:00", "-05:00" },
                { "America/La_Paz", null, "-04", "BO", "America / La Paz", null, "-04:00" },
                { "America/Lima", null, "-05", "PE", "America / Lima", null, "-05:00" },
                { "America/Los_Angeles", "PDT", "PST", "US", "America / Los Angeles", "-07:00", "-08:00" },
                { "America/Maceio", null, "-03", "BR", "America / Maceio", null, "-03:00" },
                { "America/Managua", null, "CST", "NI", "America / Managua", null, "-06:00" },
                { "America/Manaus", null, "-04", "BR", "America / Manaus", null, "-04:00" },
                { "America/Martinique", null, "AST", "MQ", "America / Martinique", null, "-04:00" },
                { "America/Matamoros", "CDT", "CST", "MX", "America / Matamoros", "-05:00", "-06:00" },
                { "America/Mazatlan", null, "MST", "MX", "America / Mazatlan", null, "-07:00" },
                { "America/Menominee", "CDT", "CST", "US", "America / Menominee", "-05:00", "-06:00" },
                { "America/Merida", null, "CST", "MX", "America / Merida", null, "-06:00" },
                { "America/Metlakatla", "AKDT", "AKST", "US", "America / Metlakatla", "-08:00", "-09:00" },
                { "America/Mexico_City", null, "CST", "MX", "America / Mexico City", null, "-06:00" },
                { "America/Miquelon", "-02", "-03", "PM", "America / Miquelon", "-02:00", "-03:00" },
                { "America/Moncton", "ADT", "AST", "CA", "America / Moncton", "-03:00", "-04:00" },
                { "America/Monterrey", null, "CST", "MX", "America / Monterrey", null, "-06:00" },
                { "America/Montevideo", null, "-03", "UY", "America / Montevideo", null, "-03:00" },
                { "America/New_York", "EDT", "EST", "US", "America / New York", "-04:00", "-05:00" },
                { "America/Nome", "AKDT", "AKST", "US", "America / Nome", "-08:00", "-09:00" },
                { "America/Noronha", null, "-02", "BR", "America / Noronha", null, "-02:00" },
                { "America/North_Dakota/Beulah", "CDT", "CST", "US", "America / North Dakota / Beulah", "-05:00", "-06:00" },
                { "America/North_Dakota/Center", "CDT", "CST", "US", "America / North Dakota / Center", "-05:00", "-06:00" },
                { "America/North_Dakota/New_Salem", "CDT", "CST", "US", "America / North Dakota / New Salem", "-05:00", "-06:00" },
                { "America/Nuuk", "-01", "-02", "GL", "America / Nuuk", "-01:00", "-02:00" },
                { "America/Ojinaga", "CDT", "CST", "MX", "America / Ojinaga", "-05:00", "-06:00" },
                { "America/Panama", null, "EST", "PA", "America / Panama", null, "-05:00" },
                { "America/Paramaribo", null, "-03", "SR", "America / Paramaribo", null, "-03:00" },
                { "America/Phoenix", null, "MST", "US", "America / Phoenix", null, "-07:00" },
                { "America/Port-au-Prince", "EDT", "EST", "HT", "America / Port-au-Prince", "-04:00", "-05:00" },
                { "America/Porto_Velho", null, "-04", "BR", "America / Porto Velho", null, "-04:00" },
                { "America/Puerto_Rico", null, "AST", "PR", "America / Puerto Rico", null, "-04:00" },
                { "America/Punta_Arenas", null, "-03", "CL", "America / Punta Arenas", null, "-03:00" },
                { "America/Rankin_Inlet", "CDT", "CST", "CA", "America / Rankin Inlet", "-05:00", "-06:00" },
                { "America/Recife", null, "-03", "BR", "America / Recife", null, "-03:00" },
                { "America/Regina", null, "CST", "CA", "America / Regina", null, "-06:00" },
                { "America/Resolute", "CDT", "CST", "CA", "America / Resolute", "-05:00", "-06:00" },
                { "America/Rio_Branco", null, "-05", "BR", "America / Rio Branco", null, "-05:00" },
                { "America/Santarem", null, "-03", "BR", "America / Santarem", null, "-03:00" },
                { "America/Santiago", "-03", "-04", "CL", "America / Santiago", "-03:00", "-04:00" },
                { "America/Santo_Domingo", null, "AST", "DO", "America / Santo Domingo", null, "-04:00" },
                { "America/Sao_Paulo", null, "-03", "BR", "America / Sao Paulo", null, "-03:00" },
                { "America/Scoresbysund", "-01", "-02", "GL", "America / Scoresbysund", "-01:00", "-02:00" },
                { "America/Sitka", "AKDT", "AKST", "US", "America / Sitka", "-08:00", "-09:00" },
                { "America/St_Johns", "NDT", "NST", "CA", "America / St Johns", "-02:30", "-03:30" },
                { "America/Swift_Current", null, "CST", "CA", "America / Swift Current", null, "-06:00" },
                { "America/Tegucigalpa", null, "CST", "HN", "America / Tegucigalpa", null, "-06:00" },
                { "America/Thule", "ADT", "AST", "GL", "America / Thule", "-03:00", "-04:00" },
                { "America/Tijuana", "PDT", "PST", "MX", "America / Tijuana", "-07:00", "-08:00" },
                { "America/Toronto", "EDT", "EST", "CA", "America / Toronto", "-04:00", "-05:00" },
                { "America/Vancouver", "PDT", "PST", "CA", "America / Vancouver", "-07:00", "-08:00" },
                { "America/Whitehorse", null, "MST", "CA", "America / Whitehorse", null, "-07:00" },
                { "America/Winnipeg", "CDT", "CST", "CA", "America / Winnipeg", "-05:00", "-06:00" },
                { "America/Yakutat", "AKDT", "AKST", "US", "America / Yakutat", "-08:00", "-09:00" },
                { "Antarctica/Casey", null, "+08", "AQ", "Antarctica / Casey", null, "+08:00" },
                { "Antarctica/Davis", null, "+07", "AQ", "Antarctica / Davis", null, "+07:00" },
                { "Antarctica/Macquarie", "AEDT", "AEST", "AU", "Antarctica / Macquarie", "+11:00", "+10:00" },
                { "Antarctica/Mawson", null, "+05", "AQ", "Antarctica / Mawson", null, "+05:00" },
                { "Antarctica/Palmer", null, "-03", "AQ", "Antarctica / Palmer", null, "-03:00" },
                { "Antarctica/Rothera", null, "-03", "AQ", "Antarctica / Rothera", null, "-03:00" },
                { "Antarctica/Troll", "+02", "+00", "AQ", "Antarctica / Troll", "+02:00", "+00:00" },
                { "Antarctica/Vostok", null, "+05", "AQ", "Antarctica / Vostok", null, "+05:00" },
                { "Asia/Almaty", null, "+05", "KZ", "Asia / Almaty", null, "+05:00" },
                { "Asia/Amman", null, "+03", "JO", "Asia / Amman", null, "+03:00" },
                { "Asia/Anadyr", null, "+12", "RU", "Asia / Anadyr", null, "+12:00" },
                { "Asia/Aqtau", null, "+05", "KZ", "Asia / Aqtau", null, "+05:00" },
                { "Asia/Aqtobe", null, "+05", "KZ", "Asia / Aqtobe", null, "+05:00" },
                { "Asia/Ashgabat", null, "+05", "TM", "Asia / Ashgabat", null, "+05:00" },
                { "Asia/Atyrau", null, "+05", "KZ", "Asia / Atyrau", null, "+05:00" },
                { "Asia/Baghdad", null, "+03", "IQ", "Asia / Baghdad", null, "+03:00" },
                { "Asia/Baku", null, "+04", "AZ", "Asia / Baku", null, "+04:00" },
                { "Asia/Bangkok", null, "+07", "TH", "Asia / Bangkok", null, "+07:00" },
                { "Asia/Barnaul", null, "+07", "RU", "Asia / Barnaul", null, "+07:00" },
                { "Asia/Beirut", "EEST", "EET", "LB", "Asia / Beirut", "+03:00", "+02:00" },
                { "Asia/Bishkek", null, "+06", "KG", "Asia / Bishkek", null, "+06:00" },
                { "Asia/Colombo", null, "+0530", "LK", "Asia / Colombo", null, "+05:30" },
                { "Asia/Damascus", null, "+03", "SY", "Asia / Damascus", null, "+03:00" },
                { "Asia/Dhaka", null, "+06", "BD", "Asia / Dhaka", null, "+06:00" },
                { "Asia/Dili", null, "+09", "TL", "Asia / Dili", null, "+09:00" },
                { "Asia/Dubai", null, "+04", "AE", "Asia / Dubai", null, "+04:00" },
                { "Asia/Dushanbe", null, "+05", "TJ", "Asia / Dushanbe", null, "+05:00" },
                { "Asia/Famagusta", "EEST", "EET", "CY", "Asia / Famagusta", "+03:00", "+02:00" },
                { "Asia/Gaza", "EEST", "EET", "PS", "Asia / Gaza", "+03:00", "+02:00" },
                { "Asia/Hebron", "EEST", "EET", "PS", "Asia / Hebron", "+03:00", "+02:00" },
                { "Asia/Ho_Chi_Minh", null, "+07", "VN", "Asia / Ho Chi Minh", null, "+07:00" },
                { "Asia/Hong_Kong", null, "HKT", "HK", "Asia / Hong Kong", null, "+08:00" },
                { "Asia/Hovd", null, "+07", "MN", "Asia / Hovd", null, "+07:00" },
                { "Asia/Irkutsk", null, "+08", "RU", "Asia / Irkutsk", null, "+08:00" },
                { "Asia/Jakarta", null, "WIB", "ID", "Asia / Jakarta", null, "+07:00" },
                { "Asia/Jayapura", null, "WIT", "ID", "Asia / Jayapura", null, "+09:00" },
                { "Asia/Jerusalem", "IDT", "IST", "IL", "Asia / Jerusalem", "+03:00", "+02:00" },
                { "Asia/Kabul", null, "+0430", "AF", "Asia / Kabul", null, "+04:30" },
                { "Asia/Kamchatka", null, "+12", "RU", "Asia / Kamchatka", null, "+12:00" },
                { "Asia/Karachi", null, "PKT", "PK", "Asia / Karachi", null, "+05:00" },
                { "Asia/Kathmandu", null, "+0545", "NP", "Asia / Kathmandu", null, "+05:45" },
                { "Asia/Khandyga", null, "+09", "RU", "Asia / Khandyga", null, "+09:00" },
                { "Asia/Kolkata", null, "IST", "IN", "Asia / Kolkata", null, "+05:30" },
                { "Asia/Krasnoyarsk", null, "+07", "RU", "Asia / Krasnoyarsk", null, "+07:00" },
                { "Asia/Kuching", null, "+08", "MY", "Asia / Kuching", null, "+08:00" },
                { "Asia/Macau", null, "CST", "MO", "Asia / Macau", null, "+08:00" },
                { "Asia/Magadan", null, "+11", "RU", "Asia / Magadan", null, "+11:00" },
                { "Asia/Makassar", null, "WITA", "ID", "Asia / Makassar", null, "+08:00" },
                { "Asia/Manila", null, "PST", "PH", "Asia / Manila", null, "+08:00" },
                { "Asia/Nicosia", "EEST", "EET", "CY", "Asia / Nicosia", "+03:00", "+02:00" },
                { "Asia/Novokuznetsk", null, "+07", "RU", "Asia / Novokuznetsk", null, "+07:00" },
                { "Asia/Novosibirsk", null, "+07", "RU", "Asia / Novosibirsk", null, "+07:00" },
                { "Asia/Omsk", null, "+06", "RU", "Asia / Omsk", null, "+06:00" },
                { "Asia/Oral", null, "+05", "KZ", "Asia / Oral", null, "+05:00" },
                { "Asia/Pontianak", null, "WIB", "ID", "Asia / Pontianak", null, "+07:00" },
                { "Asia/Pyongyang", null, "KST", "KP", "Asia / Pyongyang", null, "+09:00" },
                { "Asia/Qatar", null, "+03", "QA", "Asia / Qatar", null, "+03:00" },
                { "Asia/Qostanay", null, "+05", "KZ", "Asia / Qostanay", null, "+05:00" },
                { "Asia/Qyzylorda", null, "+05", "KZ", "Asia / Qyzylorda", null, "+05:00" },
                { "Asia/Riyadh", null, "+03", "SA", "Asia / Riyadh", null, "+03:00" },
                { "Asia/Sakhalin", null, "+11", "RU", "Asia / Sakhalin", null, "+11:00" },
                { "Asia/Samarkand", null, "+05", "UZ", "Asia / Samarkand", null, "+05:00" },
                { "Asia/Seoul", null, "KST", "KR", "Asia / Seoul", null, "+09:00" },
                { "Asia/Shanghai", null, "CST", "CN", "Asia / Shanghai", null, "+08:00" },
                { "Asia/Singapore", null, "+08", "SG", "Asia / Singapore", null, "+08:00" },
                { "Asia/Srednekolymsk", null, "+11", "RU", "Asia / Srednekolymsk", null, "+11:00" },
                { "Asia/Taipei", null, "CST", "TW", "Asia / Taipei", null, "+08:00" },
                { "Asia/Tashkent", null, "+05", "UZ", "Asia / Tashkent", null, "+05:00" },
                { "Asia/Tbilisi", null, "+04", "GE", "Asia / Tbilisi", null, "+04:00" },
                { "Asia/Tehran", null, "+0330", "IR", "Asia / Tehran", null, "+03:30" },
                { "Asia/Thimphu", null, "+06", "BT", "Asia / Thimphu", null, "+06:00" },
                { "Asia/Tokyo", null, "JST", "JP", "Asia / Tokyo", null, "+09:00" },
                { "Asia/Tomsk", null, "+07", "RU", "Asia / Tomsk", null, "+07:00" },
                { "Asia/Ulaanbaatar", null, "+08", "MN", "Asia / Ulaanbaatar", null, "+08:00" },
                { "Asia/Urumqi", null, "+06", "CN", "Asia / Urumqi", null, "+06:00" },
                { "Asia/Ust-Nera", null, "+10", "RU", "Asia / Ust-Nera", null, "+10:00" },
                { "Asia/Vladivostok", null, "+10", "RU", "Asia / Vladivostok", null, "+10:00" },
                { "Asia/Yakutsk", null, "+09", "RU", "Asia / Yakutsk", null, "+09:00" },
                { "Asia/Yangon", null, "+0630", "MM", "Asia / Yangon", null, "+06:30" },
                { "Asia/Yekaterinburg", null, "+05", "RU", "Asia / Yekaterinburg", null, "+05:00" },
                { "Asia/Yerevan", null, "+04", "AM", "Asia / Yerevan", null, "+04:00" },
                { "Atlantic/Azores", "+00", "-01", "PT", "Atlantic / Azores", "+00:00", "-01:00" },
                { "Atlantic/Bermuda", "ADT", "AST", "BM", "Atlantic / Bermuda", "-03:00", "-04:00" },
                { "Atlantic/Cape_Verde", null, "-01", "CV", "Atlantic / Cape Verde", null, "-01:00" },
                { "Atlantic/Faroe", "WEST", "WET", "FO", "Atlantic / Faroe", "+01:00", "+00:00" },
                { "Atlantic/Madeira", "WEST", "WET", "PT", "Atlantic / Madeira", "+01:00", "+00:00" },
                { "Atlantic/South_Georgia", null, "-02", "GS", "Atlantic / South Georgia", null, "-02:00" },
                { "Atlantic/Stanley", null, "-03", "FK", "Atlantic / Stanley", null, "-03:00" },
                { "Australia/Adelaide", "ACDT", "ACST", "AU", "Australia / Adelaide", "+10:30", "+09:30" },
                { "Australia/Brisbane", null, "AEST", "AU", "Australia / Brisbane", null, "+10:00" },
                { "Australia/Broken_Hill", "ACDT", "ACST", "AU", "Australia / Broken Hill", "+10:30", "+09:30" },
                { "Australia/Darwin", null, "ACST", "AU", "Australia / Darwin", null, "+09:30" },
                { "Australia/Eucla", null, "+0845", "AU", "Australia / Eucla", null, "+08:45" },
                { "Australia/Hobart", "AEDT", "AEST", "AU", "Australia / Hobart", "+11:00", "+10:00" },
                { "Australia/Lindeman", null, "AEST", "AU", "Australia / Lindeman", null, "+10:00" },
                { "Australia/Lord_Howe", "+11", "+1030", "AU", "Australia / Lord Howe", "+11:00", "+10:30" },
                { "Australia/Melbourne", "AEDT", "AEST", "AU", "Australia / Melbourne", "+11:00", "+10:00" },
                { "Australia/Perth", null, "AWST", "AU", "Australia / Perth", null, "+08:00" },
                { "Australia/Sydney", "AEDT", "AEST", "AU", "Australia / Sydney", "+11:00", "+10:00" },
                { "Europe/Andorra", "CEST", "CET", "AD", "Europe / Andorra", "+02:00", "+01:00" },
                { "Europe/Astrakhan", null, "+04", "RU", "Europe / Astrakhan", null, "+04:00" },
                { "Europe/Athens", "EEST", "EET", "GR", "Europe / Athens", "+03:00", "+02:00" },
                { "Europe/Belgrade", "CEST", "CET", "RS", "Europe / Belgrade", "+02:00", "+01:00" },
                { "Europe/Berlin", "CEST", "CET", "DE", "Europe / Berlin", "+02:00", "+01:00" },
                { "Europe/Brussels", "CEST", "CET", "BE", "Europe / Brussels", "+02:00", "+01:00" },
                { "Europe/Bucharest", "EEST", "EET", "RO", "Europe / Bucharest", "+03:00", "+02:00" },
                { "Europe/Budapest", "CEST", "CET", "HU", "Europe / Budapest", "+02:00", "+01:00" },
                { "Europe/Chisinau", "EEST", "EET", "MD", "Europe / Chisinau", "+03:00", "+02:00" },
                { "Europe/Dublin", "IST", "GMT", "IE", "Europe / Dublin", "+01:00", "+00:00" },
                { "Europe/Gibraltar", "CEST", "CET", "GI", "Europe / Gibraltar", "+02:00", "+01:00" },
                { "Europe/Helsinki", "EEST", "EET", "FI", "Europe / Helsinki", "+03:00", "+02:00" },
                { "Europe/Istanbul", null, "+03", "TR", "Europe / Istanbul", null, "+03:00" },
                { "Europe/Kaliningrad", null, "EET", "RU", "Europe / Kaliningrad", null, "+02:00" },
                { "Europe/Kirov", null, "MSK", "RU", "Europe / Kirov", null, "+03:00" },
                { "Europe/Kyiv", "EEST", "EET", "UA", "Europe / Kyiv", "+03:00", "+02:00" },
                { "Europe/Lisbon", "WEST", "WET", "PT", "Europe / Lisbon", "+01:00", "+00:00" },
                { "Europe/London", "BST", "GMT", "GB", "Europe / London", "+01:00", "+00:00" },
                { "Europe/Madrid", "CEST", "CET", "ES", "Europe / Madrid", "+02:00", "+01:00" },
                { "Europe/Malta", "CEST", "CET", "MT", "Europe / Malta", "+02:00", "+01:00" },
                { "Europe/Minsk", null, "+03", "BY", "Europe / Minsk", null, "+03:00" },
                { "Europe/Moscow", null, "MSK", "RU", "Europe / Moscow", null, "+03:00" },
                { "Europe/Paris", "CEST", "CET", "FR", "Europe / Paris", "+02:00", "+01:00" },
                { "Europe/Prague", "CEST", "CET", "CZ", "Europe / Prague", "+02:00", "+01:00" },
                { "Europe/Riga", "EEST", "EET", "LV", "Europe / Riga", "+03:00", "+02:00" },
                { "Europe/Rome", "CEST", "CET", "IT", "Europe / Rome", "+02:00", "+01:00" },
                { "Europe/Samara", null, "+04", "RU", "Europe / Samara", null, "+04:00" },
                { "Europe/Saratov", null, "+04", "RU", "Europe / Saratov", null, "+04:00" },
                { "Europe/Simferopol", null, "MSK", "RU", "Europe / Simferopol", null, "+03:00" },
                { "Europe/Sofia", "EEST", "EET", "BG", "Europe / Sofia", "+03:00", "+02:00" },
                { "Europe/Tallinn", "EEST", "EET", "EE", "Europe / Tallinn", "+03:00", "+02:00" },
                { "Europe/Tirane", "CEST", "CET", "AL", "Europe / Tirane", "+02:00", "+01:00" },
                { "Europe/Ulyanovsk", null, "+04", "RU", "Europe / Ulyanovsk", null, "+04:00" },
                { "Europe/Vienna", "CEST", "CET", "AT", "Europe / Vienna", "+02:00", "+01:00" },
                { "Europe/Vilnius", "EEST", "EET", "LT", "Europe / Vilnius", "+03:00", "+02:00" },
                { "Europe/Volgograd", null, "MSK", "RU", "Europe / Volgograd", null, "+03:00" },
                { "Europe/Warsaw", "CEST", "CET", "PL", "Europe / Warsaw", "+02:00", "+01:00" },
                { "Europe/Zurich", "CEST", "CET", "CH", "Europe / Zurich", "+02:00", "+01:00" },
                { "Indian/Chagos", null, "+06", "IO", "Indian / Chagos", null, "+06:00" },
                { "Indian/Maldives", null, "+05", "MV", "Indian / Maldives", null, "+05:00" },
                { "Indian/Mauritius", null, "+04", "MU", "Indian / Mauritius", null, "+04:00" },
                { "Pacific/Apia", null, "+13", "WS", "Pacific / Apia", null, "+13:00" },
                { "Pacific/Auckland", "NZDT", "NZST", "NZ", "Pacific / Auckland", "+13:00", "+12:00" },
                { "Pacific/Bougainville", null, "+11", "PG", "Pacific / Bougainville", null, "+11:00" },
                { "Pacific/Chatham", "+1345", "+1245", "NZ", "Pacific / Chatham", "+13:45", "+12:45" },
                { "Pacific/Easter", "-05", "-06", "CL", "Pacific / Easter", "-05:00", "-06:00" },
                { "Pacific/Efate", null, "+11", "VU", "Pacific / Efate", null, "+11:00" },
                { "Pacific/Fakaofo", null, "+13", "TK", "Pacific / Fakaofo", null, "+13:00" },
                { "Pacific/Fiji", null, "+12", "FJ", "Pacific / Fiji", null, "+12:00" },
                { "Pacific/Galapagos", null, "-06", "EC", "Pacific / Galapagos", null, "-06:00" },
                { "Pacific/Gambier", null, "-09", "PF", "Pacific / Gambier", null, "-09:00" },
                { "Pacific/Guadalcanal", null, "+11", "SB", "Pacific / Guadalcanal", null, "+11:00" },
                { "Pacific/Guam", null, "ChST", "GU", "Pacific / Guam", null, "+10:00" },
                { "Pacific/Honolulu", null, "HST", "US", "Pacific / Honolulu", null, "-10:00" },
                { "Pacific/Kanton", null, "+13", "KI", "Pacific / Kanton", null, "+13:00" },
                { "Pacific/Kiritimati", null, "+14", "KI", "Pacific / Kiritimati", null, "+14:00" },
                { "Pacific/Kosrae", null, "+11", "FM", "Pacific / Kosrae", null, "+11:00" },
                { "Pacific/Kwajalein", null, "+12", "MH", "Pacific / Kwajalein", null, "+12:00" },
                { "Pacific/Marquesas", null, "-0930", "PF", "Pacific / Marquesas", null, "-09:30" },
                { "Pacific/Nauru", null, "+12", "NR", "Pacific / Nauru", null, "+12:00" },
                { "Pacific/Niue", null, "-11", "NU", "Pacific / Niue", null, "-11:00" },
                { "Pacific/Norfolk", "+12", "+11", "NF", "Pacific / Norfolk", "+12:00", "+11:00" },
                { "Pacific/Noumea", null, "+11", "NC", "Pacific / Noumea", null, "+11:00" },
                { "Pacific/Pago_Pago", null, "SST", "AS", "Pacific / Pago Pago", null, "-11:00" },
                { "Pacific/Palau", null, "+09", "PW", "Pacific / Palau", null, "+09:00" },
                { "Pacific/Pitcairn", null, "-08", "PN", "Pacific / Pitcairn", null, "-08:00" },
                { "Pacific/Port_Moresby", null, "+10", "PG", "Pacific / Port Moresby", null, "+10:00" },
                { "Pacific/Rarotonga", null, "-10", "CK", "Pacific / Rarotonga", null, "-10:00" },
                { "Pacific/Tarawa", null, "+12", "KI", "Pacific / Tarawa", null, "+12:00" },
                { "Pacific/Tongatapu", null, "+13", "TO", "Pacific / Tongatapu", null, "+13:00" },
            });

        migrationBuilder.CreateIndex(
            name: "IX_timezones_country_iso_3166_1_alpha_2_code",
            table: "timezones",
            column: "country_iso_3166_1_alpha_2_code");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "timezones");

        migrationBuilder.UpdateData(
            table: "reference_data_version",
            keyColumn: "id",
            keyValue: 0,
            columns: new[] { "updated_at", "version" },
            values: new object[] { new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc), "1.4.0" });
    }
}
