// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace D2.Edge.KeyCustodian.App.Application.Handlers.Queries.GetOidcConfiguration;

using D2.Edge.KeyCustodian.Client.OidcConfiguration;

/// <summary>Generated handler interface for the <c>GetOidcConfiguration</c> operation.</summary>
public interface IGetOidcConfigurationHandler : IHandler<GetOidcConfigurationInput, GetOidcConfigurationOutput>;
