// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Facade;

using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Facade;

/// <summary>
/// Generated DI extension that registers the module façade (Transient).
/// Called from the hand-written app DI extension.
/// </summary>
public static class KeyCustodianClientGeneratedServiceCollectionExtensions
{
    extension(IServiceCollection services)
    {
        /// <summary>
        /// Registers <see cref="IKeyCustodianApi"/> → <see cref="KeyCustodianApi"/> as Transient.
        /// </summary>
        public IServiceCollection AddD2KeyCustodianClient()
        {
            services.AddTransient<IKeyCustodianApi, KeyCustodianApi>();
            return services;
        }
    }
}
