// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Facade;

using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Commands.GetOrLazyProvisionOwnSealPrivateKey;
using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Commands.GetOrLazyProvisionSealPublicKey;
using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Commands.IssueLeaf;
using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Queries.GetCaCertificate;
using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Queries.GetJwks;
using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Queries.GetKeyring;
using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Queries.GetOidcConfiguration;
using DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Queries.Sign;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.CaCertificate;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Facade;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Issuance;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Jwks;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Keyring;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.OidcConfiguration;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Signing;

/// <summary>
/// Generated façade implementation. Delegates each exposed operation to the
/// corresponding app-layer handler. Registered Transient to match handler lifetime.
/// </summary>
public sealed class KeyCustodianApi(
    IGetJwksHandler getJwksHandler,
    IGetOidcConfigurationHandler getOidcConfigurationHandler,
    ISignHandler signHandler,
    IGetKeyringHandler getKeyringHandler,
    IIssueLeafHandler issueLeafHandler,
    IGetCaCertificateHandler getCaCertificateHandler,
    IGetOrLazyProvisionSealPublicKeyHandler getOrLazyProvisionSealPublicKeyHandler,
    IGetOrLazyProvisionOwnSealPrivateKeyHandler getOrLazyProvisionOwnSealPrivateKeyHandler) : IKeyCustodianApi
{
    /// <inheritdoc/>
    public ValueTask<D2Result<GetJwksOutput?>> GetJwksAsync(GetJwksInput input, CancellationToken ct = default)
        => getJwksHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetOidcConfigurationOutput?>> GetOidcConfigurationAsync(GetOidcConfigurationInput input, CancellationToken ct = default)
        => getOidcConfigurationHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<SignOutput?>> SignAsync(SignInput input, CancellationToken ct = default)
        => signHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetKeyringOutput?>> GetKeyringAsync(GetKeyringInput input, CancellationToken ct = default)
        => getKeyringHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<IssueLeafOutput?>> IssueLeafAsync(IssueLeafInput input, CancellationToken ct = default)
        => issueLeafHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetCaCertificateOutput?>> GetCaCertificateAsync(GetCaCertificateInput input, CancellationToken ct = default)
        => getCaCertificateHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetOrLazyProvisionSealPublicKeyOutput?>> GetOrLazyProvisionSealPublicKeyAsync(GetOrLazyProvisionSealPublicKeyInput input, CancellationToken ct = default)
        => getOrLazyProvisionSealPublicKeyHandler.HandleAsync(input, ct);
    /// <inheritdoc/>
    public ValueTask<D2Result<GetOrLazyProvisionOwnSealPrivateKeyOutput?>> GetOrLazyProvisionOwnSealPrivateKeyAsync(GetOrLazyProvisionOwnSealPrivateKeyInput input, CancellationToken ct = default)
        => getOrLazyProvisionOwnSealPrivateKeyHandler.HandleAsync(input, ct);
}
