// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Audit.Api.Grpc;

using PingAuditRequest = global::D2.Services.Protos.Audit.V2Alpha.PingAuditRequest;
using PingAuditResponse = global::D2.Services.Protos.Audit.V2Alpha.PingAuditResponse;
using ProtoPingAuditOutput = global::D2.Services.Protos.Audit.V2Alpha.PingAuditOutput;
using PingAuditInput = global::D2.Audit.Client.Ping.PingAuditInput;
using PingAuditOutput = global::D2.Audit.Client.Ping.PingAuditOutput;
using D2.Shared.Result;
using D2.Shared.Result.Grpc;
using Google.Protobuf;

/// <summary>Generated transport mappers: proto ↔ DTO for the <c>PingAudit</c> operation.</summary>
internal static class PingAuditTransportMappers
{
    extension(PingAuditRequest request)
    {
        internal PingAuditInput ToPingAuditInput()
        {
            return new PingAuditInput();
        }
    }

    extension(D2Result<PingAuditOutput?> result)
    {
        internal PingAuditResponse ToProtoResponse()
        {
            var response = new PingAuditResponse { Result = result.ToProto() };

            if (result.IsOk && result.Data is not null)
                response.Data = result.Data.ToProtoPingAuditOutput();

            return response;
        }
    }

    extension(PingAuditOutput output)
    {
        internal ProtoPingAuditOutput ToProtoPingAuditOutput()
        {
            return new ProtoPingAuditOutput
            {
                Status = output.Status,
            };
        }
    }
}
