// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/auth-context/IAuthContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

import type { ActorKind } from "../enums/actor-kind.g.js";
import type { ImpersonationKind } from "../enums/impersonation-kind.g.js";
import type { OrgType } from "../enums/org-type.g.js";
import type { Role } from "../enums/role.g.js";

/**
 * One link in the RFC 8693 actor chain. Mirrors .NET ActorEntry record.
 * Per rules.md §6.15 (TS `undefined`-over-`null`): optional fields use
 * the `?:` shorthand; absent links arrive as `undefined`, never `null`.
 */
export interface ActorEntry {
  readonly kind: ActorKind;
  readonly subject: string;
  readonly clientId?: string;
  readonly impersonationKind?: ImpersonationKind;
  readonly sessionId?: string;
  readonly orgId?: string;
  readonly orgName?: string;
  readonly orgType?: OrgType;
  readonly orgRole?: Role;
  readonly act?: ActorEntry;
}
