// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/auth-context/IAuthContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

import type { ActorKind } from "../enums/actor-kind.g.js";
import type { ImpersonationKind } from "../enums/impersonation-kind.g.js";
import type { OrgType } from "../enums/org-type.g.js";
import type { Role } from "../enums/role.g.js";

/**
 * One link in the RFC 8693 actor chain. Mirrors .NET ActorEntry record.
 */
export interface ActorEntry {
  readonly kind: ActorKind;
  readonly subject: string;
  readonly clientId?: string | null;
  readonly impersonationKind?: ImpersonationKind | null;
  readonly sessionId?: string | null;
  readonly orgId?: string | null;
  readonly orgName?: string | null;
  readonly orgType?: OrgType | null;
  readonly orgRole?: Role | null;
  readonly act?: ActorEntry | null;
}
