// -----------------------------------------------------------------------
// <copyright file="NodeLeafClientCsrFixtureTests.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Edge.Tests.Integration.KeyCustodian.NodeLeafClient;

using System.Security.Cryptography.X509Certificates;
using System.Text.Json;
using D2.Edge.Tests.Unit.KeyCustodian.TypeSpecGrpc;

/// <summary>
/// The PRIMARY file-based cross-runtime gate for the Node workload-leaf client
/// (<c>@d2/key-custodian-client</c>): committed CSR DER fixtures GENERATED BY THE
/// TS CLIENT'S OWN CSR construction (plus its adversarial matrix) are validated
/// here by the REAL KeyCustodian rules — <see cref="CsrVerification"/> for
/// proof-of-possession + the P-256 curve policy + the size cap, and
/// <see cref="RealCertAuthority.IssueLeafMaterial"/> for production-rule issuance.
/// </summary>
/// <remarks>
/// <para>
/// Fixtures live in <c>fixtures/</c> beside this file, emitted by
/// <c>client-ts/scripts/emit-csr-fixtures.fixture.ts</c> (regenerate:
/// <c>pnpm --filter @d2/key-custodian-client emit-csr-fixtures</c>). Each fixture
/// carries its expected verdict in <c>csr-fixtures.manifest.fixture.json</c>; the
/// manifest-sync test pins that the folder and the manifest never drift apart.
/// </para>
/// <para>
/// The headline structural proof: a TS CSR whose SUBJECT claims another service
/// still issues with the AUTHENTICATED identity's SAN — the CSR subject is
/// structurally ignored, so cross-runtime impersonation-by-subject is
/// unrepresentable. All fixture material is public (public keys +
/// self-signatures); no private key exists on this side at all.
/// </para>
/// </remarks>
[Trait("Category", "Integration")]
public sealed class NodeLeafClientCsrFixtureTests
{
    private const string _AUTHENTICATED_WORKLOAD = "edge";
    private const string _EXPECTED_SAN = "spiffe://d2.internal/workload/edge";

    // ----------------------------------------------------------------------
    // Valid CSR — the production TS construction verifies and issues
    // ----------------------------------------------------------------------

    [Fact]
    public void ValidCsr_Verifies_AndIssuesLeafCertifyingTheCsrKey()
    {
        var csrDer = LoadFixture("valid-p256.csr.fixture.der");

        var verified = CsrVerification.Verify(csrDer);

        verified.Success.Should().BeTrue(
            because: "the TS client's production CSR construction must pass the real "
            + "proof-of-possession + P-256 curve policy + size cap");

        using var ca = new RealCertAuthority();
        var material = ca.IssueLeafMaterial(csrDer, _AUTHENTICATED_WORKLOAD);

        using var leaf = X509CertificateLoader.LoadCertificate(material.CertificateDer);

        // The leaf certifies EXACTLY the CSR's public key (the TS mismatch defense's
        // premise) and carries the authenticated identity's SPIFFE SAN.
        leaf.PublicKey.ExportSubjectPublicKeyInfo()
            .Should().Equal(verified.Data!.ExportSubjectPublicKeyInfo());
        SpiffeUriSanOf(leaf).Should().Be(_EXPECTED_SAN);
    }

    // ----------------------------------------------------------------------
    // Foreign-CN CSR — the subject is STRUCTURALLY ignored (self-issue pin)
    // ----------------------------------------------------------------------

    [Fact]
    public void ForeignCnCsr_Issues_WithAuthenticatedIdentitySan_SubjectIgnored()
    {
        var csrDer = LoadFixture("foreign-cn.csr.fixture.der");

        CsrVerification.Verify(csrDer).Success.Should().BeTrue(
            because: "a well-formed P-256 CSR verifies regardless of its subject "
            + "— the subject is never read");

        using var ca = new RealCertAuthority();
        var material = ca.IssueLeafMaterial(csrDer, _AUTHENTICATED_WORKLOAD);

        using var leaf = X509CertificateLoader.LoadCertificate(material.CertificateDer);

        // The CSR claimed CN=files — the leaf's SAN is STILL the authenticated
        // caller's identity, and nothing from the claimed subject reaches the SAN.
        SpiffeUriSanOf(leaf).Should().Be(
            _EXPECTED_SAN,
            because: "the leaf subject-alternative-name is always the issuer's "
            + "authenticated view of the caller; the CSR subject is structurally ignored");
        SpiffeUriSanOf(leaf).Should().NotContain("files");
    }

    // ----------------------------------------------------------------------
    // Adversarial matrix — each rejected by the real verification rule
    // ----------------------------------------------------------------------

    [Theory]
    [InlineData("wrong-curve-p384.csr.fixture.der")]
    [InlineData("oversized.csr.fixture.der")]
    [InlineData("tampered-pop.csr.fixture.der")]
    public void AdversarialCsr_RejectedWithCoarseInvalidCsr(string fixtureFile)
    {
        var csrDer = LoadFixture(fixtureFile);

        var result = CsrVerification.Verify(csrDer);

        result.Success.Should().BeFalse();
        result.ErrorCode.Should().Be(
            KeyCustodianErrorCodes.KEYCUSTODIAN_INVALID_CSR,
            because: "every verification failure folds into ONE coarse code so the "
            + "surface never leaks which check failed");
        result.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    // ----------------------------------------------------------------------
    // Manifest-driven closure — folder and manifest never drift; every verdict
    // is enforced by the real rules
    // ----------------------------------------------------------------------

    [Fact]
    public void ManifestAndFixtureFolder_NeverDrift()
    {
        var manifest = LoadManifest();
        var listed = manifest.Select(f => f.File).ToHashSet(StringComparer.Ordinal);

        var present = Directory
            .GetFiles(FixturesDir(), "*.fixture.der")
            .Select(Path.GetFileName)
            .Cast<string>()
            .ToHashSet(StringComparer.Ordinal);

        listed.Should().BeEquivalentTo(
            present,
            because: "every fixture the emitter script writes is manifest-listed and "
            + "every committed fixture file is accounted for");
        listed.Should().NotBeEmpty();
    }

    [Fact]
    public void EveryManifestVerdict_IsEnforcedByTheRealRules()
    {
        using var ca = new RealCertAuthority();

        foreach (var fixture in LoadManifest())
        {
            var csrDer = LoadFixture(fixture.File);
            var verified = CsrVerification.Verify(csrDer);

            if (fixture.ExpectedVerdict == "rejected-invalid-csr")
            {
                verified.Success.Should().BeFalse(
                    because: $"{fixture.File} declares verdict {fixture.ExpectedVerdict}");

                continue;
            }

            // "issues" / "issues-subject-ignored" — verifies AND issues with the
            // authenticated identity's SAN.
            verified.Success.Should().BeTrue(
                because: $"{fixture.File} declares verdict {fixture.ExpectedVerdict}");

            var material = ca.IssueLeafMaterial(csrDer, _AUTHENTICATED_WORKLOAD);

            using var leaf = X509CertificateLoader.LoadCertificate(material.CertificateDer);
            SpiffeUriSanOf(leaf).Should().Be(_EXPECTED_SAN);
        }
    }

    // ----------------------------------------------------------------------
    // Helpers
    // ----------------------------------------------------------------------

    private static string FixturesDir() =>
        Path.Combine(
            TestPaths.RepoRoot(),
            "private",
            "services",
            "edge",
            "tests",
            "Integration",
            "KeyCustodian",
            "NodeLeafClient",
            "fixtures");

    private static byte[] LoadFixture(string fileName) =>
        File.ReadAllBytes(Path.Combine(FixturesDir(), fileName));

    private static IReadOnlyList<FixtureEntry> LoadManifest()
    {
        var manifestPath = Path.Combine(
            FixturesDir(), "csr-fixtures.manifest.fixture.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(manifestPath));

        return doc.RootElement
            .GetProperty("fixtures")
            .EnumerateArray()
            .Select(e => new FixtureEntry(
                e.GetProperty("file").GetString()!,
                e.GetProperty("expectedVerdict").GetString()!))
            .ToList();
    }

    /// <summary>
    /// Reads the single URI subject-alternative-name from a leaf (the issuance rule
    /// emits exactly one — the SPIFFE SVID).
    /// </summary>
    /// <param name="leaf">The leaf certificate.</param>
    /// <returns>The SPIFFE URI SAN string, or empty when none is present.</returns>
    private static string SpiffeUriSanOf(X509Certificate2 leaf)
    {
        var san = leaf.Extensions
            .OfType<X509SubjectAlternativeNameExtension>()
            .FirstOrDefault();

        if (san is null)
            return string.Empty;

        var formatted = san.Format(multiLine: false);
        var marker = formatted.IndexOf("spiffe://", StringComparison.Ordinal);

        return marker < 0 ? string.Empty : formatted[marker..].Trim();
    }

    private sealed record FixtureEntry(string File, string ExpectedVerdict);
}
