import { NodeHost, compile, navigateProgram } from "@typespec/compiler";
import { getHttpOperation } from "@typespec/http";
const mainFile = new URL("./control.tsp", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const program = await compile(NodeHost, mainFile, { noEmit: true });
let op; navigateProgram(program, { operation(o){ if(o.name==="sign") op=o; }});
const raw = op.parameters;
console.log("raw op.parameters fields:", [...raw.properties.keys()]);
const rawBody = raw.properties.get("input")?.type;
const [http] = getHttpOperation(program, op);
const httpBody = http.parameters.body?.type;
console.log("http path params:", http.parameters.parameters.map(p=>`${p.type}:${p.name}`).join(", "));
console.log("raw body model:", rawBody?.name, "fields:", [...rawBody.properties.keys()]);
console.log("http body model:", httpBody?.name, "fields:", [...(httpBody?.properties?.keys()??[])]);
console.log("SAME OBJECT (===)?:", rawBody === httpBody, "  <- body model intact even WITH a path param");
