// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/** Generated DTO interface for `GetCaCertificateInput`. */
export interface GetCaCertificateInput {
}

/** Generated DTO interface for `GetCaCertificateOutput`. */
export interface GetCaCertificateOutput {
  readonly rootCertificateDer: Uint8Array;
  readonly intermediateCertificateDer: Uint8Array;
}
