// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/headers/headers.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

/**
 * D2 wire-protocol headers applicable to the common catalog.
 * Generated from headers.spec.json. Mirrors .NET D2.Shared.Headers.Common.CommonHeaders.
 */
export const CommonHeaders = {
  /**
   * RFC 6750 bearer token header. Carries the JWT; identity rebuilds from this on every hop. Not used on AMQP (broker uses connection-level credentials).
   * Convention: oauth.
   * Applicability: grpc, http.
   */
  AUTHORIZATION: "Authorization",
  /**
   * Base64url-of-JSON encoded PropagatedContext — small set of cross-hop fields a downstream consumer can't recompute (request id, original request path, fingerprints, WhoIs hash). Same header name + encoding on AMQP / gRPC / HTTP. Identity fields are NEVER in here — they rebuild from the JWT at every hop.
   * Convention: d2.
   * Applicability: amqp, grpc, http.
   */
  PROPAGATED_CONTEXT: "x-d2-context",
  /**
   * W3C traceparent header — full {version}-{traceId}-{spanId}-{flags} string per https://www.w3.org/TR/trace-context. Consumers parse it to start a child span whose parent is the producer's span, so cross-hop trace assembly works in any OTel backend without bespoke linking.
   * Convention: w3c.
   * Applicability: amqp, grpc, http.
   */
  TRACEPARENT: "traceparent",
  /**
   * W3C tracestate header (vendor-specific tracing context that rides alongside traceparent). Forwarded as-is so non-D2 tracing systems chained through us don't lose state.
   * Convention: w3c.
   * Applicability: amqp, grpc, http.
   */
  TRACESTATE: "tracestate",
} as const;

export type CommonHeaderName =
  (typeof CommonHeaders)[keyof typeof CommonHeaders];

export const ALL_COMMON_HEADERS: readonly string[] = [
  "Authorization",
  "x-d2-context",
  "traceparent",
  "tracestate",
];
