// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace D2.Edge.KeyCustodian.Client.Sealing;

/// <summary>Generated DTO for the <c>GetOrLazyProvisionSealPublicKeyOutput</c> operation.</summary>
public sealed record GetOrLazyProvisionSealPublicKeyOutput(
    string ActiveKid,
    IReadOnlyList<SealPublicEntry> Entries);

/// <summary>Generated nested model DTO for <c>SealPublicEntry</c>.</summary>
public sealed record SealPublicEntry(
    string Kid,
    byte[] PublicSpki);
