// -----------------------------------------------------------------------
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) DCSV
// -----------------------------------------------------------------------

// Tests for the banner helper — direct-unit.
//
// Asserts:
//   - The canonical fence lines are present (grep-stable across tooling).
//   - The interpolated source-spec path is present.
//   - The "Manual edits will be lost" line is present.
//   - The output ends with a trailing blank line.
//   - The "Generated by" attribution line names the @d2/typespec-emitters pipeline.

import { describe, it, expect } from "vitest";
import { buildBanner } from "../src/lib/banner.js";

describe("buildBanner", () => {
  const banner = buildBanner("contracts/auth/v1/auth.tsp");

  it("contains the opening fence line", () => {
    expect(banner).toContain(
      "// -----------------------------------------------------------------------",
    );
  });

  it("contains <auto-generated> opening tag", () => {
    expect(banner).toContain("// <auto-generated>");
  });

  it("contains </auto-generated> closing tag", () => {
    expect(banner).toContain("// </auto-generated>");
  });

  it("contains the interpolated source spec path", () => {
    expect(banner).toContain("//   Source spec: contracts/auth/v1/auth.tsp");
  });

  it("contains the 'Manual edits will be lost on rebuild' warning", () => {
    expect(banner).toContain("//   Manual edits will be lost on rebuild.");
  });

  it("attributes the emitter pipeline (not ts-codegen)", () => {
    expect(banner).toContain("@d2/typespec-emitters TypeSpec emitter");
  });

  it("does NOT mention 'tools/ts-codegen' (separate pipeline)", () => {
    expect(banner).not.toContain("tools/ts-codegen");
  });

  it("ends with a trailing blank line", () => {
    expect(banner.endsWith("\n")).toBe(true);
    // The last two characters should be the closing fence newline + blank newline.
    const lines = banner.split("\n");
    expect(lines[lines.length - 1]).toBe("");
  });

  it("interpolates a different path correctly", () => {
    const other = buildBanner("contracts/geo/v1/geo.tsp");
    expect(other).toContain("//   Source spec: contracts/geo/v1/geo.tsp");
    expect(other).not.toContain("contracts/auth/v1/auth.tsp");
  });

  it("handles empty string source path without throwing", () => {
    const empty = buildBanner("");
    expect(empty).toContain("//   Source spec: ");
    expect(empty).toContain("<auto-generated>");
  });
});
