// -----------------------------------------------------------------------
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) DCSV
// -----------------------------------------------------------------------

// Unit tests for the WireVersion constant emitter.
//
// Covers:
//   emitWireVersionConstant — emitted channel string, generation int, stability
//     string, namespace placement, banner presence, #nullable enable, file name.

import { describe, it, expect } from "vitest";
import { emitWireVersionConstant } from "../src/lib/wire-version-emitter.js";
import { parseChannel } from "../src/lib/wire-channel.js";

const PROTO_CSHARP_NS = "D2.Services.Protos.Sample.V2Alpha";
const SOURCE_SPEC = "contracts/typespec/key-custodian/key-custodian.tsp";

const ALPHA_CHANNEL = parseChannel("d2.sample.v2alpha")!;
const STABLE_CHANNEL = parseChannel("d2.auth.v2")!;

// ---------------------------------------------------------------------------
// Alpha channel
// ---------------------------------------------------------------------------

describe("emitWireVersionConstant_AlphaChannel_EmitsCorrectConstants", () => {
  it("emits CHANNEL = 'v2alpha' for an alpha channel", () => {
    const file = emitWireVersionConstant(
      PROTO_CSHARP_NS,
      ALPHA_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain('CHANNEL = "v2alpha"');
  });

  it("emits GENERATION = 2 for a generation-2 channel", () => {
    const file = emitWireVersionConstant(
      PROTO_CSHARP_NS,
      ALPHA_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain("GENERATION = 2");
  });

  it("emits STABILITY = 'alpha' for an alpha channel", () => {
    const file = emitWireVersionConstant(
      PROTO_CSHARP_NS,
      ALPHA_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain('STABILITY = "alpha"');
  });
});

// ---------------------------------------------------------------------------
// Stable channel
// ---------------------------------------------------------------------------

describe("emitWireVersionConstant_StableChannel_EmitsStableStability", () => {
  it("emits STABILITY = 'stable' for a stable channel", () => {
    const file = emitWireVersionConstant(
      "D2.Services.Protos.Auth.V2",
      STABLE_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain('STABILITY = "stable"');
  });

  it("emits CHANNEL = 'v2' for a stable channel", () => {
    const file = emitWireVersionConstant(
      "D2.Services.Protos.Auth.V2",
      STABLE_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain('CHANNEL = "v2"');
  });
});

// ---------------------------------------------------------------------------
// Namespace placement
// ---------------------------------------------------------------------------

describe("emitWireVersionConstant_Namespace_MatchesProtoCsharpNs", () => {
  it("emitted namespace declaration matches the proto C# namespace", () => {
    const file = emitWireVersionConstant(
      PROTO_CSHARP_NS,
      ALPHA_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain(`namespace ${PROTO_CSHARP_NS};`);
  });
});

// ---------------------------------------------------------------------------
// Banner and nullable
// ---------------------------------------------------------------------------

describe("emitWireVersionConstant_Banner_IsPresentAndNullableEnabled", () => {
  it("carries the auto-generated banner", () => {
    const file = emitWireVersionConstant(
      PROTO_CSHARP_NS,
      ALPHA_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain("<auto-generated>");
    expect(file.content).toContain(SOURCE_SPEC);
  });

  it("contains #nullable enable", () => {
    const file = emitWireVersionConstant(
      PROTO_CSHARP_NS,
      ALPHA_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.content).toContain("#nullable enable");
  });
});

// ---------------------------------------------------------------------------
// File name
// ---------------------------------------------------------------------------

describe("emitWireVersionConstant_FileName_IsWireVersionGcs", () => {
  it("fileName is WireVersion.g.cs", () => {
    const file = emitWireVersionConstant(
      PROTO_CSHARP_NS,
      ALPHA_CHANNEL,
      SOURCE_SPEC,
    );
    expect(file.fileName).toBe("WireVersion.g.cs");
  });
});
