// -----------------------------------------------------------------------
// <copyright file="InProcessKeysEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.InProcessKeys.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;

/// <summary>
/// Pure logic for emitting one binding-specific in-process keys catalog
/// source from a parsed <see cref="InProcessKeysSpec"/>. Stateless and
/// unit-testable in isolation. The Roslyn-host integration
/// (<see cref="InProcessKeysGenerator"/>) calls this once per consuming
/// assembly with the matching binding filter.
/// </summary>
internal static class InProcessKeysEmitter
{
    /// <summary>Closed enum of supported bindings.</summary>
    public static readonly ImmutableHashSet<string> SR_ValidBindings =
        ImmutableHashSet.Create(StringComparer.Ordinal, "http", "grpc");

    private static readonly Regex sr_constNameRegex =
        new("^[A-Z][A-Z0-9_]*$", RegexOptions.Compiled);

    /// <summary>Closed enum of supported in-process bindings.</summary>
    public enum BindingFilter
    {
        /// <summary>HTTP binding (HttpContext.Items).</summary>
        Http,

        /// <summary>gRPC binding (ServerCallContext.UserState).</summary>
        Grpc,
    }

    /// <summary>
    /// Emits the per-binding in-process keys class source plus diagnostics.
    /// </summary>
    /// <param name="spec">Parsed in-process keys spec.</param>
    /// <param name="filter">Binding filter selecting which entries to emit.</param>
    /// <param name="targetNamespace">Namespace the emitted class lives in.</param>
    /// <param name="className">Emitted static class name (e.g. <c>D2HttpContextItems</c>).</param>
    /// <param name="visibility">Either <c>"public"</c> or <c>"internal"</c>.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(
        InProcessKeysSpec spec,
        BindingFilter filter,
        string targetNamespace,
        string className,
        string visibility)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var validEntries = new List<KeyEntry>();
        var bindingName = BindingName(filter);

        foreach (var entry in spec.Keys)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            var badBinding = false;
            foreach (var b in entry.Bindings)
            {
                if (!SR_ValidBindings.Contains(b))
                {
                    diagnostics.Add(EmitDiagnostics.UnknownBinding(
                        entry.ConstName,
                        b,
                        string.Join(
                            ", ",
                            SR_ValidBindings.OrderBy(s => s, StringComparer.Ordinal))));
                    badBinding = true;
                    break;
                }
            }

            if (badBinding) continue;
            validEntries.Add(entry);
        }

        var filtered = validEntries
            .Where(e => e.Bindings.Contains(bindingName))
            .OrderBy(e => e.ConstName, StringComparer.Ordinal)
            .ToList();

        var source = EmitSource(filtered, targetNamespace, className, visibility);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    /// <summary>Maps a binding filter to its lowercase name.</summary>
    /// <param name="filter">The binding filter to map.</param>
    /// <returns>The lowercase name of the binding.</returns>
    public static string BindingName(BindingFilter filter) => filter switch
    {
        BindingFilter.Http => "http",
        BindingFilter.Grpc => "grpc",
        _ => "unknown",
    };

    private static string EmitSource(
        List<KeyEntry> entries,
        string targetNamespace,
        string className,
        string visibility)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.InProcessKeys.SourceGen.InProcessKeysGenerator");
        sb.AppendLine("//   from contracts/in-process-keys/keys.spec.json (the source of truth).");
        sb.AppendLine("//   Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            $"/// In-process slot-key constants for the binding hosting <c>{className}</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Generated from contracts/in-process-keys/keys.spec.json. Cross-binding entries");
        sb.AppendLine(
            "/// share an identical wire value across every binding in their <c>bindings</c>");
        sb.AppendLine("/// array, codegen-guaranteed.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"{visibility} static class {className}");
        sb.AppendLine("{");

        foreach (var entry in entries)
        {
            sb.AppendLine("    /// <summary>");
            foreach (var line in entry.Purpose.Split('\n'))
                sb.AppendLine($"    /// {EscapeXmlDoc(line)}");
            sb.AppendLine("    /// </summary>");
            var literal = EscapeStringLiteral(entry.Value);
            sb.AppendLine(
                $"    public const string {entry.ConstName} = \"{literal}\";");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
