// -----------------------------------------------------------------------
// <copyright file="DlqCausesEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Messaging.DlqMetadata.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>DlqFailureCauses</c> static class
/// (closed-enum cause-string constants) into
/// <c>DcsvIo.D2.Messaging.RabbitMq</c>.
/// </summary>
internal static class DlqCausesEmitter
{
    /// <summary>The namespace the <c>DlqFailureCauses</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.Messaging.RabbitMq.Subscribing";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "DlqFailureCauses";

    private static readonly Regex sr_constNameRegex = new(
        "^[A-Z][A-Z0-9_]*$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    /// <summary>Emits the causes-catalog class source + diagnostics.</summary>
    /// <param name="spec">Parsed dlq-failure-metadata spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(DlqFailureMetadataSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var validCauses = ValidateCauses(spec.Causes, diagnostics);
        var source = EmitSource(validCauses);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static List<DlqCauseEntry> ValidateCauses(
        ImmutableArray<DlqCauseEntry> causes,
        ImmutableArray<EmitDiagnostic>.Builder diagnostics)
    {
        var valid = new List<DlqCauseEntry>();
        var seenConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenValues = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in causes)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (entry.Value.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyValue(entry.ConstName));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateCause(entry.ConstName));
                continue;
            }

            if (!seenValues.Add(entry.Value))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateCause(entry.Value));
                continue;
            }

            valid.Add(entry);
        }

        return valid;
    }

    private static string EmitSource(List<DlqCauseEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by");
        sb.AppendLine(
            "//   DcsvIo.D2.Messaging.DlqMetadata.SourceGen.DlqFailureMetadataGenerator");
        sb.AppendLine(
            "//   from contracts/dlq-failure-metadata/dlq-failure-metadata.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived closed-enum catalog of DLQ failure-cause string values");
        sb.AppendLine(
            "/// emitted on the <c>x-d2-failure-reason</c> header's");
        sb.AppendLine(
            "/// <see cref=\"DcsvIo.D2.Messaging.DlqFailureMetadata.Cause\"/> field.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        var first = true;
        foreach (var entry in entries)
        {
            if (!first)
                sb.AppendLine();
            first = false;
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
        }

        if (entries.Count > 0)
            sb.AppendLine();

        EmitAllCauses(sb, entries);

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static void EmitAllCauses(StringBuilder sb, List<DlqCauseEntry> entries)
    {
        sb.AppendLine("    /// <summary>All declared cause wire-values in spec order.</summary>");
        sb.AppendLine(
            "    public static IReadOnlyList<string> AllCauses => sr_allCauses;");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyList<string> sr_allCauses = new string[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
            sb.AppendLine($"        \"{EscapeStringLiteral(entry.Value)}\",");

        sb.AppendLine("    };");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
