// -----------------------------------------------------------------------
// <copyright file="DlqFieldsEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Messaging.DlqMetadata.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting (a) the <c>DlqFailureMetadataFields</c> static
/// class carrying property-name constants AND (b) the partial-class
/// JsonPropertyName-attribute half decorating <c>DlqFailureMetadata</c>'s
/// properties. Both target <c>DcsvIo.D2.Messaging.Abstractions</c>.
/// </summary>
internal static class DlqFieldsEmitter
{
    /// <summary>The namespace the emitted artifacts live in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.Messaging";

    /// <summary>The emitted fields-catalog class name.</summary>
    public const string FIELDS_CLASS_NAME = "DlqFailureMetadataFields";

    private static readonly Regex sr_constNameRegex = new(
        "^[A-Z][A-Z0-9_]*$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    /// <summary>Emits the fields-catalog class source + diagnostics.</summary>
    /// <param name="spec">Parsed dlq-failure-metadata spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult EmitFieldsCatalog(DlqFailureMetadataSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var validFields = ValidateFields(spec.Fields, diagnostics);
        var source = EmitFieldsSource(validFields);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static List<DlqFieldEntry> ValidateFields(
        ImmutableArray<DlqFieldEntry> fields,
        ImmutableArray<EmitDiagnostic>.Builder diagnostics)
    {
        var valid = new List<DlqFieldEntry>();
        var seenConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenValues = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in fields)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (entry.Value.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyValue(entry.ConstName));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateFieldConstName(entry.ConstName));
                continue;
            }

            if (!seenValues.Add(entry.Value))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateFieldValue(entry.Value));
                continue;
            }

            valid.Add(entry);
        }

        return valid;
    }

    private static string EmitFieldsSource(List<DlqFieldEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by");
        sb.AppendLine(
            "//   DcsvIo.D2.Messaging.DlqMetadata.SourceGen.DlqFailureMetadataGenerator");
        sb.AppendLine(
            "//   from contracts/dlq-failure-metadata/dlq-failure-metadata.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived JSON property-name catalog for the DLQ failure-metadata");
        sb.AppendLine(
            "/// wire shape. Every JSON serializer / deserializer references these");
        sb.AppendLine(
            "/// constants for property names instead of inline string literals.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {FIELDS_CLASS_NAME}");
        sb.AppendLine("{");

        var first = true;
        foreach (var entry in entries)
        {
            if (!first)
                sb.AppendLine();
            first = false;
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
        }

        if (entries.Count > 0)
            sb.AppendLine();

        EmitAllFields(sb, entries);

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static void EmitAllFields(StringBuilder sb, List<DlqFieldEntry> entries)
    {
        sb.AppendLine(
            "    /// <summary>All declared DLQ field wire-names in spec order.</summary>");
        sb.AppendLine(
            "    public static IReadOnlyList<string> AllFields => sr_allFields;");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyList<string> sr_allFields = new string[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
            sb.AppendLine($"        \"{EscapeStringLiteral(entry.Value)}\",");

        sb.AppendLine("    };");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
