// -----------------------------------------------------------------------
// <copyright file="FixturePathHelpers.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.Tests.Integration.ContractFixtures;

using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using D2.Shared.Tests.Unit.Auth;

/// <summary>
/// Shared write helpers for cross-language parity fixture emitters.
/// Every emitter writes via <see cref="WriteFixture"/> so the on-disk
/// shape (envelope + canonical-JSON data) is consistent across catalogs.
/// </summary>
internal static class FixturePathHelpers
{
    /// <summary>
    /// Synthetic-data discipline preamble. Stamped into every fixture
    /// envelope's <c>$comment</c> field so a reader inspecting a fixture
    /// in isolation knows the data origin and can trust there's no PII.
    /// </summary>
    public const string SYNTHETIC_DATA_NOTE =
        "Synthetic test data; no real PII."
        + " Generated by D2.Shared.Tests Integration/ContractFixtures.";

    private static readonly JsonSerializerOptions sr_writeOptions = new()
    {
        WriteIndented = true,
    };

    /// <summary>
    /// Resolve the on-disk path for a fixture file. The
    /// <c>contract-tests/fixtures/&lt;catalog&gt;/&lt;scenario&gt;.json</c>
    /// path lives under the TS contract-tests workspace package (the parity
    /// tests are TS-side; the .NET emitter writes there via the
    /// <see cref="TestPaths.RepoRoot"/> walk).
    /// </summary>
    /// <param name="catalog">Catalog directory name (e.g. <c>headers</c>).</param>
    /// <param name="scenario">Scenario base name (without <c>.json</c> suffix).</param>
    /// <returns>Absolute file path the emitter should write to.</returns>
    public static string FixturePath(string catalog, string scenario)
    {
        return Path.Combine(
            TestPaths.RepoRoot(),
            "server",
            "shared",
            "typescript",
            "contract-tests",
            "fixtures",
            catalog,
            scenario + ".json");
    }

    /// <summary>
    /// Emit a fixture envelope to disk. The envelope wraps the
    /// parity-compared <paramref name="data"/> payload with metadata
    /// (scenario name + synthetic-data note). The <paramref name="data"/>
    /// is canonicalized (sorted keys recursively) before serialization
    /// so the file diff is stable across reorderings on the .NET side.
    /// </summary>
    /// <param name="catalog">Catalog directory name.</param>
    /// <param name="scenario">Scenario base name (without <c>.json</c> suffix).</param>
    /// <param name="data">The payload to serialize as the envelope's <c>data</c> field.</param>
    public static void WriteFixture(string catalog, string scenario, object data)
    {
        var path = FixturePath(catalog, scenario);
        var dir = Path.GetDirectoryName(path)!;
        Directory.CreateDirectory(dir);

        var canonical = Canonicalize(data);
        var envelope = new SortedDictionary<string, object?>(System.StringComparer.Ordinal)
        {
            ["$comment"] = SYNTHETIC_DATA_NOTE,
            ["scenario"] = scenario,
            ["data"] = canonical,
        };

        var json = JsonSerializer.Serialize(envelope, sr_writeOptions);

        // Normalize to LF line endings (System.Text.Json emits Environment.NewLine
        // between indented lines — CRLF on Windows). The repo enforces LF via
        // .gitattributes / .editorconfig; emitted fixtures must match so
        // `pnpm exec prettier --check` (and any downstream LF-expecting tooling)
        // stays clean across platforms. Idempotent — already-LF content is unchanged.
        // Trailing newline keeps Unix line-tooling happy and matches the
        // common convention for committed JSON fixtures.
        var lfNormalized = json.Replace("\r\n", "\n") + "\n";
        File.WriteAllText(path, lfNormalized);
    }

    /// <summary>
    /// Recursively canonicalize a value: <c>IDictionary</c>s become
    /// <see cref="SortedDictionary{TKey, TValue}"/> with ordinal key
    /// sorting; arrays / lists preserve order; primitives pass through.
    /// Mirrors the TS-side <c>canonicalize()</c> helper exactly.
    /// </summary>
    /// <param name="value">Value to canonicalize.</param>
    /// <returns>Canonicalized form of <paramref name="value"/>.</returns>
    public static object? Canonicalize(object? value)
    {
        if (value is null) return null;
        if (value is string) return value;
        if (value is System.Collections.IDictionary dict)
        {
            var sorted = new SortedDictionary<string, object?>(System.StringComparer.Ordinal);
            foreach (System.Collections.DictionaryEntry entry in dict)
            {
                var key = entry.Key.ToString()!;
                sorted[key] = Canonicalize(entry.Value);
            }

            return sorted;
        }

        if (value is System.Collections.IEnumerable enumerable)
        {
            var list = new List<object?>();
            foreach (var item in enumerable) list.Add(Canonicalize(item));
            return list;
        }

        return value;
    }
}
