// -----------------------------------------------------------------------
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) DCSV
// -----------------------------------------------------------------------

// NuGet extraction helpers — the .NET half of the build-free artifact-diff
// engine.
//
// The bump is driven by two signals, BOTH derived from committed text with no
// `dotnet build`:
//
//   A. apiDiff — a git-ref TEXT DIFF of the committed PublicAPI.Shipped.txt: the
//      baseline report at the run's baseline ref (`git show <ref>:<path>`) vs
//      the HEAD report on disk, compared by set difference of the canonical
//      API lines. RS0016/RS0017 still guard the COMMITTED report's currency at
//      build time (the solution Build lane under TreatWarningsAsErrors), so the
//      fingerprint can TRUST the committed report.
//
//   B. fingerprint — a SOURCE-BASED hash composed in real-diff-provider.ts over
//      ( committed source + PublicAPI.* + resolved deps + toolchain pin ). This
//      module only supplies the PublicAPI path helpers + the Shipped-line
//      parser/differ; the composition lives in source-fingerprint.ts.
//
// Both paths read committed text only — the bump runs no build / subprocess.

import { join } from "node:path";
import { truthy } from "@dcsv-io/d2-utilities";
import type { ApiDiff } from "./diff-bump.js";

// ---------------------------------------------------------------------------
// PublicAPI.* line parsing + diff (git-ref text diff)
// ---------------------------------------------------------------------------

/**
 * Parse the set of canonical API lines from a `PublicAPI.Shipped.txt` (or
 * `.Unshipped.txt`) file. Each non-header, non-blank line is one public
 * type/member as emitted by PublicApiAnalyzers. The `#nullable enable` header
 * and blank lines are excluded; lines are trimmed of trailing whitespace so a
 * CRLF checkout does not perturb the set.
 *
 * @param content - The raw text of a `PublicAPI.*.txt` file.
 * @returns The set of canonical API line strings.
 */
export function parseShippedTxt(content: string): Set<string> {
  const members = new Set<string>();

  for (const rawLine of content.split("\n")) {
    const line = rawLine.trimEnd();

    if (truthy(line) && !line.startsWith("#")) members.add(line);
  }

  return members;
}

/**
 * Diff two sets of canonical PublicAPI lines and return an `ApiDiff`.
 *
 * Lines present only in `head` are `added`; lines present only in `baseline`
 * are `removed`. A signature change shows up as a removed (old) + added (new)
 * line pair — modeled as `added && removed`, which the bump engine maps to a
 * break (same outcome as `changed`). `changed` itself is not separately
 * derivable from the line text, so it is left false.
 *
 * @param baseline - Canonical lines from the baseline-ref report.
 * @param head     - Canonical lines from the HEAD report.
 * @returns The derived ApiDiff.
 */
export function diffShippedLines(
  baseline: ReadonlySet<string>,
  head: ReadonlySet<string>,
): ApiDiff {
  let added = false;
  let removed = false;

  for (const line of head) {
    if (!baseline.has(line)) added = true;
  }

  for (const line of baseline) {
    if (!head.has(line)) removed = true;
  }

  return { added, removed, changed: false };
}

// ---------------------------------------------------------------------------
// Baseline file naming conventions
// ---------------------------------------------------------------------------

/** Strip the trailing `<name>.csproj` segment from an absolute csproj path. */
function csprojDir(csprojPath: string): string {
  return csprojPath.replace(/[\\/][^\\/]+\.csproj$/, "");
}

/**
 * Return the path to the committed source-based fingerprint baseline file for a
 * package (`.release-fingerprint` next to the .csproj).
 *
 * The file is committed and regenerated by the seed script after each bump;
 * its absence is treated as a first run.
 *
 * @param csprojPath - Absolute path to the .csproj file.
 */
export function fingerprintBaselinePath(csprojPath: string): string {
  return join(csprojDir(csprojPath), ".release-fingerprint");
}

/** Return the path to the committed PublicAPI.Shipped.txt for a package. */
export function shippedTxtPath(csprojPath: string): string {
  return join(csprojDir(csprojPath), "PublicAPI.Shipped.txt");
}

/** Return the path to the committed PublicAPI.Unshipped.txt for a package. */
export function unshippedTxtPath(csprojPath: string): string {
  return join(csprojDir(csprojPath), "PublicAPI.Unshipped.txt");
}
