// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace D2.Edge.KeyCustodian.Clients;

/// <summary>Generated DTO for the <c>GetJwksOutput</c> operation.</summary>
public sealed record GetJwksOutput(
    IReadOnlyList<Jwk> Keys);

/// <summary>Generated nested model DTO for <c>Jwk</c>.</summary>
public sealed record Jwk(
    string Kid,
    string N,
    string E,
    string Kty,
    string Use,
    string Alg);
