// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace D2.Edge.KeyCustodian.Clients;

/// <summary>
/// Generated internal API façade for the module. Lists only the operations
/// exposed across a boundary; internal-only operations are absent.
/// </summary>
public interface IKeyCustodianApi
{
    /// <summary>Dispatches the <c>GetJwks</c> operation.</summary>
    ValueTask<D2Result<GetJwksOutput?>> GetJwksAsync(GetJwksInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>GetOidcConfiguration</c> operation.</summary>
    ValueTask<D2Result<GetOidcConfigurationOutput?>> GetOidcConfigurationAsync(GetOidcConfigurationInput input, CancellationToken ct = default);
}
