// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace D2.Edge.KeyCustodian.Clients;

/// <summary>Generated DTO for the <c>IssueLeafOutput</c> operation.</summary>
public sealed record IssueLeafOutput(
    byte[] CertificateDer,
    byte[] IssuerCertificateDer,
    DateTimeOffset NotBefore,
    DateTimeOffset NotAfter);
