// -----------------------------------------------------------------------
// <copyright file="ProtocolAudiencesGenerator.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Auth.ProtocolAudiences.SourceGen;

using System;
using System.IO;
using System.Linq;
using DcsvIo.D2.SourceGen;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Roslyn incremental source generator that emits the <c>WellKnownAudiences</c>
/// static partial class into <c>DcsvIo.D2.Auth.Abstractions</c> by reading
/// <c>contracts/auth-protocol-audiences/protocol-audiences.spec.json</c> via
/// <c>AdditionalFiles</c>. Single-target — only emits when the consuming assembly
/// is <c>DcsvIo.D2.Auth.Abstractions</c>.
/// </summary>
[Generator]
public sealed class ProtocolAudiencesGenerator : IIncrementalGenerator
{
    private const string _GENERATED_SOURCE_NAME = "WellKnownAudiences.g.cs";
    private const string _SPEC_FILE_NAME = "protocol-audiences.spec.json";
    private const string _TARGET_ASSEMBLY_NAME = "DcsvIo.D2.Auth.Abstractions";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Filter AdditionalFiles to protocol-audiences.spec.json files.
        var specs = context.AdditionalTextsProvider
            .Where(static file => IsSpecFile(file.Path))
            .Select(static (file, ct) => new SpecFile(
                Path: file.Path,
                Content: file.GetText(ct)?.ToString() ?? string.Empty))
            .Collect();

        // 2. Combine with the compilation so we can gate emission by assembly name.
        var combined = specs.Combine(context.CompilationProvider);

        // 3. For each pipeline run, drive the emitter.
        context.RegisterSourceOutput(combined, static (spc, tuple) =>
        {
            var (specFiles, compilation) = tuple;

            // Only emit when the consuming assembly is DcsvIo.D2.Auth.Abstractions.
            if (!string.Equals(
                compilation.AssemblyName,
                _TARGET_ASSEMBLY_NAME,
                StringComparison.Ordinal))
            {
                return;
            }

            if (specFiles.IsDefaultOrEmpty)
            {
                spc.ReportDiagnostic(ToRoslynDiagnostic(EmitDiagnostics.MissingSpecFile()));
                spc.AddSource(
                    _GENERATED_SOURCE_NAME,
                    SourceText.From(EmptySource(), System.Text.Encoding.UTF8));
                return;
            }

            // Convention: only one protocol-audiences.spec.json per consuming project.
            var spec = specFiles.OrderBy(s => s.Path, StringComparer.Ordinal).First();

            var loadResult = ProtocolAudienceSpecLoader.Load(spec.Path, spec.Content);
            if (loadResult.Diagnostic is { } loadDiag)
            {
                spc.ReportDiagnostic(ToRoslynDiagnostic(loadDiag));
                spc.AddSource(
                    _GENERATED_SOURCE_NAME,
                    SourceText.From(EmptySource(), System.Text.Encoding.UTF8));
                return;
            }

            var emitResult = ProtocolAudiencesEmitter.Emit(loadResult.Spec!);
            foreach (var d in emitResult.Diagnostics)
                spc.ReportDiagnostic(ToRoslynDiagnostic(d));

            spc.AddSource(
                _GENERATED_SOURCE_NAME,
                SourceText.From(emitResult.GeneratedSource, System.Text.Encoding.UTF8));
        });
    }

    private static bool IsSpecFile(string path) =>
        string.Equals(
            Path.GetFileName(path),
            _SPEC_FILE_NAME,
            StringComparison.OrdinalIgnoreCase);

    private static Diagnostic ToRoslynDiagnostic(EmitDiagnostic emitDiag)
    {
        var descriptor = ResolveDescriptor(emitDiag.DescriptorId);
        return Diagnostic.Create(descriptor, Location.None, emitDiag.Args.ToArray());
    }

    private static DiagnosticDescriptor ResolveDescriptor(string id) => id switch
    {
        DiagnosticIds.DuplicateName => DiagnosticDescriptors.DuplicateName,
        DiagnosticIds.InvalidName => DiagnosticDescriptors.InvalidName,
        DiagnosticIds.DuplicateValue => DiagnosticDescriptors.DuplicateValue,
        DiagnosticIds.EmptyValue => DiagnosticDescriptors.EmptyValue,
        DiagnosticIds.MalformedSpec => DiagnosticDescriptors.MalformedSpec,
        DiagnosticIds.MissingSpecFile => DiagnosticDescriptors.MissingSpecFile,
        _ => throw new InvalidOperationException($"Unknown EmitDiagnostic descriptor id '{id}'."),
    };

    private static string EmptySource() =>
        "// <auto-generated>\n#nullable enable\n" +
        "namespace DcsvIo.D2.Auth.Abstractions;\npublic static partial class WellKnownAudiences { }\n";
}
