// -----------------------------------------------------------------------
// <copyright file="ProtocolAudiencesEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Auth.ProtocolAudiences.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>WellKnownAudiences</c> static partial class
/// source from a parsed <see cref="ProtocolAudiencesSpec"/>. Stateless and
/// unit-testable in isolation. The Roslyn-host integration
/// (<see cref="ProtocolAudiencesGenerator"/>) calls this and translates emit-side
/// <see cref="EmitDiagnostic"/> records into Roslyn <c>Diagnostic</c> instances.
/// </summary>
internal static class ProtocolAudiencesEmitter
{
    private const string _ROOT_NAMESPACE = "DcsvIo.D2.Auth.Abstractions";
    private const string _CLASS_NAME = "WellKnownAudiences";

    /// <summary>
    /// Emits the WellKnownAudiences class source plus diagnostics for the supplied spec.
    /// </summary>
    /// <param name="spec">Parsed protocol-audience spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(ProtocolAudiencesSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var valid = new List<ProtocolAudienceEntry>();
        var seenNames = new HashSet<string>(StringComparer.Ordinal);
        var valueToFirstName = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var entry in spec.ProtocolAudiences)
        {
            if (!seenNames.Add(entry.Name))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateName(entry.Name));
                continue;
            }

            if (!ValidateName(entry.Name, out var nameReason))
            {
                diagnostics.Add(EmitDiagnostics.InvalidName(entry.Name, nameReason));
                continue;
            }

            if (entry.Value.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyValue(entry.Name));
                continue;
            }

            if (valueToFirstName.TryGetValue(entry.Value, out var firstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateValue(
                    firstName,
                    entry.Name,
                    entry.Value));
                continue;
            }

            valueToFirstName[entry.Value] = entry.Name;
            valid.Add(entry);
        }

        var source = EmitSource(valid);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static bool ValidateName(string name, out string reason)
    {
        if (name.Falsey())
        {
            reason = "name is empty";
            return false;
        }

        if (!IsAsciiUpperLetter(name[0]))
        {
            reason = $"name '{name}' must start with an uppercase ASCII letter";
            return false;
        }

        for (var i = 1; i < name.Length; i++)
        {
            var c = name[i];
            if (!IsAsciiUpperLetter(c) && !IsAsciiDigit(c) && c != '_')
            {
                reason =
                    $"name '{name}' contains invalid character '{c}' "
                    + "(only uppercase ASCII letters, digits, and underscores allowed)";
                return false;
            }
        }

        reason = string.Empty;
        return true;
    }

    private static string EmitSource(IReadOnlyList<ProtocolAudienceEntry> valid)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by DcsvIo.D2.Auth.ProtocolAudiences.SourceGen.ProtocolAudiencesGenerator");
        sb.AppendLine(
            "//   from contracts/auth-protocol-audiences/protocol-audiences.spec.json (the source of truth).");
        sb.AppendLine("//   Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {_ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Well-known PROTOCOL audiences generated from "
            + "<c>contracts/auth-protocol-audiences/protocol-audiences.spec.json</c>.");
        sb.AppendLine(
            "/// These are bare-token <c>aud</c> values (the universal internal receive");
        sb.AppendLine(
            "/// audience and the Edge self-audience), distinct from the URL-shaped");
        sb.AppendLine(
            "/// token-exchange targets in the spec-generated <see cref=\"Audiences\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {_CLASS_NAME}");
        sb.AppendLine("{");

        var ordered = valid
            .OrderBy(a => a.Name, StringComparer.Ordinal)
            .ToList();

        for (var i = 0; i < ordered.Count; i++)
        {
            var entry = ordered[i];
            var doc = entry.Description ?? entry.Value;
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {EscapeXmlDoc(doc)}");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine(
                $"    public const string {entry.Name} = "
                + $"\"{EscapeStringLiteral(entry.Value)}\";");
            if (i < ordered.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");

    private static bool IsAsciiUpperLetter(char c) => c is >= 'A' and <= 'Z';

    private static bool IsAsciiDigit(char c) => c is >= '0' and <= '9';
}
