<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>D2.Gateways.REST</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\..\..\..\contracts\messages\*.json" Link="messages\%(FileName)%(Extension)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\shared\Handler.Extensions\Handler.Extensions.csproj" />
        <ProjectReference Include="..\..\services\Geo\Geo.Client\Geo.Client.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Caching\Distributed\DistributedCache.Redis\DistributedCache.Redis.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Middleware\AuthPolicy.Default\AuthPolicy.Default.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Middleware\JwtAuth.Default\JwtAuth.Default.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Middleware\ServiceKey.Default\ServiceKey.Default.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Middleware\Idempotency.Default\Idempotency.Default.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Middleware\RateLimit.Default\RateLimit.Default.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Middleware\RequestEnrichment.Default\RequestEnrichment.Default.csproj" />
        <ProjectReference Include="..\..\shared\Implementations\Middleware\Translation.Default\Translation.Default.csproj" />
        <ProjectReference Include="..\..\shared\Result.Extensions\Result.Extensions.csproj" />
        <ProjectReference Include="..\..\shared\ServiceDefaults\ServiceDefaults.csproj"/>
        <ProjectReference Include="..\..\shared\protos\_gen\Protos.DotNet\Protos.DotNet.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Net.ClientFactory" Version="2.76.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    </ItemGroup>

</Project>
