// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/** Generated DTO interface for `IssueLeafInput`. */
export interface IssueLeafInput {
  readonly csrDer: Uint8Array;
}

/** Generated DTO interface for `IssueLeafOutput`. */
export interface IssueLeafOutput {
  readonly certificateDer: Uint8Array;
  readonly issuerCertificateDer: Uint8Array;
  readonly notBefore: string;
  readonly notAfter: string;
}
