# Documentation: https://grafana.com/docs/mimir/latest/configure/configuration-parameters/
target: all

multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9097
  log_level: info
  log_format: json

common:
  storage:
    backend: s3
    s3:
      endpoint: d2-minio:9000
      bucket_name: mimir-blocks
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      insecure: true
      http:
        insecure_skip_verify: true
      signature_version: v4
      storage_class: STANDARD

blocks_storage:
  backend: s3
  s3:
    endpoint: d2-minio:9000
    bucket_name: mimir-blocks
    access_key_id: ${MINIO_ROOT_USER}
    secret_access_key: ${MINIO_ROOT_PASSWORD}
    insecure: true
  tsdb:
    dir: /var/mimir/tsdb
  bucket_store:
    sync_dir: /var/mimir/tsdb-sync
    index_cache:
      backend: inmemory

compactor:
  data_dir: /var/mimir/compactor
  deletion_delay: 24h
  sharding_ring:
    kvstore:
      store: inmemory

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: inmemory

ruler_storage:
  backend: s3
  s3:
    endpoint: d2-minio:9000
    bucket_name: mimir-ruler
    access_key_id: ${MINIO_ROOT_USER}
    secret_access_key: ${MINIO_ROOT_PASSWORD}
    insecure: true

limits:
  compactor_blocks_retention_period: 2160h  # 90 days

activity_tracker:
  filepath: /var/mimir/activity.log