// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.Client.Keyring;

using DcsvIo.D2.Utilities.Attributes;
using DcsvIo.D2.Utilities.Enums;

/// <summary>Generated DTO for the <c>GetKeyringOutput</c> operation.</summary>
public sealed record GetKeyringOutput(
    string ActiveKid,
    IReadOnlyList<KeyringEntry> Entries,
    byte[] AadContext);

/// <summary>Generated nested model DTO for <c>KeyringEntry</c>.</summary>
public sealed record KeyringEntry(
    string Kid,
    [property: RedactData(Reason = RedactReason.SecretInformation)] byte[] KeyBytes);
