// -----------------------------------------------------------------------
// <copyright file="WireShapeEmitterTests.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Tests.Unit.WireShapes.SourceGen;

using System.Collections.Immutable;
using AwesomeAssertions;
using DcsvIo.D2.WireShapes.SourceGen;
using Xunit;

/// <summary>
/// Pure-logic tests for the wire-shape emitter. Drives the emitter
/// directly with synthetic specs and asserts both the generated source
/// shape (per-VALUE pin) and the diagnostics surfaced for invalid spec
/// inputs.
/// </summary>
public sealed class WireShapeEmitterTests
{
    [Theory]
    [InlineData("KEY", "key")]
    [InlineData("PARAMS", "params")]
    [InlineData("FIELD", "field")]
    [InlineData("ERRORS", "errors")]
    public void Emit_ValidProperty_EmitsPublicConstWithExactValue(
        string constName, string wireValue)
    {
        var spec = MakeSpec(new WireShapeProperty(constName, wireValue, "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "Some");

        result.Diagnostics.Should().BeEmpty();
        result.GeneratedSource.Should().Contain(
            $"public const string {constName} = \"{wireValue}\";");
    }

    [Fact]
    public void Emit_ValidSpec_EmitsHeaderAndNamespaceAndClass()
    {
        var spec = MakeSpec(new WireShapeProperty("KEY", "key", "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "DcsvIo.D2.I18n", "TkMessageWireShape", "TKMessage");

        result.Diagnostics.Should().BeEmpty();
        result.GeneratedSource.Should().Contain("// <auto-generated>");
        result.GeneratedSource.Should().Contain("namespace DcsvIo.D2.I18n;");
        result.GeneratedSource.Should().Contain("public static class TkMessageWireShape");
        result.GeneratedSource.Should().Contain("#nullable enable");
    }

    [Fact]
    public void Emit_DuplicateConstName_EmitsD2WS002Diagnostic()
    {
        var spec = MakeSpec(
            new WireShapeProperty("KEY", "key", "Doc."),
            new WireShapeProperty("KEY", "key2", "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "Some");

        result.Diagnostics.Should().ContainSingle(d =>
            d.DescriptorId == DiagnosticIds.DuplicatePropertyConstName);
    }

    [Fact]
    public void Emit_DuplicateValue_EmitsD2WS003Diagnostic()
    {
        var spec = MakeSpec(
            new WireShapeProperty("KEY_A", "key", "Doc."),
            new WireShapeProperty("KEY_B", "key", "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "Some");

        result.Diagnostics.Should().ContainSingle(d =>
            d.DescriptorId == DiagnosticIds.DuplicatePropertyValue);
    }

    [Theory]
    [InlineData("lowerCase")]
    [InlineData("123_starts_with_digit")]
    [InlineData("Has-Hyphen")]
    [InlineData("")]
    [InlineData("hasSpaces inside")]
    public void Emit_InvalidConstName_EmitsD2WS004Diagnostic(string badConstName)
    {
        var spec = MakeSpec(new WireShapeProperty(badConstName, "value", "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "Some");

        result.Diagnostics.Should().ContainSingle(d =>
            d.DescriptorId == DiagnosticIds.InvalidConstName);
    }

    [Fact]
    public void Emit_PreservesSpecOrderOfProperties()
    {
        // Spec ordering drives emitted ordering — predictable diff on
        // spec edits. Mirrors the problem-details emitter's preserve-order
        // discipline.
        var spec = MakeSpec(
            new WireShapeProperty("Z", "z_val", "Doc."),
            new WireShapeProperty("A", "a_val", "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "Some");

        result.Diagnostics.Should().BeEmpty();
        var zPos = result.GeneratedSource.IndexOf(
            "Z = \"z_val\"", System.StringComparison.Ordinal);
        var aPos = result.GeneratedSource.IndexOf(
            "A = \"a_val\"", System.StringComparison.Ordinal);
        zPos.Should().BeLessThan(aPos);
    }

    [Fact]
    public void Emit_RunsTwiceWithIdenticalInput_ProducesIdenticalSource()
    {
        var spec = MakeSpec(new WireShapeProperty("KEY", "key", "Doc."));

        var first = WireShapeEmitter.Emit(
            spec, "DcsvIo.D2.I18n", "TkMessageWireShape", "TKMessage");
        var second = WireShapeEmitter.Emit(
            spec, "DcsvIo.D2.I18n", "TkMessageWireShape", "TKMessage");

        second.GeneratedSource.Should().Be(first.GeneratedSource);
    }

    [Fact]
    public void Emit_EscapesXmlDocSpecialCharacters()
    {
        // Doc text with <, >, & should be XML-encoded in the emitted summary
        // — otherwise the generated source won't compile.
        var spec = MakeSpec(
            new WireShapeProperty(
                "KEY",
                "key",
                "Record<string, unknown> & generics."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "Some");

        result.Diagnostics.Should().BeEmpty();
        result.GeneratedSource.Should().Contain("&lt;string, unknown&gt;");
        result.GeneratedSource.Should().Contain("&amp; generics");
    }

    [Fact]
    public void Emit_EscapesStringLiteralBackslashAndQuote()
    {
        var spec = MakeSpec(new WireShapeProperty("WEIRD", @"a\b""c", "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "Some");

        result.Diagnostics.Should().BeEmpty();
        result.GeneratedSource.Should().Contain(@"public const string WEIRD = ""a\\b\""c""");
    }

    [Fact]
    public void Emit_CatalogDescriptionEscapedIntoSummary()
    {
        var spec = MakeSpec(new WireShapeProperty("KEY", "key", "Doc."));

        var result = WireShapeEmitter.Emit(
            spec, "D2.Some.Ns", "SomeWireShape", "<TK&Message>");

        result.GeneratedSource.Should().Contain("&lt;TK&amp;Message&gt;");
    }

    private static WireShapeSpec MakeSpec(params WireShapeProperty[] properties) =>
        new(properties.ToImmutableArray());
}
