// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/jwt-claims/jwt-claims.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

/**
 * JWT claim name string constants used across the platform. Mirrors
 * .NET D2.Shared.Auth.Abstractions.JwtClaimTypes (same string values).
 *
 * Standard OAuth/OIDC claims keep their canonical names (sub, aud,
 * scope, ...); D2-specific claims use the d2_ prefix; inside-act claims
 * are nested under the act object per RFC 8693 §2.1 (lookup path
 * act[ACT_KIND]).
 */
export const JwtClaimTypes = {
  /**
   * Subject — the user's identifier (Guid string for user tokens) or service client_id for pure service-identity tokens (RFC 6749 §4.4).
   * Kind: standard.
   */
  SUB: "sub",
  /**
   * Audience — the intended recipient service identifier(s). Per RFC 7519 §4.1.3 may be a single string OR a JSON array; both wire shapes accepted.
   * Kind: standard.
   */
  AUD: "aud",
  /**
   * Issued-at — Unix timestamp seconds when the token was minted.
   * Kind: standard.
   */
  IAT: "iat",
  /**
   * Expiry — Unix timestamp seconds after which the token is invalid.
   * Kind: standard.
   */
  EXP: "exp",
  /**
   * Authorized party (RFC 7519 §4.1.7) — the OAuth client the token was issued for.
   * Kind: standard.
   */
  AZP: "azp",
  /**
   * Space-separated string of granted permissions per RFC 6749 §3.3. Some authorization servers send this as a JSON array; the runtime parser accepts both shapes.
   * Kind: standard.
   */
  SCOPE: "scope",
  /**
   * Actor chain — RFC 8693 §2.1 nested-object structure identifying the chain of services / impersonators that minted the token. Empty / absent when the token is an end-user-direct token.
   * Kind: standard.
   */
  ACT: "act",
  /**
   * OAuth client identifier of the client that requested THIS specific token from the authorization server (RFC 8693 §4.3 / RFC 9068 §2.2). Updates on every token exchange — for a multi-hop chain, this is the immediate requesting client, not the originating one.
   * Kind: standard.
   */
  CLIENT_ID: "client_id",
  /**
   * User session identifier — links the token to a session record in d2-auth.
   * Kind: d2-custom.
   */
  SESSION_ID: "d2_session_id",
  /**
   * Login handle — unique, lowercase username.
   * Kind: d2-custom.
   */
  USERNAME: "d2_username",
  /**
   * JWT fingerprint — SHA-256 of canonical request signal (User-Agent + Accept). Used for token-binding adversarial checks.
   * Kind: d2-custom.
   */
  FINGERPRINT: "d2_fp",
  /**
   * Operating organization identifier. During impersonation: the impersonated user's org.
   * Kind: d2-custom.
   */
  ORG_ID: "d2_org_id",
  /**
   * Operating organization display name.
   * Kind: d2-custom.
   */
  ORG_NAME: "d2_org_name",
  /**
   * Operating organization type — string form of the OrgType enum.
   * Kind: d2-custom.
   */
  ORG_TYPE: "d2_org_type",
  /**
   * User's role in the operating organization — string form of the Role enum.
   * Kind: d2-custom.
   */
  ORG_ROLE: "d2_org_role",
  /**
   * Inside-act claim — flavor of impersonation when the actor's kind is impersonation. Values are lowercase strings matching ImpersonationKind (consent or force). Lookup path: act.d2_kind. There is NO top-level d2_kind claim; token kind is derived from the act chain's shape.
   * Kind: inside-act.
   */
  ACT_KIND: "d2_kind",
  /**
   * Inside-act claim — impersonation session identifier when the actor's kind is impersonation. Lookup path: act.d2_session_id. Wire value collides with top-level d2_session_id but the lookup path is distinct (nested under act).
   * Kind: inside-act.
   */
  ACT_SESSION_ID: "d2_session_id",
  /**
   * Authentication Methods Reference (RFC 8176). Array of strings identifying the authentication methods used. Input to risk-scoring and audit — 'password-only vs MFA vs OAuth2-with-WebAuthn' matters for sensitive-action gating.
   * Kind: standard.
   */
  AMR: "amr",
  /**
   * Unix-seconds timestamp of last step-up authentication completion. Handlers gating sensitive actions enforce 'step-up within last N minutes'. Edge auth populates from session record at JWT mint.
   * Kind: d2-custom.
   */
  STEP_UP_AT: "d2_step_up_at",
} as const;

export type JwtClaimType = (typeof JwtClaimTypes)[keyof typeof JwtClaimTypes];
