// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Edge.Api.Grpc.KeyCustodian;

using GetCaCertificateRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetCaCertificateRequest;
using GetCaCertificateResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetCaCertificateResponse;
using GetCaCertificateInput = global::D2.Edge.KeyCustodian.Client.CaCertificate.GetCaCertificateInput;
using GetCaCertificateOutput = global::D2.Edge.KeyCustodian.Client.CaCertificate.GetCaCertificateOutput;
using global::D2.Shared.Result.Grpc;
using global::Grpc.Core;
using D2.Edge.KeyCustodian.Client.Facade;

/// <summary>Generated gRPC service for the <c>GetCaCertificate</c> operation, delegating to <see cref="IKeyCustodianApi"/>.</summary>
public sealed class KeyCustodianCaCertificateService(IKeyCustodianApi facade)
    : global::D2.Services.Protos.KeyCustodian.V2Alpha.KeyCustodianCaCertificate.KeyCustodianCaCertificateBase
{
    /// <inheritdoc/>
    public override async Task<GetCaCertificateResponse> GetCaCertificate(GetCaCertificateRequest request, ServerCallContext context)
    {
        GetCaCertificateInput input = request.ToGetCaCertificateInput();
        var result = await facade.GetCaCertificateAsync(input, context.CancellationToken).ConfigureAwait(false);
        return result.ToProtoResponse();
    }
}
