// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Edge.Api.Grpc.KeyCustodian;

using GetOrLazyProvisionOwnSealPrivateKeyRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetOrLazyProvisionOwnSealPrivateKeyRequest;
using GetOrLazyProvisionOwnSealPrivateKeyResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetOrLazyProvisionOwnSealPrivateKeyResponse;
using GetOrLazyProvisionOwnSealPrivateKeyInput = global::D2.Edge.KeyCustodian.Client.Sealing.GetOrLazyProvisionOwnSealPrivateKeyInput;
using GetOrLazyProvisionOwnSealPrivateKeyOutput = global::D2.Edge.KeyCustodian.Client.Sealing.GetOrLazyProvisionOwnSealPrivateKeyOutput;
using global::D2.Shared.Result.Grpc;
using global::Grpc.Core;
using D2.Edge.KeyCustodian.Client.Facade;

/// <summary>Generated gRPC service for the <c>GetOrLazyProvisionOwnSealPrivateKey</c> operation, delegating to <see cref="IKeyCustodianApi"/>.</summary>
public sealed class KeyCustodianOwnSealPrivateKeyService(IKeyCustodianApi facade)
    : global::D2.Services.Protos.KeyCustodian.V2Alpha.KeyCustodianOwnSealPrivateKey.KeyCustodianOwnSealPrivateKeyBase
{
    /// <inheritdoc/>
    public override async Task<GetOrLazyProvisionOwnSealPrivateKeyResponse> GetOrLazyProvisionOwnSealPrivateKey(GetOrLazyProvisionOwnSealPrivateKeyRequest request, ServerCallContext context)
    {
        GetOrLazyProvisionOwnSealPrivateKeyInput input = request.ToGetOrLazyProvisionOwnSealPrivateKeyInput();
        var result = await facade.GetOrLazyProvisionOwnSealPrivateKeyAsync(input, context.CancellationToken).ConfigureAwait(false);
        return result.ToProtoResponse();
    }
}
