// -----------------------------------------------------------------------
// <copyright file="TKGenerator.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.I18n.SourceGen;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using D2.Shared.I18n.SourceGen.Polyfills;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Roslyn incremental source generator that emits the <c>TK</c> static class
/// into <c>D2.Shared.I18n.Abstractions</c> by reading
/// <c>contracts/messages/*.json</c> via <c>AdditionalFiles</c>.
/// </summary>
/// <remarks>
/// The generator filters AdditionalFiles to <c>.json</c> files whose
/// containing directory is named <c>messages</c>. That directory convention
/// matches the consuming csproj's
/// <c>&lt;AdditionalFiles Include="...contracts/messages/*.json" /&gt;</c>
/// glob and avoids accidentally treating unrelated AdditionalFiles as catalogs.
/// </remarks>
[Generator]
public sealed class TKGenerator : IIncrementalGenerator
{
    private const string _GENERATED_SOURCE_NAME = "TK.g.cs";
    private const string _MESSAGES_DIRECTORY_NAME = "messages";
    private const string _EN_US_LOCALE = "en-US";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Filter AdditionalFiles to JSON catalogs.
        var catalogs = context.AdditionalTextsProvider
            .Where(static file => IsCatalogPath(file.Path))
            .Select(static (file, ct) => new LocaleFile(
                Locale: Path.GetFileNameWithoutExtension(file.Path),
                Content: file.GetText(ct)?.ToString() ?? string.Empty))
            .Collect();

        // 2. For each pipeline run, drive the emitter.
        context.RegisterSourceOutput(catalogs, static (spc, files) =>
        {
            var enUs = files.FirstOrDefault(f =>
                string.Equals(f.Locale, _EN_US_LOCALE, StringComparison.OrdinalIgnoreCase));

            if (enUs is null || enUs.Content.Falsey())
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MissingEnUsJson,
                    Location.None));
                spc.AddSource(
                    _GENERATED_SOURCE_NAME,
                    SourceText.From(EmptyTKSource(), System.Text.Encoding.UTF8));
                return;
            }

            var others = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var file in files)
            {
                if (string.Equals(file.Locale, _EN_US_LOCALE, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                others[file.Locale] = file.Content;
            }

            var result = TKEmitter.Emit(enUs.Content, others);

            foreach (var d in result.Diagnostics)
            {
                spc.ReportDiagnostic(ToRoslynDiagnostic(d));
            }

            spc.AddSource(
                _GENERATED_SOURCE_NAME,
                SourceText.From(result.GeneratedSource, System.Text.Encoding.UTF8));
        });
    }

    private static bool IsCatalogPath(string path)
    {
        if (!path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var dir = Path.GetDirectoryName(path);
        if (dir is null)
        {
            return false;
        }

        var dirName = Path.GetFileName(dir);
        return string.Equals(dirName, _MESSAGES_DIRECTORY_NAME, StringComparison.OrdinalIgnoreCase);
    }

    private static Diagnostic ToRoslynDiagnostic(EmitDiagnostic emitDiag)
    {
        var descriptor = ResolveDescriptor(emitDiag.DescriptorId);
        return Diagnostic.Create(descriptor, Location.None, emitDiag.Args.ToArray());
    }

    private static DiagnosticDescriptor ResolveDescriptor(string id) => id switch
    {
        DiagnosticIds.InvalidTranslationKey => DiagnosticDescriptors.InvalidTranslationKey,
        DiagnosticIds.MissingKeyInLocale => DiagnosticDescriptors.MissingKeyInLocale,
        DiagnosticIds.TranslationKeyCollision => DiagnosticDescriptors.TranslationKeyCollision,
        DiagnosticIds.OrphanKeyInLocale => DiagnosticDescriptors.OrphanKeyInLocale,
        DiagnosticIds.MissingEnUsJson => DiagnosticDescriptors.MissingEnUsJson,
        DiagnosticIds.MalformedJsonCatalog => DiagnosticDescriptors.MalformedJsonCatalog,
        _ => throw new InvalidOperationException($"Unknown EmitDiagnostic descriptor id '{id}'."),
    };

    private static string EmptyTKSource() =>
        "// <auto-generated>\n#nullable enable\n" +
        "namespace D2.Shared.I18n;\npublic static partial class TK { }\n";
}
