// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.Client.Facade;

using DcsvIo.D2.Private.Edge.KeyCustodian.Client.CaCertificate;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Issuance;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Jwks;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Keyring;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.OidcConfiguration;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Signing;

/// <summary>
/// Generated internal API façade for the module. Lists only the operations
/// exposed across a boundary; internal-only operations are absent.
/// </summary>
public interface IKeyCustodianApi
{
    /// <summary>Dispatches the <c>GetJwks</c> operation.</summary>
    ValueTask<D2Result<GetJwksOutput?>> GetJwksAsync(GetJwksInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>GetOidcConfiguration</c> operation.</summary>
    ValueTask<D2Result<GetOidcConfigurationOutput?>> GetOidcConfigurationAsync(GetOidcConfigurationInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>Sign</c> operation.</summary>
    ValueTask<D2Result<SignOutput?>> SignAsync(SignInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>GetKeyring</c> operation.</summary>
    ValueTask<D2Result<GetKeyringOutput?>> GetKeyringAsync(GetKeyringInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>IssueLeaf</c> operation.</summary>
    ValueTask<D2Result<IssueLeafOutput?>> IssueLeafAsync(IssueLeafInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>GetCaCertificate</c> operation.</summary>
    ValueTask<D2Result<GetCaCertificateOutput?>> GetCaCertificateAsync(GetCaCertificateInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>GetOrLazyProvisionSealPublicKey</c> operation.</summary>
    ValueTask<D2Result<GetOrLazyProvisionSealPublicKeyOutput?>> GetOrLazyProvisionSealPublicKeyAsync(GetOrLazyProvisionSealPublicKeyInput input, CancellationToken ct = default);
    /// <summary>Dispatches the <c>GetOrLazyProvisionOwnSealPrivateKey</c> operation.</summary>
    ValueTask<D2Result<GetOrLazyProvisionOwnSealPrivateKeyOutput?>> GetOrLazyProvisionOwnSealPrivateKeyAsync(GetOrLazyProvisionOwnSealPrivateKeyInput input, CancellationToken ct = default);
}
