// -----------------------------------------------------------------------
// <copyright file="EncryptionDomainsEmitter.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.EncryptionDomains.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using D2.Shared.SourceGen;
using D2.Shared.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>EncryptionDomains</c> static class source
/// from a parsed <see cref="EncryptionDomainsSpec"/>.
/// </summary>
internal static class EncryptionDomainsEmitter
{
    /// <summary>The namespace the <c>EncryptionDomains</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "D2.Shared.Encryption";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "EncryptionDomains";

    private static readonly Regex sr_constNameRegex = new(
        "^[A-Z][A-Z0-9_]*$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    /// <summary>Emits the EncryptionDomains class source + diagnostics.</summary>
    /// <param name="spec">Parsed encryption-domains spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(EncryptionDomainsSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        var validEntries = new List<EncryptionDomainEntry>();
        var seenConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenValues = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.Domains)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (entry.Value.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyValue(entry.ConstName));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateConstName(entry.ConstName));
                continue;
            }

            if (!seenValues.Add(entry.Value))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateValue(entry.Value));
                continue;
            }

            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(List<EncryptionDomainEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by D2.Shared.EncryptionDomains.SourceGen.EncryptionDomainsGenerator");
        sb.AppendLine(
            "//   from contracts/encryption-domains/encryption-domains.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived closed catalog of encryption-domain identifiers. Each");
        sb.AppendLine(
            "/// domain corresponds to an independently-rotated keyring registered via");
        sb.AppendLine(
            "/// <c>services.AddD2EncryptionFor(domain, factory)</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Use these constants instead of raw strings so a typo can't silently");
        sb.AppendLine(
            "/// route a message to a non-existent keyring. Adding a new domain is an");
        sb.AppendLine(
            "/// architectural decision that requires KeyCustodian provisioning,");
        sb.AppendLine(
            "/// key-rotation runbook updates, and operator coordination — the spec");
        sb.AppendLine("/// edit forces all parties into the loop.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        var first = true;
        foreach (var entry in entries)
        {
            if (!first)
                sb.AppendLine();
            first = false;
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
        }

        if (entries.Count > 0)
            sb.AppendLine();

        EmitAllDomains(sb, entries);

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static void EmitAllDomains(StringBuilder sb, List<EncryptionDomainEntry> entries)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// All declared encryption-domain wire-values in spec order.");
        sb.AppendLine(
            "    /// Useful for cross-spec consistency tests (e.g. validating");
        sb.AppendLine(
            "    /// mq-messages.spec's 'encryption' field values against the");
        sb.AppendLine("    /// catalog).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static IReadOnlyList<string> AllDomains => sr_allDomains;");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyList<string> sr_allDomains = new string[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
            sb.AppendLine($"        \"{EscapeStringLiteral(entry.Value)}\",");

        sb.AppendLine("    };");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
