// -----------------------------------------------------------------------
// <copyright file="AdvisoryLocksEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.AdvisoryLocks.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;

/// <summary>
/// Pure logic for emitting the <c>AdvisoryLocks</c> static class from a
/// parsed <see cref="AdvisoryLocksSpec"/>.
/// </summary>
internal static class AdvisoryLocksEmitter
{
    /// <summary>The namespace the <c>AdvisoryLocks</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.Private.Edge.KeyCustodian.Infra";

    /// <summary>The emitted top-level class name.</summary>
    public const string CLASS_NAME = "AdvisoryLocks";

    private static readonly Regex sr_constNameRegex = new(
        "^[A-Z][A-Z0-9_]*$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    /// <summary>Emits the <c>AdvisoryLocks</c> class source + diagnostics.</summary>
    /// <param name="spec">Parsed advisory-locks spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(AdvisoryLocksSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        // Per-database: seen keys and seen constNames.
        // The same key in two DIFFERENT databases is LEGAL — different keyspaces.
        var seenKeysByDb = new Dictionary<string, Dictionary<long, string>>(
            StringComparer.Ordinal);
        var seenConstNamesByDb = new Dictionary<string, HashSet<string>>(
            StringComparer.Ordinal);

        var validEntries = new List<AdvisoryLockEntry>();

        foreach (var entry in spec.Locks)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (!seenKeysByDb.TryGetValue(entry.Database, out var seenKeys))
            {
                seenKeys = new Dictionary<long, string>();
                seenKeysByDb[entry.Database] = seenKeys;
            }

            if (!seenConstNamesByDb.TryGetValue(entry.Database, out var seenConstNames))
            {
                seenConstNames = new HashSet<string>(StringComparer.Ordinal);
                seenConstNamesByDb[entry.Database] = seenConstNames;
            }

            // Duplicate constName within the same database.
            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateConstNameInDatabase(
                    entry.ConstName, entry.Database));
                continue;
            }

            // Duplicate key within the same database — the load-bearing uniqueness check.
            if (seenKeys.TryGetValue(entry.Key, out var existingConst))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateKeyInDatabase(
                    entry.Key, existingConst, entry.Database));
                continue;
            }

            seenKeys[entry.Key] = entry.ConstName;
            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    /// <summary>
    /// Converts a database name to PascalCase for the nested lock class.
    /// Segments are split on <c>_</c> and <c>-</c> (canonical PG names use the
    /// <c>d2-&#123;domain&#125;</c> form, e.g. <c>d2-keycustodian</c> →
    /// <c>D2Keycustodian</c>).
    /// </summary>
    /// <param name="databaseName">The database name to convert.</param>
    internal static string SnakeToPascal(string databaseName)
    {
        if (databaseName.Length == 0)
            return databaseName;

        var parts = databaseName.Split(['_', '-'], StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part, 1, part.Length - 1);
        }

        return sb.ToString();
    }

    private static string EmitSource(List<AdvisoryLockEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.AdvisoryLocks.SourceGen.AdvisoryLocksGenerator");
        sb.AppendLine(
            "//   from contracts/advisory-locks/advisory-locks.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived registry of PostgreSQL session advisory lock keys,");
        sb.AppendLine(
            "/// partitioned by owning database. Keys are unique within each");
        sb.AppendLine(
            "/// database; the same key value in two different databases is legal");
        sb.AppendLine("/// (different keyspaces).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Use these constants instead of raw literals so a collision");
        sb.AppendLine(
            "/// between two locks in the same database is caught at build time.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        // Group entries by database, preserving spec order within each group.
        var byDatabase = entries
            .GroupBy(e => e.Database, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        var firstDb = true;
        foreach (var group in byDatabase)
        {
            if (!firstDb)
                sb.AppendLine();
            firstDb = false;

            var dbClass = SnakeToPascal(group.Key);
            sb.AppendLine($"    /// <summary>Advisory locks owned by {group.Key}.</summary>");
            sb.AppendLine($"    public static class {dbClass}");
            sb.AppendLine("    {");

            var firstEntry = true;
            foreach (var entry in group)
            {
                if (!firstEntry)
                    sb.AppendLine();
                firstEntry = false;

                sb.AppendLine(
                    $"        /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
                sb.AppendLine(
                    $"        public const long {entry.ConstName} = {entry.Key}L;");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
