// -----------------------------------------------------------------------
// <copyright file="ErrorCategoryEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.ErrorCodes.Category.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>ErrorCategory</c> enum, the
/// <c>ErrorCategoryWire</c> ↔ wire-string mapping, and the
/// <c>ErrorCategoryJsonConverter</c> from a parsed
/// <see cref="ErrorCategorySpec"/>. The emitted artifacts are byte-stable
/// with the shape the registry source-gen generates — the enum members
/// are sorted by wire string (ordinal) so the closed set is deterministic
/// across builds.
/// </summary>
internal static class ErrorCategoryEmitter
{
    /// <summary>The namespace the emitted types live in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.ErrorCodes.Category";

    /// <summary>
    /// snake_case wire-string validator. Bucket 1 (no backtracking) — anchored
    /// character-class match; no timeout needed.
    /// </summary>
    private static readonly Regex sr_wireRegex = new(
        "^[a-z][a-z0-9_]*$",
        RegexOptions.Compiled);

    /// <summary>Emits the ErrorCategory enum + wire mapping + converter source.</summary>
    /// <param name="spec">Parsed error-category spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(ErrorCategorySpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        var validEntries = new List<ErrorCategoryEntry>();
        var seenWires = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.Categories)
        {
            if (!sr_wireRegex.IsMatch(entry.Wire))
            {
                diagnostics.Add(EmitDiagnostics.InvalidWire(entry.Wire));
                continue;
            }

            if (entry.Doc.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyDoc(entry.Wire));
                continue;
            }

            if (!seenWires.Add(entry.Wire))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateWire(entry.Wire));
                continue;
            }

            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    /// <summary>
    /// Maps a spec category wire string (snake_case) to a C# PascalCase
    /// enum member name. The mapping must be stable and reversible so the
    /// parity test can compare wire strings against enum values.
    /// </summary>
    /// <param name="wire">Wire category string (e.g. <c>validation_failure</c>).</param>
    /// <returns>PascalCase enum member name (e.g. <c>ValidationFailure</c>).</returns>
    public static string WireToMemberName(string wire)
    {
        var segments = wire.Split('_');
        var sb = new StringBuilder(wire.Length);
        foreach (var segment in segments)
        {
            if (segment.Length == 0)
                continue;
            sb.Append(char.ToUpperInvariant(segment[0]));
            if (segment.Length > 1)
                sb.Append(segment.Substring(1).ToLowerInvariant());
        }

        return sb.ToString();
    }

    private static string EmitSource(List<ErrorCategoryEntry> entries)
    {
        // Sort by wire string (ordinal) so the emitted enum + mappings are
        // deterministic across builds and byte-stable with the closed set.
        var sorted = new List<ErrorCategoryEntry>(entries);
        sorted.Sort(static (a, b) => string.CompareOrdinal(a.Wire, b.Wire));

        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.ErrorCodes.Category.SourceGen.ErrorCategoryGenerator");
        sb.AppendLine(
            "//   from contracts/error-category/error-category.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        EmitEnum(sb, sorted);
        sb.AppendLine();
        EmitWireMapping(sb, sorted);
        sb.AppendLine();
        EmitJsonConverter(sb);

        return sb.ToString().LfNormalized();
    }

    private static void EmitEnum(StringBuilder sb, List<ErrorCategoryEntry> entries)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Closed semantic/telemetry classification for error codes. Each value");
        sb.AppendLine("/// maps one-to-one to the <c>category</c> wire string in the spec.");
        sb.AppendLine("/// Serializes/deserializes as the snake_case wire string via");
        sb.AppendLine("/// <see cref=\"ErrorCategoryJsonConverter\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[JsonConverter(typeof(ErrorCategoryJsonConverter))]");
        sb.AppendLine("public enum ErrorCategory");
        sb.AppendLine("{");

        var first = true;
        foreach (var entry in entries)
        {
            if (!first)
                sb.AppendLine();
            first = false;

            var memberName = WireToMemberName(entry.Wire);
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Wire value: <c>{EscapeXml(entry.Wire)}</c>.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    {memberName},");
        }

        sb.AppendLine("}");
    }

    private static void EmitWireMapping(StringBuilder sb, List<ErrorCategoryEntry> entries)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Canonical <see cref=\"ErrorCategory\"/> ↔ snake_case wire-string mapping.");
        sb.AppendLine("/// All consumers — JSON serialization, gRPC trailers, fixture emission —");
        sb.AppendLine("/// delegate to these two methods so the mapping has a single source of");
        sb.AppendLine("/// truth inside this assembly.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ErrorCategoryWire");
        sb.AppendLine("{");

        // sr_toWire — FrozenDictionary<ErrorCategory, string>
        sb.AppendLine("    private static readonly FrozenDictionary<ErrorCategory, string> sr_toWire =");
        sb.AppendLine("        new Dictionary<ErrorCategory, string>()");
        sb.AppendLine("        {");
        foreach (var entry in entries)
        {
            var memberName = WireToMemberName(entry.Wire);
            var escapedWire = EscapeStringLiteral(entry.Wire);
            sb.AppendLine($"            [ErrorCategory.{memberName}] = \"{escapedWire}\",");
        }

        sb.AppendLine("        }.ToFrozenDictionary();");
        sb.AppendLine();

        // sr_fromWire — FrozenDictionary<string, ErrorCategory>
        sb.AppendLine("    private static readonly FrozenDictionary<string, ErrorCategory> sr_fromWire =");
        sb.AppendLine("        new Dictionary<string, ErrorCategory>(StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (var entry in entries)
        {
            var memberName = WireToMemberName(entry.Wire);
            var escapedWire = EscapeStringLiteral(entry.Wire);
            sb.AppendLine($"            [\"{escapedWire}\"] = ErrorCategory.{memberName},");
        }

        sb.AppendLine("        }.ToFrozenDictionary(StringComparer.Ordinal);");
        sb.AppendLine();

        // ToWire
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Returns the snake_case wire string for the given");
        sb.AppendLine("    /// <see cref=\"ErrorCategory\"/> value");
        sb.AppendLine("    /// (e.g. <see cref=\"ErrorCategory.ValidationFailure\"/> →");
        sb.AppendLine("    /// <c>\"validation_failure\"</c>).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"category\">The enum value to convert.</param>");
        sb.AppendLine("    /// <returns>The canonical snake_case wire string.</returns>");
        sb.AppendLine("    /// <exception cref=\"System.ArgumentOutOfRangeException\">");
        sb.AppendLine("    /// Thrown when <paramref name=\"category\"/> is not a known member.");
        sb.AppendLine("    /// </exception>");
        sb.AppendLine("    public static string ToWire(this ErrorCategory category)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (sr_toWire.TryGetValue(category, out var wire))");
        sb.AppendLine("            return wire;");
        sb.AppendLine("        throw new System.ArgumentOutOfRangeException(");
        sb.AppendLine("            nameof(category),");
        sb.AppendLine("            category,");
        sb.AppendLine("            $\"Unknown ErrorCategory value: {category}\");");
        sb.AppendLine("    }");
        sb.AppendLine();

        // TryFromWire
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Attempts to parse a snake_case wire string into an");
        sb.AppendLine("    /// <see cref=\"ErrorCategory\"/> value.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"wire\">The snake_case wire string (e.g. <c>\"validation_failure\"</c>).</param>");
        sb.AppendLine("    /// <param name=\"category\">");
        sb.AppendLine("    /// When the method returns <see langword=\"true\"/>, contains the parsed value;");
        sb.AppendLine("    /// otherwise the default value.");
        sb.AppendLine("    /// </param>");
        sb.AppendLine("    /// <returns>");
        sb.AppendLine("    /// <see langword=\"true\"/> when <paramref name=\"wire\"/> is a known category;");
        sb.AppendLine("    /// <see langword=\"false\"/> for any unknown string.");
        sb.AppendLine("    /// </returns>");
        sb.AppendLine("    public static bool TryFromWire(string wire, out ErrorCategory category) =>");
        sb.AppendLine("        sr_fromWire.TryGetValue(wire, out category);");

        sb.AppendLine("}");
    }

    private static void EmitJsonConverter(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// <see cref=\"JsonConverter{T}\"/> for <see cref=\"ErrorCategory\"/>.");
        sb.AppendLine("/// Reads and writes the canonical snake_case wire string via");
        sb.AppendLine("/// <see cref=\"ErrorCategoryWire.ToWire\"/> /");
        sb.AppendLine("/// <see cref=\"ErrorCategoryWire.TryFromWire\"/>.");
        sb.AppendLine("/// Unknown wire strings throw <see cref=\"JsonException\"/> (strict policy).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class ErrorCategoryJsonConverter : JsonConverter<ErrorCategory>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public override ErrorCategory Read(");
        sb.AppendLine("        ref Utf8JsonReader reader,");
        sb.AppendLine("        Type typeToConvert,");
        sb.AppendLine("        JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.TokenType != JsonTokenType.String)");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new JsonException(");
        sb.AppendLine("                $\"Expected a string for ErrorCategory; got {reader.TokenType}.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var wire = reader.GetString();");
        sb.AppendLine("        if (wire is null)");
        sb.AppendLine("            throw new JsonException(\"Expected a non-null string for ErrorCategory.\");");
        sb.AppendLine();
        sb.AppendLine("        if (!ErrorCategoryWire.TryFromWire(wire, out var category))");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new JsonException(");
        sb.AppendLine("                $\"Unknown ErrorCategory wire value '{wire}'.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return category;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public override void Write(");
        sb.AppendLine("        Utf8JsonWriter writer,");
        sb.AppendLine("        ErrorCategory value,");
        sb.AppendLine("        JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(writer);");
        sb.AppendLine("        writer.WriteStringValue(value.ToWire());");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string EscapeXml(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string EscapeStringLiteral(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
