// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/dlq-failure-metadata/dlq-failure-metadata.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

/**
 * Spec-derived DLQ failure-metadata wire-shape catalogs.
 * Mirrors .NET D2.Shared.Messaging.DlqFailureMetadataFields and
 * D2.Shared.Messaging.RabbitMq.Subscribing.DlqFailureCauses (same wire values).
 */

/**
 * JSON property-name constants for the DlqFailureMetadata record.
 */
export const DlqFailureMetadataFields = {
  /**
   * JSON property carrying the closed-enum cause string (see DlqFailureCauses). Identifies what
   * category of failure triggered the dead-letter route.
   */
  CAUSE: "cause",
  /**
   * JSON property carrying either the exception type's FullName (HANDLER_EXCEPTION /
   * DECRYPT_FAILURE / DESERIALIZE_FAILURE) or the D2Result error code (HANDLER_RESULT_FAILURE).
   * Free-form string.
   */
  ERROR_CODE: "errorCode",
  /**
   * JSON property carrying the truncated diagnostic detail (≤256 chars). NEVER built from
   * exception.Message — for result-failure cases this is the join of result.messages.Select(m =>
   * m.Key); for exception cases it stays null.
   */
  DETAIL: "detail",
  /**
   * JSON property carrying the number of redelivery attempts observed before final NACK. Parsed
   * from the AMQP x-death header when available; 0 when not.
   */
  ATTEMPT_COUNT: "attemptCount",
  /**
   * JSON property carrying the W3C trace id (lower-hex, 32 chars) copied from the producer-side
   * headers so the DLQ entry stays correlatable across services.
   */
  TRACE_ID: "traceId",
  /**
   * JSON property carrying the consumer service name (which replica nacked the message). Optional.
   */
  NACKED_BY: "nackedBy",
} as const;

export type DlqFailureMetadataField =
  (typeof DlqFailureMetadataFields)[keyof typeof DlqFailureMetadataFields];

export const ALL_DLQ_FAILURE_METADATA_FIELDS: readonly string[] = [
  "cause",
  "errorCode",
  "detail",
  "attemptCount",
  "traceId",
  "nackedBy",
];

/**
 * Closed-enum cause-string constants for DlqFailureMetadata.Cause.
 */
export const DlqFailureCauses = {
  /**
   * Handler returned a non-Ok D2Result. The errorCode field carries result.ErrorCode.
   */
  HANDLER_RESULT_FAILURE: "HANDLER_RESULT_FAILURE",
  /**
   * Handler threw an unhandled exception. The errorCode field carries the exception type's FullName
   * (NEVER ex.Message — PII guard).
   */
  HANDLER_EXCEPTION: "HANDLER_EXCEPTION",
  /**
   * AEAD decrypt failed (kid missing from keyring, tag mismatch, etc.). Surfaces before the handler
   * is ever invoked.
   */
  DECRYPT_FAILURE: "DECRYPT_FAILURE",
  /**
   * JSON deserialization of the message body failed. Surfaces before the handler is ever invoked.
   */
  DESERIALIZE_FAILURE: "DESERIALIZE_FAILURE",
  /**
   * Tiered-retry attempt counter hit MaxAttempts; message routed direct to DLQ without invoking the
   * handler this time. The errorCode field also carries RETRIES_EXHAUSTED.
   */
  RETRIES_EXHAUSTED: "RETRIES_EXHAUSTED",
} as const;

export type DlqFailureCause =
  (typeof DlqFailureCauses)[keyof typeof DlqFailureCauses];

export const ALL_DLQ_FAILURE_CAUSES: readonly string[] = [
  "HANDLER_RESULT_FAILURE",
  "HANDLER_EXCEPTION",
  "DECRYPT_FAILURE",
  "DESERIALIZE_FAILURE",
  "RETRIES_EXHAUSTED",
];
