// -----------------------------------------------------------------------
// <copyright file="RegistryEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.ErrorCodes.Registry.SourceGen;

using System.Collections.Generic;
using System.Text;
using DcsvIo.D2.SourceGen;

/// <summary>
/// Emits the merged <c>ErrorCodeRegistry.g.cs</c> source file into
/// <c>DcsvIo.D2.ErrorCodes.Registry</c>. The emitter generates:
/// <list type="bullet">
///   <item>
///     The <c>ErrorCodeInfo</c> readonly-record-struct — the 9-field runtime
///     carrier: <c>Code</c>, <c>HttpStatus</c>, <c>Category</c>,
///     <c>UserMessageKey</c> (typed <c>TKMessage</c>), <c>FactoryName</c>,
///     <c>FactoryShape</c>, <c>Doc</c>, <c>Domain</c>, <c>IsDeprecated</c>.
///   </item>
///   <item>
///     The <c>ErrorCodeRegistry</c> static class — a
///     <c>FrozenDictionary&lt;string, ErrorCodeInfo&gt;</c>-backed lookup
///     exposing <c>TryResolve</c>, <c>Resolve</c>, and <c>All</c>.
///   </item>
/// </list>
/// The <c>ErrorCategory</c> enum (+ <c>ErrorCategoryWire</c> mapping +
/// <c>ErrorCategoryJsonConverter</c>) is NOT emitted here — it is the
/// relocated foundational <c>DcsvIo.D2.ErrorCodes.Category</c> leaf, which the
/// generated file references via a <c>using</c>. The
/// <see cref="CategoryToMemberName"/> map still resolves each code's
/// <c>category</c> wire string to the relocated enum member for the lookup
/// table.
/// </summary>
internal static class RegistryEmitter
{
    private const string _BANNER =
        "// -----------------------------------------------------------------------\n" +
        "// <auto-generated>\n" +
        "//   Generated by DcsvIo.D2.ErrorCodes.Registry.SourceGen.RegistryGenerator\n" +
        "//   from all contracts/*-error-codes/*.spec.json files (the source of truth).\n" +
        "//   Manual edits will be lost on rebuild.\n" +
        "// </auto-generated>\n" +
        "// -----------------------------------------------------------------------\n";

    /// <summary>
    /// Emits the complete <c>ErrorCodeRegistry.g.cs</c> source from the
    /// aggregated registry entries.
    /// </summary>
    /// <param name="entries">
    /// All registry entries, already validated (no collisions).
    /// </param>
    /// <returns>The generated C# source text.</returns>
    public static string Emit(IReadOnlyList<RegistrySpecEntry> entries)
    {
        var sb = new StringBuilder();

        sb.Append(_BANNER);
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace DcsvIo.D2.ErrorCodes.Registry;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.ObjectModel;");
        sb.AppendLine("using DcsvIo.D2.ErrorCodes.Category;");
        sb.AppendLine("using DcsvIo.D2.I18n;");
        sb.AppendLine();

        EmitErrorCodeInfoRecord(sb);
        sb.AppendLine();
        EmitRegistryClass(sb, entries);

        return sb.ToString().LfNormalized();
    }

    /// <summary>
    /// Maps a spec category wire string (snake_case) to a C# PascalCase
    /// enum member name. The mapping must be stable and reversible so the
    /// parity test can compare wire strings against enum values.
    /// </summary>
    /// <param name="category">Wire category string (e.g. <c>validation_failure</c>).</param>
    /// <returns>PascalCase enum member name (e.g. <c>ValidationFailure</c>).</returns>
    internal static string CategoryToMemberName(string category)
    {
        var segments = category.Split('_');
        var sb = new StringBuilder(category.Length);

        foreach (var segment in segments)
        {
            if (segment.Length == 0)
                continue;

            sb.Append(char.ToUpperInvariant(segment[0]));

            if (segment.Length > 1)
                sb.Append(segment.Substring(1).ToLowerInvariant());
        }

        return sb.ToString();
    }

    private static void EmitErrorCodeInfoRecord(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Full metadata record for one error code. All 9 fields are populated");
        sb.AppendLine("/// from the source spec; the registry exposes them via");
        sb.AppendLine("/// <see cref=\"ErrorCodeRegistry.TryResolve\"/> /");
        sb.AppendLine("/// <see cref=\"ErrorCodeRegistry.Resolve\"/> /");
        sb.AppendLine("/// <see cref=\"ErrorCodeRegistry.All\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <param name=\"Code\">");
        sb.AppendLine("/// Wire-format error code (SCREAMING_SNAKE, e.g. <c>AUTH_BEARER_MISSING</c>).");
        sb.AppendLine("/// </param>");
        sb.AppendLine("/// <param name=\"HttpStatus\">HTTP status mapping for transport (e.g. 401, 404).</param>");
        sb.AppendLine("/// <param name=\"Category\">");
        sb.AppendLine("/// Closed semantic/telemetry classification. Serializes as the snake_case");
        sb.AppendLine("/// wire string via <see cref=\"ErrorCategoryJsonConverter\"/>; to obtain the");
        sb.AppendLine("/// wire string in code call <c>Category.ToWire()</c>.");
        sb.AppendLine("/// </param>");
        sb.AppendLine("/// <param name=\"UserMessageKey\">");
        sb.AppendLine("/// Typed <see cref=\"TKMessage\"/> constant for the user-facing translation key.");
        sb.AppendLine("/// Consumers that need the raw wire key read <c>.Key</c> off this value.");
        sb.AppendLine("/// </param>");
        sb.AppendLine("/// <param name=\"FactoryName\">PascalCase factory name (e.g. <c>BearerMissing</c>).</param>");
        sb.AppendLine("/// <param name=\"FactoryShape\">");
        sb.AppendLine("/// Factory signature variant: <c>standard</c> (the universal");
        sb.AppendLine("/// error-factory shape) or <c>none</c>.");
        sb.AppendLine("/// </param>");
        sb.AppendLine("/// <param name=\"Doc\">XML summary / JSDoc documentation text for this code.</param>");
        sb.AppendLine("/// <param name=\"Domain\">");
        sb.AppendLine("/// Domain token derived from the spec filename (<c>common</c> for the generic");
        sb.AppendLine("/// catalog; e.g. <c>auth</c> for auth-error-codes.spec.json).");
        sb.AppendLine("/// </param>");
        sb.AppendLine("/// <param name=\"IsDeprecated\">");
        sb.AppendLine("/// <see langword=\"true\"/> when the spec entry carries the deprecation marker");
        sb.AppendLine("/// (<c>\"deprecated\": true</c>); the generated constant + factories also carry");
        sb.AppendLine("/// <c>[Obsolete]</c>. Lets runtime / telemetry consumers observe deprecation");
        sb.AppendLine("/// state. <see langword=\"false\"/> for an active code.");
        sb.AppendLine("/// </param>");
        sb.AppendLine("public readonly record struct ErrorCodeInfo(");
        sb.AppendLine("    string Code,");
        sb.AppendLine("    int HttpStatus,");
        sb.AppendLine("    ErrorCategory Category,");
        sb.AppendLine("    TKMessage UserMessageKey,");
        sb.AppendLine("    string FactoryName,");
        sb.AppendLine("    string FactoryShape,");
        sb.AppendLine("    string Doc,");
        sb.AppendLine("    string Domain,");
        sb.AppendLine("    bool IsDeprecated);");
    }

    private static void EmitRegistryClass(
        StringBuilder sb, IReadOnlyList<RegistrySpecEntry> entries)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Merged cross-catalog error-code registry. Aggregates every");
        sb.AppendLine("/// <c>*-error-codes.spec.json</c> into a single compile-time-frozen");
        sb.AppendLine("/// lookup table keyed by the SCREAMING_SNAKE wire code string.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// <para>");
        sb.AppendLine("/// The registry is a pure static lookup with no I/O, no DI, and no");
        sb.AppendLine("/// runtime configuration. The data is baked in at build time from the");
        sb.AppendLine("/// spec files and is immutable at runtime.");
        sb.AppendLine("/// </para>");
        sb.AppendLine("/// <para>");
        sb.AppendLine("/// Unknown codes return <see langword=\"false\"/> / <see langword=\"null\"/> —");
        sb.AppendLine("/// a hard not-found that signals deploy-skew to the caller. The caller");
        sb.AppendLine("/// decides any fallback (e.g. treat as <c>UNHANDLED_EXCEPTION</c>).");
        sb.AppendLine("/// </para>");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine("public static class ErrorCodeRegistry");
        sb.AppendLine("{");

        // sr_lookup field
        sb.AppendLine("    private static readonly FrozenDictionary<string, ErrorCodeInfo> sr_lookup =");
        sb.AppendLine("        new Dictionary<string, ErrorCodeInfo>(StringComparer.Ordinal)");
        sb.AppendLine("        {");

        // NOTE: the emitted string literals below are pipeline output — do not reformat for line length.
        foreach (var entry in entries)
        {
            var categoryMember = CategoryToMemberName(entry.Category);
            var tkPath = entry.UserMessageKey;
            var escapedDoc = EscapeStringLiteral(entry.Doc);
            var escapedFactoryName = EscapeStringLiteral(entry.FactoryName);
            var escapedFactoryShape = EscapeStringLiteral(entry.FactoryShape);
            var escapedCode = EscapeStringLiteral(entry.Code);
            var escapedDomain = EscapeStringLiteral(entry.Domain);

            sb.AppendLine($"            [\"{escapedCode}\"] = new ErrorCodeInfo(");
            sb.AppendLine($"                Code: \"{escapedCode}\",");
            sb.AppendLine($"                HttpStatus: {entry.HttpStatus},");
            sb.AppendLine($"                Category: ErrorCategory.{categoryMember},");
            sb.AppendLine($"                UserMessageKey: {tkPath},");
            sb.AppendLine($"                FactoryName: \"{escapedFactoryName}\",");
            sb.AppendLine($"                FactoryShape: \"{escapedFactoryShape}\",");
            sb.AppendLine($"                Doc: \"{escapedDoc}\",");
            sb.AppendLine($"                Domain: \"{escapedDomain}\",");
            sb.AppendLine(
                $"                IsDeprecated: {(entry.IsDeprecated ? "true" : "false")}),");
        }

        sb.AppendLine("        }.ToFrozenDictionary(StringComparer.Ordinal);");
        sb.AppendLine();

        // All property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// All registered error codes. The collection is in deterministic");
        sb.AppendLine("    /// spec-file-alphabetical order (stable across builds).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyCollection<ErrorCodeInfo> All { get; } =");
        sb.AppendLine("        new ReadOnlyCollection<ErrorCodeInfo>(");

        sb.AppendLine("            [");

        foreach (var entry in entries)
        {
            var escapedCode = EscapeStringLiteral(entry.Code);
            sb.AppendLine($"                sr_lookup[\"{escapedCode}\"],");
        }

        sb.AppendLine("            ]);");
        sb.AppendLine();

        // TryResolve
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Resolves the full <see cref=\"ErrorCodeInfo\"/> for the given wire");
        sb.AppendLine("    /// code string. The lookup is ordinal case-sensitive and allocation-free");
        sb.AppendLine("    /// on the hot path (backed by a <see cref=\"FrozenDictionary{TKey,TValue}\"/>).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"code\">");
        sb.AppendLine("    /// The SCREAMING_SNAKE wire code to look up");
        sb.AppendLine("    /// (e.g. <c>\"AUTH_BEARER_MISSING\"</c>).");
        sb.AppendLine("    /// </param>");
        sb.AppendLine("    /// <param name=\"info\">");
        sb.AppendLine("    /// When the method returns <see langword=\"true\"/>, contains the full");
        sb.AppendLine("    /// <see cref=\"ErrorCodeInfo\"/> for the code; otherwise the default value.");
        sb.AppendLine("    /// </param>");
        sb.AppendLine("    /// <returns>");
        sb.AppendLine("    /// <see langword=\"true\"/> when the code is registered;");
        sb.AppendLine("    /// <see langword=\"false\"/> for any unknown code (including empty /");
        sb.AppendLine("    /// null / wrong-case).");
        sb.AppendLine("    /// </returns>");
        sb.AppendLine("    public static bool TryResolve(string? code, out ErrorCodeInfo info)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (code is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            info = default;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return sr_lookup.TryGetValue(code, out info);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Resolve
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Convenience nullable overload of <see cref=\"TryResolve\"/>. Returns");
        sb.AppendLine("    /// <see langword=\"null\"/> for any unknown code.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"code\">The SCREAMING_SNAKE wire code to look up.</param>");
        sb.AppendLine("    /// <returns>");
        sb.AppendLine("    /// The <see cref=\"ErrorCodeInfo\"/> for the code, or");
        sb.AppendLine("    /// <see langword=\"null\"/> when the code is not registered.");
        sb.AppendLine("    /// </returns>");
        sb.AppendLine("    public static ErrorCodeInfo? Resolve(string? code) =>");
        sb.AppendLine("        TryResolve(code, out var info) ? info : null;");

        sb.AppendLine("}");
    }

    private static string EscapeStringLiteral(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
