// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Audit.Api.Grpc;

using PingAuditRequest = global::D2.Services.Protos.Audit.V2Alpha.PingAuditRequest;
using PingAuditResponse = global::D2.Services.Protos.Audit.V2Alpha.PingAuditResponse;
using PingAuditInput = global::D2.Audit.Client.Ping.PingAuditInput;
using PingAuditOutput = global::D2.Audit.Client.Ping.PingAuditOutput;
using global::D2.Shared.Result.Grpc;
using global::Grpc.Core;
using D2.Audit.App.Application.Handlers.Queries.PingAudit;

/// <summary>Generated gRPC service for the <c>PingAudit</c> operation, delegating to <see cref="IPingAuditHandler"/>.</summary>
public sealed class AuditPingService(IPingAuditHandler handler)
    : global::D2.Services.Protos.Audit.V2Alpha.AuditPing.AuditPingBase
{
    /// <inheritdoc/>
    public override async Task<PingAuditResponse> PingAudit(PingAuditRequest request, ServerCallContext context)
    {
        PingAuditInput input = request.ToPingAuditInput();
        var result = await handler.HandleAsync(input, context.CancellationToken).ConfigureAwait(false);
        return result.ToProtoResponse();
    }
}
