// <auto-generated />
using DcsvIo.D2.Private.Edge.KeyCustodian.Infra.Persistence.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.Infra.Persistence.Postgres.Migrations
{
    [DbContext(typeof(KeyCustodianDbContext))]
    partial class KeyCustodianDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DcsvIo.D2.Private.Edge.KeyCustodian.App.Infrastructure.Persistence.KeyAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("detail");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kid");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ResultingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resulting_status");

                    b.HasKey("Id");

                    b.HasIndex("Kid", "OccurredAt")
                        .HasDatabaseName("ix_key_audit_record_kid_occurred_at");

                    b.ToTable("key_audit_record", (string)null);
                });

            modelBuilder.Entity("DcsvIo.D2.Private.Edge.KeyCustodian.App.Infrastructure.Persistence.KeyRecord", b =>
                {
                    b.Property<string>("Kid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kid");

                    b.Property<Instant?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<byte[]>("CaCertificate")
                        .HasColumnType("bytea")
                        .HasColumnName("ca_certificate");

                    b.Property<string>("CompromiseReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("compromise_reason");

                    b.Property<Instant?>("CompromisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("compromised_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyDomain")
                        .IsRequired()
                        .HasMaxLength(69)
                        .HasColumnType("character varying(69)")
                        .HasColumnName("key_domain");

                    b.Property<byte[]>("KeyMaterialEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_material_encrypted");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_type");

                    b.Property<byte[]>("PublicKeyMaterial")
                        .HasColumnType("bytea")
                        .HasColumnName("public_key_material");

                    b.Property<Instant?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<Instant?>("RetiringAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retiring_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Kid");

                    b.HasIndex("KeyDomain")
                        .IsUnique()
                        .HasDatabaseName("ux_key_record_one_pending_per_domain")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("KeyDomain", "Status")
                        .HasDatabaseName("ix_key_record_key_domain_status");

                    b.ToTable("key_record", (string)null);
                });

            modelBuilder.Entity("DcsvIo.D2.Private.Edge.KeyCustodian.App.Infrastructure.Persistence.LeafIssuanceAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("IssuingCaKid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("issuing_ca_kid");

                    b.Property<Instant>("LeafNotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leaf_not_after");

                    b.Property<string>("WorkloadServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("workload_service_id");

                    b.HasKey("Id");

                    b.HasIndex("IssuingCaKid")
                        .HasDatabaseName("ix_leaf_issuance_audit_record_issuing_ca_kid");

                    b.HasIndex("WorkloadServiceId", "IssuedAt")
                        .HasDatabaseName("ix_leaf_issuance_audit_record_workload_service_id_issued_at");

                    b.ToTable("leaf_issuance_audit_record", (string)null);
                });

            modelBuilder.Entity("DcsvIo.D2.Private.Edge.KeyCustodian.App.Infrastructure.Persistence.KeyAuditRecord", b =>
                {
                    b.HasOne("DcsvIo.D2.Private.Edge.KeyCustodian.App.Infrastructure.Persistence.KeyRecord", null)
                        .WithMany()
                        .HasForeignKey("Kid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DcsvIo.D2.Private.Edge.KeyCustodian.App.Infrastructure.Persistence.LeafIssuanceAuditRecord", b =>
                {
                    b.HasOne("DcsvIo.D2.Private.Edge.KeyCustodian.App.Infrastructure.Persistence.KeyRecord", null)
                        .WithMany()
                        .HasForeignKey("IssuingCaKid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
