// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Edge.Api.Grpc.KeyCustodian;

using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Facade;
using global::DcsvIo.D2.Result.Grpc;
using global::Grpc.Core;
using GetOrLazyProvisionSealPublicKeyInput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing.GetOrLazyProvisionSealPublicKeyInput;
using GetOrLazyProvisionSealPublicKeyOutput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing.GetOrLazyProvisionSealPublicKeyOutput;
using GetOrLazyProvisionSealPublicKeyRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetOrLazyProvisionSealPublicKeyRequest;
using GetOrLazyProvisionSealPublicKeyResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetOrLazyProvisionSealPublicKeyResponse;

/// <summary>Generated gRPC service for the <c>GetOrLazyProvisionSealPublicKey</c> operation, delegating to <see cref="IKeyCustodianApi"/>.</summary>
public sealed class KeyCustodianSealPublicKeyService(IKeyCustodianApi facade)
    : global::D2.Services.Protos.KeyCustodian.V2Alpha.KeyCustodianSealPublicKey.KeyCustodianSealPublicKeyBase
{
    /// <inheritdoc/>
    public override async Task<GetOrLazyProvisionSealPublicKeyResponse> GetOrLazyProvisionSealPublicKey(GetOrLazyProvisionSealPublicKeyRequest request, ServerCallContext context)
    {
        GetOrLazyProvisionSealPublicKeyInput input = request.ToGetOrLazyProvisionSealPublicKeyInput();
        var result = await facade.GetOrLazyProvisionSealPublicKeyAsync(input, context.CancellationToken).ConfigureAwait(false);
        return result.ToProtoResponse();
    }
}
