// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Edge.Api.Grpc.KeyCustodian;

using GetKeyringRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetKeyringRequest;
using GetKeyringResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetKeyringResponse;
using GetKeyringInput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Keyring.GetKeyringInput;
using GetKeyringOutput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Keyring.GetKeyringOutput;
using global::DcsvIo.D2.Result.Grpc;
using global::Grpc.Core;
using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Facade;

/// <summary>Generated gRPC service for the <c>GetKeyring</c> operation, delegating to <see cref="IKeyCustodianApi"/>.</summary>
public sealed class KeyCustodianKeyringService(IKeyCustodianApi facade)
    : global::D2.Services.Protos.KeyCustodian.V2Alpha.KeyCustodianKeyring.KeyCustodianKeyringBase
{
    /// <inheritdoc/>
    public override async Task<GetKeyringResponse> GetKeyring(GetKeyringRequest request, ServerCallContext context)
    {
        GetKeyringInput input = request.ToGetKeyringInput();
        var result = await facade.GetKeyringAsync(input, context.CancellationToken).ConfigureAwait(false);
        return result.ToProtoResponse();
    }
}
