// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.Client.CaCertificate;

/// <summary>Generated DTO for the <c>GetCaCertificateOutput</c> operation.</summary>
public sealed record GetCaCertificateOutput(
    byte[] RootCertificateDer,
    byte[] IntermediateCertificateDer);
