// -----------------------------------------------------------------------
// <copyright file="EmitterHelpers.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.Geo.SourceGen.Emitters;

using System.Text;

/// <summary>
/// Shared scaffolding helpers used by every per-target emitter in this
/// directory — the autogen file-header banner + per-language escape rules
/// for embedded values (string literals + XML doc text).
/// </summary>
internal static class EmitterHelpers
{
    /// <summary>The shared <c>DcsvIo.D2.Geo.Abstractions</c> namespace.</summary>
    public const string AbstractionsNamespace = "DcsvIo.D2.Geo.Abstractions";

    /// <summary>
    /// Appends the auto-generated file banner (5-line block + <c>#nullable enable</c>)
    /// to the supplied <see cref="StringBuilder"/>. Keeps every emitted file's
    /// preamble identical so consumers can spot a hand-edit at a glance.
    /// </summary>
    /// <param name="sb">The destination buffer.</param>
    public static void AppendFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by DcsvIo.D2.Geo.SourceGen.GeoGenerator");
        sb.AppendLine("//   from the contracts/geo/*.spec.json files (the source of truth).");
        sb.AppendLine("//   Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
    }

    /// <summary>
    /// Escapes the supplied value for inclusion in a C# string literal.
    /// </summary>
    /// <param name="value">The value to escape.</param>
    /// <returns>The escaped value.</returns>
    public static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    /// <summary>
    /// Escapes the supplied value for inclusion inside an XML doc comment.
    /// </summary>
    /// <param name="value">The value to escape.</param>
    /// <returns>The escaped value.</returns>
    public static string EscapeXmlDoc(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
