// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Queries.GetJwks;

using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Jwks;

/// <summary>Generated handler interface for the <c>GetJwks</c> operation.</summary>
public interface IGetJwksHandler : IHandler<GetJwksInput, GetJwksOutput>;
