// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/auth-context/IAuthContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

export const CallPathKind = {
  Edge: "Edge",
  WorkloadHop: "WorkloadHop",
  ModuleHop: "ModuleHop",
  System: "System",
} as const;

export type CallPathKind = (typeof CallPathKind)[keyof typeof CallPathKind];

/** The Edge HTTP inbound boundary (the originating hop). */
export const CallPathKind_Edge: CallPathKind = CallPathKind.Edge;
/** A cross-process workload hop reached over authenticated mutual TLS. */
export const CallPathKind_WorkloadHop: CallPathKind = CallPathKind.WorkloadHop;
/** An in-process module hop (the in-host leaf). */
export const CallPathKind_ModuleHop: CallPathKind = CallPathKind.ModuleHop;
/** An in-host system worker (a background service). */
export const CallPathKind_System: CallPathKind = CallPathKind.System;
