// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/auth-context/IAuthContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

export const OrgType = {
  Admin: "Admin",
  Support: "Support",
  Customer: "Customer",
  ThirdParty: "ThirdParty",
  Affiliate: "Affiliate",
} as const;

export type OrgType = (typeof OrgType)[keyof typeof OrgType];

/** Administrative organization. */
export const OrgType_Admin: OrgType = OrgType.Admin;
/** Support organization. */
export const OrgType_Support: OrgType = OrgType.Support;
/** Customer organization. */
export const OrgType_Customer: OrgType = OrgType.Customer;
/** Third-party organization. */
export const OrgType_ThirdParty: OrgType = OrgType.ThirdParty;
/** Affiliate organization. */
export const OrgType_Affiliate: OrgType = OrgType.Affiliate;
