// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace D2.Audit.App.Application.Handlers.Queries.PingAudit;

using D2.Audit.Client.Ping;

/// <summary>Generated handler interface for the <c>PingAudit</c> operation.</summary>
public interface IPingAuditHandler : IHandler<PingAuditInput, PingAuditOutput>;
