// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/request-context/IRequestContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

/**
 * Cross-hop propagated subset of IRequestContext. Identity fields
 * (UserId / OrgId / Scopes / ActorChain) are NOT included — they
 * rebuild from the JWT at every sync hop.
 */
export interface IPropagatedContext {
  readonly requestId: string | null;
  readonly requestPath: string | null;
  readonly sessionFingerprint: string | null;
  readonly currentFingerprint: string | null;
  readonly riskScore: number | null;
  readonly whoIsHashId: string | null;
}
