// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by tools/ts-codegen — see this script's source for details.
//   Source spec: contracts/request-context/IRequestContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

import type { IPropagatedContext } from "./IPropagatedContext.g.js";

/**
 * Serializer for the IPropagatedContext envelope. Round-trip-safe:
 * `serialize(deserialize(s)) === s` for any well-formed envelope.
 * `tryDecode` enforces per-field maxLength caps from the spec; a
 * forged envelope with any cap exceeded is dropped wholesale.
 */
export class PropagatedContextSerializer {
  static serialize(ctx: IPropagatedContext): string {
    const o: Record<string, unknown> = {};
    if (ctx.requestId !== null && ctx.requestId !== undefined) o["requestId"] = ctx.requestId;
    if (ctx.requestPath !== null && ctx.requestPath !== undefined) o["requestPath"] = ctx.requestPath;
    if (ctx.requestStartedAt !== null && ctx.requestStartedAt !== undefined) o["requestStartedAt"] = ctx.requestStartedAt;
    if (ctx.idempotencyKey !== null && ctx.idempotencyKey !== undefined) o["idempotencyKey"] = ctx.idempotencyKey;
    if (ctx.sessionFingerprint !== null && ctx.sessionFingerprint !== undefined) o["sessionFingerprint"] = ctx.sessionFingerprint;
    if (ctx.currentFingerprint !== null && ctx.currentFingerprint !== undefined) o["currentFingerprint"] = ctx.currentFingerprint;
    if (ctx.riskScore !== null && ctx.riskScore !== undefined) o["riskScore"] = ctx.riskScore;
    if (ctx.edgeNodeId !== null && ctx.edgeNodeId !== undefined) o["edgeNodeId"] = ctx.edgeNodeId;
    if (ctx.localeIetfBcp47Tag !== null && ctx.localeIetfBcp47Tag !== undefined) o["localeIetfBcp47Tag"] = ctx.localeIetfBcp47Tag;
    if (ctx.timezoneIanaName !== null && ctx.timezoneIanaName !== undefined) o["timezoneIanaName"] = ctx.timezoneIanaName;
    if (ctx.currencyIso4217Code !== null && ctx.currencyIso4217Code !== undefined) o["currencyIso4217Code"] = ctx.currencyIso4217Code;
    if (ctx.orgPlanTier !== null && ctx.orgPlanTier !== undefined) o["orgPlanTier"] = ctx.orgPlanTier;
    if (ctx.featureFlagsCsv !== null && ctx.featureFlagsCsv !== undefined) o["featureFlagsCsv"] = ctx.featureFlagsCsv;
    if (ctx.whoIsHashId !== null && ctx.whoIsHashId !== undefined) o["whoIsHashId"] = ctx.whoIsHashId;
    return JSON.stringify(o);
  }

  static tryDecode(input: string | null | undefined): IPropagatedContext | undefined {
    if (input === null || input === undefined || input === "") return undefined;
    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(input) as Record<string, unknown>;
    } catch {
      return undefined;
    }
    if (parsed === null || typeof parsed !== "object") return undefined;
    const out: Record<string, unknown> = {};
    {
      const v = parsed["requestId"];
      if (v === undefined || v === null) {
        // absent — leave out["requestId"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        if (v.length > 256) return undefined;
        out["requestId"] = v;
      }
    }
    {
      const v = parsed["requestPath"];
      if (v === undefined || v === null) {
        // absent — leave out["requestPath"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        if (v.length > 2048) return undefined;
        out["requestPath"] = v;
      }
    }
    {
      const v = parsed["requestStartedAt"];
      if (v === undefined || v === null) {
        // absent — leave out["requestStartedAt"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        out["requestStartedAt"] = v;
      }
    }
    {
      const v = parsed["idempotencyKey"];
      if (v === undefined || v === null) {
        // absent — leave out["idempotencyKey"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        if (v.length > 255) return undefined;
        out["idempotencyKey"] = v;
      }
    }
    {
      const v = parsed["sessionFingerprint"];
      if (v === undefined || v === null) {
        // absent — leave out["sessionFingerprint"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        if (v.length > 512) return undefined;
        out["sessionFingerprint"] = v;
      }
    }
    {
      const v = parsed["currentFingerprint"];
      if (v === undefined || v === null) {
        // absent — leave out["currentFingerprint"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        if (v.length > 512) return undefined;
        out["currentFingerprint"] = v;
      }
    }
    {
      const v = parsed["riskScore"];
      if (v === undefined || v === null) {
        // absent — leave out["riskScore"] unset (undefined)
      } else {
        if (typeof v !== "number" || !Number.isFinite(v)) return undefined;
        out["riskScore"] = v;
      }
    }
    {
      const v = parsed["edgeNodeId"];
      if (v === undefined || v === null) {
        // absent — leave out["edgeNodeId"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        out["edgeNodeId"] = v;
      }
    }
    {
      const v = parsed["localeIetfBcp47Tag"];
      if (v === undefined || v === null) {
        // absent — leave out["localeIetfBcp47Tag"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        out["localeIetfBcp47Tag"] = v;
      }
    }
    {
      const v = parsed["timezoneIanaName"];
      if (v === undefined || v === null) {
        // absent — leave out["timezoneIanaName"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        out["timezoneIanaName"] = v;
      }
    }
    {
      const v = parsed["currencyIso4217Code"];
      if (v === undefined || v === null) {
        // absent — leave out["currencyIso4217Code"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        out["currencyIso4217Code"] = v;
      }
    }
    {
      const v = parsed["orgPlanTier"];
      if (v === undefined || v === null) {
        // absent — leave out["orgPlanTier"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        out["orgPlanTier"] = v;
      }
    }
    {
      const v = parsed["featureFlagsCsv"];
      if (v === undefined || v === null) {
        // absent — leave out["featureFlagsCsv"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        out["featureFlagsCsv"] = v;
      }
    }
    {
      const v = parsed["whoIsHashId"];
      if (v === undefined || v === null) {
        // absent — leave out["whoIsHashId"] unset (undefined)
      } else {
        if (typeof v !== "string") return undefined;
        if (v.length > 128) return undefined;
        out["whoIsHashId"] = v;
      }
    }
    return out as unknown as IPropagatedContext;
  }
}
