// -----------------------------------------------------------------------
// <copyright file="ErrorCodesEmitter.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.ResultErrorCodes.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using D2.Shared.SourceGen;
using D2.Shared.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>ErrorCodes</c> static class source from
/// a parsed <see cref="ErrorCodesSpec"/>. Stateless and unit-testable in
/// isolation. The Roslyn-host integration (<see cref="ErrorCodesGenerator"/>)
/// calls this and translates emit-side <see cref="EmitDiagnostic"/> records
/// into Roslyn <c>Diagnostic</c> instances.
/// </summary>
internal static class ErrorCodesEmitter
{
    /// <summary>The namespace the <c>ErrorCodes</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "D2.Shared.Result";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "ErrorCodes";

    /// <summary>
    /// HTTP statuses the codegen mapping currently supports. Expanding the
    /// runtime D2Result taxonomy to a new status requires adding an entry
    /// here AND in the JSON-Schema enum at
    /// <c>contracts/error-codes/schema.json</c>.
    /// </summary>
    public static readonly ImmutableArray<int> SR_SupportedHttpStatuses =
        ImmutableArray.Create(200, 206, 207, 400, 401, 403, 404, 409, 413, 429, 500, 503);

    private static readonly Regex sr_codePattern =
        new("^[A-Z][A-Z0-9_]*$", RegexOptions.CultureInvariant);

    /// <summary>
    /// Emits the <c>ErrorCodes</c> class source plus diagnostics for the
    /// supplied spec.
    /// </summary>
    /// <param name="spec">Parsed error-codes spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(ErrorCodesSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();
        var supportedStatuses = string.Join(
            ", ",
            SR_SupportedHttpStatuses.Select(
                s => s.ToString(System.Globalization.CultureInfo.InvariantCulture)));

        var validEntries = new List<ErrorCodeEntry>();
        var seenCodes = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.ErrorCodes)
        {
            if (entry.Code.Falsey() || !sr_codePattern.IsMatch(entry.Code))
            {
                diagnostics.Add(EmitDiagnostics.InvalidCode(entry.Code));
                continue;
            }

            if (!seenCodes.Add(entry.Code))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateCode(entry.Code));
                continue;
            }

            if (!SR_SupportedHttpStatuses.Contains(entry.HttpStatus))
            {
                diagnostics.Add(EmitDiagnostics.InvalidHttpStatus(
                    entry.Code, entry.HttpStatus, supportedStatuses));
                continue;
            }

            if (entry.Doc.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.MissingDoc(entry.Code));
                continue;
            }

            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(List<ErrorCodeEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by D2.Shared.Result.ErrorCodes.SourceGen");
        sb.AppendLine(
            "//   (ErrorCodesGenerator) from contracts/error-codes/error-codes.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Standardized error codes used across the application as the value of");
        sb.AppendLine(
            "/// <see cref=\"D2Result.ErrorCode\"/>. Consumers may compare against these");
        sb.AppendLine(
            "/// constants (or use the per-code boolean helpers on <see cref=\"D2Result\"/>)");
        sb.AppendLine("/// to discriminate between known failure modes.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            "/// Generated from the spec file - cross-language drift between the .NET");
        sb.AppendLine(
            "/// constants and the TS-side @d2/result catalog is structurally impossible");
        sb.AppendLine(
            "/// (the TS emitter consumes the same spec via tools/ts-codegen).");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        foreach (var entry in entries)
        {
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.Code} = \"{EscapeStringLiteral(entry.Code)}\";");
            sb.AppendLine();
        }

        EmitAllCodes(sb, entries);
        sb.AppendLine();
        EmitGetHttpStatus(sb, entries);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitAllCodes(StringBuilder sb, List<ErrorCodeEntry> entries)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// All declared error codes in spec order. Useful for telemetry");
        sb.AppendLine(
            "    /// tag-value membership checks and cross-spec consistency tests.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static IReadOnlyList<string> AllCodes => sr_allCodes;");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyList<string> sr_allCodes = new string[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
            sb.AppendLine($"        \"{EscapeStringLiteral(entry.Code)}\",");

        sb.AppendLine("    };");
    }

    private static void EmitGetHttpStatus(StringBuilder sb, List<ErrorCodeEntry> entries)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Returns the HTTP status code declared in the spec for");
        sb.AppendLine(
            "    /// <paramref name=\"errorCode\"/>, or <c>500</c> if the code is not");
        sb.AppendLine(
            "    /// recognized (defensive default - every shipped code is in the table).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"errorCode\">The error code.</param>");
        sb.AppendLine("    /// <returns>The HTTP status code.</returns>");
        sb.AppendLine("    public static int GetHttpStatus(string errorCode) => errorCode switch");
        sb.AppendLine("    {");
        foreach (var entry in entries)
        {
            sb.AppendLine(
                $"        \"{EscapeStringLiteral(entry.Code)}\" => {entry.HttpStatus},");
        }

        sb.AppendLine("        _ => 500,");
        sb.AppendLine("    };");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
