// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Audit.Client;

using PingAuditInput = global::DcsvIo.D2.Private.Audit.Client.Ping.PingAuditInput;
using PingAuditOutput = global::DcsvIo.D2.Private.Audit.Client.Ping.PingAuditOutput;
using D2.Services.Protos.Common.V1;
using DcsvIo.D2.Resilience.Pipeline;
using DcsvIo.D2.Resilience.Retry;
using DcsvIo.D2.Result.Grpc;
using Grpc.Core;
using Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Generated sealed cross-process gRPC client for the Audit module.
/// Runs each throwing stub call inside the keyed ResilientPipeline (transport-only
/// retry); reconstructs the business D2Result from the captured envelope after the
/// pipeline returns.
/// </summary>
public sealed class AuditGrpcClient(
    global::D2.Services.Protos.Audit.V2Alpha.AuditPing.AuditPingClient auditPingStub,
    [FromKeyedServices(PingAuditClientKeys.PIPELINE)] ResilientPipeline<string, PingAuditOutput?> pingAuditPipeline
) : IAuditGrpcClient
{
    private readonly ResilientPipeline<string, PingAuditOutput?> r_pingAuditPipeline = pingAuditPipeline;

    /// <inheritdoc/>
    public ValueTask<D2Result<PingAuditOutput?>> PingAuditAsync(
        PingAuditInput input,
        ResilientPipeline<string, PingAuditOutput?>? pipelineOverride = null,
        CancellationToken ct = default)
        => PingAuditCoreAsync(input, pipelineOverride ?? r_pingAuditPipeline, ct);

    private async ValueTask<D2Result<PingAuditOutput?>> PingAuditCoreAsync(
        PingAuditInput input,
        ResilientPipeline<string, PingAuditOutput?> pipeline,
        CancellationToken ct)
    {
        var request = input.ToPingAuditRequest();
        D2ResultProto? envelope = null;                  // captured out of the closure
        RpcException? transportFault = null;             // captured out of the closure
        var pipelineResult = await pipeline.ExecuteAsync(
            PingAuditClientKeys.PIPELINE_KEY,
            async innerCt =>
            {
                try
                {
                    var response = await auditPingStub.PingAuditAsync(request, cancellationToken: innerCt);
                    envelope = response.Result;          // business result (gRPC status OK)
                    return response.Data is null ? default : response.Data.ToPingAuditOutput();
                }
                catch (RpcException ex)
                {
                    transportFault = ex;                 // capture; rethrow so the retry layer still sees the throw
                    throw;
                }
            },
            ct);
        // Transport fault: the pipeline classifies RpcException via the gRPC-agnostic generic
        // path (mis-mapping to UnhandledException); remap the captured RpcException to the
        // gRPC-aware code (Cancelled -> Canceled, else -> ServiceUnavailable).
        if (!pipelineResult.Success && transportFault is not null)
            return transportFault.ToTransportFaultResult<PingAuditOutput?>();
        // Business result: reconstruct the full D2Result from the captured envelope. Other
        // pipeline failures (CircuitOpen, RateLimit, caller-cancel) pass through verbatim.
        return pipelineResult.Success && envelope is not null
            ? envelope.ToD2Result<PingAuditOutput?>(pipelineResult.Data)
            : pipelineResult;
    }
}
