// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Audit.Client;

/// <summary>
/// Service-key constants for the <c>PingAudit</c> gRPC client resilience pipeline.
/// </summary>
public static class PingAuditClientKeys
{
    /// <summary>DI service key for the keyed <c>ResilientPipeline&lt;TKey, TValue&gt;</c> registration.</summary>
    public const string PIPELINE = "PingAuditGrpcClientPipeline";

    /// <summary>
    /// Per-call pipeline key passed to <c>ExecuteAsync</c>. Inert for retry-only
    /// pipelines; a singleflight-enabled pipeline must supply a per-request key
    /// instead to avoid wrongly deduplicating distinct calls.
    /// </summary>
    internal const string PIPELINE_KEY = "PingAuditGrpcClientCall";
}
