// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Tests for the TS extraction adapter (ts-api-adapter.ts).
//
// Coverage:
//   Unit (synthetic fixtures):
//     - parseApiMembers: fence extraction, multi-line declarations
//     - extractMemberName: identifier extraction per declaration kind
//     - diffApiMembers: added / removed / changed detection
//     - normaliseJsForFingerprint: comment stripping + blank-line collapse
//     - computeDistFingerprint: determinism, comment-stability, content change
//
//   Integration (real @d2/error-category package on disk):
//     - ApiDiff: no-op baseline, added-export detection, removed-export detection
//     - FingerprintDiff: comment-only .js edit → SAME hash; logic edit → DIFFERENT hash
//
// The integration tests use REAL api-extractor against the built dist/ of
// @d2/error-category. They inject BaselineReader and DistReader seams so the
// tests are deterministic and do not mutate committed files.

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { repoRoot } from "./repo-root.js";
import {
  computeDistFingerprint,
  diffApiMembers,
  extractMemberName,
  extractTsPackageDiff,
  normaliseJsForFingerprint,
  parseApiMembers,
  type BaselineReader,
  type DistReader,
} from "../src/ts-api-adapter.js";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const ERROR_CATEGORY_DIR = resolve(
  repoRoot,
  "server/shared/typescript/error-category",
);

/** The committed baseline api.md content for @d2/error-category. */
const BASELINE_API_MD = `## API Report File for "@d2/error-category"

> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).

\`\`\`ts

// @public
export const ALL_ERROR_CATEGORIES: readonly ErrorCategory[];

// @public
export type ErrorCategory = "conflict" | "infrastructure_unavailable" | "internal_error" | "not_found" | "partial_success" | "payload_too_large" | "policy_denied" | "rate_limited" | "validation_failure";

// @public
export const ErrorCategoryWire: {
    readonly Conflict: "conflict";
    readonly InfrastructureUnavailable: "infrastructure_unavailable";
    readonly InternalError: "internal_error";
    readonly NotFound: "not_found";
    readonly PartialSuccess: "partial_success";
    readonly PayloadTooLarge: "payload_too_large";
    readonly PolicyDenied: "policy_denied";
    readonly RateLimited: "rate_limited";
    readonly ValidationFailure: "validation_failure";
};

// (No @packageDocumentation comment for this package)

\`\`\`
`;

/**
 * Committed baseline fingerprint for @d2/error-category.
 * Computed by hashing dist/ .js (comment-normalised) + .d.ts + package.json
 * metadata. See tools/release-runner/fingerprint-probe.mjs for the derivation.
 */
const BASELINE_FINGERPRINT =
  "5bf53e286e4f8b76c4c3103953ddd6b4b855e3947440eb60c53c0c5a8e221ec5";

// ---------------------------------------------------------------------------
// Helpers — synthetic seams
// ---------------------------------------------------------------------------

function makeFixedBaselineReader(
  apiMd: string | undefined,
  fingerprint: string | undefined,
): BaselineReader {
  return {
    read(filePath: string): string | undefined {
      if (filePath.endsWith(".api.md")) return apiMd;
      if (filePath.endsWith("dist-fingerprint.txt")) return fingerprint;
      return undefined;
    },
  };
}

/**
 * A DistReader backed by real fs but with injectable per-file overrides.
 * Overrides are keyed by the filename (basename only) and extension,
 * e.g. { "index.js": "... custom content ..." }.
 */
function makeOverrideDistReader(
  overrides: Record<string, string> = {},
): DistReader {
  return {
    listFiles(distDir: string, extensions: string[]): string[] {
      if (!existsSync(distDir)) return [];

      const results: string[] = [];

      function walk(dir: string): void {
        const entries = readdirSync(dir, { withFileTypes: true });

        for (const entry of entries) {
          const full = join(dir, entry.name);

          if (entry.isDirectory()) {
            walk(full);
          } else if (entry.isFile()) {
            const ext = entry.name.slice(entry.name.lastIndexOf("."));

            if (extensions.includes(ext)) results.push(full);
          }
        }
      }

      walk(distDir);

      return results.sort();
    },

    readFile(filePath: string): string {
      // Check if there is a basename override.
      const parts = filePath.replaceAll("\\", "/").split("/");
      const fileName = parts[parts.length - 1] ?? "";

      if (Object.prototype.hasOwnProperty.call(overrides, fileName)) {
        return overrides[fileName]!;
      }

      return readFileSync(filePath, "utf-8");
    },
  };
}

// ---------------------------------------------------------------------------
// Unit tests — parseApiMembers
// ---------------------------------------------------------------------------

describe("parseApiMembers — fence extraction", () => {
  it("parses a simple single-line export const", () => {
    const md = `## API Report File for "@d2/x"\n\n\`\`\`ts\n\n// @public\nexport const FOO: string;\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.has("export const FOO: string;")).toBe(true);
    expect(members.size).toBe(1);
  });

  it("parses a single-line export type alias", () => {
    const md = `\`\`\`ts\n\n// @public\nexport type Cat = "a" | "b";\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.has(`export type Cat = "a" | "b";`)).toBe(true);
  });

  it("parses a multi-line export const object", () => {
    const md =
      `\`\`\`ts\n\n// @public\nexport const Wire: {\n` +
      `    readonly A: "a";\n    readonly B: "b";\n};\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.size).toBe(1);
    const decl = [...members][0]!;
    expect(decl).toContain("export const Wire:");
    expect(decl).toContain(`readonly A: "a";`);
  });

  it("excludes comment lines and blank lines at top level", () => {
    const md = `\`\`\`ts\n\n// @public\nexport const X: number;\n\n// (No @packageDocumentation comment for this package)\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.size).toBe(1);
    expect([...members][0]).toBe("export const X: number;");
  });

  it("handles content before the fence (ignores it)", () => {
    const md = `# Header\nSome prose\n\n\`\`\`ts\n\n// @public\nexport function foo(): void;\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.has("export function foo(): void;")).toBe(true);
  });

  it("returns empty set for an api.md with no exports", () => {
    const md = `\`\`\`ts\n\n// (No @packageDocumentation comment for this package)\n\n\`\`\`\n`;
    const members = parseApiMembers(md);
    expect(members.size).toBe(0);
  });

  it("parses the real @d2/error-category baseline: 3 members", () => {
    const members = parseApiMembers(BASELINE_API_MD);
    expect(members.size).toBe(3);
    expect(
      members.has(
        "export const ALL_ERROR_CATEGORIES: readonly ErrorCategory[];",
      ),
    ).toBe(true);
    expect(
      members.has(
        `export type ErrorCategory = "conflict" | "infrastructure_unavailable" | "internal_error" | "not_found" | "partial_success" | "payload_too_large" | "policy_denied" | "rate_limited" | "validation_failure";`,
      ),
    ).toBe(true);

    const wireDecl = [...members].find((m) =>
      m.startsWith("export const ErrorCategoryWire:"),
    );

    expect(wireDecl).toBeDefined();
  });
});

// ---------------------------------------------------------------------------
// Unit tests — extractMemberName
// ---------------------------------------------------------------------------

describe("extractMemberName", () => {
  it("extracts name from export const", () => {
    expect(extractMemberName("export const FOO: string;")).toBe("FOO");
  });

  it("extracts name from export type", () => {
    expect(extractMemberName("export type MyType = string;")).toBe("MyType");
  });

  it("extracts name from export function", () => {
    expect(extractMemberName("export function doThing(): void;")).toBe(
      "doThing",
    );
  });

  it("extracts name from export class", () => {
    expect(extractMemberName("export class Foo {")).toBe("Foo");
  });

  it("extracts name from export interface", () => {
    expect(extractMemberName("export interface IBar {")).toBe("IBar");
  });

  it("extracts name from export enum", () => {
    expect(extractMemberName("export enum Status {")).toBe("Status");
  });

  it("falls back to first line for unrecognised pattern", () => {
    expect(extractMemberName("export default something;")).toBe(
      "export default something;",
    );
  });

  it("extracts name from multi-line decl (uses first line only)", () => {
    const decl = `export const Wire: {\n    readonly A: "a";\n};`;
    expect(extractMemberName(decl)).toBe("Wire");
  });
});

// ---------------------------------------------------------------------------
// Unit tests — diffApiMembers
// ---------------------------------------------------------------------------

describe("diffApiMembers", () => {
  it("no change → all false", () => {
    const base = new Set([
      "export const A: string;",
      "export type B = number;",
    ]);
    const fresh = new Set([
      "export const A: string;",
      "export type B = number;",
    ]);

    expect(diffApiMembers(base, fresh)).toEqual({
      added: false,
      removed: false,
      changed: false,
    });
  });

  it("added member → added: true, others false", () => {
    const base = new Set(["export const A: string;"]);
    const fresh = new Set([
      "export const A: string;",
      "export const C: boolean;",
    ]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(true);
    expect(result.removed).toBe(false);
    expect(result.changed).toBe(false);
  });

  it("removed member → removed: true, others false", () => {
    const base = new Set([
      "export const A: string;",
      "export const B: number;",
    ]);
    const fresh = new Set(["export const A: string;"]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(false);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });

  it("changed member signature (same name, different type) → changed: true", () => {
    const base = new Set(["export const A: string;"]);
    const fresh = new Set(["export const A: number;"]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(false);
    expect(result.removed).toBe(false);
    expect(result.changed).toBe(true);
  });

  it("rename (old removed, new added) → added:true + removed:true, changed:false", () => {
    const base = new Set(["export const OldName: string;"]);
    const fresh = new Set(["export const NewName: string;"]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(true);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });

  it("empty baseline + one member fresh → added:true only", () => {
    const result = diffApiMembers(
      new Set(),
      new Set(["export const X: string;"]),
    );

    expect(result.added).toBe(true);
    expect(result.removed).toBe(false);
    expect(result.changed).toBe(false);
  });

  it("one member baseline + empty fresh → removed:true only", () => {
    const result = diffApiMembers(
      new Set(["export const X: string;"]),
      new Set(),
    );

    expect(result.added).toBe(false);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });

  it("both removed and added simultaneously → removed:true + added:true", () => {
    const base = new Set([
      "export const A: string;",
      "export const B: number;",
    ]);
    const fresh = new Set([
      "export const A: string;",
      "export const C: boolean;",
    ]);
    const result = diffApiMembers(base, fresh);

    expect(result.added).toBe(true);
    expect(result.removed).toBe(true);
    expect(result.changed).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Unit tests — normaliseJsForFingerprint
// ---------------------------------------------------------------------------

describe("normaliseJsForFingerprint", () => {
  it("strips single-line comments", () => {
    const js = "// copyright header\nexport const X = 1;\n// footer\n";
    const result = normaliseJsForFingerprint(js);

    expect(result).not.toContain("//");
    expect(result).toContain("export const X = 1;");
  });

  it("strips block comments", () => {
    const js = "/* block\ncomment */\nexport const Y = 2;\n";
    const result = normaliseJsForFingerprint(js);

    expect(result).not.toContain("/*");
    expect(result).toContain("export const Y = 2;");
  });

  it("strips sourcemap URL comments (// #sourceMappingURL=...)", () => {
    const js = "export const Z = 3;\n//# sourceMappingURL=index.js.map\n";
    const result = normaliseJsForFingerprint(js);

    expect(result).not.toContain("sourceMappingURL");
    expect(result).toContain("export const Z = 3;");
  });

  it("collapses multiple blank lines to at most one", () => {
    const js = "export const A = 1;\n\n\n\nexport const B = 2;\n";
    const result = normaliseJsForFingerprint(js);

    expect(result).not.toMatch(/\n{3,}/);
    expect(result).toContain("export const A = 1;");
    expect(result).toContain("export const B = 2;");
  });

  it("is idempotent — running twice yields same result", () => {
    const js = "// comment\nexport const X = 1;\n\n\nexport const Y = 2;\n";
    const once = normaliseJsForFingerprint(js);
    const twice = normaliseJsForFingerprint(once);

    expect(once).toBe(twice);
  });

  it("different real code → different normalised output", () => {
    const jsA = "export const X = 1;\n";
    const jsB = "export const X = 2;\n";

    expect(normaliseJsForFingerprint(jsA)).not.toBe(
      normaliseJsForFingerprint(jsB),
    );
  });
});

// ---------------------------------------------------------------------------
// Unit tests — computeDistFingerprint (synthetic DistReader)
// ---------------------------------------------------------------------------

describe("computeDistFingerprint — synthetic", () => {
  function makeStaticDistReader(
    jsFiles: Record<string, string>,
    dtsFiles: Record<string, string>,
  ): DistReader {
    return {
      listFiles(_distDir: string, extensions: string[]): string[] {
        const files: string[] = [];

        if (extensions.includes(".js"))
          files.push(...Object.keys(jsFiles).sort());

        if (extensions.includes(".d.ts"))
          files.push(...Object.keys(dtsFiles).sort());

        return files;
      },

      readFile(filePath: string): string {
        const content =
          jsFiles[filePath] !== undefined
            ? jsFiles[filePath]
            : dtsFiles[filePath];

        if (content === undefined) throw new Error(`Unknown file: ${filePath}`);

        return content;
      },
    };
  }

  const pkgMeta = {
    name: "@d2/test",
    version: "0.1.0",
    dependencies: { "@d2/utilities": "0.1.0" },
  };
  const pkgDir = "/fake/pkg";

  it("is deterministic across multiple calls with same inputs", () => {
    const dr = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": "export const X = 1;\n" },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );
    const h1 = computeDistFingerprint(pkgDir, pkgMeta, dr);
    const h2 = computeDistFingerprint(pkgDir, pkgMeta, dr);

    expect(h1).toBe(h2);
  });

  it("different .js code content → different hash", () => {
    const dr1 = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": "export const X = 1;\n" },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );
    const dr2 = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": "export const X = 2;\n" },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );

    expect(computeDistFingerprint(pkgDir, pkgMeta, dr1)).not.toBe(
      computeDistFingerprint(pkgDir, pkgMeta, dr2),
    );
  });

  it("PROOF — comment-only .js change → SAME hash (comment normalisation)", () => {
    // This is the stability proof: a comment added to a .js file does NOT
    // change the fingerprint because normalisation strips it first.
    const codeNoComment = "export const X = 1;\n";
    const codeWithComment =
      "// This is a new developer comment\nexport const X = 1;\n";
    const dr1 = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": codeNoComment },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );
    const dr2 = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": codeWithComment },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );

    expect(computeDistFingerprint(pkgDir, pkgMeta, dr1)).toBe(
      computeDistFingerprint(pkgDir, pkgMeta, dr2),
    );
  });

  it("different package.json version → different hash", () => {
    const dr = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": "export const X = 1;\n" },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );
    const h1 = computeDistFingerprint(pkgDir, pkgMeta, dr);
    const h2 = computeDistFingerprint(
      pkgDir,
      { ...pkgMeta, version: "0.2.0" },
      dr,
    );

    expect(h1).not.toBe(h2);
  });

  it("different package.json dependency version → different hash", () => {
    const dr = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": "export const X = 1;\n" },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );
    const h1 = computeDistFingerprint(pkgDir, pkgMeta, dr);
    const h2 = computeDistFingerprint(
      pkgDir,
      { ...pkgMeta, dependencies: { "@d2/utilities": "0.2.0" } },
      dr,
    );

    expect(h1).not.toBe(h2);
  });

  it("different .d.ts content → different hash", () => {
    const dr1 = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": "export const X = 1;\n" },
      { "/fake/pkg/dist/index.d.ts": "export declare const X: number;\n" },
    );
    const dr2 = makeStaticDistReader(
      { "/fake/pkg/dist/index.js": "export const X = 1;\n" },
      {
        "/fake/pkg/dist/index.d.ts":
          "export declare const X: number;\nexport declare const Y: string;\n",
      },
    );

    expect(computeDistFingerprint(pkgDir, pkgMeta, dr1)).not.toBe(
      computeDistFingerprint(pkgDir, pkgMeta, dr2),
    );
  });
});

// ---------------------------------------------------------------------------
// Integration tests — real @d2/error-category
// ---------------------------------------------------------------------------

// These tests invoke the real api-extractor against the committed dist/ of
// @d2/error-category. They inject BaselineReader to simulate various baseline
// states without mutating the committed etc/ files, and DistReader to inject
// synthetic content changes.

describe("extractTsPackageDiff — integration with @d2/error-category", () => {
  it("no-op: current dist matches committed baseline → all diffs false", () => {
    const result = extractTsPackageDiff({
      packageDir: ERROR_CATEGORY_DIR,
      baselineReader: makeFixedBaselineReader(
        BASELINE_API_MD,
        BASELINE_FINGERPRINT,
      ),
    });

    expect(result.apiDiff.added).toBe(false);
    expect(result.apiDiff.removed).toBe(false);
    expect(result.apiDiff.changed).toBe(false);
    expect(result.fingerprintDiff.changed).toBe(false);
    expect(result.freshFingerprint).toBe(BASELINE_FINGERPRINT);
  });

  it("added export: baseline missing ALL_ERROR_CATEGORIES → apiDiff.added = true", () => {
    // Simulate a committed baseline that did not yet include ALL_ERROR_CATEGORIES.
    const baselineWithoutAll = BASELINE_API_MD.replace(
      "// @public\nexport const ALL_ERROR_CATEGORIES: readonly ErrorCategory[];\n\n",
      "",
    );

    const result = extractTsPackageDiff({
      packageDir: ERROR_CATEGORY_DIR,
      baselineReader: makeFixedBaselineReader(
        baselineWithoutAll,
        BASELINE_FINGERPRINT,
      ),
    });

    // Fresh report has ALL_ERROR_CATEGORIES; baseline does not → added.
    expect(result.apiDiff.added).toBe(true);
    expect(result.apiDiff.removed).toBe(false);
    expect(result.apiDiff.changed).toBe(false);
  });

  it("removed export: baseline has LEGACY_FIELD not in fresh → apiDiff.removed = true", () => {
    // Simulate a committed baseline that contained a now-removed export.
    const baselineWithLegacy = BASELINE_API_MD.replace(
      "// (No @packageDocumentation comment for this package)",
      "// @public\nexport const LEGACY_FIELD: string;\n\n// (No @packageDocumentation comment for this package)",
    );

    const result = extractTsPackageDiff({
      packageDir: ERROR_CATEGORY_DIR,
      baselineReader: makeFixedBaselineReader(
        baselineWithLegacy,
        BASELINE_FINGERPRINT,
      ),
    });

    // Fresh report does NOT have LEGACY_FIELD → removed.
    expect(result.apiDiff.removed).toBe(true);
    expect(result.apiDiff.added).toBe(false);
    expect(result.apiDiff.changed).toBe(false);
  });

  it("PROOF — comment-only .js edit → fingerprintDiff.changed = false", () => {
    // Override the index.js content with a comment-only prepend.
    // Because normaliseJsForFingerprint strips it, the hash must stay the same.
    const realIndexJs = readFileSync(
      join(ERROR_CATEGORY_DIR, "dist/index.js"),
      "utf-8",
    );
    const commentOnlyModified =
      "// EXTRA COMMENT THAT MUST NOT CHANGE THE FINGERPRINT\n" + realIndexJs;

    const result = extractTsPackageDiff({
      packageDir: ERROR_CATEGORY_DIR,
      baselineReader: makeFixedBaselineReader(
        BASELINE_API_MD,
        BASELINE_FINGERPRINT,
      ),
      distReader: makeOverrideDistReader({ "index.js": commentOnlyModified }),
    });

    expect(result.fingerprintDiff.changed).toBe(false);
    expect(result.freshFingerprint).toBe(BASELINE_FINGERPRINT);
  });

  it("PROOF — internal logic .js edit → fingerprintDiff.changed = true, hash differs", () => {
    // Override the index.js content with a real code addition.
    // Normalisation does not remove code → the hash must differ.
    const realIndexJs = readFileSync(
      join(ERROR_CATEGORY_DIR, "dist/index.js"),
      "utf-8",
    );
    const logicModified =
      realIndexJs + "\nexport const INTERNAL_CHANGE_SENTINEL = true;\n";

    const result = extractTsPackageDiff({
      packageDir: ERROR_CATEGORY_DIR,
      baselineReader: makeFixedBaselineReader(
        BASELINE_API_MD,
        BASELINE_FINGERPRINT,
      ),
      distReader: makeOverrideDistReader({ "index.js": logicModified }),
    });

    expect(result.fingerprintDiff.changed).toBe(true);
    expect(result.freshFingerprint).not.toBe(BASELINE_FINGERPRINT);
  });
});
