// -----------------------------------------------------------------------
// <copyright file="AudiencesGenerator.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.Auth.Audiences.SourceGen;

using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Roslyn incremental source generator that emits the <c>Audiences</c> static
/// partial class into <c>D2.Shared.Auth.Abstractions</c> by reading
/// <c>contracts/auth-audiences/audiences.spec.json</c> via <c>AdditionalFiles</c>.
/// Single-target — only emits when the consuming assembly is
/// <c>D2.Shared.Auth.Abstractions</c>.
/// </summary>
[Generator]
public sealed class AudiencesGenerator : IIncrementalGenerator
{
    private const string _GENERATED_SOURCE_NAME = "Audiences.g.cs";
    private const string _SPEC_FILE_NAME = "audiences.spec.json";
    private const string _TARGET_ASSEMBLY_NAME = "D2.Shared.Auth.Abstractions";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Filter AdditionalFiles to audiences.spec.json files.
        var specs = context.AdditionalTextsProvider
            .Where(static file => IsSpecFile(file.Path))
            .Select(static (file, ct) => new SpecFile(
                Path: file.Path,
                Content: file.GetText(ct)?.ToString() ?? string.Empty))
            .Collect();

        // 2. Combine with the compilation so we can gate emission by assembly name.
        var combined = specs.Combine(context.CompilationProvider);

        // 3. For each pipeline run, drive the emitter.
        context.RegisterSourceOutput(combined, static (spc, tuple) =>
        {
            var (specFiles, compilation) = tuple;

            // Only emit when the consuming assembly is D2.Shared.Auth.Abstractions.
            if (!string.Equals(
                compilation.AssemblyName,
                _TARGET_ASSEMBLY_NAME,
                StringComparison.Ordinal))
            {
                return;
            }

            if (specFiles.IsDefaultOrEmpty)
            {
                spc.ReportDiagnostic(ToRoslynDiagnostic(EmitDiagnostic.MissingSpecFile()));
                spc.AddSource(
                    _GENERATED_SOURCE_NAME,
                    SourceText.From(EmptyAudiencesSource(), System.Text.Encoding.UTF8));
                return;
            }

            // Convention: only one audiences.spec.json per consuming project.
            var spec = specFiles.OrderBy(s => s.Path, StringComparer.Ordinal).First();

            var loadResult = AudienceSpecLoader.Load(spec.Path, spec.Content);
            if (loadResult.Diagnostic is { } loadDiag)
            {
                spc.ReportDiagnostic(ToRoslynDiagnostic(loadDiag));
                spc.AddSource(
                    _GENERATED_SOURCE_NAME,
                    SourceText.From(EmptyAudiencesSource(), System.Text.Encoding.UTF8));
                return;
            }

            var emitResult = AudiencesEmitter.Emit(loadResult.Spec!);
            foreach (var d in emitResult.Diagnostics)
                spc.ReportDiagnostic(ToRoslynDiagnostic(d));

            spc.AddSource(
                _GENERATED_SOURCE_NAME,
                SourceText.From(emitResult.GeneratedSource, System.Text.Encoding.UTF8));
        });
    }

    private static bool IsSpecFile(string path) =>
        string.Equals(
            Path.GetFileName(path),
            _SPEC_FILE_NAME,
            StringComparison.OrdinalIgnoreCase);

    private static Diagnostic ToRoslynDiagnostic(EmitDiagnostic emitDiag)
    {
        var descriptor = ResolveDescriptor(emitDiag.DescriptorId);
        return Diagnostic.Create(descriptor, Location.None, emitDiag.Args.ToArray());
    }

    private static DiagnosticDescriptor ResolveDescriptor(string id) => id switch
    {
        DiagnosticIds.MalformedSpec => DiagnosticDescriptors.MalformedSpec,
        DiagnosticIds.InvalidAudienceName => DiagnosticDescriptors.InvalidAudienceName,
        DiagnosticIds.DuplicateAudienceName => DiagnosticDescriptors.DuplicateAudienceName,
        DiagnosticIds.DuplicateAudienceUrl => DiagnosticDescriptors.DuplicateAudienceUrl,
        DiagnosticIds.InvalidAudienceUrl => DiagnosticDescriptors.InvalidAudienceUrl,
        DiagnosticIds.MissingSpecFile => DiagnosticDescriptors.MissingSpecFile,
        _ => throw new InvalidOperationException($"Unknown EmitDiagnostic descriptor id '{id}'."),
    };

    private static string EmptyAudiencesSource() =>
        "// <auto-generated>\n#nullable enable\n" +
        "namespace D2.Shared.Auth.Abstractions;\npublic static partial class Audiences { }\n";
}
