// -----------------------------------------------------------------------
// <copyright file="WireShapeEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.WireShapes.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;

/// <summary>
/// Pure logic for emitting a static-class source carrying a wire-shape
/// catalog (e.g. <c>TkMessageWireShape</c> with <c>KEY</c>/<c>PARAMS</c>
/// constants, <c>InputErrorWireShape</c> with <c>FIELD</c>/<c>ERRORS</c>
/// constants) from a parsed <see cref="WireShapeSpec"/>. Stateless and
/// unit-testable in isolation. Parameterized by namespace + class name so
/// the same emitter serves every wire-shape catalog. The Roslyn-host
/// integration (<see cref="WireShapesGenerator"/>) calls this and
/// translates emit-side <see cref="EmitDiagnostic"/> records into Roslyn
/// <c>Diagnostic</c> instances.
/// </summary>
internal static class WireShapeEmitter
{
    private static readonly Regex sr_constNameRegex = new(
        "^[A-Z][A-Z0-9_]*$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    /// <summary>
    /// Emits the static-class source carrying the spec-derived property
    /// name constants.
    /// </summary>
    /// <param name="spec">Parsed wire-shape spec.</param>
    /// <param name="namespaceName">Target namespace for the emitted class.</param>
    /// <param name="className">
    /// Name of the emitted static class (e.g. <c>TkMessageWireShape</c>).
    /// </param>
    /// <param name="catalogDescription">
    /// Human-readable catalog description used in the emitted class XML
    /// summary (e.g. "TKMessage", "InputError").
    /// </param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(
        WireShapeSpec spec,
        string namespaceName,
        string className,
        string catalogDescription)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        var validProperties = new List<WireShapeProperty>();
        var seenConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenValues = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.Properties)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(
                    EmitDiagnostics.DuplicatePropertyConstName(entry.ConstName));
                continue;
            }

            if (!seenValues.Add(entry.Value))
            {
                diagnostics.Add(EmitDiagnostics.DuplicatePropertyValue(entry.Value));
                continue;
            }

            validProperties.Add(entry);
        }

        var source = EmitSource(namespaceName, className, catalogDescription, validProperties);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(
        string namespaceName,
        string className,
        string catalogDescription,
        List<WireShapeProperty> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.WireShapes.SourceGen.WireShapesGenerator");
        sb.AppendLine(
            "//   from a contracts/<wire-shape>/<wire-shape>.spec.json file (the source");
        sb.AppendLine("//   of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine(
            $"/// <summary>Spec-derived JSON property-name catalog for the "
                + $"{EscapeXmlDoc(catalogDescription)} wire shape. Every JSON serializer / "
                + $"deserializer in .NET references these constants for property names instead "
                + $"of inline string literals — drift between the wire and the code is "
                + $"structurally impossible.</summary>");
        sb.AppendLine(
            "/// <remarks>Cross-language parity: the SAME spec drives the TS-side "
                + "<c>@dcsv-io/d2-result</c> catalog via <c>tools/ts-codegen</c>. Both sides emit the "
                + "same property names byte-for-byte; cross-language wire drift is "
                + "impossible.</remarks>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var first = true;
        foreach (var entry in properties)
        {
            if (!first)
                sb.AppendLine();
            first = false;
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
        }

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
