// -----------------------------------------------------------------------
// <copyright file="ErrorCodesGenerator.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.Auth.ErrorCodes.SourceGen;

using System;
using D2.Shared.ErrorCodes.SourceGen;
using Microsoft.CodeAnalysis;

/// <summary>
/// Roslyn incremental source generator that emits the <c>AuthErrorCodes</c>
/// constants class + the <c>AuthFailures</c> factory class into
/// <c>D2.Shared.Auth</c> by reading
/// <c>contracts/auth-error-codes/auth-error-codes.spec.json</c> via
/// <c>AdditionalFiles</c>. A thin shell over the shared
/// <see cref="ErrorCodesEngine"/> — it owns only the auth catalog's identity
/// (assembly name + this type's FQN, both load-bearing for the on-disk
/// generated path) + its <see cref="CatalogConfig"/>; all generation logic
/// lives in the shared engine. Single-target — only emits when the consuming
/// assembly is <c>D2.Shared.Auth</c>.
/// </summary>
[Generator]
public sealed class ErrorCodesGenerator : IIncrementalGenerator
{
    private const string _CONSTANTS_BANNER =
        "// -----------------------------------------------------------------------\n" +
        "// <auto-generated>\n" +
        "//   Generated by D2.Shared.Auth.ErrorCodes.SourceGen.ErrorCodesGenerator\n" +
        "//   from contracts/auth-error-codes/auth-error-codes.spec.json (the source\n" +
        "//   of truth). Manual edits will be lost on rebuild.\n" +
        "// </auto-generated>\n" +
        "// -----------------------------------------------------------------------\n";

    private const string _FAILURES_BANNER = _CONSTANTS_BANNER;

    private const string _CONSTANTS_SUMMARY =
        "/// <summary>\n" +
        "/// Machine-readable <c>d2_error_code</c> string constants surfaced on\n" +
        "/// <see cref=\"D2.Shared.Result.D2Result\"/> failures + RFC 7807\n" +
        "/// <c>ProblemDetails.Extensions[\"d2_error_code\"]</c>.\n" +
        "/// </summary>\n" +
        "/// <remarks>\n" +
        "/// Generated from the spec file - drift between the codes here and the\n" +
        "/// telemetry tag-value enumeration is impossible (the telemetry-tags\n" +
        "/// SrcGen consumes the same spec via <c>valuesFromSpec</c>).\n" +
        "/// </remarks>\n";

    private const string _ALL_CODES_DOC =
        "    /// <summary>\n" +
        "    /// All declared <c>AUTH_*</c> codes in spec order. Useful for\n" +
        "    /// telemetry-tag-value membership checks and cross-spec consistency\n" +
        "    /// tests.\n" +
        "    /// </summary>\n";

    private const string _GET_HTTP_STATUS_DOC =
        "    /// <summary>\n" +
        "    /// Returns the HTTP status code declared in the spec for\n" +
        "    /// <paramref name=\"errorCode\"/>, or <c>500</c> if the code is not\n" +
        "    /// recognized (defensive default - every shipped <c>AUTH_*</c> code\n" +
        "    /// is in the table).\n" +
        "    /// </summary>\n" +
        "    /// <param name=\"errorCode\">The auth error code.</param>\n" +
        "    /// <returns>The HTTP status code.</returns>\n";

    private const string _FAILURES_SUMMARY =
        "/// <summary>\n" +
        "/// Pre-built <see cref=\"D2Result\"/> failures for inbound auth runtime -\n" +
        "/// JWT validation rejections, session liveness outages, JWKS upstream\n" +
        "/// failures.\n" +
        "/// </summary>\n" +
        "/// <remarks>\n" +
        "/// Two-axis design: coarse user-facing TK key (per status bucket) plus\n" +
        "/// granular machine-readable <see cref=\"AuthErrorCodes\"/> constant. Generated\n" +
        "/// from the spec file - drift between the factory list and the\n" +
        "/// <see cref=\"AuthErrorCodes\"/> constants is impossible (single spec source).\n" +
        "/// </remarks>\n";

    private const string _GENERIC_FAILURES_SUMMARY =
        "/// <summary>\n" +
        "/// Typed twin of <see cref=\"AuthFailures\"/> - pre-built\n" +
        "/// <see cref=\"D2Result{T}\"/> auth failures for callers that need a typed\n" +
        "/// result (e.g. <c>AuthFailures&lt;User&gt;.BearerMissing()</c>). Identical\n" +
        "/// method names to the non-generic class; each delegates to the typed\n" +
        "/// <see cref=\"D2Result{T}\"/> base factory, stamping the same\n" +
        "/// <see cref=\"AuthErrorCodes\"/> constant + user-facing TK key.\n" +
        "/// </summary>\n" +
        "/// <remarks>\n" +
        "/// <see cref=\"AuthFailures\"/> (non-generic) and <c>AuthFailures&lt;T&gt;</c>\n" +
        "/// (generic) are distinct types (arity differs) - exactly as\n" +
        "/// <see cref=\"D2Result\"/> / <see cref=\"D2Result{T}\"/> coexist. Generated\n" +
        "/// from the spec file (single source).\n" +
        "/// </remarks>\n";

    private static readonly CatalogConfig sr_config = new(
        TargetAssemblyName: "D2.Shared.Auth",
        SpecFileName: "auth-error-codes.spec.json",
        RootNamespace: "D2.Shared.Auth.Errors",
        ConstantsClassName: "AuthErrorCodes",
        ConstantsSourceName: "AuthErrorCodes.g.cs",
        ConstantsBanner: _CONSTANTS_BANNER,
        ConstantsSummary: _CONSTANTS_SUMMARY,
        AllCodesDoc: _ALL_CODES_DOC,
        GetHttpStatusDoc: _GET_HTTP_STATUS_DOC,
        DomainPrefix: "AUTH_",
        EmitKebabCase: true,
        EmitFailures: true,
        FailuresClassName: "AuthFailures",
        FailuresSourceName: "AuthFailures.g.cs",
        FailuresBanner: _FAILURES_BANNER,
        FailuresSummary: _FAILURES_SUMMARY,
        ValidateCategory: true,
        MalformedSpecId: DiagnosticIds.MalformedSpec,
        DuplicateCodeId: DiagnosticIds.DuplicateCode,
        InvalidHttpStatusId: DiagnosticIds.InvalidHttpStatus,
        InvalidCodeId: null,
        MissingDocId: null,
        UnknownCategoryId: DiagnosticIds.UnknownCategoryEnum,
        DuplicateFactoryNameId: DiagnosticIds.DuplicateFactoryName,
        FactoryHost: FactoryHost.Domain,
        GenericFailuresSourceName: "AuthFailures.Generic.g.cs",
        GenericFailuresSummary: _GENERIC_FAILURES_SUMMARY);

    /// <summary>
    /// Gets the auth catalog configuration. Exposed for unit tests that drive
    /// the shared engine emitters directly with the real catalog config.
    /// </summary>
    internal static CatalogConfig Config => sr_config;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        ErrorCodesEngine.Run(context, sr_config, ResolveDescriptor);

    private static DiagnosticDescriptor ResolveDescriptor(string id) => id switch
    {
        DiagnosticIds.MalformedSpec => DiagnosticDescriptors.MalformedSpec,
        DiagnosticIds.UnknownCategoryEnum => DiagnosticDescriptors.UnknownCategoryEnum,
        DiagnosticIds.DuplicateCode => DiagnosticDescriptors.DuplicateCode,
        DiagnosticIds.DuplicateFactoryName => DiagnosticDescriptors.DuplicateFactoryName,
        DiagnosticIds.InvalidHttpStatus => DiagnosticDescriptors.InvalidHttpStatus,
        _ => throw new InvalidOperationException(
            $"Unknown EmitDiagnostic descriptor id '{id}'."),
    };
}
