// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Audit.App.Application.Handlers.Queries.PingAudit;

using DcsvIo.D2.Private.Audit.Client.Ping;

/// <summary>Generated handler interface for the <c>PingAudit</c> operation.</summary>
public interface IPingAuditHandler : IHandler<PingAuditInput, PingAuditOutput>;
