// -----------------------------------------------------------------------
// <copyright file="OtelMessagingTagsEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.OtelMessagingTags.SourceGen;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using DcsvIo.D2.SourceGen;
using DcsvIo.D2.SourceGen.Polyfills;

/// <summary>
/// Pure logic for emitting the <c>MessagingActivityTags</c> static class
/// source from a parsed <see cref="OtelMessagingTagsSpec"/>.
/// </summary>
internal static class OtelMessagingTagsEmitter
{
    /// <summary>The namespace the <c>MessagingActivityTags</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.Messaging.RabbitMq";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "MessagingActivityTags";

    private static readonly Regex sr_constNameRegex = new(
        "^[A-Z][A-Z0-9_]*$",
        RegexOptions.Compiled,
        TimeSpan.FromMilliseconds(50));

    /// <summary>
    /// Emits the <c>MessagingActivityTags</c> class source plus diagnostics
    /// for the supplied spec.
    /// </summary>
    /// <param name="spec">Parsed otel-messaging-tags spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(OtelMessagingTagsSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        var validEntries = new List<OtelMessagingTagEntry>();
        var seenConstNames = new HashSet<string>(StringComparer.Ordinal);
        var seenValues = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in spec.Tags)
        {
            if (!sr_constNameRegex.IsMatch(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.InvalidConstName(entry.ConstName));
                continue;
            }

            if (entry.Value.Falsey())
            {
                diagnostics.Add(EmitDiagnostics.EmptyValue(entry.ConstName));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateConstName(entry.ConstName));
                continue;
            }

            if (!seenValues.Add(entry.Value))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateValue(entry.Value));
                continue;
            }

            validEntries.Add(entry);
        }

        var source = EmitSource(validEntries);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static string EmitSource(List<OtelMessagingTagEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.OtelMessagingTags.SourceGen.OtelMessagingTagsGenerator");
        sb.AppendLine(
            "//   from contracts/otel-messaging-tags/otel-messaging-tags.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived OTel activity-tag attribute-name constants. Every");
        sb.AppendLine(
            "/// messaging publisher / consumer Activity.SetTag call references these");
        sb.AppendLine(
            "/// constants instead of inline string literals — keeps publisher + consumer");
        sb.AppendLine(
            "/// in lockstep with the OTel semantic-convention catalog AND with each");
        sb.AppendLine("/// other.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");

        var first = true;
        foreach (var entry in entries)
        {
            if (!first)
                sb.AppendLine();
            first = false;
            sb.AppendLine($"    /// <summary>{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    public const string {entry.ConstName} = "
                    + $"\"{EscapeStringLiteral(entry.Value)}\";");
        }

        if (entries.Count > 0)
            sb.AppendLine();

        EmitAllTags(sb, entries);

        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static void EmitAllTags(StringBuilder sb, List<OtelMessagingTagEntry> entries)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// All declared activity-tag wire-names in spec order. Useful for");
        sb.AppendLine(
            "    /// cross-spec consistency tests and operator-side tag enumeration.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static IReadOnlyList<string> AllTags => sr_allTags;");
        sb.AppendLine();
        sb.AppendLine(
            "    private static readonly IReadOnlyList<string> sr_allTags = new string[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
            sb.AppendLine($"        \"{EscapeStringLiteral(entry.Value)}\",");

        sb.AppendLine("    };");
    }

    private static string EscapeStringLiteral(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
