// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Audit.Api.Grpc;

using PingAuditRequest = global::D2.Services.Protos.Audit.V2Alpha.PingAuditRequest;
using PingAuditResponse = global::D2.Services.Protos.Audit.V2Alpha.PingAuditResponse;
using PingAuditInput = global::DcsvIo.D2.Private.Audit.Client.Ping.PingAuditInput;
using PingAuditOutput = global::DcsvIo.D2.Private.Audit.Client.Ping.PingAuditOutput;
using global::DcsvIo.D2.Result.Grpc;
using global::Grpc.Core;
using DcsvIo.D2.Private.Audit.App.Application.Handlers.Queries.PingAudit;

/// <summary>Generated gRPC service for the <c>PingAudit</c> operation, delegating to <see cref="IPingAuditHandler"/>.</summary>
public sealed class AuditPingService(IPingAuditHandler handler)
    : global::D2.Services.Protos.Audit.V2Alpha.AuditPing.AuditPingBase
{
    /// <inheritdoc/>
    public override async Task<PingAuditResponse> PingAudit(PingAuditRequest request, ServerCallContext context)
    {
        PingAuditInput input = request.ToPingAuditInput();
        var result = await handler.HandleAsync(input, context.CancellationToken).ConfigureAwait(false);
        return result.ToProtoResponse();
    }
}
