// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Edge.Api.Grpc.KeyCustodian;

using GetCaCertificateRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetCaCertificateRequest;
using GetCaCertificateResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetCaCertificateResponse;
using ProtoGetCaCertificateOutput = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetCaCertificateOutput;
using GetCaCertificateInput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.CaCertificate.GetCaCertificateInput;
using GetCaCertificateOutput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.CaCertificate.GetCaCertificateOutput;
using DcsvIo.D2.Result;
using DcsvIo.D2.Result.Grpc;
using Google.Protobuf;

/// <summary>Generated transport mappers: proto ↔ DTO for the <c>GetCaCertificate</c> operation.</summary>
internal static class GetCaCertificateTransportMappers
{
    extension(GetCaCertificateRequest request)
    {
        internal GetCaCertificateInput ToGetCaCertificateInput()
        {
            return new GetCaCertificateInput();
        }
    }

    extension(D2Result<GetCaCertificateOutput?> result)
    {
        internal GetCaCertificateResponse ToProtoResponse()
        {
            var response = new GetCaCertificateResponse { Result = result.ToProto() };

            if (result.IsOk && result.Data is not null)
                response.Data = result.Data.ToProtoGetCaCertificateOutput();

            return response;
        }
    }

    extension(GetCaCertificateOutput output)
    {
        internal ProtoGetCaCertificateOutput ToProtoGetCaCertificateOutput()
        {
            return new ProtoGetCaCertificateOutput
            {
                RootCertificateDer = ByteString.CopyFrom(output.RootCertificateDer),
                IntermediateCertificateDer = ByteString.CopyFrom(output.IntermediateCertificateDer),
            };
        }
    }
}
