// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Edge.Api.Grpc.KeyCustodian;

using GetOrLazyProvisionOwnSealPrivateKeyRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetOrLazyProvisionOwnSealPrivateKeyRequest;
using GetOrLazyProvisionOwnSealPrivateKeyResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetOrLazyProvisionOwnSealPrivateKeyResponse;
using ProtoGetOrLazyProvisionOwnSealPrivateKeyOutput = global::D2.Services.Protos.KeyCustodian.V2Alpha.GetOrLazyProvisionOwnSealPrivateKeyOutput;
using GetOrLazyProvisionOwnSealPrivateKeyInput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing.GetOrLazyProvisionOwnSealPrivateKeyInput;
using GetOrLazyProvisionOwnSealPrivateKeyOutput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing.GetOrLazyProvisionOwnSealPrivateKeyOutput;
using ProtoSealPrivateEntry = global::D2.Services.Protos.KeyCustodian.V2Alpha.SealPrivateEntry;
using SealPrivateEntry = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing.SealPrivateEntry;
using DcsvIo.D2.Result;
using DcsvIo.D2.Result.Grpc;
using Google.Protobuf;
using System.Linq;

/// <summary>Generated transport mappers: proto ↔ DTO for the <c>GetOrLazyProvisionOwnSealPrivateKey</c> operation.</summary>
internal static class GetOrLazyProvisionOwnSealPrivateKeyTransportMappers
{
    extension(GetOrLazyProvisionOwnSealPrivateKeyRequest request)
    {
        internal GetOrLazyProvisionOwnSealPrivateKeyInput ToGetOrLazyProvisionOwnSealPrivateKeyInput()
        {
            return new GetOrLazyProvisionOwnSealPrivateKeyInput();
        }
    }

    extension(D2Result<GetOrLazyProvisionOwnSealPrivateKeyOutput?> result)
    {
        internal GetOrLazyProvisionOwnSealPrivateKeyResponse ToProtoResponse()
        {
            var response = new GetOrLazyProvisionOwnSealPrivateKeyResponse { Result = result.ToProto() };

            if (result.IsOk && result.Data is not null)
                response.Data = result.Data.ToProtoGetOrLazyProvisionOwnSealPrivateKeyOutput();

            return response;
        }
    }

    extension(GetOrLazyProvisionOwnSealPrivateKeyOutput output)
    {
        internal ProtoGetOrLazyProvisionOwnSealPrivateKeyOutput ToProtoGetOrLazyProvisionOwnSealPrivateKeyOutput()
        {
            return new ProtoGetOrLazyProvisionOwnSealPrivateKeyOutput
            {
                ActiveKid = output.ActiveKid,
                Entries = { output.Entries.Select(x => x.ToProtoSealPrivateEntry()) },
            };
        }
    }

    extension(SealPrivateEntry source)
    {
        /// <summary>Maps the <c>SealPrivateEntry</c> DTO to its proto message.</summary>
        internal ProtoSealPrivateEntry ToProtoSealPrivateEntry()
        {
            return new ProtoSealPrivateEntry
            {
                Kid = source.Kid,
                PrivatePkcs8 = global::Google.Protobuf.ByteString.CopyFrom(source.PrivatePkcs8),
            };
        }
    }

    extension(ProtoSealPrivateEntry source)
    {
        /// <summary>Maps the <c>SealPrivateEntry</c> proto message to its DTO.</summary>
        internal SealPrivateEntry ToSealPrivateEntry()
        {
            return new SealPrivateEntry(source.Kid, source.PrivatePkcs8.ToByteArray());
        }
    }
}
