// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: private/contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Edge.Api.Grpc.KeyCustodian;

using SignRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.SignRequest;
using SignResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.SignResponse;
using ProtoSignOutput = global::D2.Services.Protos.KeyCustodian.V2Alpha.SignOutput;
using SignInput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Signing.SignInput;
using SignOutput = global::DcsvIo.D2.Private.Edge.KeyCustodian.Client.Signing.SignOutput;
using DcsvIo.D2.Result;
using DcsvIo.D2.Result.Grpc;
using Google.Protobuf;

/// <summary>Generated transport mappers: proto ↔ DTO for the <c>Sign</c> operation.</summary>
internal static class SignTransportMappers
{
    extension(SignRequest request)
    {
        internal SignInput ToSignInput()
        {
            return new SignInput(request.KeyDomain, request.SigningInput.ToByteArray());
        }
    }

    extension(D2Result<SignOutput?> result)
    {
        internal SignResponse ToProtoResponse()
        {
            var response = new SignResponse { Result = result.ToProto() };

            if (result.IsOk && result.Data is not null)
                response.Data = result.Data.ToProtoSignOutput();

            return response;
        }
    }

    extension(SignOutput output)
    {
        internal ProtoSignOutput ToProtoSignOutput()
        {
            return new ProtoSignOutput
            {
                Signature = output.Signature,
                Kid = output.Kid,
            };
        }
    }
}
