// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Byte-parity gate: regenerating emitter output must produce byte-identical
// content to the committed .g.cs / .g.ts fixtures.
//
// The gate is non-vacuous per §26.5.1 + §1.20: a deliberate-drift case
// (mutate one byte of the fixture) is tested to verify the gate FAILS when
// there is actual divergence. This prevents the byte-gate becoming a tautology
// (comparing a buffer to itself, never catching real drift).

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Model, ModelProperty, Program, Scalar } from "@typespec/compiler";
import { D2_REDACT_KEY } from "@d2/typespec-decorators";
import { walkModel } from "../src/lib/model-walk.js";
import { emitCsharpDtos } from "../src/lib/csharp-dto-emitter.js";
import { emitTsDtos } from "../src/lib/ts-dto-emitter.js";
import { emitProto } from "../src/lib/proto-emitter.js";
import { emitGrpcService } from "../src/lib/grpc-service-emitter.js";
import { emitGrpcClient } from "../src/lib/grpc-client-emitter.js";
import type { FieldInfo, NestedEnum } from "../src/lib/model-walk.js";

// ---------------------------------------------------------------------------
// Fixture definitions — the canonical committed content
// (mirrors the committed .g.cs files: GetJwks DTOs in
// server/services/edge/key-custodian/clients/; sign fixture DTOs in
// D2.Edge.Tests/TypeSpecDto/Generated/)
// ---------------------------------------------------------------------------

/** The committed clients/GetJwksInput.g.cs content (namespace D2.Edge.KeyCustodian.Clients). */
const GET_JWKS_INPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.KeyCustodian.Clients;",
  "",
  "/// <summary>Generated input DTO. No parameters required.</summary>",
  "public sealed record GetJwksInput;",
  "",
].join("\n");

/** The committed clients/GetJwksOutput.g.cs content (namespace D2.Edge.KeyCustodian.Clients). */
const GET_JWKS_OUTPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.KeyCustodian.Clients;",
  "",
  "/// <summary>Generated DTO for the <c>GetJwksOutput</c> operation.</summary>",
  "public sealed record GetJwksOutput(",
  "    IReadOnlyList<Jwk> Keys);",
  "",
  "/// <summary>Generated nested model DTO for <c>Jwk</c>.</summary>",
  "public sealed record Jwk(",
  "    string Kid,",
  "    string N,",
  "    string E,",
  "    string Kty,",
  "    string Use,",
  "    string Alg);",
  "",
].join("\n");

/** The committed TemporalInput.g.cs content (every temporal scalar + 2 composite refs). */
const TEMPORAL_INPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/temporal-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecDto.Generated;",
  "",
  "/// <summary>Generated DTO for the <c>TemporalInput</c> operation.</summary>",
  "public sealed record TemporalInput(",
  "    DateTimeOffset PastInstant,",
  "    DateTimeOffset Deadline,",
  "    DateTimeOffset WithOffset,",
  "    string Birthday,",
  "    string AlarmTime,",
  "    string WallClock,",
  "    string Elapsed,",
  "    DateTimeOffset? OptionalInstant,",
  "    ZonedInstantWire Zoned,",
  "    LocalAnchoredEventWire Schedule);",
  "",
].join("\n");

/** The committed TemporalOutput.g.cs content (mirrors input + the 2 nested composite records). */
const TEMPORAL_OUTPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/temporal-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecDto.Generated;",
  "",
  "/// <summary>Generated DTO for the <c>TemporalOutput</c> operation.</summary>",
  "public sealed record TemporalOutput(",
  "    DateTimeOffset PastInstant,",
  "    DateTimeOffset Deadline,",
  "    DateTimeOffset WithOffset,",
  "    string Birthday,",
  "    string AlarmTime,",
  "    string WallClock,",
  "    string Elapsed,",
  "    DateTimeOffset? OptionalInstant,",
  "    ZonedInstantWire Zoned,",
  "    LocalAnchoredEventWire Schedule);",
  "",
  "/// <summary>Generated nested model DTO for <c>ZonedInstantWire</c>.</summary>",
  "public sealed record ZonedInstantWire(",
  "    DateTimeOffset Instant,",
  "    string ZoneId);",
  "",
  "/// <summary>Generated nested model DTO for <c>LocalAnchoredEventWire</c>.</summary>",
  "public sealed record LocalAnchoredEventWire(",
  "    string ScheduledLocal,",
  "    string IanaZone,",
  "    DateTimeOffset? NextFireUtc);",
  "",
].join("\n");

/** The committed SignInput.g.cs content. */
const SIGN_INPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecDto.Generated;",
  "",
  "using D2.Shared.Utilities.Attributes;",
  "using D2.Shared.Utilities.Enums;",
  "",
  "/// <summary>Generated DTO for the <c>SignInput</c> operation.</summary>",
  "public sealed record SignInput(",
  "    string Kid,",
  "    [property: RedactData(Reason = RedactReason.PersonalInformation)] byte[] Payload);",
  "",
].join("\n");

// ---------------------------------------------------------------------------
// Helpers — build TypeSpec stubs matching the committed shapes
// ---------------------------------------------------------------------------

function makeScalar(name: string): Scalar {
  return { kind: "Scalar", name } as unknown as Scalar;
}

function makeProp(type: Scalar, optional = false): ModelProperty {
  return { type, optional } as unknown as ModelProperty;
}

function makeRedactProp(type: Scalar): {
  prop: ModelProperty;
  redactMap: Map<object, unknown>;
} {
  const prop = { type, optional: false } as unknown as ModelProperty;
  return { prop, redactMap: new Map([[prop, true]]) };
}

function makeProgram(redactMap: Map<object, unknown> = new Map()): Program {
  return {
    stateMap(key: symbol): Map<object, unknown> {
      if (key === D2_REDACT_KEY) return redactMap;
      return new Map();
    },
  } as unknown as Program;
}

// ---------------------------------------------------------------------------
// GetJwksInput fixture — empty model
// ---------------------------------------------------------------------------

function buildGetJwksInputWalk() {
  const model: Model = {
    kind: "Model",
    name: "GetJwksInput",
    properties: new Map(),
  } as unknown as Model;
  return walkModel(makeProgram(), model, () => {});
}

// ---------------------------------------------------------------------------
// GetJwksOutput fixture — Jwk[] collection
// ---------------------------------------------------------------------------

function buildGetJwksOutputWalk() {
  const jwkModel: Model = {
    kind: "Model",
    name: "Jwk",
    properties: new Map<string, ModelProperty>([
      ["kid", makeProp(makeScalar("string"))],
      ["n", makeProp(makeScalar("string"))],
      ["e", makeProp(makeScalar("string"))],
      ["kty", makeProp(makeScalar("string"))],
      ["use", makeProp(makeScalar("string"))],
      ["alg", makeProp(makeScalar("string"))],
    ]),
  } as unknown as Model;

  const arrayModel: Model = {
    kind: "Model",
    name: "Array",
    indexer: { value: jwkModel },
    properties: new Map(),
  } as unknown as Model;

  const model: Model = {
    kind: "Model",
    name: "GetJwksOutput",
    properties: new Map<string, ModelProperty>([
      [
        "keys",
        { type: arrayModel, optional: false } as unknown as ModelProperty,
      ],
    ]),
  } as unknown as Model;

  return walkModel(makeProgram(), model, () => {});
}

// ---------------------------------------------------------------------------
// SignInput fixture — redacted bytes field
// ---------------------------------------------------------------------------

function buildSignInputWalk() {
  const { prop: payloadProp, redactMap } = makeRedactProp(makeScalar("bytes"));
  const kidProp = makeProp(makeScalar("string"));
  const model: Model = {
    kind: "Model",
    name: "SignInput",
    properties: new Map<string, ModelProperty>([
      ["kid", kidProp],
      ["payload", payloadProp],
    ]),
  } as unknown as Model;

  return {
    walk: walkModel(makeProgram(redactMap), model, () => {}),
    redactMap,
  };
}

// ---------------------------------------------------------------------------
// Temporal fixture — every temporal scalar + 2 composite nested models
// ---------------------------------------------------------------------------

function buildTemporalWalks() {
  const zonedInstantWire: Model = {
    kind: "Model",
    name: "ZonedInstantWire",
    properties: new Map<string, ModelProperty>([
      ["instant", makeProp(makeScalar("utcDateTime"))],
      ["zoneId", makeProp(makeScalar("string"))],
    ]),
  } as unknown as Model;

  const localAnchoredEventWire: Model = {
    kind: "Model",
    name: "LocalAnchoredEventWire",
    properties: new Map<string, ModelProperty>([
      ["scheduledLocal", makeProp(makeScalar("plainDateTime"))],
      ["ianaZone", makeProp(makeScalar("string"))],
      ["nextFireUtc", makeProp(makeScalar("utcDateTime"), true)],
    ]),
  } as unknown as Model;

  const fieldEntries: Array<[string, ModelProperty]> = [
    ["pastInstant", makeProp(makeScalar("utcDateTime"))],
    ["deadline", makeProp(makeScalar("utcDateTime"))],
    ["withOffset", makeProp(makeScalar("offsetDateTime"))],
    ["birthday", makeProp(makeScalar("plainDate"))],
    ["alarmTime", makeProp(makeScalar("plainTime"))],
    ["wallClock", makeProp(makeScalar("plainDateTime"))],
    ["elapsed", makeProp(makeScalar("duration"))],
    ["optionalInstant", makeProp(makeScalar("utcDateTime"), true)],
    [
      "zoned",
      { type: zonedInstantWire, optional: false } as unknown as ModelProperty,
    ],
    [
      "schedule",
      {
        type: localAnchoredEventWire,
        optional: false,
      } as unknown as ModelProperty,
    ],
  ];

  const inputModel: Model = {
    kind: "Model",
    name: "TemporalInput",
    properties: new Map(fieldEntries),
  } as unknown as Model;

  const outputModel: Model = {
    kind: "Model",
    name: "TemporalOutput",
    properties: new Map(fieldEntries),
  } as unknown as Model;

  return {
    input: walkModel(makeProgram(), inputModel, () => {}),
    output: walkModel(makeProgram(), outputModel, () => {}),
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("byteParity_GetJwksInput_CommittedFixtureIdentical", () => {
  it("regenerated GetJwksInput.g.cs is byte-identical to the committed fixture", () => {
    const { fields, nestedModels } = buildGetJwksInputWalk();
    const [inputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      fields,
      [],
      nestedModels,
    );

    expect(inputFile!.content).toBe(GET_JWKS_INPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match regenerated output", () => {
    // Non-vacuous guard: deliberately corrupt the fixture by one byte.
    const driftedFixture = GET_JWKS_INPUT_FIXTURE.replace(
      "GetJwksInput",
      "GetJwksInputDRIFTED",
    );

    const { fields, nestedModels } = buildGetJwksInputWalk();
    const [inputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      fields,
      [],
      nestedModels,
    );

    // The drifted fixture must NOT match — proving the gate would catch real drift.
    expect(inputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_GetJwksOutput_CommittedFixtureIdentical", () => {
  it("regenerated GetJwksOutput.g.cs is byte-identical to the committed fixture", () => {
    const { fields, nestedModels } = buildGetJwksOutputWalk();
    const [, outputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      [],
      fields,
      nestedModels,
    );

    expect(outputFile!.content).toBe(GET_JWKS_OUTPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match regenerated output", () => {
    // Non-vacuous guard: deliberately corrupt the fixture by one byte.
    const driftedFixture = GET_JWKS_OUTPUT_FIXTURE.replace(
      "GetJwksOutput",
      "GetJwksOutputDRIFTED",
    );

    const { fields, nestedModels } = buildGetJwksOutputWalk();
    const [, outputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      [],
      fields,
      nestedModels,
    );

    // The drifted fixture must NOT match — proving the gate would catch real drift.
    expect(outputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_SignInput_CommittedFixtureIdentical", () => {
  it("regenerated SignInput.g.cs is byte-identical to the committed fixture", () => {
    const { walk } = buildSignInputWalk();
    const [inputFile] = emitCsharpDtos(
      "sign",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/sign-shaped.tsp",
      walk.fields,
      [],
      [],
    );

    expect(inputFile!.content).toBe(SIGN_INPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match regenerated output", () => {
    // §1.20 non-vacuous guard: deliberately corrupt the fixture by one byte.
    const driftedFixture = SIGN_INPUT_FIXTURE.replace(
      "SignInput",
      "SignInputDRIFTED",
    );

    const { walk } = buildSignInputWalk();
    const [inputFile] = emitCsharpDtos(
      "sign",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/sign-shaped.tsp",
      walk.fields,
      [],
      [],
    );

    // The drifted fixture must NOT match — proving the gate would catch real drift.
    expect(inputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_TemporalInput_CommittedFixtureIdentical", () => {
  it("regenerated TemporalInput.g.cs is byte-identical to the committed fixture", () => {
    const { input, output } = buildTemporalWalks();
    const [inputFile] = emitCsharpDtos(
      "temporal",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/temporal-shaped.tsp",
      input.fields,
      output.fields,
      output.nestedModels,
    );

    expect(inputFile!.content).toBe(TEMPORAL_INPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated TemporalInput fixture does NOT match regenerated output", () => {
    // §1.20 / NV-1 non-vacuous guard: corrupt the fixture by one byte.
    const driftedFixture = TEMPORAL_INPUT_FIXTURE.replace(
      "DateTimeOffset PastInstant",
      "DateTimeOffset PastInstantDRIFTED",
    );

    const { input, output } = buildTemporalWalks();
    const [inputFile] = emitCsharpDtos(
      "temporal",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/temporal-shaped.tsp",
      input.fields,
      output.fields,
      output.nestedModels,
    );

    expect(inputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_TemporalOutput_CommittedFixtureIdentical", () => {
  it("regenerated TemporalOutput.g.cs (with the 2 nested composite records) is byte-identical", () => {
    const { input, output } = buildTemporalWalks();
    const [, outputFile] = emitCsharpDtos(
      "temporal",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/temporal-shaped.tsp",
      input.fields,
      output.fields,
      output.nestedModels,
    );

    expect(outputFile!.content).toBe(TEMPORAL_OUTPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated TemporalOutput fixture does NOT match regenerated output", () => {
    // §1.20 / NV-1 non-vacuous guard: corrupt a composite record by one byte.
    const driftedFixture = TEMPORAL_OUTPUT_FIXTURE.replace(
      "public sealed record ZonedInstantWire(",
      "public sealed record ZonedInstantWireDRIFTED(",
    );

    const { input, output } = buildTemporalWalks();
    const [, outputFile] = emitCsharpDtos(
      "temporal",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/temporal-shaped.tsp",
      input.fields,
      output.fields,
      output.nestedModels,
    );

    expect(outputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_TemporalDto_TsFile", () => {
  it("regenerated temporal-dto.g.ts carries every temporal field + both composite interfaces", () => {
    const { input, output } = buildTemporalWalks();
    const tsFile = emitTsDtos(
      "temporal",
      "contracts/typespec/fixtures/temporal-shaped.tsp",
      input.fields,
      output.fields,
      output.nestedModels,
    );

    expect(tsFile.fileName).toBe("temporal-dto.g.ts");
    expect(tsFile.content).toContain("export interface ZonedInstantWire {");
    expect(tsFile.content).toContain("readonly instant: string;");
    expect(tsFile.content).toContain(
      "export interface LocalAnchoredEventWire {",
    );
    expect(tsFile.content).toContain("readonly nextFireUtc?: string;");
    expect(tsFile.content).toContain("export interface TemporalInput {");
    expect(tsFile.content).toContain("readonly optionalInstant?: string;");
    expect(tsFile.content).toContain("readonly zoned: ZonedInstantWire;");
    expect(tsFile.content).toContain(
      "readonly schedule: LocalAnchoredEventWire;",
    );
    // No null union — prefer-undefined.
    expect(tsFile.content).not.toContain("| null");
  });
});

describe("byteParity_GetJwksDto_TsFile", () => {
  it("regenerated get-jwks-dto.g.ts matches expected shape", () => {
    const inputWalk = buildGetJwksInputWalk();
    const outputWalk = buildGetJwksOutputWalk();
    const tsFile = emitTsDtos(
      "getJwks",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      inputWalk.fields,
      outputWalk.fields,
      outputWalk.nestedModels,
    );

    expect(tsFile.fileName).toBe("get-jwks-dto.g.ts");
    // Structural checks (byte-exact would require committing the .g.ts too;
    // structural assertion pins the shape without the fragility of full-string compare).
    expect(tsFile.content).toContain("export interface Jwk {");
    expect(tsFile.content).toContain("readonly kid: string;");
    expect(tsFile.content).toContain("export interface GetJwksInput {");
    expect(tsFile.content).toContain("export interface GetJwksOutput {");
    expect(tsFile.content).toContain("readonly keys: readonly Jwk[];");
  });
});

// ---------------------------------------------------------------------------
// Enum-shaped byte-gates (the enum-shaped.tsp committed fixtures)
// ---------------------------------------------------------------------------

const REPO = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "..",
);
const DTO_HOME = join(
  REPO,
  "server/services/edge/tests/Unit/KeyCustodian/TypeSpecDto/Generated",
);
const GRPC_ENUM_HOME = join(
  REPO,
  "server/services/edge/tests/Unit/KeyCustodian/TypeSpecGrpcEnum/Generated",
);
const GRPC_ENUM_PROTOS = join(
  REPO,
  "server/services/edge/tests/Unit/KeyCustodian/TypeSpecGrpcEnum/Protos",
);

function readFixture(absPath: string): string {
  // Committed generated files are LF; the emitter joins with "\n". Normalize the
  // on-disk read defensively (git working-tree may have CRLF) before comparing.
  return readFileSync(absPath, "utf8").replace(/\r\n/g, "\n");
}

const ENUM_SHAPED_SRC = "contracts/typespec/fixtures/enum-shaped.tsp";
const ENUM_DTO_NS = "D2.Edge.Tests.TypeSpecDto.Generated";

// The enum-shaped `enums` op model (Input mirrors Output) — synthetic stubs that
// produce the SAME walk result the real .tsp compile produces.
function makeEnumStub(
  name: string,
  members: Array<{ name: string; value?: string | number }>,
): Scalar {
  return {
    kind: "Enum",
    name,
    members: new Map(
      members.map((m) => [m.name, { name: m.name, value: m.value }]),
    ),
  } as unknown as Scalar;
}

function makeUnionStub(name: string | undefined, literals: string[]): Scalar {
  return {
    kind: "Union",
    name,
    variants: new Map(
      literals.map((lit, i) => [
        Symbol(`v${i}`),
        { type: { kind: "String", value: lit } },
      ]),
    ),
  } as unknown as Scalar;
}

function buildEnumsWalks() {
  const keyKind = makeEnumStub("KeyKind", [
    { name: "Rsa" },
    { name: "Aes" },
    { name: "Secret" },
  ]);
  const level = makeEnumStub("Level", [
    { name: "Low", value: 0 },
    { name: "Medium", value: 5 },
    { name: "High", value: 10 },
  ]);
  const status = makeUnionStub("Status", ["active", "inactive", "pending"]);
  const accountKind = makeUnionStub("AccountKind", ["internal", "third-party"]);
  const inline = makeUnionStub(undefined, ["draft", "published", "archived"]);
  const keyKindArray: Model = {
    kind: "Model",
    name: "Array",
    indexer: { value: keyKind },
    properties: new Map(),
  } as unknown as Model;

  const fields = (modelName: string): Model =>
    ({
      kind: "Model",
      name: modelName,
      properties: new Map<string, ModelProperty>([
        [
          "keyKind",
          { type: keyKind, optional: false } as unknown as ModelProperty,
        ],
        ["level", { type: level, optional: false } as unknown as ModelProperty],
        [
          "status",
          { type: status, optional: false } as unknown as ModelProperty,
        ],
        [
          "accountKind",
          { type: accountKind, optional: false } as unknown as ModelProperty,
        ],
        [
          "inlineState",
          { type: inline, optional: false } as unknown as ModelProperty,
        ],
        [
          "optionalKind",
          { type: keyKind, optional: true } as unknown as ModelProperty,
        ],
        [
          "kinds",
          { type: keyKindArray, optional: false } as unknown as ModelProperty,
        ],
      ]),
    }) as unknown as Model;

  return {
    input: walkModel(makeProgram(), fields("EnumInput"), () => {}),
    output: walkModel(makeProgram(), fields("EnumOutput"), () => {}),
  };
}

describe("byteParity_EnumsDto_CommittedFixtures", () => {
  it("regenerated EnumsOutput.g.cs is byte-identical to the committed fixture", () => {
    const { input, output } = buildEnumsWalks();
    const [, outputFile] = emitCsharpDtos(
      "enums",
      ENUM_DTO_NS,
      ENUM_SHAPED_SRC,
      input.fields,
      output.fields,
      output.nestedModels,
      input.nestedEnums,
      output.nestedEnums,
    );

    expect(outputFile!.content).toBe(
      readFixture(join(DTO_HOME, "EnumsOutput.g.cs")),
    );
  });

  it("regenerated EnumsInput.g.cs is byte-identical to the committed fixture", () => {
    const { input, output } = buildEnumsWalks();
    const [inputFile] = emitCsharpDtos(
      "enums",
      ENUM_DTO_NS,
      ENUM_SHAPED_SRC,
      input.fields,
      output.fields,
      output.nestedModels,
      input.nestedEnums,
      output.nestedEnums,
    );

    expect(inputFile!.content).toBe(
      readFixture(join(DTO_HOME, "EnumsInput.g.cs")),
    );
  });

  it("regenerated enums-dto.g.ts is byte-identical to the committed fixture", () => {
    const { input, output } = buildEnumsWalks();
    const tsFile = emitTsDtos(
      "enums",
      ENUM_SHAPED_SRC,
      input.fields,
      output.fields,
      output.nestedModels,
      input.nestedEnums,
      output.nestedEnums,
    );

    expect(tsFile.content).toBe(readFixture(join(DTO_HOME, "enums-dto.g.ts")));
  });

  it("deliberate-drift detection: mutated EnumsOutput fixture does NOT match", () => {
    const drifted = readFixture(join(DTO_HOME, "EnumsOutput.g.cs")).replace(
      "public enum KeyKind",
      "public enum KeyKindDRIFTED",
    );
    const { input, output } = buildEnumsWalks();
    const [, outputFile] = emitCsharpDtos(
      "enums",
      ENUM_DTO_NS,
      ENUM_SHAPED_SRC,
      input.fields,
      output.fields,
      output.nestedModels,
      input.nestedEnums,
      output.nestedEnums,
    );

    expect(outputFile!.content).not.toBe(drifted);
  });
});

// ---------------------------------------------------------------------------
// gRPC enum byte-gates (proto string-field + transport mapper enum bridge)
// ---------------------------------------------------------------------------

const GRPC_ENUM_NS = "D2.Edge.Tests.TypeSpecGrpcEnum.Generated";
const ENUM_PROTO_NS = "D2.Services.Protos.EnumFixtures.V1";

const SIGN_WITH_KIND_KEY_KIND: NestedEnum = {
  name: "KeyKind",
  members: [
    { csName: "Rsa", wireValue: "Rsa", needsEnumMember: false },
    { csName: "Aes", wireValue: "Aes", needsEnumMember: false },
    { csName: "Secret", wireValue: "Secret", needsEnumMember: false },
  ],
};

function signWithKindReqFields(): readonly FieldInfo[] {
  return [
    {
      name: "kid",
      csName: "Kid",
      csType: "string",
      tsName: "kid",
      tsType: "string",
      protoType: "string",
      repeated: false,
      optional: false,
      redact: false,
    },
    {
      name: "keyKind",
      csName: "KeyKind",
      csType: "KeyKind",
      tsName: "keyKind",
      tsType: "KeyKind",
      protoType: "string",
      repeated: false,
      optional: false,
      redact: false,
      enumRef: SIGN_WITH_KIND_KEY_KIND,
    },
  ];
}

function signWithKindRespFields(): readonly FieldInfo[] {
  return [
    {
      name: "signature",
      csName: "Signature",
      csType: "string",
      tsName: "signature",
      tsType: "string",
      protoType: "string",
      repeated: false,
      optional: false,
      redact: false,
    },
    {
      // Response enum (S-1) — exercises the client proto-string -> DTO-enum parse.
      name: "keyKind",
      csName: "KeyKind",
      csType: "KeyKind",
      tsName: "keyKind",
      tsType: "KeyKind",
      protoType: "string",
      repeated: false,
      optional: false,
      redact: false,
      enumRef: SIGN_WITH_KIND_KEY_KIND,
    },
  ];
}

describe("byteParity_SignWithKindEnumGrpc_CommittedFixtures", () => {
  it("regenerated enum-proto carries `string key_kind` + is byte-identical", () => {
    const proto = emitProto(
      "signWithKind",
      "EnumFixturesSigner",
      "SignWithKind",
      "unary",
      "d2.enumfixtures.v1",
      ENUM_PROTO_NS,
      ENUM_SHAPED_SRC,
      "SignWithKindRequest",
      signWithKindReqFields(),
      "SignWithKindOutput",
      signWithKindRespFields(),
      [],
      () => {},
    );

    expect(proto!.content).toContain("string key_kind = 2;");
    expect(proto!.content).toBe(
      readFixture(
        join(GRPC_ENUM_PROTOS, "enum_fixtures_signer_sign_with_kind.g.proto"),
      ),
    );
  });

  it("regenerated SignWithKindTransportMappers.g.cs (the enum-string bridge) is byte-identical", () => {
    const [, mapper] = emitGrpcService(
      "signWithKind",
      "EnumFixturesSigner",
      "SignWithKind",
      ENUM_PROTO_NS,
      GRPC_ENUM_NS,
      GRPC_ENUM_NS,
      ENUM_SHAPED_SRC,
      "SignWithKindRequest",
      "SignWithKindResponse",
      "SignWithKindInput",
      signWithKindReqFields(),
      "SignWithKindOutput",
      signWithKindRespFields(),
      {
        kind: "handler",
        typeName: "ISignWithKindHandler",
        methodName: "HandleAsync",
        targetNamespace: undefined,
      },
    );

    expect(mapper.content).toContain(
      "internal static D2Result<KeyKind> ParseKeyKindWire(string? value)",
    );
    expect(mapper.content).toContain("internal string ToWire()");
    expect(mapper.content).toBe(
      readFixture(join(GRPC_ENUM_HOME, "SignWithKindTransportMappers.g.cs")),
    );
  });

  it("deliberate-drift detection: mutated mapper fixture does NOT match", () => {
    const drifted = readFixture(
      join(GRPC_ENUM_HOME, "SignWithKindTransportMappers.g.cs"),
    ).replace("ParseKeyKindWire", "ParseKeyKindWireDRIFTED");
    const [, mapper] = emitGrpcService(
      "signWithKind",
      "EnumFixturesSigner",
      "SignWithKind",
      ENUM_PROTO_NS,
      GRPC_ENUM_NS,
      GRPC_ENUM_NS,
      ENUM_SHAPED_SRC,
      "SignWithKindRequest",
      "SignWithKindResponse",
      "SignWithKindInput",
      signWithKindReqFields(),
      "SignWithKindOutput",
      signWithKindRespFields(),
      {
        kind: "handler",
        typeName: "ISignWithKindHandler",
        methodName: "HandleAsync",
        targetNamespace: undefined,
      },
    );

    expect(mapper.content).not.toBe(drifted);
  });
});

// The CLIENT-side gRPC enum fixtures (mapper + impl) carry the F-3 response-enum
// parse (To<Output>() returns D2Result<<Output>> + the impl surfaces a parse
// failure via BubbleFail). Pin them byte-identical so the committed fixtures stay
// emitter-determined (never hand-edited, §26.5).
const GRPC_ENUM_CLIENTS_NS = "D2.Edge.Tests.TypeSpecGrpcEnum.Clients";

function signWithKindClientOp() {
  return {
    opName: "signWithKind",
    grpcService: "EnumFixturesSigner",
    grpcMethod: "SignWithKind",
    protoCsharpNs: ENUM_PROTO_NS,
    dtoCsharpNs: GRPC_ENUM_NS,
    sourceSpec: ENUM_SHAPED_SRC,
    requestModelName: "SignWithKindInput",
    requestFields: signWithKindReqFields(),
    responseModelName: "SignWithKindOutput",
    responseFields: signWithKindRespFields(),
  };
}

describe("byteParity_SignWithKindEnumGrpcClient_CommittedFixtures", () => {
  it("regenerated SignWithKindClientMappers.g.cs (response-enum parse) is byte-identical", () => {
    const [, , clientMappers] = emitGrpcClient(
      "EnumFixtures",
      [signWithKindClientOp()],
      GRPC_ENUM_CLIENTS_NS,
    );

    expect(clientMappers!.content).toContain(
      "var keyKindResult = string.ParseKeyKindWire(data.KeyKind);",
    );
    expect(clientMappers!.content).toBe(
      readFixture(join(GRPC_ENUM_HOME, "SignWithKindClientMappers.g.cs")),
    );
  });

  it("regenerated EnumFixturesGrpcClient.g.cs (response-parse surfacing) is byte-identical", () => {
    const [, impl] = emitGrpcClient(
      "EnumFixtures",
      [signWithKindClientOp()],
      GRPC_ENUM_CLIENTS_NS,
    );

    expect(impl!.content).toContain(
      "return D2Result<SignWithKindOutput?>.BubbleFail(responseParseFailure);",
    );
    expect(impl!.content).toBe(
      readFixture(join(GRPC_ENUM_HOME, "EnumFixturesGrpcClient.g.cs")),
    );
  });

  it("deliberate-drift detection: mutated client mapper fixture does NOT match", () => {
    const drifted = readFixture(
      join(GRPC_ENUM_HOME, "SignWithKindClientMappers.g.cs"),
    ).replace("ParseKeyKindWire", "ParseKeyKindWireDRIFTED");
    const [, , clientMappers] = emitGrpcClient(
      "EnumFixtures",
      [signWithKindClientOp()],
      GRPC_ENUM_CLIENTS_NS,
    );

    expect(clientMappers!.content).not.toBe(drifted);
  });
});
