// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Byte-parity gate: regenerating emitter output must produce byte-identical
// content to the committed .g.cs / .g.ts fixtures.
//
// The gate is non-vacuous per §26.5.1 + §1.20: a deliberate-drift case
// (mutate one byte of the fixture) is tested to verify the gate FAILS when
// there is actual divergence. This prevents the byte-gate becoming a tautology
// (comparing a buffer to itself, never catching real drift).

import { describe, it, expect } from "vitest";
import type { Model, ModelProperty, Program, Scalar } from "@typespec/compiler";
import { D2_REDACT_KEY } from "@d2/typespec-decorators";
import { walkModel } from "../src/lib/model-walk.js";
import { emitCsharpDtos } from "../src/lib/csharp-dto-emitter.js";
import { emitTsDtos } from "../src/lib/ts-dto-emitter.js";

// ---------------------------------------------------------------------------
// Fixture definitions — the canonical committed content
// (mirrors the committed .g.cs files: GetJwks DTOs in
// server/services/edge/key-custodian/clients/; sign fixture DTOs in
// D2.Edge.Tests/TypeSpecDto/Generated/)
// ---------------------------------------------------------------------------

/** The committed clients/GetJwksInput.g.cs content (namespace D2.Edge.KeyCustodian.Clients). */
const GET_JWKS_INPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.KeyCustodian.Clients;",
  "",
  "/// <summary>Generated input DTO. No parameters required.</summary>",
  "public sealed record GetJwksInput;",
  "",
].join("\n");

/** The committed clients/GetJwksOutput.g.cs content (namespace D2.Edge.KeyCustodian.Clients). */
const GET_JWKS_OUTPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.KeyCustodian.Clients;",
  "",
  "/// <summary>Generated DTO for the <c>GetJwksOutput</c> operation.</summary>",
  "public sealed record GetJwksOutput(",
  "    IReadOnlyList<Jwk> Keys);",
  "",
  "/// <summary>Generated nested model DTO for <c>Jwk</c>.</summary>",
  "public sealed record Jwk(",
  "    string Kid,",
  "    string N,",
  "    string E,",
  "    string Kty,",
  "    string Use,",
  "    string Alg);",
  "",
].join("\n");

/** The committed SignInput.g.cs content. */
const SIGN_INPUT_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecDto.Generated;",
  "",
  "using D2.Shared.Utilities.Attributes;",
  "using D2.Shared.Utilities.Enums;",
  "",
  "/// <summary>Generated DTO for the <c>SignInput</c> operation.</summary>",
  "public sealed record SignInput(",
  "    string Kid,",
  "    [property: RedactData(Reason = RedactReason.PersonalInformation)] byte[] Payload);",
  "",
].join("\n");

// ---------------------------------------------------------------------------
// Helpers — build TypeSpec stubs matching the committed shapes
// ---------------------------------------------------------------------------

function makeScalar(name: string): Scalar {
  return { kind: "Scalar", name } as unknown as Scalar;
}

function makeProp(type: Scalar, optional = false): ModelProperty {
  return { type, optional } as unknown as ModelProperty;
}

function makeRedactProp(type: Scalar): { prop: ModelProperty; redactMap: Map<object, unknown> } {
  const prop = { type, optional: false } as unknown as ModelProperty;
  return { prop, redactMap: new Map([[prop, true]]) };
}

function makeProgram(redactMap: Map<object, unknown> = new Map()): Program {
  return {
    stateMap(key: symbol): Map<object, unknown> {
      if (key === D2_REDACT_KEY) return redactMap;
      return new Map();
    },
  } as unknown as Program;
}

// ---------------------------------------------------------------------------
// GetJwksInput fixture — empty model
// ---------------------------------------------------------------------------

function buildGetJwksInputWalk() {
  const model: Model = {
    kind: "Model",
    name: "GetJwksInput",
    properties: new Map(),
  } as unknown as Model;
  return walkModel(makeProgram(), model, () => {});
}

// ---------------------------------------------------------------------------
// GetJwksOutput fixture — Jwk[] collection
// ---------------------------------------------------------------------------

function buildGetJwksOutputWalk() {
  const jwkModel: Model = {
    kind: "Model",
    name: "Jwk",
    properties: new Map<string, ModelProperty>([
      ["kid", makeProp(makeScalar("string"))],
      ["n", makeProp(makeScalar("string"))],
      ["e", makeProp(makeScalar("string"))],
      ["kty", makeProp(makeScalar("string"))],
      ["use", makeProp(makeScalar("string"))],
      ["alg", makeProp(makeScalar("string"))],
    ]),
  } as unknown as Model;

  const arrayModel: Model = {
    kind: "Model",
    name: "Array",
    indexer: { value: jwkModel },
    properties: new Map(),
  } as unknown as Model;

  const model: Model = {
    kind: "Model",
    name: "GetJwksOutput",
    properties: new Map<string, ModelProperty>([
      ["keys", { type: arrayModel, optional: false } as unknown as ModelProperty],
    ]),
  } as unknown as Model;

  return walkModel(makeProgram(), model, () => {});
}

// ---------------------------------------------------------------------------
// SignInput fixture — redacted bytes field
// ---------------------------------------------------------------------------

function buildSignInputWalk() {
  const { prop: payloadProp, redactMap } = makeRedactProp(makeScalar("bytes"));
  const kidProp = makeProp(makeScalar("string"));
  const model: Model = {
    kind: "Model",
    name: "SignInput",
    properties: new Map<string, ModelProperty>([
      ["kid", kidProp],
      ["payload", payloadProp],
    ]),
  } as unknown as Model;

  return { walk: walkModel(makeProgram(redactMap), model, () => {}), redactMap };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("byteParity_GetJwksInput_CommittedFixtureIdentical", () => {
  it("regenerated GetJwksInput.g.cs is byte-identical to the committed fixture", () => {
    const { fields, nestedModels } = buildGetJwksInputWalk();
    const [inputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      fields,
      [],
      nestedModels,
    );

    expect(inputFile!.content).toBe(GET_JWKS_INPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match regenerated output", () => {
    // Non-vacuous guard: deliberately corrupt the fixture by one byte.
    const driftedFixture = GET_JWKS_INPUT_FIXTURE.replace("GetJwksInput", "GetJwksInputDRIFTED");

    const { fields, nestedModels } = buildGetJwksInputWalk();
    const [inputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      fields,
      [],
      nestedModels,
    );

    // The drifted fixture must NOT match — proving the gate would catch real drift.
    expect(inputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_GetJwksOutput_CommittedFixtureIdentical", () => {
  it("regenerated GetJwksOutput.g.cs is byte-identical to the committed fixture", () => {
    const { fields, nestedModels } = buildGetJwksOutputWalk();
    const [, outputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      [],
      fields,
      nestedModels,
    );

    expect(outputFile!.content).toBe(GET_JWKS_OUTPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match regenerated output", () => {
    // Non-vacuous guard: deliberately corrupt the fixture by one byte.
    const driftedFixture = GET_JWKS_OUTPUT_FIXTURE.replace("GetJwksOutput", "GetJwksOutputDRIFTED");

    const { fields, nestedModels } = buildGetJwksOutputWalk();
    const [, outputFile] = emitCsharpDtos(
      "getJwks",
      "D2.Edge.KeyCustodian.Clients",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      [],
      fields,
      nestedModels,
    );

    // The drifted fixture must NOT match — proving the gate would catch real drift.
    expect(outputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_SignInput_CommittedFixtureIdentical", () => {
  it("regenerated SignInput.g.cs is byte-identical to the committed fixture", () => {
    const { walk } = buildSignInputWalk();
    const [inputFile] = emitCsharpDtos(
      "sign",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/sign-shaped.tsp",
      walk.fields,
      [],
      [],
    );

    expect(inputFile!.content).toBe(SIGN_INPUT_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match regenerated output", () => {
    // §1.20 non-vacuous guard: deliberately corrupt the fixture by one byte.
    const driftedFixture = SIGN_INPUT_FIXTURE.replace("SignInput", "SignInputDRIFTED");

    const { walk } = buildSignInputWalk();
    const [inputFile] = emitCsharpDtos(
      "sign",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      "contracts/typespec/fixtures/sign-shaped.tsp",
      walk.fields,
      [],
      [],
    );

    // The drifted fixture must NOT match — proving the gate would catch real drift.
    expect(inputFile!.content).not.toBe(driftedFixture);
  });
});

describe("byteParity_GetJwksDto_TsFile", () => {
  it("regenerated get-jwks-dto.g.ts matches expected shape", () => {
    const inputWalk = buildGetJwksInputWalk();
    const outputWalk = buildGetJwksOutputWalk();
    const tsFile = emitTsDtos(
      "getJwks",
      "contracts/typespec/key-custodian/key-custodian.tsp",
      inputWalk.fields,
      outputWalk.fields,
      outputWalk.nestedModels,
    );

    expect(tsFile.fileName).toBe("get-jwks-dto.g.ts");
    // Structural checks (byte-exact would require committing the .g.ts too;
    // structural assertion pins the shape without the fragility of full-string compare).
    expect(tsFile.content).toContain("export interface Jwk {");
    expect(tsFile.content).toContain("readonly kid: string;");
    expect(tsFile.content).toContain("export interface GetJwksInput {");
    expect(tsFile.content).toContain("export interface GetJwksOutput {");
    expect(tsFile.content).toContain("readonly keys: readonly Jwk[];");
  });
});
