// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Direct-unit tests for emitCsharpDtos.
// Covers: scalar params, empty input (parameterless record), collection of
// nested model, redacted fields (with [property:] target), no-redact ops,
// banner presence, American-English check, nested model emitted once.

import { describe, it, expect } from "vitest";
import { emitCsharpDtos } from "../src/lib/csharp-dto-emitter.js";
import type { FieldInfo, NestedModel } from "../src/lib/model-walk.js";

const TEST_NAMESPACE = "D2.Test.Application";
const TEST_SPEC = "contracts/typespec/test.tsp";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function field(
  name: string,
  csType: string,
  tsType: string,
  optional = false,
  redact = false,
): FieldInfo {
  return {
    name,
    csName: name[0]!.toUpperCase() + name.slice(1),
    csType,
    tsName: name,
    tsType,
    optional,
    redact,
    repeated: false,
  };
}

function nested(name: string, fields: FieldInfo[]): NestedModel {
  return { name, fields };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("emitCsharpDtos_ScalarInput_PositionalRecord", () => {
  it("emits positional sealed record with scalar params and banner", () => {
    const input = [field("kid", "string", "string"), field("count", "int", "number")];
    const [inputFile] = emitCsharpDtos("rotateKey", TEST_NAMESPACE, TEST_SPEC, input, [], []);

    expect(inputFile!.fileName).toBe("RotateKeyInput.g.cs");
    expect(inputFile!.content).toContain("// <auto-generated>");
    expect(inputFile!.content).toContain(`Source spec: ${TEST_SPEC}`);
    expect(inputFile!.content).toContain("public sealed record RotateKeyInput(");
    expect(inputFile!.content).toContain("string Kid");
    expect(inputFile!.content).toContain("int Count");
    expect(inputFile!.content).toContain("#nullable enable");
    expect(inputFile!.content).toContain(`namespace ${TEST_NAMESPACE};`);
  });
});

describe("emitCsharpDtos_EmptyInput_ParameterlessRecord", () => {
  it("emits parameterless sealed record for op with no input params", () => {
    const [inputFile] = emitCsharpDtos("getJwks", TEST_NAMESPACE, TEST_SPEC, [], [], []);

    expect(inputFile!.fileName).toBe("GetJwksInput.g.cs");
    // Parameterless record ends with semicolon — no parentheses.
    expect(inputFile!.content).toContain("public sealed record GetJwksInput;");
    expect(inputFile!.content).not.toContain("GetJwksInput(");
  });
});

describe("emitCsharpDtos_OutputWithNestedCollection", () => {
  it("emits IReadOnlyList<Jwk> and the Jwk nested record", () => {
    const jwkFields = [
      field("kid", "string", "string"),
      field("n", "string", "string"),
      field("e", "string", "string"),
    ];
    const outputFields = [field("keys", "IReadOnlyList<Jwk>", "readonly Jwk[]")];
    const [, outputFile] = emitCsharpDtos(
      "getJwks",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      [nested("Jwk", jwkFields)],
    );

    expect(outputFile!.content).toContain("IReadOnlyList<Jwk> Keys");
    expect(outputFile!.content).toContain("public sealed record Jwk(");
    expect(outputFile!.content).toContain("string Kid");
    expect(outputFile!.content).toContain("string N");
    expect(outputFile!.content).toContain("string E");
  });
});

describe("emitCsharpDtos_RedactedField_PropertyTarget", () => {
  it("emits [property: RedactData] on redacted param and adds using directives", () => {
    const inputFields = [
      field("kid", "string", "string"),
      field("payload", "byte[]", "Uint8Array", false, true), // redacted
    ];
    const [inputFile] = emitCsharpDtos("sign", TEST_NAMESPACE, TEST_SPEC, inputFields, [], []);

    // The [property:] attribute target is mandatory — a bare param attribute
    // would NOT be seen by the property-reflecting RedactDataDestructuringPolicy.
    expect(inputFile!.content).toContain(
      "[property: RedactData(Reason = RedactReason.PersonalInformation)] byte[] Payload",
    );
    expect(inputFile!.content).toContain("using D2.Shared.Utilities.Attributes;");
    expect(inputFile!.content).toContain("using D2.Shared.Utilities.Enums;");
    // Non-redacted field has no attribute.
    expect(inputFile!.content).toContain("string Kid");
    expect(inputFile!.content).not.toContain("string Kid\n    [property:");
  });

  it("non-redacted op emits NO using directives for RedactData", () => {
    const inputFields = [field("id", "string", "string")];
    const [inputFile] = emitCsharpDtos("noRedact", TEST_NAMESPACE, TEST_SPEC, inputFields, [], []);

    expect(inputFile!.content).not.toContain("using D2.Shared.Utilities.Attributes;");
    expect(inputFile!.content).not.toContain("using D2.Shared.Utilities.Enums;");
    expect(inputFile!.content).not.toContain("RedactData");
  });
});

describe("emitCsharpDtos_BannerAndAutoGenerated", () => {
  it("every emitted file starts with the auto-generated banner", () => {
    const [inputFile, outputFile] = emitCsharpDtos(
      "testOp",
      TEST_NAMESPACE,
      TEST_SPEC,
      [field("x", "string", "string")],
      [field("y", "int", "number")],
      [],
    );

    for (const f of [inputFile!, outputFile!]) {
      expect(f.content).toContain("// <auto-generated>");
      // The banner indents the body lines with spaces (see buildBanner).
      expect(f.content).toContain("//   Generated by the @d2/typespec-emitters TypeSpec emitter.");
      expect(f.content).toContain("//   Manual edits will be lost on rebuild.");
      // No copyright-file header (that is for hand-authored files only).
      expect(f.content).not.toContain("<copyright file=");
    }
  });
});

describe("emitCsharpDtos_AmericanEnglish", () => {
  it("generated summaries use American English (no 'cancelled', 'behaviour', etc.)", () => {
    const [inputFile, outputFile] = emitCsharpDtos(
      "cancelOrder",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [field("result", "string", "string")],
      [],
    );

    for (const f of [inputFile!, outputFile!]) {
      // American English: "canceled" not "cancelled"
      expect(f.content).not.toMatch(/cancelled/i);
    }
  });
});

describe("emitCsharpDtos_NestedModelEmittedOnce", () => {
  it("same nested model referenced twice in one output emits one record", () => {
    const jwkFields = [field("kid", "string", "string")];
    const outputFields = [
      field("active", "IReadOnlyList<Jwk>", "readonly Jwk[]"),
      field("retiring", "IReadOnlyList<Jwk>", "readonly Jwk[]"),
    ];
    const [, outputFile] = emitCsharpDtos(
      "getKeys",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      // Dedup is done at walkModel level; emit receives the already-deduped list.
      [nested("Jwk", jwkFields)],
    );

    const jwkCount = (outputFile!.content.match(/public sealed record Jwk/g) ?? []).length;
    expect(jwkCount).toBe(1);
  });
});

describe("emitCsharpDtos_FilePairNames", () => {
  it("returns exactly two files with Input and Output names", () => {
    const files = emitCsharpDtos("doSomething", TEST_NAMESPACE, TEST_SPEC, [], [], []);

    expect(files).toHaveLength(2);
    expect(files[0]!.fileName).toBe("DoSomethingInput.g.cs");
    expect(files[1]!.fileName).toBe("DoSomethingOutput.g.cs");
  });
});

describe("emitCsharpDtos_EmptyOpName_Passthrough", () => {
  it("empty op name string → graceful degenerate output (defensive branch)", () => {
    // Exercises the `if (s.length === 0) return s;` branch in toPascalFromCamel.
    const files = emitCsharpDtos("", TEST_NAMESPACE, TEST_SPEC, [], [], []);

    // Both file names degenerate but no crash.
    expect(files[0]!.fileName).toBe("Input.g.cs");
    expect(files[1]!.fileName).toBe("Output.g.cs");
  });
});

describe("emitCsharpDtos_EmptyNestedModel_ParameterlessRecord", () => {
  it("nested model with no fields emits a parameterless record (no parentheses)", () => {
    const outputFields = [field("wrapper", "Inner", "Inner")];
    const [, outputFile] = emitCsharpDtos(
      "getInner",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      // Empty nested model — no fields.
      [{ name: "Inner", fields: [] }],
    );

    // The parameterless nested record uses semicolon form.
    expect(outputFile!.content).toContain("public sealed record Inner;");
    expect(outputFile!.content).not.toContain("Inner(");
  });
});
