// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Direct-unit tests for emitCsharpDtos.
// Covers: scalar params, empty input (parameterless record), collection of
// nested model, redacted fields (with [property:] target), no-redact ops,
// banner presence, American-English check, nested model emitted once.

import { describe, it, expect } from "vitest";
import { emitCsharpDtos } from "../src/lib/csharp-dto-emitter.js";
import type {
  FieldInfo,
  NestedEnum,
  NestedModel,
} from "../src/lib/model-walk.js";

const TEST_NAMESPACE = "D2.Test.Application";
const TEST_SPEC = "contracts/typespec/test.tsp";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function field(
  name: string,
  csType: string,
  tsType: string,
  optional = false,
  redactReason?: string,
  jsonName?: string,
): FieldInfo {
  return {
    name,
    csName: name[0]!.toUpperCase() + name.slice(1),
    csType,
    tsName: name,
    tsType,
    optional,
    redactReason,
    jsonName,
    repeated: false,
  };
}

function enumField(name: string, enumRef: NestedEnum): FieldInfo {
  return {
    name,
    csName: name[0]!.toUpperCase() + name.slice(1),
    csType: enumRef.name,
    tsName: name,
    tsType: enumRef.name,
    protoType: "string",
    optional: false,
    redactReason: undefined,
    repeated: false,
    enumRef,
  };
}

function nested(name: string, fields: FieldInfo[]): NestedModel {
  return { name, fields };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("emitCsharpDtos_ScalarInput_PositionalRecord", () => {
  it("emits positional sealed record with scalar params and banner", () => {
    const input = [
      field("kid", "string", "string"),
      field("count", "int", "number"),
    ];
    const [inputFile] = emitCsharpDtos(
      "rotateKey",
      TEST_NAMESPACE,
      TEST_SPEC,
      input,
      [],
      [],
    );

    expect(inputFile!.fileName).toBe("RotateKeyInput.g.cs");
    expect(inputFile!.content).toContain("// <auto-generated>");
    expect(inputFile!.content).toContain(`Source spec: ${TEST_SPEC}`);
    expect(inputFile!.content).toContain(
      "public sealed record RotateKeyInput(",
    );
    expect(inputFile!.content).toContain("string Kid");
    expect(inputFile!.content).toContain("int Count");
    expect(inputFile!.content).toContain("#nullable enable");
    expect(inputFile!.content).toContain(`namespace ${TEST_NAMESPACE};`);
  });
});

describe("emitCsharpDtos_EmptyInput_ParameterlessRecord", () => {
  it("emits parameterless sealed record for op with no input params", () => {
    const [inputFile] = emitCsharpDtos(
      "getJwks",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [],
      [],
    );

    expect(inputFile!.fileName).toBe("GetJwksInput.g.cs");
    // Parameterless record ends with semicolon — no parentheses.
    expect(inputFile!.content).toContain("public sealed record GetJwksInput;");
    expect(inputFile!.content).not.toContain("GetJwksInput(");
  });
});

describe("emitCsharpDtos_OutputWithNestedCollection", () => {
  it("emits IReadOnlyList<Jwk> and the Jwk nested record", () => {
    const jwkFields = [
      field("kid", "string", "string"),
      field("n", "string", "string"),
      field("e", "string", "string"),
    ];
    const outputFields = [
      field("keys", "IReadOnlyList<Jwk>", "readonly Jwk[]"),
    ];
    const [, outputFile] = emitCsharpDtos(
      "getJwks",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      [nested("Jwk", jwkFields)],
    );

    expect(outputFile!.content).toContain("IReadOnlyList<Jwk> Keys");
    expect(outputFile!.content).toContain("public sealed record Jwk(");
    expect(outputFile!.content).toContain("string Kid");
    expect(outputFile!.content).toContain("string N");
    expect(outputFile!.content).toContain("string E");
  });
});

describe("emitCsharpDtos_RedactedField_PropertyTarget", () => {
  it("emits [property: RedactData] on redacted param and adds using directives", () => {
    const inputFields = [
      field("kid", "string", "string"),
      field("payload", "byte[]", "Uint8Array", false, "SecretInformation"), // redacted
    ];
    const [inputFile] = emitCsharpDtos(
      "sign",
      TEST_NAMESPACE,
      TEST_SPEC,
      inputFields,
      [],
      [],
    );

    // The [property:] attribute target is mandatory — a bare param attribute
    // would NOT be seen by the property-reflecting RedactDataDestructuringPolicy.
    expect(inputFile!.content).toContain(
      "[property: RedactData(Reason = RedactReason.SecretInformation)] byte[] Payload",
    );
    expect(inputFile!.content).toContain(
      "using D2.Shared.Utilities.Attributes;",
    );
    expect(inputFile!.content).toContain("using D2.Shared.Utilities.Enums;");
    // Non-redacted field has no attribute.
    expect(inputFile!.content).toContain("string Kid");
    expect(inputFile!.content).not.toContain("string Kid\n    [property:");
  });

  it("non-redacted op emits NO using directives for RedactData", () => {
    const inputFields = [field("id", "string", "string")];
    const [inputFile] = emitCsharpDtos(
      "noRedact",
      TEST_NAMESPACE,
      TEST_SPEC,
      inputFields,
      [],
      [],
    );

    expect(inputFile!.content).not.toContain(
      "using D2.Shared.Utilities.Attributes;",
    );
    expect(inputFile!.content).not.toContain(
      "using D2.Shared.Utilities.Enums;",
    );
    expect(inputFile!.content).not.toContain("RedactData");
  });
});

describe("emitCsharpDtos_RedactedField_ReasonThreadedFailLoud", () => {
  it("emits the exact threaded RedactReason, never a hard-coded default", () => {
    const inputFields = [
      field("token", "string", "string", false, "FinancialInformation"),
    ];
    const [inputFile] = emitCsharpDtos(
      "store",
      TEST_NAMESPACE,
      TEST_SPEC,
      inputFields,
      [],
      [],
    );

    expect(inputFile!.content).toContain(
      "[property: RedactData(Reason = RedactReason.FinancialInformation)] string Token",
    );
    // The reason is threaded from @d2Redact — never defaulted to PersonalInformation.
    expect(inputFile!.content).not.toContain("PersonalInformation");
  });

  it("fails loud when a redacted field carries an unrecognized RedactReason", () => {
    const inputFields = [
      field("payload", "byte[]", "Uint8Array", false, "NotARealReason"),
    ];

    expect(() =>
      emitCsharpDtos("sign", TEST_NAMESPACE, TEST_SPEC, inputFields, [], []),
    ).toThrow(/RedactReason/);
  });
});

describe("emitCsharpDtos_JsonPropertyName_WireOverride", () => {
  it("jsonName set (differs from default) → [property: JsonPropertyName] + System.Text.Json using", () => {
    // The OIDC discovery doc's snake_case field: a property JwksUri whose JSON
    // wire form must be jwks_uri.
    const outputFields = [
      field("jwksUri", "string", "string", false, undefined, "jwks_uri"),
    ];
    const [, outputFile] = emitCsharpDtos(
      "getOidcConfiguration",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      [],
    );

    expect(outputFile!.content).toContain(
      '[property: JsonPropertyName("jwks_uri")] string JwksUri',
    );
    expect(outputFile!.content).toContain(
      "using System.Text.Json.Serialization;",
    );
  });

  it("no jsonName + no enums → attribute absent AND the System.Text.Json using absent (byte-stability guard)", () => {
    const outputFields = [field("issuer", "string", "string")];
    const [, outputFile] = emitCsharpDtos(
      "getOidcConfiguration",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      [],
    );

    expect(outputFile!.content).not.toContain("JsonPropertyName");
    expect(outputFile!.content).not.toContain(
      "using System.Text.Json.Serialization;",
    );
  });

  it("jsonName + redact on the same field → BOTH attributes, JsonPropertyName first", () => {
    const outputFields = [
      field(
        "secretWire",
        "string",
        "string",
        false,
        "SecretInformation",
        "secret_wire",
      ),
    ];
    const [, outputFile] = emitCsharpDtos(
      "combo",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      [],
    );

    expect(outputFile!.content).toContain(
      '[property: JsonPropertyName("secret_wire")] [property: RedactData(Reason = RedactReason.SecretInformation)] string SecretWire',
    );
    // Both namespaces are present.
    expect(outputFile!.content).toContain(
      "using System.Text.Json.Serialization;",
    );
    expect(outputFile!.content).toContain(
      "using D2.Shared.Utilities.Attributes;",
    );
  });

  it("jsonName on an array field → [property: JsonPropertyName] precedes the IReadOnlyList type", () => {
    const outputFields: FieldInfo[] = [
      {
        name: "idTokenSigningAlgValuesSupported",
        csName: "IdTokenSigningAlgValuesSupported",
        csType: "IReadOnlyList<string>",
        tsName: "idTokenSigningAlgValuesSupported",
        tsType: "readonly string[]",
        protoType: "string",
        optional: false,
        redactReason: undefined,
        jsonName: "id_token_signing_alg_values_supported",
        repeated: true,
      },
    ];
    const [, outputFile] = emitCsharpDtos(
      "getOidcConfiguration",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      [],
    );

    expect(outputFile!.content).toContain(
      '[property: JsonPropertyName("id_token_signing_alg_values_supported")] IReadOnlyList<string> IdTokenSigningAlgValuesSupported',
    );
  });

  it("jsonName on a nested-model field → the System.Text.Json using is added for the owning record", () => {
    const nestedWithJsonName = nested("Inner", [
      field("wireField", "string", "string", false, undefined, "wire_field"),
    ]);
    const [, outputFile] = emitCsharpDtos(
      "withNested",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [field("inner", "Inner", "Inner")],
      [nestedWithJsonName],
    );

    expect(outputFile!.content).toContain(
      "using System.Text.Json.Serialization;",
    );
    expect(outputFile!.content).toContain(
      '[property: JsonPropertyName("wire_field")] string WireField',
    );
  });
});

describe("emitCsharpDtos_BannerAndAutoGenerated", () => {
  it("every emitted file starts with the auto-generated banner", () => {
    const [inputFile, outputFile] = emitCsharpDtos(
      "testOp",
      TEST_NAMESPACE,
      TEST_SPEC,
      [field("x", "string", "string")],
      [field("y", "int", "number")],
      [],
    );

    for (const f of [inputFile!, outputFile!]) {
      expect(f.content).toContain("// <auto-generated>");
      // The banner indents the body lines with spaces (see buildBanner).
      expect(f.content).toContain(
        "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
      );
      expect(f.content).toContain("//   Manual edits will be lost on rebuild.");
      // No copyright-file header (that is for hand-authored files only).
      expect(f.content).not.toContain("<copyright file=");
    }
  });
});

describe("emitCsharpDtos_AmericanEnglish", () => {
  it("generated summaries use American English (no 'cancelled', 'behaviour', etc.)", () => {
    const [inputFile, outputFile] = emitCsharpDtos(
      "cancelOrder",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [field("result", "string", "string")],
      [],
    );

    for (const f of [inputFile!, outputFile!]) {
      // American English: "canceled" not "cancelled"
      expect(f.content).not.toMatch(/cancelled/i);
    }
  });
});

describe("emitCsharpDtos_NestedModelEmittedOnce", () => {
  it("same nested model referenced twice in one output emits one record", () => {
    const jwkFields = [field("kid", "string", "string")];
    const outputFields = [
      field("active", "IReadOnlyList<Jwk>", "readonly Jwk[]"),
      field("retiring", "IReadOnlyList<Jwk>", "readonly Jwk[]"),
    ];
    const [, outputFile] = emitCsharpDtos(
      "getKeys",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      // Dedup is done at walkModel level; emit receives the already-deduped list.
      [nested("Jwk", jwkFields)],
    );

    const jwkCount = (
      outputFile!.content.match(/public sealed record Jwk/g) ?? []
    ).length;
    expect(jwkCount).toBe(1);
  });
});

describe("emitCsharpDtos_FilePairNames", () => {
  it("returns exactly two files with Input and Output names", () => {
    const files = emitCsharpDtos(
      "doSomething",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [],
      [],
    );

    expect(files).toHaveLength(2);
    expect(files[0]!.fileName).toBe("DoSomethingInput.g.cs");
    expect(files[1]!.fileName).toBe("DoSomethingOutput.g.cs");
  });
});

describe("emitCsharpDtos_EmptyOpName_Passthrough", () => {
  it("empty op name string → graceful degenerate output (defensive branch)", () => {
    // Exercises the `if (s.length === 0) return s;` branch in toPascalFromCamel.
    const files = emitCsharpDtos("", TEST_NAMESPACE, TEST_SPEC, [], [], []);

    // Both file names degenerate but no crash.
    expect(files[0]!.fileName).toBe("Input.g.cs");
    expect(files[1]!.fileName).toBe("Output.g.cs");
  });
});

describe("emitCsharpDtos_EmptyNestedModel_ParameterlessRecord", () => {
  it("nested model with no fields emits a parameterless record (no parentheses)", () => {
    const outputFields = [field("wrapper", "Inner", "Inner")];
    const [, outputFile] = emitCsharpDtos(
      "getInner",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      outputFields,
      // Empty nested model — no fields.
      [{ name: "Inner", fields: [] }],
    );

    // The parameterless nested record uses semicolon form.
    expect(outputFile!.content).toContain("public sealed record Inner;");
    expect(outputFile!.content).not.toContain("Inner(");
  });
});

// ---------------------------------------------------------------------------
// Enum / string-literal-union emission
// ---------------------------------------------------------------------------

const KEY_KIND: NestedEnum = {
  name: "KeyKind",
  members: [
    { csName: "Rsa", wireValue: "Rsa", needsEnumMember: false },
    { csName: "Aes", wireValue: "Aes", needsEnumMember: false },
    { csName: "Secret", wireValue: "Secret", needsEnumMember: false },
  ],
};

const LEVEL: NestedEnum = {
  name: "Level",
  members: [
    { csName: "Low", wireValue: "Low", needsEnumMember: false, intValue: 0 },
    {
      csName: "Medium",
      wireValue: "Medium",
      needsEnumMember: false,
      intValue: 5,
    },
    { csName: "High", wireValue: "High", needsEnumMember: false, intValue: 10 },
  ],
};

const ACCOUNT_KIND: NestedEnum = {
  name: "AccountKind",
  members: [
    { csName: "Internal", wireValue: "internal", needsEnumMember: true },
    { csName: "ThirdParty", wireValue: "third-party", needsEnumMember: true },
  ],
};

describe("emitCsharpDtos_BareEnum_SiblingDeclaration", () => {
  it("S-1 bare enum → sibling public enum + [JsonConverter], no [JsonStringEnumMemberName], correct using", () => {
    const [, outputFile] = emitCsharpDtos(
      "op",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [enumField("keyKind", KEY_KIND)],
      [],
      [],
      [KEY_KIND],
    );

    expect(outputFile!.content).toContain(
      "[JsonConverter(typeof(JsonStringEnumConverter))]",
    );
    expect(outputFile!.content).toContain("public enum KeyKind");
    expect(outputFile!.content).toContain("    Rsa,");
    expect(outputFile!.content).toContain("    Secret,");
    // Bare members carry NO member-name attribute.
    expect(outputFile!.content).not.toContain("JsonStringEnumMemberName");
    expect(outputFile!.content).toContain(
      "using System.Text.Json.Serialization;",
    );
    // The NET 9+ attribute namespace is System.Text.Json.Serialization — NOT the
    // old [EnumMember] / System.Runtime.Serialization (which the converter ignores).
    expect(outputFile!.content).not.toContain("System.Runtime.Serialization");
    expect(outputFile!.content).not.toContain("EnumMember");
  });
});

describe("emitCsharpDtos_ExplicitIntEnum_BackingPreserved", () => {
  it("S-2 explicit-int enum → '= 0/5/10' backing preserved (wire is still the name)", () => {
    const [, outputFile] = emitCsharpDtos(
      "op",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [enumField("level", LEVEL)],
      [],
      [],
      [LEVEL],
    );

    expect(outputFile!.content).toContain("    Low = 0,");
    expect(outputFile!.content).toContain("    Medium = 5,");
    expect(outputFile!.content).toContain("    High = 10,");
  });
});

describe("emitCsharpDtos_NonIdentifierLiteral_JsonStringEnumMemberName", () => {
  it('S-3 third-party → ThirdParty + [JsonStringEnumMemberName("third-party")]', () => {
    const [, outputFile] = emitCsharpDtos(
      "op",
      TEST_NAMESPACE,
      TEST_SPEC,
      [],
      [enumField("accountKind", ACCOUNT_KIND)],
      [],
      [],
      [ACCOUNT_KIND],
    );

    expect(outputFile!.content).toContain(
      '[JsonStringEnumMemberName("internal")]',
    );
    expect(outputFile!.content).toContain(
      '[JsonStringEnumMemberName("third-party")]',
    );
    expect(outputFile!.content).toContain("    ThirdParty,");
    // STRICT — no Unknown sentinel emitted.
    expect(outputFile!.content).not.toContain("Unknown");
  });
});

describe("emitCsharpDtos_InputOnlyEnum_LandsInInputFile", () => {
  it("an enum referenced only by the input walk is emitted in the Input file (not duplicated in Output)", () => {
    const [inputFile, outputFile] = emitCsharpDtos(
      "op",
      TEST_NAMESPACE,
      TEST_SPEC,
      [enumField("keyKind", KEY_KIND)],
      [field("signature", "string", "string")],
      [],
      [KEY_KIND], // input enums
      [], // output enums
    );

    // The enum is declared exactly once — in the Input file.
    expect(inputFile!.content).toContain("public enum KeyKind");
    expect(outputFile!.content).not.toContain("public enum KeyKind");
  });

  it("an enum on BOTH input + output is emitted ONLY in the Output file (no duplicate type)", () => {
    const [inputFile, outputFile] = emitCsharpDtos(
      "op",
      TEST_NAMESPACE,
      TEST_SPEC,
      [enumField("keyKind", KEY_KIND)],
      [enumField("keyKind", KEY_KIND)],
      [],
      [KEY_KIND],
      [KEY_KIND],
    );

    expect(outputFile!.content).toContain("public enum KeyKind");
    expect(inputFile!.content).not.toContain("public enum KeyKind");
  });
});
