// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Unit tests for the idempotency-gate emitter.
//
// Coverage:
//   emitIdempotencyStoreSeam — interface shape, namespace, banner, usings.
//   buildIdempotencyGate — header keySource (key resolution, Falsey guard,
//     TryGetAsync replay, StoreAsync post-delegate), derived keySource (SHA-256
//     hash, PascalCase field access, no header guard), adversarial inputs
//     (empty fields for derived, unknown keySource, empty field name, ttl).
//   emitRoutePolicy integration — gate woven into route delegate (header +
//     derived), absent gate → byte-identical to non-gated output.

import { describe, it, expect } from "vitest";
import {
  emitIdempotencyStoreSeam,
  buildIdempotencyGate,
} from "../src/lib/idempotency-gate-emitter.js";
import { emitRoutePolicy } from "../src/lib/route-policy-emitter.js";
import type { RoutePolicyEmitInput } from "../src/lib/route-policy-emitter.js";
import type { IdempotencyGateInput } from "../src/lib/idempotency-gate-emitter.js";
import { $lib } from "../src/lib.js";

// ---------------------------------------------------------------------------
// Shared fixture builders
// ---------------------------------------------------------------------------

const NS = "D2.Edge.Tests.TypeSpecRoute.Generated";
const SOURCE = "contracts/typespec/fixtures/sign-shaped.tsp";

function makeBaseRouteInput(
  overrides: Partial<RoutePolicyEmitInput> = {},
): RoutePolicyEmitInput {
  return {
    opName: "signFixture",
    verb: "post",
    routePath: "/internal/v1/fixtures/sign-fixture",
    delegationTarget: {
      kind: "facade",
      typeName: "ISignFixtureSignerFacade",
      methodName: "SignFixtureAsync",
    },
    delegationTargetNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated.Facade",
    inputTypeName: "SignFixtureInput",
    outputTypeName: "SignFixtureOutput",
    dtoNamespace: "D2.Edge.Tests.TypeSpecDto.Generated",
    scopePolicy: { kind: "any", scopes: ["self.write"] },
    rateTier: "Standard",
    csrf: "exempt",
    registrationNamespace: NS,
    sourceSpec: SOURCE,
    ...overrides,
  };
}

function makeHeaderGateInput(
  overrides: Partial<IdempotencyGateInput> = {},
): IdempotencyGateInput {
  return {
    keySource: "header",
    ttlSeconds: 86400,
    fields: [],
    inputTypeName: "SignFixtureInput",
    outputTypeName: "SignFixtureOutput",
    pascalOpName: "SignFixture",
    ...overrides,
  };
}

function makeDerivedGateInput(
  overrides: Partial<IdempotencyGateInput> = {},
): IdempotencyGateInput {
  return {
    keySource: "derived",
    ttlSeconds: 3600,
    fields: ["Kid"],
    inputTypeName: "SignFixtureInput",
    outputTypeName: "SignFixtureOutput",
    pascalOpName: "SignDerived",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// emitIdempotencyStoreSeam
// ---------------------------------------------------------------------------

describe("emitIdempotencyStoreSeam — file shape", () => {
  it("returns fileName D2GeneratedIdempotencyStore.g.cs", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.fileName).toBe("D2GeneratedIdempotencyStore.g.cs");
  });

  it("emits auto-generated banner", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain("<auto-generated>");
    expect(file.content).toContain("Manual edits will be lost on rebuild.");
  });

  it("emits #nullable enable", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain("#nullable enable");
  });

  it("namespace appears before using directives", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    const nsIdx = file.content.indexOf("namespace ");
    const usingIdx = file.content.indexOf("using ");
    expect(nsIdx).toBeGreaterThan(-1);
    expect(usingIdx).toBeGreaterThan(-1);
    expect(nsIdx).toBeLessThan(usingIdx);
  });

  it("emits the correct namespace", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain(`namespace ${NS};`);
  });

  it("emits using D2.Shared.Result", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain("using D2.Shared.Result;");
  });

  it("emits public interface D2GeneratedIdempotencyStore", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain(
      "public interface D2GeneratedIdempotencyStore",
    );
  });

  it("emits TryGetAsync generic method signature", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain(
      "ValueTask<D2Result<TStored?>> TryGetAsync<TStored>(string key, CancellationToken ct = default);",
    );
  });

  it("emits StoreAsync generic method signature", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain(
      "ValueTask<D2Result> StoreAsync<TStored>(string key, TStored value, TimeSpan ttl, CancellationToken ct = default);",
    );
  });

  it("emits XML doc summary on interface", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).toContain("/// <summary>");
    expect(file.content).toContain(
      "Faithful seam for the generated idempotency gate",
    );
  });

  it("throws on empty registrationNamespace", () => {
    expect(() => emitIdempotencyStoreSeam("", SOURCE)).toThrow(
      "registrationNamespace must not be empty",
    );
  });
});

describe("emitIdempotencyStoreSeam — no phase/step labels", () => {
  it("content contains no 'Step N' patterns", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).not.toMatch(/Step\s+\d+/i);
  });

  it("content contains no 'Phase N' patterns", () => {
    const file = emitIdempotencyStoreSeam(NS, SOURCE);
    expect(file.content).not.toMatch(/Phase\s+\d+/i);
  });
});

// ---------------------------------------------------------------------------
// buildIdempotencyGate — header keySource
// ---------------------------------------------------------------------------

describe("buildIdempotencyGate — header keySource", () => {
  it("storeParam is 'D2GeneratedIdempotencyStore store'", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    expect(weave.storeParam).toBe("D2GeneratedIdempotencyStore store");
  });

  it("preDelegateLines include header read from Idempotency-Key", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain('"Idempotency-Key"');
  });

  it("preDelegateLines include Falsey() guard for null/empty/whitespace", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain(".Falsey()");
  });

  it("preDelegateLines include ValidationFailed return when key is absent/whitespace", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain("ValidationFailed()");
    expect(pre).toContain("statusCode: 400");
    expect(pre).toContain("application/problem+json");
  });

  it("preDelegateLines include TryGetAsync replay-check", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain("store.TryGetAsync");
    expect(pre).toContain("idempotencyKey");
  });

  it("preDelegateLines include replay short-circuit (return replayed result)", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain("cachedResult.Success");
    expect(pre).toContain("replayed");
    expect(pre).toContain("replayStatus = (int)replayed.StatusCode");
    expect(pre).toContain("if (replayStatus < 400)");
    expect(pre).toContain(
      "Results.Json(replayed.Data, statusCode: replayStatus)",
    );
    expect(pre).toContain("ToProblemDetails");
  });

  it("postDelegateLines include StoreAsync with correct TTL", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    const post = weave.postDelegateLines.join("\n");
    expect(post).toContain("store.StoreAsync");
    expect(post).toContain("idempotencyKey");
    expect(post).toContain("TimeSpan.FromSeconds(86400)");
  });

  it("extraUsings includes D2.Shared.Utilities.Extensions (for Falsey)", () => {
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    expect(weave.extraUsings).toContain("D2.Shared.Utilities.Extensions");
  });

  it("replay-check appears BEFORE postDelegateLines (order: pre → delegate → post)", () => {
    // preDelegateLines must contain replay; postDelegateLines must contain store.
    const weave = buildIdempotencyGate(makeHeaderGateInput());
    const preCombined = weave.preDelegateLines.join("\n");
    const postCombined = weave.postDelegateLines.join("\n");
    expect(preCombined).toContain("TryGetAsync");
    expect(postCombined).toContain("StoreAsync");
    // StoreAsync must NOT appear in pre (it must be after the delegation call).
    expect(preCombined).not.toContain("StoreAsync");
    // TryGetAsync must NOT appear in post.
    expect(postCombined).not.toContain("TryGetAsync");
  });

  it("different ttlSeconds propagates correctly", () => {
    const weave = buildIdempotencyGate(
      makeHeaderGateInput({ ttlSeconds: 3600 }),
    );
    expect(weave.postDelegateLines.join("\n")).toContain(
      "TimeSpan.FromSeconds(3600)",
    );
  });
});

// ---------------------------------------------------------------------------
// buildIdempotencyGate — derived keySource
// ---------------------------------------------------------------------------

describe("buildIdempotencyGate — derived keySource", () => {
  it("storeParam is 'D2GeneratedIdempotencyStore store'", () => {
    const weave = buildIdempotencyGate(makeDerivedGateInput());
    expect(weave.storeParam).toBe("D2GeneratedIdempotencyStore store");
  });

  it("preDelegateLines do NOT contain Idempotency-Key header read", () => {
    const weave = buildIdempotencyGate(makeDerivedGateInput());
    expect(weave.preDelegateLines.join("\n")).not.toContain(
      '"Idempotency-Key"',
    );
  });

  it("preDelegateLines do NOT contain Falsey() guard (no header to check)", () => {
    const weave = buildIdempotencyGate(makeDerivedGateInput());
    expect(weave.preDelegateLines.join("\n")).not.toContain(".Falsey()");
  });

  it("preDelegateLines contain SHA256.HashData for the derived key", () => {
    const weave = buildIdempotencyGate(makeDerivedGateInput());
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain("SHA256.HashData");
  });

  it("preDelegateLines use Convert.ToHexStringLower for hex encoding", () => {
    const weave = buildIdempotencyGate(makeDerivedGateInput());
    expect(weave.preDelegateLines.join("\n")).toContain(
      "Convert.ToHexStringLower",
    );
  });

  it("preDelegateLines access PascalCase field 'Kid' on input", () => {
    const weave = buildIdempotencyGate(
      makeDerivedGateInput({ fields: ["Kid"] }),
    );
    expect(weave.preDelegateLines.join("\n")).toContain("input.Kid");
  });

  it("multiple fields are all included in the hash expression", () => {
    const weave = buildIdempotencyGate(
      makeDerivedGateInput({ fields: ["Kid", "Payload"] }),
    );
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain("input.Kid");
    expect(pre).toContain("input.Payload");
  });

  it("postDelegateLines include StoreAsync with derived TTL", () => {
    const weave = buildIdempotencyGate(makeDerivedGateInput());
    expect(weave.postDelegateLines.join("\n")).toContain(
      "TimeSpan.FromSeconds(3600)",
    );
  });

  it("preDelegateLines still include TryGetAsync replay check (same as header)", () => {
    const weave = buildIdempotencyGate(makeDerivedGateInput());
    expect(weave.preDelegateLines.join("\n")).toContain("store.TryGetAsync");
  });
});

// ---------------------------------------------------------------------------
// buildIdempotencyGate — adversarial inputs
// ---------------------------------------------------------------------------

describe("buildIdempotencyGate — adversarial inputs", () => {
  it("unknown keySource throws loudly (not silent empty emit)", () => {
    expect(() =>
      buildIdempotencyGate({
        keySource: "cookie" as "header" | "derived",
        ttlSeconds: 100,
        fields: [],
        inputTypeName: "Foo",
        outputTypeName: "FooOutput",
        pascalOpName: "Foo",
      }),
    ).toThrow("unknown keySource 'cookie'");
  });

  it("derived keySource with empty fields array throws loudly", () => {
    expect(() =>
      buildIdempotencyGate({
        keySource: "derived",
        ttlSeconds: 100,
        fields: [],
        inputTypeName: "Foo",
        outputTypeName: "FooOutput",
        pascalOpName: "Foo",
      }),
    ).toThrow("derived keySource requires at least one field name");
  });

  it("derived keySource with an empty field name throws loudly", () => {
    expect(() =>
      buildIdempotencyGate({
        keySource: "derived",
        ttlSeconds: 100,
        fields: [""],
        inputTypeName: "Foo",
        outputTypeName: "FooOutput",
        pascalOpName: "Foo",
      }),
    ).toThrow("field name must not be empty");
  });

  it("header keySource with zero ttlSeconds emits as-is (decorator validates; emitter trusts)", () => {
    // The decorator layer guarantees ttl > 0; the emitter reads it defensively
    // (emits whatever it is given, no silent default substitution).
    const weave = buildIdempotencyGate(makeHeaderGateInput({ ttlSeconds: 0 }));
    expect(weave.postDelegateLines.join("\n")).toContain(
      "TimeSpan.FromSeconds(0)",
    );
  });

  it("derived keySource with many fields produces a hash over all of them", () => {
    const weave = buildIdempotencyGate(
      makeDerivedGateInput({ fields: ["A", "B", "C", "D"] }),
    );
    const pre = weave.preDelegateLines.join("\n");
    expect(pre).toContain("input.A");
    expect(pre).toContain("input.B");
    expect(pre).toContain("input.C");
    expect(pre).toContain("input.D");
  });
});

// ---------------------------------------------------------------------------
// emitRoutePolicy — idempotency gate woven into route delegate
// ---------------------------------------------------------------------------

describe("emitRoutePolicy — header idempotency gate woven in", () => {
  it("store param appears in the delegate signature (header)", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    expect(file.content).toContain("D2GeneratedIdempotencyStore store");
  });

  it("header read appears BEFORE the delegation call", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    const headerIdx = file.content.indexOf('"Idempotency-Key"');
    const delegateIdx = file.content.indexOf("facade.SignFixtureAsync");
    expect(headerIdx).toBeGreaterThan(-1);
    expect(delegateIdx).toBeGreaterThan(-1);
    expect(headerIdx).toBeLessThan(delegateIdx);
  });

  it("TryGetAsync replay check appears BEFORE the delegation call", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    const tryGetIdx = file.content.indexOf("store.TryGetAsync");
    const delegateIdx = file.content.indexOf("facade.SignFixtureAsync");
    expect(tryGetIdx).toBeGreaterThan(-1);
    expect(tryGetIdx).toBeLessThan(delegateIdx);
  });

  it("StoreAsync call appears AFTER the delegation call", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    const storeIdx = file.content.indexOf("store.StoreAsync");
    const delegateIdx = file.content.indexOf("facade.SignFixtureAsync");
    expect(storeIdx).toBeGreaterThan(-1);
    expect(storeIdx).toBeGreaterThan(delegateIdx);
  });

  it("ValidationFailed guard present for absent/whitespace key (header)", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    expect(file.content).toContain("ValidationFailed()");
    expect(file.content).toContain(".Falsey()");
  });

  it("emits D2.Shared.Utilities.Extensions using (for Falsey)", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    expect(file.content).toContain("using D2.Shared.Utilities.Extensions;");
  });

  it("using directives remain sorted after adding gate usings", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    const lines = file.content.split("\n");
    const usingLines = lines
      .filter((l) => l.startsWith("using "))
      .map((l) =>
        l
          .replace(/^using /, "")
          .replace(";", "")
          .trim(),
      );
    for (let i = 1; i < usingLines.length; i++)
      expect(
        usingLines[i]!.localeCompare(usingLines[i - 1]!),
      ).toBeGreaterThanOrEqual(0);
  });

  it("MAP-ii success/failure shape is still present AFTER the gate lines", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      }),
    );
    const storeIdx = file.content.indexOf("store.StoreAsync");
    const statusIdx = file.content.indexOf(
      "var status = (int)result.StatusCode;",
      storeIdx,
    );
    expect(statusIdx).toBeGreaterThan(storeIdx);
    expect(file.content).toContain("if (status < 400)");
    expect(file.content).toContain(
      "Results.Json(result.Data, statusCode: status)",
    );
    expect(file.content).toContain("ToProblemDetails");
  });
});

describe("emitRoutePolicy — derived idempotency gate woven in", () => {
  it("store param appears in the delegate signature (derived)", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: {
          keySource: "derived",
          ttlSeconds: 3600,
          fields: ["Kid"],
        },
      }),
    );
    expect(file.content).toContain("D2GeneratedIdempotencyStore store");
  });

  it("SHA-256 derived key block appears BEFORE the delegation call", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: {
          keySource: "derived",
          ttlSeconds: 3600,
          fields: ["Kid"],
        },
      }),
    );
    const sha256Idx = file.content.indexOf("SHA256.HashData");
    const delegateIdx = file.content.indexOf("facade.SignFixtureAsync");
    expect(sha256Idx).toBeGreaterThan(-1);
    expect(sha256Idx).toBeLessThan(delegateIdx);
  });

  it("derived key references PascalCase input.Kid", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: {
          keySource: "derived",
          ttlSeconds: 3600,
          fields: ["Kid"],
        },
      }),
    );
    expect(file.content).toContain("input.Kid");
  });

  it("no Idempotency-Key header read for derived keySource", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: {
          keySource: "derived",
          ttlSeconds: 3600,
          fields: ["Kid"],
        },
      }),
    );
    expect(file.content).not.toContain('"Idempotency-Key"');
  });

  it("StoreAsync uses the derived TTL (3600)", () => {
    const file = emitRoutePolicy(
      makeBaseRouteInput({
        idempotency: {
          keySource: "derived",
          ttlSeconds: 3600,
          fields: ["Kid"],
        },
      }),
    );
    expect(file.content).toContain("TimeSpan.FromSeconds(3600)");
  });
});

describe("emitRoutePolicy — absent idempotency (regression guard)", () => {
  it("no idempotency → no D2GeneratedIdempotencyStore param in delegate signature", () => {
    const file = emitRoutePolicy(makeBaseRouteInput()); // no idempotency field
    expect(file.content).not.toContain("D2GeneratedIdempotencyStore");
  });

  it("no idempotency → no StoreAsync call in emitted content", () => {
    const file = emitRoutePolicy(makeBaseRouteInput());
    expect(file.content).not.toContain("store.StoreAsync");
  });

  it("no idempotency → no TryGetAsync call in emitted content", () => {
    const file = emitRoutePolicy(makeBaseRouteInput());
    expect(file.content).not.toContain("store.TryGetAsync");
  });

  it("no idempotency → delegate body still contains the delegation call unchanged", () => {
    const file = emitRoutePolicy(makeBaseRouteInput());
    expect(file.content).toContain("facade.SignFixtureAsync(input, ct)");
  });

  it("no idempotency → Falsey guard NOT emitted", () => {
    const file = emitRoutePolicy(makeBaseRouteInput());
    expect(file.content).not.toContain(".Falsey()");
  });

  it("no idempotency → no ValidationFailed in emitted content", () => {
    const file = emitRoutePolicy(makeBaseRouteInput());
    // The delegation test will have ValidationFailed from the facade, but the
    // gate itself must not add ValidationFailed when absent.
    // We check that the emitted content still works normally.
    expect(file.content).not.toContain("idempotencyKey");
  });
});

// ---------------------------------------------------------------------------
// Byte-parity: SignFixtureRouteRegistration.g.cs with header idempotency gate
// ---------------------------------------------------------------------------

/**
 * Expected content of SignFixtureRouteRegistration.g.cs AFTER adding @d2Idempotent("header", 86400).
 * The gate adds:
 *   - D2GeneratedIdempotencyStore store in the delegate signature
 *   - using D2.Shared.Utilities.Extensions (sorted)
 *   - pre-delegate: header read, Falsey guard, TryGetAsync replay check
 *   - post-delegate: StoreAsync with 86400s TTL
 *   - blank lines separating gate sections from the delegation call
 */
const SIGN_ROUTE_REGISTRATION_GATED_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecRoute.Generated;",
  "",
  "using D2.Edge.Tests.TypeSpecDto.Generated;",
  "using D2.Edge.Tests.TypeSpecRoute.Generated.Facade;",
  "using D2.Shared.Auth.Http.Endpoints;",
  "using D2.Shared.Auth.Http.ProblemDetails;",
  "using D2.Shared.Result;",
  "using D2.Shared.Utilities.Extensions;",
  "using Microsoft.AspNetCore.Builder;",
  "using Microsoft.AspNetCore.Http;",
  "using Microsoft.AspNetCore.Routing;",
  "",
  "/// <summary>Faithful seam marker: rate-limit tier declaration for this route.</summary>",
  "public sealed record D2GeneratedRateLimitTier(string Tier);",
  "",
  "/// <summary>Faithful seam marker: CSRF posture declaration for this route.</summary>",
  "public sealed record D2GeneratedCsrfPosture(string Posture);",
  "",
  "/// <summary>Generated REST route registration for the <c>SignFixture</c> operation.</summary>",
  "public static class SignFixtureRouteRegistration",
  "{",
  "    extension(IEndpointRouteBuilder endpoints)",
  "    {",
  '        /// <summary>Maps <c>POST /internal/v1/fixtures/sign-fixture</c>, delegating to <see cref="ISignFixtureSignerFacade"/>.</summary>',
  "        /// <remarks>Audience is enforced service-wide via <c>AuthOptions.Audience</c> — no per-route audience fluent (§9.2).</remarks>",
  "        public IEndpointConventionBuilder MapSignFixtureRoute()",
  "        {",
  "            var builder = endpoints.MapPost(",
  '                "/internal/v1/fixtures/sign-fixture",',
  "                static async (SignFixtureInput input, ISignFixtureSignerFacade facade, D2GeneratedIdempotencyStore store, HttpContext http, CancellationToken ct) =>",
  "                {",
  '                    var idempotencyKey = http.Request.Headers["Idempotency-Key"].ToString();',
  "                    if (idempotencyKey.Falsey())",
  "                        return Results.Json(",
  "                            D2Result<SignFixtureOutput?>.ValidationFailed().ToProblemDetails(http),",
  "                            statusCode: 400,",
  '                            contentType: "application/problem+json");',
  "                    var cachedResult = await store.TryGetAsync<D2Result<SignFixtureOutput?>>(idempotencyKey, ct).ConfigureAwait(false);",
  "                    if (cachedResult.Success && cachedResult.Data is not null)",
  "                    {",
  "                        var replayed = cachedResult.Data;",
  "                        var replayStatus = (int)replayed.StatusCode;",
  "                        if (replayStatus < 400)",
  "                            return Results.Json(replayed.Data, statusCode: replayStatus);",
  "                        var rpd = replayed.ToProblemDetails(http);",
  '                        return Results.Json(rpd, statusCode: rpd.Status ?? 500, contentType: "application/problem+json");',
  "                    }",
  "",
  "                    var result = await facade.SignFixtureAsync(input, ct).ConfigureAwait(false);",
  "                    await store.StoreAsync<D2Result<SignFixtureOutput?>>(idempotencyKey, result, TimeSpan.FromSeconds(86400), ct).ConfigureAwait(false);",
  "",
  "                    var status = (int)result.StatusCode;",
  "                    if (status < 400)",
  "                        return Results.Json(result.Data, statusCode: status);",
  "                    var pd = result.ToProblemDetails(http);",
  '                    return Results.Json(pd, statusCode: pd.Status ?? 500, contentType: "application/problem+json");',
  "                });",
  "",
  '            builder.RequireAnyScope("self.write");',
  '            builder.WithMetadata(new D2GeneratedRateLimitTier("Standard"));',
  '            builder.WithMetadata(new D2GeneratedCsrfPosture("exempt"));',
  "            return builder;",
  "        }",
  "    }",
  "}",
  "",
].join("\n");

describe("byteParity_SignFixtureRouteRegistration_Gated_CommittedFixtureIdentical", () => {
  it("regenerated SignFixtureRouteRegistration.g.cs (gated) is byte-identical to the committed fixture", () => {
    const file = emitRoutePolicy({
      opName: "signFixture",
      verb: "post",
      routePath: "/internal/v1/fixtures/sign-fixture",
      delegationTarget: {
        kind: "facade",
        typeName: "ISignFixtureSignerFacade",
        methodName: "SignFixtureAsync",
      },
      delegationTargetNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated.Facade",
      inputTypeName: "SignFixtureInput",
      outputTypeName: "SignFixtureOutput",
      dtoNamespace: "D2.Edge.Tests.TypeSpecDto.Generated",
      scopePolicy: { kind: "any", scopes: ["self.write"] },
      rateTier: "Standard",
      csrf: "exempt",
      idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      registrationNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated",
      sourceSpec: "contracts/typespec/fixtures/sign-shaped.tsp",
    });
    expect(file.content).toBe(SIGN_ROUTE_REGISTRATION_GATED_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match", () => {
    const drifted = SIGN_ROUTE_REGISTRATION_GATED_FIXTURE.replace(
      "TryGetAsync",
      "TryGetAsyncDRIFTED",
    );
    const file = emitRoutePolicy({
      opName: "signFixture",
      verb: "post",
      routePath: "/internal/v1/fixtures/sign-fixture",
      delegationTarget: {
        kind: "facade",
        typeName: "ISignFixtureSignerFacade",
        methodName: "SignFixtureAsync",
      },
      delegationTargetNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated.Facade",
      inputTypeName: "SignFixtureInput",
      outputTypeName: "SignFixtureOutput",
      dtoNamespace: "D2.Edge.Tests.TypeSpecDto.Generated",
      scopePolicy: { kind: "any", scopes: ["self.write"] },
      rateTier: "Standard",
      csrf: "exempt",
      idempotency: { keySource: "header", ttlSeconds: 86400, fields: [] },
      registrationNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated",
      sourceSpec: "contracts/typespec/fixtures/sign-shaped.tsp",
    });
    expect(file.content).not.toBe(drifted);
  });
});

// ---------------------------------------------------------------------------
// Byte-parity: SignFixtureDerivedRouteRegistration.g.cs with derived idempotency gate
// ---------------------------------------------------------------------------

const SIGN_DERIVED_ROUTE_REGISTRATION_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecRoute.Generated;",
  "",
  "using D2.Edge.Tests.TypeSpecDto.Generated;",
  "using D2.Edge.Tests.TypeSpecRoute.Generated.Facade;",
  "using D2.Shared.Auth.Http.Endpoints;",
  "using D2.Shared.Auth.Http.ProblemDetails;",
  "using D2.Shared.Result;",
  "using D2.Shared.Utilities.Extensions;",
  "using Microsoft.AspNetCore.Builder;",
  "using Microsoft.AspNetCore.Http;",
  "using Microsoft.AspNetCore.Routing;",
  "",
  "/// <summary>Generated REST route registration for the <c>SignFixtureDerived</c> operation.</summary>",
  "public static class SignFixtureDerivedRouteRegistration",
  "{",
  "    extension(IEndpointRouteBuilder endpoints)",
  "    {",
  '        /// <summary>Maps <c>POST /internal/v1/fixtures/sign-fixture-derived</c>, delegating to <see cref="ISignFixtureSignerFacade"/>.</summary>',
  "        /// <remarks>Audience is enforced service-wide via <c>AuthOptions.Audience</c> — no per-route audience fluent (§9.2).</remarks>",
  "        public IEndpointConventionBuilder MapSignFixtureDerivedRoute()",
  "        {",
  "            var builder = endpoints.MapPost(",
  '                "/internal/v1/fixtures/sign-fixture-derived",',
  "                static async (SignFixtureInput input, ISignFixtureSignerFacade facade, D2GeneratedIdempotencyStore store, HttpContext http, CancellationToken ct) =>",
  "                {",
  "                    var idempotencyKeyRaw = System.Text.Encoding.UTF8.GetBytes(input.Kid);",
  "                    var idempotencyKey = Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(idempotencyKeyRaw));",
  "                    var cachedResult = await store.TryGetAsync<D2Result<SignFixtureOutput?>>(idempotencyKey, ct).ConfigureAwait(false);",
  "                    if (cachedResult.Success && cachedResult.Data is not null)",
  "                    {",
  "                        var replayed = cachedResult.Data;",
  "                        var replayStatus = (int)replayed.StatusCode;",
  "                        if (replayStatus < 400)",
  "                            return Results.Json(replayed.Data, statusCode: replayStatus);",
  "                        var rpd = replayed.ToProblemDetails(http);",
  '                        return Results.Json(rpd, statusCode: rpd.Status ?? 500, contentType: "application/problem+json");',
  "                    }",
  "",
  "                    var result = await facade.SignFixtureDerivedAsync(input, ct).ConfigureAwait(false);",
  "                    await store.StoreAsync<D2Result<SignFixtureOutput?>>(idempotencyKey, result, TimeSpan.FromSeconds(3600), ct).ConfigureAwait(false);",
  "",
  "                    var status = (int)result.StatusCode;",
  "                    if (status < 400)",
  "                        return Results.Json(result.Data, statusCode: status);",
  "                    var pd = result.ToProblemDetails(http);",
  '                    return Results.Json(pd, statusCode: pd.Status ?? 500, contentType: "application/problem+json");',
  "                });",
  "",
  '            builder.RequireAnyScope("self.write");',
  "            return builder;",
  "        }",
  "    }",
  "}",
  "",
].join("\n");

describe("byteParity_SignFixtureDerivedRouteRegistration_CommittedFixtureIdentical", () => {
  it("regenerated SignFixtureDerivedRouteRegistration.g.cs is byte-identical to the committed fixture", () => {
    const file = emitRoutePolicy({
      opName: "signFixtureDerived",
      verb: "post",
      routePath: "/internal/v1/fixtures/sign-fixture-derived",
      delegationTarget: {
        kind: "facade",
        typeName: "ISignFixtureSignerFacade",
        methodName: "SignFixtureDerivedAsync",
      },
      delegationTargetNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated.Facade",
      inputTypeName: "SignFixtureInput",
      outputTypeName: "SignFixtureOutput",
      dtoNamespace: "D2.Edge.Tests.TypeSpecDto.Generated",
      scopePolicy: { kind: "any", scopes: ["self.write"] },
      idempotency: { keySource: "derived", ttlSeconds: 3600, fields: ["Kid"] },
      registrationNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated",
      sourceSpec: "contracts/typespec/fixtures/sign-shaped.tsp",
    });
    expect(file.content).toBe(SIGN_DERIVED_ROUTE_REGISTRATION_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match", () => {
    const drifted = SIGN_DERIVED_ROUTE_REGISTRATION_FIXTURE.replace(
      "SHA256.HashData",
      "SHA256.HashDataDRIFTED",
    );
    const file = emitRoutePolicy({
      opName: "signFixtureDerived",
      verb: "post",
      routePath: "/internal/v1/fixtures/sign-fixture-derived",
      delegationTarget: {
        kind: "facade",
        typeName: "ISignFixtureSignerFacade",
        methodName: "SignFixtureDerivedAsync",
      },
      delegationTargetNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated.Facade",
      inputTypeName: "SignFixtureInput",
      outputTypeName: "SignFixtureOutput",
      dtoNamespace: "D2.Edge.Tests.TypeSpecDto.Generated",
      scopePolicy: { kind: "any", scopes: ["self.write"] },
      idempotency: { keySource: "derived", ttlSeconds: 3600, fields: ["Kid"] },
      registrationNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated",
      sourceSpec: "contracts/typespec/fixtures/sign-shaped.tsp",
    });
    expect(file.content).not.toBe(drifted);
  });
});

// ---------------------------------------------------------------------------
// Byte-parity: D2GeneratedIdempotencyStore.g.cs seam
// ---------------------------------------------------------------------------

const IDEMPOTENCY_STORE_SEAM_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecRoute.Generated;",
  "",
  "using D2.Shared.Result;",
  "",
  "/// <summary>",
  "/// Faithful seam for the generated idempotency gate.",
  "/// Supports result-replay: on a cache hit the stored <c>D2Result</c> is",
  "/// returned verbatim without re-invoking the handler or façade.",
  "/// The real Edge HTTP-idempotency middleware will implement this interface.",
  "/// No enforcement logic is present in this seam definition.",
  "/// </summary>",
  "public interface D2GeneratedIdempotencyStore",
  "{",
  "    /// <summary>",
  '    /// Try to retrieve a previously stored result for <paramref name="key"/>.',
  "    /// Returns <c>Ok(stored)</c> on a hit, <c>NotFound</c> on a miss,",
  "    /// or a failure result when the store is unavailable.",
  "    /// </summary>",
  "    ValueTask<D2Result<TStored?>> TryGetAsync<TStored>(string key, CancellationToken ct = default);",
  "",
  "    /// <summary>",
  '    /// Store <paramref name="value"/> under <paramref name="key"/> with the',
  '    /// given <paramref name="ttl"/>. The entry expires after the TTL elapses.',
  "    /// Returns <c>Ok</c> on success or a failure result when the store is unavailable.",
  "    /// </summary>",
  "    ValueTask<D2Result> StoreAsync<TStored>(string key, TStored value, TimeSpan ttl, CancellationToken ct = default);",
  "}",
  "",
].join("\n");

describe("byteParity_IIdempotencyStore_SeamFixtureIdentical", () => {
  it("regenerated D2GeneratedIdempotencyStore.g.cs is byte-identical to the committed fixture", () => {
    const file = emitIdempotencyStoreSeam(
      "D2.Edge.Tests.TypeSpecRoute.Generated",
      "contracts/typespec/fixtures/sign-shaped.tsp",
    );
    expect(file.content).toBe(IDEMPOTENCY_STORE_SEAM_FIXTURE);
  });

  it("deliberate-drift detection: mutated method name does NOT match", () => {
    const drifted = IDEMPOTENCY_STORE_SEAM_FIXTURE.replace(
      "TryGetAsync",
      "TryGetAsyncDRIFTED",
    );
    const file = emitIdempotencyStoreSeam(
      "D2.Edge.Tests.TypeSpecRoute.Generated",
      "contracts/typespec/fixtures/sign-shaped.tsp",
    );
    expect(file.content).not.toBe(drifted);
  });
});

// ---------------------------------------------------------------------------
// D2TSP006 — direct catalog test (idempotent-requires-route)
//
// The emitter raises D2TSP006 when @d2Idempotent is present on an op with no
// @route. This test asserts the diagnostic is registered in the $lib catalog
// with the correct code and error severity, providing direct unit-test coverage
// of the diagnostic declaration from this file.
//
// The behavior that triggers D2TSP006 (non-routed @d2Idempotent op) is
// exercised end-to-end in route-emit.direct.test.ts
// ($onEmit_routeEmitDirect_IdempotentWithoutRoute_D2TSP006) and in the TypeSpec
// compiler-host integration test in route-emit.integration.test.ts.
// ---------------------------------------------------------------------------

describe("D2TSP006_IdempotentRequiresRoute_DirectCatalogTest", () => {
  it("'idempotent-requires-route' is registered in the $lib diagnostics catalog", () => {
    expect($lib.diagnostics["idempotent-requires-route"]).toBeDefined();
  });

  it("'idempotent-requires-route' (D2TSP006) has severity 'error'", () => {
    expect($lib.diagnostics["idempotent-requires-route"].severity).toBe(
      "error",
    );
  });

  it("'idempotent-requires-route' message template is callable (paramMessage)", () => {
    const descriptor = $lib.diagnostics["idempotent-requires-route"];
    expect(typeof descriptor.messages.default).toBe("function");
  });
});
