// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Byte-parity gate for the proto + gRPC service-impl emitters.
//
// Each describe block:
//   1. Asserts byte-identical match between re-emitted content and the
//      committed fixture constant.
//   2. Contains a deliberate-drift negative that proves the gate is
//      non-vacuous (§26.5.1 + §1.20): a mutated fixture does NOT match,
//      so real drift would be caught.

import { describe, it, expect } from "vitest";
import type { FieldInfo } from "../src/lib/model-walk.js";
import { emitProto } from "../src/lib/proto-emitter.js";
import { emitGrpcService } from "../src/lib/grpc-service-emitter.js";
import type { GrpcDelegationTarget } from "../src/lib/grpc-service-emitter.js";

// ---------------------------------------------------------------------------
// Committed fixture constants
// (These are the byte-identical snapshots of the committed generated files.)
// ---------------------------------------------------------------------------

/** Committed key_custodian_signer_sign.g.proto content. */
const SIGN_PROTO_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "syntax = \"proto3\";",
  "",
  "import \"common/v1/d2_result.proto\";",
  "",
  "package d2.keycustodian.v1;",
  "",
  "option csharp_namespace = \"D2.Services.Protos.KeyCustodian.V1\";",
  "",
  "service KeyCustodianSigner {",
  "  rpc Sign(SignRequest) returns (SignResponse);",
  "}",
  "",
  "message SignRequest {",
  "  string kid = 1;",
  "  bytes payload = 2;",
  "}",
  "",
  "message SignResponse {",
  "  d2.common.v1.D2ResultProto result = 1;",
  "  SignOutput data = 2;",
  "}",
  "",
  "message SignOutput {",
  "  string signature = 1;",
  "}",
  "",
].join("\n");

/**
 * Committed KeyCustodianSignerService.g.cs content.
 * The sign op has @d2InProcess, so the service delegates through the fixture
 * façade IKeyCustodianSignerFacade (not ISignHandler directly).
 */
const SIGN_SERVICE_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecGrpc.Generated;",
  "",
  "using SignRequest = global::D2.Services.Protos.KeyCustodian.V1.SignRequest;",
  "using SignResponse = global::D2.Services.Protos.KeyCustodian.V1.SignResponse;",
  "using SignInput = global::D2.Edge.Tests.TypeSpecDto.Generated.SignInput;",
  "using SignOutput = global::D2.Edge.Tests.TypeSpecDto.Generated.SignOutput;",
  "using D2.Shared.Result.Grpc;",
  "using Grpc.Core;",
  "using D2.Edge.Tests.TypeSpecRoute.Generated.Facade;",
  "",
  "/// <summary>Generated gRPC service for the <c>Sign</c> operation, delegating to <see cref=\"IKeyCustodianSignerFacade\"/>.</summary>",
  "public sealed class KeyCustodianSignerService(IKeyCustodianSignerFacade facade)",
  "    : global::D2.Services.Protos.KeyCustodian.V1.KeyCustodianSigner.KeyCustodianSignerBase",
  "{",
  "    /// <inheritdoc/>",
  "    public override async Task<SignResponse> Sign(SignRequest request, ServerCallContext context)",
  "    {",
  "        SignInput input = request.ToSignInput();",
  "        var result = await facade.SignAsync(input, context.CancellationToken).ConfigureAwait(false);",
  "        return result.ToProtoResponse();",
  "    }",
  "}",
  "",
].join("\n");

/** Committed SignTransportMappers.g.cs content. */
const SIGN_MAPPER_FIXTURE = [
  "// -----------------------------------------------------------------------",
  "// <auto-generated>",
  "//   Generated by the @d2/typespec-emitters TypeSpec emitter.",
  "//   Source spec: contracts/typespec/fixtures/sign-shaped.tsp",
  "//   Manual edits will be lost on rebuild.",
  "// </auto-generated>",
  "// -----------------------------------------------------------------------",
  "#nullable enable",
  "",
  "namespace D2.Edge.Tests.TypeSpecGrpc.Generated;",
  "",
  "using SignRequest = global::D2.Services.Protos.KeyCustodian.V1.SignRequest;",
  "using SignResponse = global::D2.Services.Protos.KeyCustodian.V1.SignResponse;",
  "using ProtoSignOutput = global::D2.Services.Protos.KeyCustodian.V1.SignOutput;",
  "using SignInput = global::D2.Edge.Tests.TypeSpecDto.Generated.SignInput;",
  "using SignOutput = global::D2.Edge.Tests.TypeSpecDto.Generated.SignOutput;",
  "using D2.Shared.Result;",
  "using D2.Shared.Result.Grpc;",
  "using Google.Protobuf;",
  "",
  "/// <summary>Generated transport mappers: proto ↔ DTO for the <c>Sign</c> operation.</summary>",
  "internal static class SignTransportMappers",
  "{",
  "    extension(SignRequest request)",
  "    {",
  "        internal SignInput ToSignInput()",
  "        {",
  "            return new SignInput(request.Kid, request.Payload.ToByteArray());",
  "        }",
  "    }",
  "",
  "    extension(D2Result<SignOutput?> result)",
  "    {",
  "        internal SignResponse ToProtoResponse()",
  "        {",
  "            var response = new SignResponse { Result = result.ToProto() };",
  "            if (result.IsOk && result.Data is not null)",
  "                response.Data = result.Data.ToProtoSignOutput();",
  "            return response;",
  "        }",
  "    }",
  "",
  "    extension(SignOutput output)",
  "    {",
  "        internal ProtoSignOutput ToProtoSignOutput()",
  "        {",
  "            return new ProtoSignOutput",
  "            {",
  "                Signature = output.Signature,",
  "            };",
  "        }",
  "    }",
  "}",
  "",
].join("\n");

// ---------------------------------------------------------------------------
// Field stubs matching the sign fixture
// ---------------------------------------------------------------------------

function buildSignInputFields(): readonly FieldInfo[] {
  return [
    {
      name: "kid",
      csName: "Kid",
      csType: "string",
      tsName: "kid",
      tsType: "string",
      protoType: "string",
      repeated: false,
      optional: false,
      redact: false,
    },
    {
      name: "payload",
      csName: "Payload",
      csType: "byte[]",
      tsName: "payload",
      tsType: "Uint8Array",
      protoType: "bytes",
      repeated: false,
      optional: false,
      redact: true,
    },
  ];
}

function buildSignOutputFields(): readonly FieldInfo[] {
  return [
    {
      name: "signature",
      csName: "Signature",
      csType: "string",
      tsName: "signature",
      tsType: "string",
      protoType: "string",
      repeated: false,
      optional: false,
      redact: false,
    },
  ];
}

const SOURCE = "contracts/typespec/fixtures/sign-shaped.tsp";

// ---------------------------------------------------------------------------
// byteParity_SignProto
// ---------------------------------------------------------------------------

describe("byteParity_SignProto_CommittedFixtureIdentical", () => {
  it("re-emitted .proto is byte-identical to the committed fixture", () => {
    const result = emitProto(
      "sign",
      "KeyCustodianSigner",
      "Sign",
      "unary",
      "d2.keycustodian.v1",
      "D2.Services.Protos.KeyCustodian.V1",
      SOURCE,
      "SignRequest",
      buildSignInputFields(),
      "SignOutput",     // data message name — wrapper is always <grpcMethod>Response
      buildSignOutputFields(),
      [],
      () => {},
    );
    expect(result).toBeDefined();
    expect(result!.content).toBe(SIGN_PROTO_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match re-emitted output", () => {
    // §1.20 non-vacuous guard: corrupt the fixture by one byte — D2ResultProto → DRIFTED.
    const drifted = SIGN_PROTO_FIXTURE.replace("D2ResultProto", "D2ResultProtoDRIFTED");
    const result = emitProto(
      "sign",
      "KeyCustodianSigner",
      "Sign",
      "unary",
      "d2.keycustodian.v1",
      "D2.Services.Protos.KeyCustodian.V1",
      SOURCE,
      "SignRequest",
      buildSignInputFields(),
      "SignOutput",
      buildSignOutputFields(),
      [],
      () => {},
    );
    expect(result!.content).not.toBe(drifted);
  });
});

// ---------------------------------------------------------------------------
// byteParity_KeyCustodianSignerService (re-pointed to façade delegation)
// ---------------------------------------------------------------------------

/** Fixture façade delegation target for the sign op (matches the committed .g.cs). */
const SIGN_FACADE_TARGET: GrpcDelegationTarget = {
  kind: "facade",
  typeName: "IKeyCustodianSignerFacade",
  methodName: "SignAsync",
  targetNamespace: "D2.Edge.Tests.TypeSpecRoute.Generated.Facade",
};

describe("byteParity_KeyCustodianSignerService_FacadeDelegation_CommittedFixtureIdentical", () => {
  it("re-emitted service .g.cs (façade delegation) is byte-identical to the committed fixture", () => {
    const [svc] = emitGrpcService(
      "sign",
      "KeyCustodianSigner",
      "Sign",
      "D2.Services.Protos.KeyCustodian.V1",
      "D2.Edge.Tests.TypeSpecGrpc.Generated",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      SOURCE,
      "SignRequest",
      "SignResponse",
      "SignInput",
      buildSignInputFields(),
      "SignOutput",
      buildSignOutputFields(),
      SIGN_FACADE_TARGET,
    );
    expect(svc.content).toBe(SIGN_SERVICE_FIXTURE);
  });

  it("deliberate-drift detection: handler delegation does NOT match façade fixture", () => {
    // Substituting SignAsync → HandleAsync would produce a mismatch (non-vacuous gate).
    const drifted = SIGN_SERVICE_FIXTURE.replace("facade.SignAsync", "handler.HandleAsync");
    const [svc] = emitGrpcService(
      "sign",
      "KeyCustodianSigner",
      "Sign",
      "D2.Services.Protos.KeyCustodian.V1",
      "D2.Edge.Tests.TypeSpecGrpc.Generated",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      SOURCE,
      "SignRequest",
      "SignResponse",
      "SignInput",
      buildSignInputFields(),
      "SignOutput",
      buildSignOutputFields(),
      SIGN_FACADE_TARGET,
    );
    expect(svc.content).not.toBe(drifted);
  });
});

// ---------------------------------------------------------------------------
// byteParity_SignTransportMappers
// ---------------------------------------------------------------------------

describe("byteParity_SignTransportMappers_CommittedFixtureIdentical", () => {
  it("re-emitted mapper .g.cs is byte-identical to the committed fixture", () => {
    const [, mapper] = emitGrpcService(
      "sign",
      "KeyCustodianSigner",
      "Sign",
      "D2.Services.Protos.KeyCustodian.V1",
      "D2.Edge.Tests.TypeSpecGrpc.Generated",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      SOURCE,
      "SignRequest",
      "SignResponse",
      "SignInput",
      buildSignInputFields(),
      "SignOutput",
      buildSignOutputFields(),
    );
    expect(mapper.content).toBe(SIGN_MAPPER_FIXTURE);
  });

  it("deliberate-drift detection: mutated fixture does NOT match re-emitted output", () => {
    const drifted = SIGN_MAPPER_FIXTURE.replace("SignTransportMappers", "SignTransportMappersDRIFTED");
    const [, mapper] = emitGrpcService(
      "sign",
      "KeyCustodianSigner",
      "Sign",
      "D2.Services.Protos.KeyCustodian.V1",
      "D2.Edge.Tests.TypeSpecGrpc.Generated",
      "D2.Edge.Tests.TypeSpecDto.Generated",
      SOURCE,
      "SignRequest",
      "SignResponse",
      "SignInput",
      buildSignInputFields(),
      "SignOutput",
      buildSignOutputFields(),
    );
    expect(mapper.content).not.toBe(drifted);
  });
});
