// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Direct-unit tests for emitTsDtos.
// Covers: scalar interfaces, optional fields, collections, nested model,
// @d2Redact field emitted normally (no attribute in TS), banner.

import { describe, it, expect } from "vitest";
import { emitTsDtos } from "../src/lib/ts-dto-emitter.js";
import type {
  FieldInfo,
  NestedEnum,
  NestedModel,
} from "../src/lib/model-walk.js";

const TEST_SPEC = "contracts/typespec/test.tsp";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function field(
  name: string,
  tsType: string,
  optional = false,
  redact = false,
): FieldInfo {
  const csType = optional ? `${tsType}?` : tsType;
  return {
    name,
    csName: name[0]!.toUpperCase() + name.slice(1),
    csType,
    tsName: name,
    tsType,
    optional,
    redact,
    repeated: false,
  };
}

function nested(name: string, fields: FieldInfo[]): NestedModel {
  return { name, fields };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("emitTsDtos_ScalarFields_CorrectTypes", () => {
  it("emits correct TS types for string, boolean, number fields", () => {
    const inputFields = [
      field("id", "string"),
      field("active", "boolean"),
      field("count", "number"),
    ];
    const file = emitTsDtos("getItem", TEST_SPEC, inputFields, [], []);

    expect(file.fileName).toBe("get-item-dto.g.ts");
    expect(file.content).toContain("readonly id: string;");
    expect(file.content).toContain("readonly active: boolean;");
    expect(file.content).toContain("readonly count: number;");
  });
});

describe("emitTsDtos_OptionalField_QuestionMark", () => {
  it("optional field uses ?: not | null", () => {
    const inputFields = [field("hint", "string", true)];
    const file = emitTsDtos("op", TEST_SPEC, inputFields, [], []);

    expect(file.content).toContain("readonly hint?: string;");
    expect(file.content).not.toContain("| null");
  });
});

describe("emitTsDtos_CollectionField_ReadonlyArray", () => {
  it("collection field uses readonly T[]", () => {
    const outputFields = [field("keys", "readonly Jwk[]")];
    const file = emitTsDtos("getJwks", TEST_SPEC, [], outputFields, []);

    expect(file.content).toContain("readonly keys: readonly Jwk[];");
  });
});

describe("emitTsDtos_NestedModel_EmittedOnce", () => {
  it("nested model interface emitted once before owning output interface", () => {
    const jwkFields = [field("kid", "string"), field("n", "string")];
    const outputFields = [field("keys", "readonly Jwk[]")];
    const file = emitTsDtos("getJwks", TEST_SPEC, [], outputFields, [
      nested("Jwk", jwkFields),
    ]);

    expect(file.content).toContain("export interface Jwk {");
    expect(file.content).toContain("readonly kid: string;");
    // Jwk must appear BEFORE GetJwksOutput.
    const jwkPos = file.content.indexOf("export interface Jwk");
    const outputPos = file.content.indexOf("export interface GetJwksOutput");
    expect(jwkPos).toBeLessThan(outputPos);

    // Only one Jwk interface.
    const jwkCount = (file.content.match(/export interface Jwk/g) ?? []).length;
    expect(jwkCount).toBe(1);
  });
});

describe("emitTsDtos_RedactedField_EmittedNormally", () => {
  it("@d2Redact field is emitted as a normal TS field (no attribute in TS)", () => {
    const inputFields = [
      field("kid", "string"),
      field("payload", "Uint8Array", false, true), // redacted — ignored in TS
    ];
    const file = emitTsDtos("sign", TEST_SPEC, inputFields, [], []);

    // Field is present with its normal TS type.
    expect(file.content).toContain("readonly payload: Uint8Array;");
    // No C# attribute syntax.
    expect(file.content).not.toContain("RedactData");
    expect(file.content).not.toContain("[property:");
  });
});

describe("emitTsDtos_BannerPresent", () => {
  it("emitted file starts with the auto-generated banner", () => {
    const file = emitTsDtos("op", TEST_SPEC, [], [], []);

    expect(file.content).toContain("// <auto-generated>");
    expect(file.content).toContain(
      "Generated by the @d2/typespec-emitters TypeSpec emitter.",
    );
    expect(file.content).toContain(
      "//   Manual edits will be lost on rebuild.",
    );
  });
});

describe("emitTsDtos_FileNameKebabCase", () => {
  it("file name is kebab-case with .g.ts extension", () => {
    const file = emitTsDtos("getJwks", TEST_SPEC, [], [], []);
    expect(file.fileName).toBe("get-jwks-dto.g.ts");
  });

  it("single-word op name remains lowercase", () => {
    const file = emitTsDtos("sign", TEST_SPEC, [], [], []);
    expect(file.fileName).toBe("sign-dto.g.ts");
  });
});

describe("emitTsDtos_EmptyModel_EmptyInterface", () => {
  it("empty input model → empty interface body", () => {
    const file = emitTsDtos("getJwks", TEST_SPEC, [], [], []);

    expect(file.content).toContain("export interface GetJwksInput {");
    expect(file.content).toContain("export interface GetJwksOutput {");
  });
});

describe("emitTsDtos_EmptyOpName_Passthrough", () => {
  it("empty op name string is returned as-is (defensive branch)", () => {
    // Exercises the `if (s.length === 0) return s;` branch in toPascalFromCamel
    // and the equivalent kebab path. op name "" → file is "-dto.g.ts".
    const file = emitTsDtos("", TEST_SPEC, [], [], []);

    // Interface names and file name degenerate gracefully — no crash.
    expect(file.fileName).toBe("-dto.g.ts");
    expect(file.content).toContain("export interface Input {");
    expect(file.content).toContain("export interface Output {");
  });
});

// ---------------------------------------------------------------------------
// Enum / string-literal-union emission (C-2)
// ---------------------------------------------------------------------------

const KEY_KIND: NestedEnum = {
  name: "KeyKind",
  members: [
    { csName: "Rsa", wireValue: "Rsa", needsEnumMember: false },
    { csName: "Aes", wireValue: "Aes", needsEnumMember: false },
    { csName: "Secret", wireValue: "Secret", needsEnumMember: false },
  ],
};

const LEVEL: NestedEnum = {
  name: "Level",
  members: [
    { csName: "Low", wireValue: "Low", needsEnumMember: false, intValue: 0 },
    { csName: "High", wireValue: "High", needsEnumMember: false, intValue: 10 },
  ],
};

const ACCOUNT_KIND: NestedEnum = {
  name: "AccountKind",
  members: [
    { csName: "Internal", wireValue: "internal", needsEnumMember: true },
    { csName: "ThirdParty", wireValue: "third-party", needsEnumMember: true },
  ],
};

function enumField(name: string, enumRef: NestedEnum): FieldInfo {
  return {
    name,
    csName: name[0]!.toUpperCase() + name.slice(1),
    csType: enumRef.name,
    tsName: name,
    tsType: enumRef.name,
    protoType: "string",
    optional: false,
    redact: false,
    repeated: false,
    enumRef,
  };
}

describe("emitTsDtos_BareEnum_ConstObjectAndDerivedType", () => {
  it("S-1 → const-object `as const` + derived union type (NOT the TS enum keyword)", () => {
    const file = emitTsDtos(
      "op",
      TEST_SPEC,
      [],
      [enumField("keyKind", KEY_KIND)],
      [],
      [],
      [KEY_KIND],
    );

    expect(file.content).toContain("export const KeyKind = {");
    expect(file.content).toContain('  Rsa: "Rsa",');
    expect(file.content).toContain('  Secret: "Secret",');
    expect(file.content).toContain("} as const;");
    expect(file.content).toContain(
      "export type KeyKind = (typeof KeyKind)[keyof typeof KeyKind];",
    );
    // NEVER the TS `enum` keyword; NO Zod.
    expect(file.content).not.toMatch(/\benum\s+KeyKind/);
    expect(file.content).not.toContain('from "zod"');
    expect(file.content).not.toContain("z.enum");
  });
});

describe("emitTsDtos_ExplicitIntEnum_ValueIsMemberName", () => {
  it("S-2 → the const VALUE is the member-NAME string (matching the C# string wire), NOT the int", () => {
    const file = emitTsDtos(
      "op",
      TEST_SPEC,
      [],
      [enumField("level", LEVEL)],
      [],
      [],
      [LEVEL],
    );

    // The value is "Low"/"High" (member name), never 0/10.
    expect(file.content).toContain('  Low: "Low",');
    expect(file.content).toContain('  High: "High",');
    expect(file.content).not.toContain("Low: 0");
    expect(file.content).not.toContain("High: 10");
  });
});

describe("emitTsDtos_NonIdentifierLiteral_ValueIsLiteral", () => {
  it('S-3 → const key is PascalCase, value is the literal (ThirdParty: "third-party")', () => {
    const file = emitTsDtos(
      "op",
      TEST_SPEC,
      [],
      [enumField("accountKind", ACCOUNT_KIND)],
      [],
      [],
      [ACCOUNT_KIND],
    );

    expect(file.content).toContain('  Internal: "internal",');
    expect(file.content).toContain('  ThirdParty: "third-party",');
  });
});

describe("emitTsDtos_EnumSiblingAboveInterfaces", () => {
  it("the enum const is emitted ABOVE the interface that references it", () => {
    const file = emitTsDtos(
      "op",
      TEST_SPEC,
      [],
      [enumField("keyKind", KEY_KIND)],
      [],
      [],
      [KEY_KIND],
    );

    const enumPos = file.content.indexOf("export const KeyKind");
    const ifacePos = file.content.indexOf("export interface OpOutput");
    expect(enumPos).toBeGreaterThanOrEqual(0);
    expect(enumPos).toBeLessThan(ifacePos);
  });

  it("an enum on both input + output is emitted exactly once (dedup)", () => {
    const file = emitTsDtos(
      "op",
      TEST_SPEC,
      [enumField("keyKind", KEY_KIND)],
      [enumField("keyKind", KEY_KIND)],
      [],
      [KEY_KIND],
      [KEY_KIND],
    );

    const count = (file.content.match(/export const KeyKind =/g) ?? []).length;
    expect(count).toBe(1);
  });
});
