// -----------------------------------------------------------------------
// Copyright (c) DCSV. All rights reserved.
// -----------------------------------------------------------------------

// Direct-unit tests for emitTsDtos.
// Covers: scalar interfaces, optional fields, collections, nested model,
// @d2Redact field emitted normally (no attribute in TS), banner.

import { describe, it, expect } from "vitest";
import { emitTsDtos } from "../src/lib/ts-dto-emitter.js";
import type { FieldInfo, NestedModel } from "../src/lib/model-walk.js";

const TEST_SPEC = "contracts/typespec/test.tsp";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function field(
  name: string,
  tsType: string,
  optional = false,
  redact = false,
): FieldInfo {
  const csType = optional ? `${tsType}?` : tsType;
  return {
    name,
    csName: name[0]!.toUpperCase() + name.slice(1),
    csType,
    tsName: name,
    tsType,
    optional,
    redact,
  };
}

function nested(name: string, fields: FieldInfo[]): NestedModel {
  return { name, fields };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("emitTsDtos_ScalarFields_CorrectTypes", () => {
  it("emits correct TS types for string, boolean, number fields", () => {
    const inputFields = [
      field("id", "string"),
      field("active", "boolean"),
      field("count", "number"),
    ];
    const file = emitTsDtos("getItem", TEST_SPEC, inputFields, [], []);

    expect(file.fileName).toBe("get-item-dto.g.ts");
    expect(file.content).toContain("readonly id: string;");
    expect(file.content).toContain("readonly active: boolean;");
    expect(file.content).toContain("readonly count: number;");
  });
});

describe("emitTsDtos_OptionalField_QuestionMark", () => {
  it("optional field uses ?: not | null", () => {
    const inputFields = [field("hint", "string", true)];
    const file = emitTsDtos("op", TEST_SPEC, inputFields, [], []);

    expect(file.content).toContain("readonly hint?: string;");
    expect(file.content).not.toContain("| null");
  });
});

describe("emitTsDtos_CollectionField_ReadonlyArray", () => {
  it("collection field uses readonly T[]", () => {
    const outputFields = [field("keys", "readonly Jwk[]")];
    const file = emitTsDtos("getJwks", TEST_SPEC, [], outputFields, []);

    expect(file.content).toContain("readonly keys: readonly Jwk[];");
  });
});

describe("emitTsDtos_NestedModel_EmittedOnce", () => {
  it("nested model interface emitted once before owning output interface", () => {
    const jwkFields = [field("kid", "string"), field("n", "string")];
    const outputFields = [field("keys", "readonly Jwk[]")];
    const file = emitTsDtos("getJwks", TEST_SPEC, [], outputFields, [nested("Jwk", jwkFields)]);

    expect(file.content).toContain("export interface Jwk {");
    expect(file.content).toContain("readonly kid: string;");
    // Jwk must appear BEFORE GetJwksOutput.
    const jwkPos = file.content.indexOf("export interface Jwk");
    const outputPos = file.content.indexOf("export interface GetJwksOutput");
    expect(jwkPos).toBeLessThan(outputPos);

    // Only one Jwk interface.
    const jwkCount = (file.content.match(/export interface Jwk/g) ?? []).length;
    expect(jwkCount).toBe(1);
  });
});

describe("emitTsDtos_RedactedField_EmittedNormally", () => {
  it("@d2Redact field is emitted as a normal TS field (no attribute in TS)", () => {
    const inputFields = [
      field("kid", "string"),
      field("payload", "Uint8Array", false, true), // redacted — ignored in TS
    ];
    const file = emitTsDtos("sign", TEST_SPEC, inputFields, [], []);

    // Field is present with its normal TS type.
    expect(file.content).toContain("readonly payload: Uint8Array;");
    // No C# attribute syntax.
    expect(file.content).not.toContain("RedactData");
    expect(file.content).not.toContain("[property:");
  });
});

describe("emitTsDtos_BannerPresent", () => {
  it("emitted file starts with the auto-generated banner", () => {
    const file = emitTsDtos("op", TEST_SPEC, [], [], []);

    expect(file.content).toContain("// <auto-generated>");
    expect(file.content).toContain("Generated by the @d2/typespec-emitters TypeSpec emitter.");
    expect(file.content).toContain("//   Manual edits will be lost on rebuild.");
  });
});

describe("emitTsDtos_FileNameKebabCase", () => {
  it("file name is kebab-case with .g.ts extension", () => {
    const file = emitTsDtos("getJwks", TEST_SPEC, [], [], []);
    expect(file.fileName).toBe("get-jwks-dto.g.ts");
  });

  it("single-word op name remains lowercase", () => {
    const file = emitTsDtos("sign", TEST_SPEC, [], [], []);
    expect(file.fileName).toBe("sign-dto.g.ts");
  });
});

describe("emitTsDtos_EmptyModel_EmptyInterface", () => {
  it("empty input model → empty interface body", () => {
    const file = emitTsDtos("getJwks", TEST_SPEC, [], [], []);

    expect(file.content).toContain("export interface GetJwksInput {");
    expect(file.content).toContain("export interface GetJwksOutput {");
  });
});

describe("emitTsDtos_EmptyOpName_Passthrough", () => {
  it("empty op name string is returned as-is (defensive branch)", () => {
    // Exercises the `if (s.length === 0) return s;` branch in toPascalFromCamel
    // and the equivalent kebab path. op name "" → file is "-dto.g.ts".
    const file = emitTsDtos("", TEST_SPEC, [], [], []);

    // Interface names and file name degenerate gracefully — no crash.
    expect(file.fileName).toBe("-dto.g.ts");
    expect(file.content).toContain("export interface Input {");
    expect(file.content).toContain("export interface Output {");
  });
});
