// -----------------------------------------------------------------------
// <copyright file="EncryptionFrameEmitter.cs" company="DCSV">
// Copyright (c) DCSV. Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

namespace DcsvIo.D2.EncryptionFrame.SourceGen;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using DcsvIo.D2.SourceGen;

/// <summary>
/// Pure logic for emitting the <c>EncryptionFrameLayout</c> static class
/// source from a parsed <see cref="EncryptionFrameSpec"/>. Emits per-field
/// offset + length constants plus a constraints sub-class. Mirrors the
/// TS-side <c>EncryptionFrame</c> catalog in <c>@dcsv-io/d2-encryption-abstractions</c>
/// — both sides reference the same spec so the binary layout cannot drift
/// across the .NET encoder and the TS decoder.
/// </summary>
internal static class EncryptionFrameEmitter
{
    /// <summary>The namespace the <c>EncryptionFrameLayout</c> static class lives in.</summary>
    public const string ROOT_NAMESPACE = "DcsvIo.D2.Encryption";

    /// <summary>The emitted class name.</summary>
    public const string CLASS_NAME = "EncryptionFrameLayout";

    /// <summary>Emits the layout-class source + diagnostics.</summary>
    /// <param name="spec">Parsed encryption-frame spec.</param>
    /// <returns>Generated source + diagnostics.</returns>
    public static EmitResult Emit(EncryptionFrameSpec spec)
    {
        var diagnostics = ImmutableArray.CreateBuilder<EmitDiagnostic>();

        if (spec.Version < 1)
        {
            diagnostics.Add(EmitDiagnostics.InvalidVersion(spec.Version));
            return new EmitResult(string.Empty, diagnostics.ToImmutable());
        }

        var validFields = ValidateFields(spec.Fields, diagnostics);
        var source = EmitSource(spec.Version, validFields, spec.Constraints);
        return new EmitResult(source, diagnostics.ToImmutable());
    }

    private static List<EncryptionFrameField> ValidateFields(
        ImmutableArray<EncryptionFrameField> fields,
        ImmutableArray<EmitDiagnostic>.Builder diagnostics)
    {
        var valid = new List<EncryptionFrameField>();
        var seenConstNames = new HashSet<string>(System.StringComparer.Ordinal);

        foreach (var entry in fields)
        {
            if (entry.Length < -1 || entry.Length == 0)
            {
                diagnostics.Add(EmitDiagnostics.InvalidLength(entry.ConstName, entry.Length));
                continue;
            }

            if (!seenConstNames.Add(entry.ConstName))
            {
                diagnostics.Add(EmitDiagnostics.DuplicateFieldName(entry.ConstName));
                continue;
            }

            valid.Add(entry);
        }

        // Overlap check for fixed-offset fixed-length entries (offset >= 0 AND length > 0).
        for (var i = 0; i < valid.Count; i++)
        {
            for (var j = i + 1; j < valid.Count; j++)
            {
                var a = valid[i];
                var b = valid[j];
                if (a.Offset < 0 || a.Length < 1 || b.Offset < 0 || b.Length < 1)
                    continue;

                var aEnd = a.Offset + a.Length;
                var bEnd = b.Offset + b.Length;
                if (a.Offset < bEnd && b.Offset < aEnd)
                {
                    diagnostics.Add(EmitDiagnostics.OverlappingFields(a.ConstName, b.ConstName));
                }
            }
        }

        return valid;
    }

    private static string EmitSource(
        int version, List<EncryptionFrameField> entries, EncryptionFrameConstraints c)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(
            "//   Generated by DcsvIo.D2.EncryptionFrame.SourceGen.EncryptionFrameGenerator");
        sb.AppendLine(
            "//   from contracts/encryption-frame/encryption-frame.spec.json");
        sb.AppendLine("//   (the source of truth). Manual edits will be lost on rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// -----------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ROOT_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Spec-derived binary-layout constants for the D2 on-wire encryption");
        sb.AppendLine(
            "/// frame. Mirrors the offsets and lengths consumed by");
        sb.AppendLine(
            "/// <see cref=\"EncryptionFrame\"/>'s Encode + Decode paths. TS-side");
        sb.AppendLine(
            "/// decoder ships out of @dcsv-io/d2-encryption-abstractions from the same spec.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {CLASS_NAME}");
        sb.AppendLine("{");
        sb.AppendLine(
            "    /// <summary>Current frame format version. Encoders embed; decoders reject "
                + "anything else.</summary>");
        sb.AppendLine($"    public const byte CURRENT_VERSION = {version};");
        sb.AppendLine();

        foreach (var entry in entries)
        {
            sb.AppendLine(
                $"    /// <summary>{entry.ConstName} byte offset from frame start. "
                    + $"{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    /// <remarks>Kind: <c>{EscapeXmlDoc(entry.Kind)}</c>. "
                    + $"Offset value <c>{entry.Offset}</c> (-1 = variable).</remarks>");
            sb.AppendLine($"    public const int {entry.ConstName}_OFFSET = {entry.Offset};");
            sb.AppendLine();
            sb.AppendLine(
                $"    /// <summary>{entry.ConstName} byte length. "
                    + $"{EscapeXmlDoc(entry.Doc)}</summary>");
            sb.AppendLine(
                $"    /// <remarks>Kind: <c>{EscapeXmlDoc(entry.Kind)}</c>. "
                    + $"Length value <c>{entry.Length}</c> (-1 = variable).</remarks>");
            sb.AppendLine($"    public const int {entry.ConstName}_LENGTH = {entry.Length};");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>Minimum allowed kid length in UTF-8 bytes.</summary>");
        sb.AppendLine($"    public const int CONSTRAINT_MIN_KID_LENGTH = {c.MinKidLength};");
        sb.AppendLine("    /// <summary>Maximum allowed kid length in UTF-8 bytes.</summary>");
        sb.AppendLine($"    public const int CONSTRAINT_MAX_KID_LENGTH = {c.MaxKidLength};");
        sb.AppendLine(
            "    /// <summary>AES-GCM nonce length in bytes (= NONCE_LENGTH; the prefix "
                + "disambiguates from the per-field NONCE_LENGTH constant).</summary>");
        sb.AppendLine($"    public const int CONSTRAINT_NONCE_LENGTH = {c.NonceLength};");
        sb.AppendLine(
            "    /// <summary>AES-GCM authentication tag length in bytes (trailing bytes of "
                + "CIPHERTEXT_WITH_TAG).</summary>");
        sb.AppendLine($"    public const int CONSTRAINT_TAG_LENGTH = {c.TagLength};");
        sb.AppendLine("    /// <summary>Smallest valid frame size in bytes.</summary>");
        sb.AppendLine($"    public const int CONSTRAINT_MIN_FRAME_SIZE = {c.MinFrameSize};");
        sb.AppendLine("}");
        return sb.ToString().LfNormalized();
    }

    private static string EscapeXmlDoc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
