// -----------------------------------------------------------------------
// <copyright file="D2ProblemDetailsCustomizer.cs" company="DCSV">
// Copyright (c) DCSV. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace D2.Shared.AspNetCore.Internal;

using System.Diagnostics;
using D2.Shared.Utilities.Extensions;
using Microsoft.AspNetCore.Http;

/// <summary>
/// Internal helper exposing the
/// <c>Action&lt;Microsoft.AspNetCore.Http.ProblemDetailsContext&gt;</c>
/// installed by
/// <see cref="ProblemDetailsServiceCollectionExtensions.AddD2ProblemDetails"/>.
/// Encapsulated so the customizer logic is unit-testable in isolation
/// (without spinning a TestHost) and so the public extension stays a thin
/// registration shim.
/// </summary>
internal static class D2ProblemDetailsCustomizer
{
    /// <summary>
    /// Applies the D² ProblemDetails enrichment to <paramref name="ctx"/>:
    /// <c>traceId</c> from <see cref="Activity.Current"/> falling back to
    /// <see cref="HttpContext.TraceIdentifier"/>; <c>correlationId</c> from
    /// the configured request header (capped + sanitized) or a freshly
    /// generated GUID echoed back via the response header; and the RFC 7807
    /// <c>instance</c> field set to <c>{Method} {Path}</c> when enabled.
    /// </summary>
    /// <param name="ctx">The ProblemDetails context to enrich.</param>
    /// <param name="options">The configured options snapshot.</param>
    public static void Apply(
        ProblemDetailsContext ctx,
        D2ProblemDetailsOptions options)
    {
        ArgumentNullException.ThrowIfNull(ctx);
        ArgumentNullException.ThrowIfNull(options);

        var httpContext = ctx.HttpContext;

        // traceId: prefer the W3C distributed-trace id from Activity.Current
        // (set by AspNetCore-instrumentation OR the application directly);
        // fall back to HttpContext.TraceIdentifier (per-instance request id
        // generated by Kestrel) so the field is never empty even when no
        // distributed tracer is wired.
        var activityTraceId = Activity.Current?.TraceId.ToString();
        var traceId = activityTraceId.Truthy()
            ? activityTraceId
            : httpContext.TraceIdentifier;
        ctx.ProblemDetails.Extensions["traceId"] = traceId;

        // correlationId: read inbound header, validate length cap, fall back
        // to fresh GUID. The cap prevents an arbitrary-length user-supplied
        // header from inflating the response body.
        var inboundCorrelationId = ResolveInboundCorrelationId(
            httpContext,
            options.CorrelationIdHeaderName);
        var correlationId = inboundCorrelationId
            ?? Guid.NewGuid().ToString("N");
        ctx.ProblemDetails.Extensions["correlationId"] = correlationId;

        // Echo the resolved correlation id back via the response header so
        // the caller can include it in subsequent requests + log lines for
        // end-to-end correlation.
        if (options.EchoCorrelationIdInResponse)
            httpContext.Response.Headers[options.CorrelationIdHeaderName] = correlationId;

        // RFC 7807 instance field — operational metadata, never user input.
        if (options.IncludeRequestPath)
        {
            var method = httpContext.Request.Method;
            var path = httpContext.Request.Path.Value ?? string.Empty;
            ctx.ProblemDetails.Instance = $"{method} {path}";
        }
    }

    /// <summary>
    /// Reads the inbound correlation-id header. Returns null when missing /
    /// empty / whitespace OR when the value exceeds
    /// <see cref="D2AspNetCoreConstants.MAX_CORRELATION_ID_LENGTH"/>
    /// — caller MUST treat null as "absent" and substitute a fresh GUID.
    /// </summary>
    private static string? ResolveInboundCorrelationId(
        HttpContext httpContext,
        string headerName)
    {
        if (!httpContext.Request.Headers.TryGetValue(headerName, out var values))
            return null;

        var raw = values.ToString().ToNullIfEmpty();

        if (raw is null)
            return null;

        if (raw.Length > D2AspNetCoreConstants.MAX_CORRELATION_ID_LENGTH)
            return null;

        return raw;
    }
}
