// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Edge.Api.Grpc.KeyCustodian;

using IssueWorkloadCertificateRequest = global::D2.Services.Protos.KeyCustodian.V2Alpha.IssueWorkloadCertificateRequest;
using IssueWorkloadCertificateResponse = global::D2.Services.Protos.KeyCustodian.V2Alpha.IssueWorkloadCertificateResponse;
using ProtoIssueLeafOutput = global::D2.Services.Protos.KeyCustodian.V2Alpha.IssueLeafOutput;
using IssueLeafInput = global::D2.Edge.KeyCustodian.Client.Issuance.IssueLeafInput;
using IssueLeafOutput = global::D2.Edge.KeyCustodian.Client.Issuance.IssueLeafOutput;
using D2.Shared.Result;
using D2.Shared.Result.Grpc;
using Google.Protobuf;

/// <summary>Generated transport mappers: proto ↔ DTO for the <c>IssueLeaf</c> operation.</summary>
internal static class IssueLeafTransportMappers
{
    extension(IssueWorkloadCertificateRequest request)
    {
        internal IssueLeafInput ToIssueLeafInput()
        {
            return new IssueLeafInput(request.CsrDer.ToByteArray());
        }
    }

    extension(D2Result<IssueLeafOutput?> result)
    {
        internal IssueWorkloadCertificateResponse ToProtoResponse()
        {
            var response = new IssueWorkloadCertificateResponse { Result = result.ToProto() };

            if (result.IsOk && result.Data is not null)
                response.Data = result.Data.ToProtoIssueLeafOutput();

            return response;
        }
    }

    extension(IssueLeafOutput output)
    {
        internal ProtoIssueLeafOutput ToProtoIssueLeafOutput()
        {
            return new ProtoIssueLeafOutput
            {
                CertificateDer = ByteString.CopyFrom(output.CertificateDer),
                IssuerCertificateDer = ByteString.CopyFrom(output.IssuerCertificateDer),
                NotBefore = output.NotBefore.ToString("O"),
                NotAfter = output.NotAfter.ToString("O"),
            };
        }
    }
}
