// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/key-custodian/key-custodian.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

#nullable enable

namespace DcsvIo.D2.Private.Edge.KeyCustodian.App.Application.Handlers.Commands.GetOrLazyProvisionSealPublicKey;

using DcsvIo.D2.Private.Edge.KeyCustodian.Client.Sealing;

/// <summary>Generated handler interface for the <c>GetOrLazyProvisionSealPublicKey</c> operation.</summary>
public interface IGetOrLazyProvisionSealPublicKeyHandler : IHandler<GetOrLazyProvisionSealPublicKeyInput, GetOrLazyProvisionSealPublicKeyOutput>;
