// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @d2/typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace D2.Edge.Api.Bridges.Audit;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;

/// <summary>Generated aggregator that maps every Edge HTTP→gRPC bridge for the <c>Audit</c> module.</summary>
public static class AuditBridgeRegistrations
{
    extension(IEndpointRouteBuilder endpoints)
    {
        /// <summary>Maps all generated <c>Audit</c> Edge HTTP→gRPC bridges.</summary>
        public void MapAllAuditBridges()
        {
            endpoints.MapPingAuditBridge();
        }
    }
}
