// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the @dcsv-io/d2-typespec-emitters TypeSpec emitter.
//   Source spec: contracts/typespec/audit/audit.tsp
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------
#nullable enable

namespace DcsvIo.D2.Private.Edge.Api.Bridges.Audit;

using DcsvIo.D2.Auth.Abstractions;
using DcsvIo.D2.Auth.Http.Endpoints;
using DcsvIo.D2.Auth.Http.ProblemDetails;
using DcsvIo.D2.Private.Audit.Client;
using DcsvIo.D2.Private.Audit.Client.Ping;
using DcsvIo.D2.Private.Auth;
using DcsvIo.D2.Result;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

/// <summary>Generated Edge HTTPâ†’gRPC bridge registration for the <c>PingAudit</c> operation.</summary>
public static class PingAuditBridgeRegistration
{
    extension(IEndpointRouteBuilder endpoints)
    {
        /// <summary>Maps <c>GET /api/v1/audit/ping</c>, delegating to <see cref="IAuditGrpcClient"/>.</summary>
        /// <remarks>Host registers the client via <c>AddD2AuditGrpcClients(new AuditGrpcClientOptions { Address = â€¦ })</c> â€” the bridge never hardcodes a channel address. Audience is enforced service-wide via <c>AuthOptions.Audience</c> â€” no per-route audience fluent (Â§9.2).</remarks>
        public IEndpointConventionBuilder MapPingAuditBridge()
        {
            var builder = endpoints.MapGet(
                "/api/v1/audit/ping",
                static async ([AsParameters] PingAuditInput input, IAuditGrpcClient client, HttpContext http, CancellationToken ct) =>
                {
                    var result = await client.PingAuditAsync(input, ct: ct).ConfigureAwait(false);
                    var status = (int)result.StatusCode;
                    if (status < 400)
                        return Results.Json(result.Data, statusCode: status);
                    var pd = result.ToProblemDetails(http);
                    return Results.Json(pd, statusCode: pd.Status ?? 500, contentType: "application/problem+json");
                });

            builder.RequireAnyScope(ProductScopes.Internal.Audit.Ping);
            return builder;
        }
    }
}
